#!/bin/bash -x

ASDF_DIR=${ASDF_DIR:-${HOME}/lisp/asdf/build}
THIS_DIR=$(realpath $(dirname ${BASH_SOURCE}))
QUICKLISP_DIR=${QUICKLISP_DIR:-~/quicklisp}

# sbcl --no-userinit --no-sysinit --non-interactive \
#      --load "${ASDF_DIR}/asdf.lisp" \
#      --load  ${QUICKLISP_DIR}/setup.lisp \
#      --eval '(ql:quickload "cl-json")' \
#      --eval '(ql:quickload "iterate")' \
#      --eval '(ql:quickload "fiveam-asdf")' \
#      --eval '(ql:quickload "alexandria")' \
#      --eval '(ql:write-asdf-manifest-file "/tmp/quicklisp-manifest.txt")'


# --dispatched-entry "shop/shop-app::main" \
# --dispatched-entry "ess-shop/shop-app::ess-main" \
buildapp --output shop-app \
         --entry "shop-app::main" \
         --load "${ASDF_DIR}/asdf.lisp" \
         --asdf-path "${THIS_DIR}/../" \
         --asdf-tree "${THIS_DIR}/../../jenkins/ext/" \
         --eval '(declaim (optimize speed space safety))' \
         --load-system "shop3" \
         --load "${THIS_DIR}/shop-app-entrypoints.lisp"

retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Build process failed with exit code $retVal"
    exit $retVal
fi
exit $retVal

ln -sf ${THIS_DIR}/shop-app ${HOME}/bin/shop
ln -sf ${THIS_DIR}/shop-app ${HOME}/bin/ess-shop

# Local Variables:
# mode: sh
# End:
