#!/bin/bash -x

ASDF_DIR=${ASDF_DIR:-${HOME}/lisp/asdf/build}
THIS_DIR=$(realpath $(dirname ${BASH_SOURCE}))
QUICKLISP_DIR=${QUICKLISP_DIR:-~/quicklisp}

# --dispatched-entry "shop/shop-app::main" \
# --dispatched-entry "ess-shop/shop-app::ess-main" \
#          --entry "shop-app::main" \
buildapp --logfile "/tmp/buildapp-shop-app.log" \
         --output shop-app \
         --dispatched-entry "/shop-app::main" \
         --dispatched-entry "shop/shop-app::main" \
         --dispatched-entry "ess-shop/shop-app::ess-main" \
         --load "${ASDF_DIR}/asdf.lisp" \
         --asdf-path "${THIS_DIR}/../" \
         --asdf-tree "${THIS_DIR}/../../jenkins/ext/" \
         --eval '(declaim (optimize speed space safety))' \
         --load-system "shop3" \
         --load "${THIS_DIR}/shop-app-entrypoints.lisp"


retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Build process failed with exit code $retVal"
    exit $retVal
fi
exit $retVal

# Local Variables:
# mode: sh
# End:
