#!/bin/bash -x

ASDF_DIR=${ASDF_DIR:-${HOME}/lisp/asdf/build}
THIS_DIR=$(realpath $(dirname ${BASH_SOURCE}))
QUICKLISP_DIR=${QUICKLISP_DIR:-~/quicklisp}
BUILDAPP=${BUILDAPP:-buildapp}

# --DISPATCHED-ENTRY "SHOP/SHOP-APP::MAIN" \
# --DISPATCHED-ENTRY "ESS-SHOP/SHOP-APP::ESS-MAIN" \
#          --ENTRY "SHOP-APP::MAIN" \
${BUILDAPP} --logfile "/tmp/buildapp-shop-app.log" \
         --output shop-app \
         --dispatched-entry "/shop-app::main" \
         --dispatched-entry "shop/shop-app::classic-main" \
         --dispatched-entry "ess-shop/shop-app::ess-main" \
	 --dispatched-entry "tree-compare/shop-app::tree-compare-main" \
         --load "${ASDF_DIR}/asdf.lisp" \
         --asdf-path "${THIS_DIR}/../" \
         --asdf-tree "${THIS_DIR}/../../jenkins/ext/" \
         --eval '(declaim (optimize speed space safety))' \
         --load "${QUICKLISP_DIR}/setup.lisp" \
         --eval '(ql:quickload "clingon")' \
         --load-system "shop3" \
         --load "${THIS_DIR}/shop-app-entrypoints.lisp"


retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Build process failed with exit code $retVal"
    exit $retVal
fi
exit $retVal

# Local Variables:
# mode: sh
# End:
