(define (problem problem1)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 - region
          city0 city1 - city
          location0 location1 location2 location3 location4 location5 - location
          truck0 truck1 truck2 truck3 truck4 truck5 train0 train1 train2 airplane0 airplane1 airplane2 - vehicle
          plane_ramp0 plane_ramp1 - plane-ramp
          package0 package1 package2 - package
          road_route0 - route
          air_route0 air_route1 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region0)
          (= (local-height city0) 31)
          (= (local-weight city0) 319)
          (in-region city1 region0)
          (= (local-height city1) 34)
          (= (local-weight city1) 246)
          (in-city location0 city0)
          (= (height-cap-l location0) 18)
          (= (length-cap-l location0) 19)
          (= (width-cap-l location0) 28)
          (= (volume-cap-l location0) 281)
          (tcenter location0)
          (typel location0 airport)
          (availablel location0)
          (in-city location1 city1)
          (= (height-cap-l location1) 19)
          (= (length-cap-l location1) 15)
          (= (width-cap-l location1) 28)
          (= (volume-cap-l location1) 96)
          (tcenter location1)
          (typel location1 train-station)
          (availablel location1)
          (hub location1)
          (in-city location2 city1)
          (= (height-cap-l location2) 32)
          (= (length-cap-l location2) 12)
          (= (width-cap-l location2) 26)
          (= (volume-cap-l location2) 338)
          (tcenter location2)
          (typel location2 airport)
          (availablel location2)
          (in-city location3 city1)
          (= (height-cap-l location3) 12)
          (= (length-cap-l location3) 13)
          (= (width-cap-l location3) 22)
          (= (volume-cap-l location3) 225)
          (in-city location4 city1)
          (= (height-cap-l location4) 18)
          (= (length-cap-l location4) 43)
          (= (width-cap-l location4) 17)
          (= (volume-cap-l location4) 210)
          (in-city location5 city0)
          (= (height-cap-l location5) 17)
          (= (length-cap-l location5) 13)
          (= (width-cap-l location5) 33)
          (= (volume-cap-l location5) 418)
          (= (distance location0 location1) 43)
          (= (distance location1 location0) 43)
          (= (distance location0 location2) 1)
          (= (distance location2 location0) 1)
          (= (distance location0 location3) 0)
          (= (distance location3 location0) 0)
          (= (distance location0 location4) 60)
          (= (distance location4 location0) 60)
          (= (distance location0 location5) 20)
          (= (distance location5 location0) 20)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 29)
          (= (distance location2 location1) 29)
          (= (distance location1 location3) 9)
          (= (distance location3 location1) 9)
          (= (distance location1 location4) 69)
          (= (distance location4 location1) 69)
          (= (distance location1 location5) 54)
          (= (distance location5 location1) 54)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 14)
          (= (distance location3 location2) 14)
          (= (distance location2 location4) 29)
          (= (distance location4 location2) 29)
          (= (distance location2 location5) 37)
          (= (distance location5 location2) 37)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 32)
          (= (distance location4 location3) 32)
          (= (distance location3 location5) 0)
          (= (distance location5 location3) 0)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 53)
          (= (distance location5 location4) 53)
          (= (distance location4 location4) 0)
          (= (distance location5 location5) 0)
          (typev truck0 auto)
          (typevp truck0 truck)
          (at-vehicle truck0 location2)
          (= (gas-left truck0) 119)
          (= (gpm truck0) 1)
          (= (length-v truck0) 5)
          (= (height-v truck0) 6)
          (= (width-v truck0) 6)
          (= (weight-cap-v truck0) 436)
          (= (volume-cap-v truck0) 180)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 16)
          (availablev truck0)
          (typev truck1 auto)
          (typevp truck1 truck)
          (at-vehicle truck1 location2)
          (= (gas-left truck1) 440)
          (= (gpm truck1) 1)
          (= (length-v truck1) 5)
          (= (height-v truck1) 3)
          (= (width-v truck1) 4)
          (= (weight-cap-v truck1) 465)
          (= (volume-cap-v truck1) 60)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 37)
          (availablev truck1)
          (typev truck2 auto)
          (typevp truck2 truck)
          (at-vehicle truck2 location0)
          (= (gas-left truck2) 302)
          (= (gpm truck2) 2)
          (= (length-v truck2) 5)
          (= (height-v truck2) 4)
          (= (width-v truck2) 7)
          (= (weight-cap-v truck2) 388)
          (= (volume-cap-v truck2) 140)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 18)
          (availablev truck2)
          (typev truck3 auto)
          (typevp truck3 truck)
          (at-vehicle truck3 location0)
          (= (gas-left truck3) 143)
          (= (gpm truck3) 3)
          (= (length-v truck3) 8)
          (= (height-v truck3) 1)
          (= (width-v truck3) 3)
          (= (weight-cap-v truck3) 393)
          (= (volume-cap-v truck3) 24)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 29)
          (availablev truck3)
          (typev truck4 auto)
          (typevp truck4 truck)
          (at-vehicle truck4 location4)
          (= (gas-left truck4) 302)
          (= (gpm truck4) 3)
          (= (length-v truck4) 11)
          (= (height-v truck4) 3)
          (= (width-v truck4) 5)
          (= (weight-cap-v truck4) 306)
          (= (volume-cap-v truck4) 165)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 10)
          (availablev truck4)
          (typev truck5 auto)
          (typevp truck5 truck)
          (at-vehicle truck5 location3)
          (= (gas-left truck5) 463)
          (= (gpm truck5) 3)
          (= (length-v truck5) 13)
          (= (height-v truck5) 8)
          (= (width-v truck5) 1)
          (= (weight-cap-v truck5) 183)
          (= (volume-cap-v truck5) 104)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 33)
          (availablev truck5)
          (typev train0 auto)
          (typevp train0 train)
          (at-vehicle train0 location1)
          (= (gas-left train0) 245)
          (= (gpm train0) 2)
          (= (length-v train0) 9)
          (= (height-v train0) 5)
          (= (width-v train0) 4)
          (= (weight-cap-v train0) 126)
          (= (volume-cap-v train0) 180)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 37)
          (availablev train0)
          (typev train1 auto)
          (typevp train1 train)
          (at-vehicle train1 location1)
          (= (gas-left train1) 340)
          (= (gpm train1) 1)
          (= (length-v train1) 5)
          (= (height-v train1) 4)
          (= (width-v train1) 3)
          (= (weight-cap-v train1) 476)
          (= (volume-cap-v train1) 60)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 19)
          (availablev train1)
          (typev train2 auto)
          (typevp train2 train)
          (at-vehicle train2 location1)
          (= (gas-left train2) 177)
          (= (gpm train2) 2)
          (= (length-v train2) 15)
          (= (height-v train2) 8)
          (= (width-v train2) 5)
          (= (weight-cap-v train2) 203)
          (= (volume-cap-v train2) 420)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 32)
          (availablev train2)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location2)
          (= (gas-left airplane0) 147)
          (= (gpm airplane0) 3)
          (= (length-v airplane0) 8)
          (= (height-v airplane0) 5)
          (= (width-v airplane0) 10)
          (= (weight-cap-v airplane0) 107)
          (= (volume-cap-v airplane0) 280)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 38)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location2)
          (= (gas-left airplane1) 493)
          (= (gpm airplane1) 1)
          (= (length-v airplane1) 12)
          (= (height-v airplane1) 9)
          (= (width-v airplane1) 3)
          (= (weight-cap-v airplane1) 413)
          (= (volume-cap-v airplane1) 226)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 25)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location0)
          (= (gas-left airplane2) 86)
          (= (gpm airplane2) 3)
          (= (length-v airplane2) 10)
          (= (height-v airplane2) 6)
          (= (width-v airplane2) 8)
          (= (weight-cap-v airplane2) 242)
          (= (volume-cap-v airplane2) 344)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 15)
          (availablev airplane2)
          (at-equipment plane_ramp0 location0)
          (at-equipment plane_ramp1 location2)
          (typep package0 cars)
          (at-packagel package0 location2)
          (= (volume-p package0) 10)
          (= (weight-p package0) 20)
          (typep package1 cars)
          (at-packagel package1 location0)
          (= (volume-p package1) 6)
          (= (weight-p package1) 6)
          (typep package2 cars)
          (at-packagel package2 location4)
          (= (volume-p package2) 13)
          (= (weight-p package2) 5)
          (connect-city road_route0 road-route city1 city0)
          (= (height-cap-r road_route0) 15)
          (= (weight-cap-r road_route0) 227)
          (availabler road_route0)
          (connect-loc air_route0 air-route location0 location2)
          (= (height-cap-r air_route0) 9)
          (= (weight-cap-r air_route0) 476)
          (availabler air_route0)
          (connect-loc air_route1 air-route location2 location0)
          (= (height-cap-r air_route1) 27)
          (= (weight-cap-r air_route1) 507)
          (availabler air_route1)
          (= (volume-load-l location0) 6)
          (= (volume-load-l location1) 0)
          (= (volume-load-l location2) 10)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 13)
          (= (volume-load-l location5) 0)
   )

   (:goal (and (delivered package0 location2)
               (delivered package1 location0)
               (delivered package2 location5)
               (clear)))

)