(define (problem problem2)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 region1 - region
          city0 city1 city2 city3 - city
          location0 location1 location2 location3 location4 location5 location6 location7 location8 location9 - location
          truck0 truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 train0 train1 train2 train3 train4 airplane0 airplane1 airplane2 airplane3 airplane4 - vehicle
          plane_ramp0 plane_ramp1 plane_ramp2 plane_ramp3 - plane-ramp
          package0 package1 package2 package3 package4 - package
          road_route0 road_route1 road_route2 road_route3 road_route4 road_route5 road_route6 road_route7 road_route8 road_route9 road_route10 - route
          rail_route0 rail_route1 rail_route2 rail_route3 rail_route4 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 air_route6 air_route7 air_route8 air_route9 air_route10 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region1)
          (= (local-height city0) 16)
          (= (local-weight city0) 220)
          (in-region city1 region0)
          (= (local-height city1) 32)
          (= (local-weight city1) 340)
          (in-region city2 region0)
          (= (local-height city2) 34)
          (= (local-weight city2) 63)
          (in-region city3 region1)
          (= (local-height city3) 18)
          (= (local-weight city3) 73)
          (in-city location0 city0)
          (= (height-cap-l location0) 15)
          (= (length-cap-l location0) 11)
          (= (width-cap-l location0) 12)
          (= (volume-cap-l location0) 483)
          (tcenter location0)
          (typel location0 train-station)
          (availablel location0)
          (hub location0)
          (in-city location1 city0)
          (= (height-cap-l location1) 10)
          (= (length-cap-l location1) 27)
          (= (width-cap-l location1) 36)
          (= (volume-cap-l location1) 352)
          (tcenter location1)
          (typel location1 airport)
          (availablel location1)
          (in-city location2 city1)
          (= (height-cap-l location2) 23)
          (= (length-cap-l location2) 21)
          (= (width-cap-l location2) 9)
          (= (volume-cap-l location2) 205)
          (tcenter location2)
          (typel location2 train-station)
          (availablel location2)
          (in-city location3 city1)
          (= (height-cap-l location3) 13)
          (= (length-cap-l location3) 15)
          (= (width-cap-l location3) 35)
          (= (volume-cap-l location3) 364)
          (in-city location4 city2)
          (= (height-cap-l location4) 11)
          (= (length-cap-l location4) 18)
          (= (width-cap-l location4) 8)
          (= (volume-cap-l location4) 383)
          (in-city location5 city3)
          (= (height-cap-l location5) 15)
          (= (length-cap-l location5) 41)
          (= (width-cap-l location5) 18)
          (= (volume-cap-l location5) 421)
          (tcenter location5)
          (typel location5 airport)
          (availablel location5)
          (hub location5)
          (in-city location6 city0)
          (= (height-cap-l location6) 26)
          (= (length-cap-l location6) 42)
          (= (width-cap-l location6) 13)
          (= (volume-cap-l location6) 188)
          (tcenter location6)
          (typel location6 airport)
          (availablel location6)
          (in-city location7 city1)
          (= (height-cap-l location7) 8)
          (= (length-cap-l location7) 41)
          (= (width-cap-l location7) 34)
          (= (volume-cap-l location7) 91)
          (tcenter location7)
          (typel location7 train-station)
          (availablel location7)
          (hub location7)
          (in-city location8 city0)
          (= (height-cap-l location8) 28)
          (= (length-cap-l location8) 46)
          (= (width-cap-l location8) 22)
          (= (volume-cap-l location8) 426)
          (in-city location9 city3)
          (= (height-cap-l location9) 23)
          (= (length-cap-l location9) 22)
          (= (width-cap-l location9) 35)
          (= (volume-cap-l location9) 527)
          (tcenter location9)
          (typel location9 airport)
          (availablel location9)
          (= (distance location0 location1) 65)
          (= (distance location1 location0) 65)
          (= (distance location0 location2) 69)
          (= (distance location2 location0) 69)
          (= (distance location0 location3) 4)
          (= (distance location3 location0) 4)
          (= (distance location0 location4) 15)
          (= (distance location4 location0) 15)
          (= (distance location0 location5) 17)
          (= (distance location5 location0) 17)
          (= (distance location0 location6) 56)
          (= (distance location6 location0) 56)
          (= (distance location0 location7) 20)
          (= (distance location7 location0) 20)
          (= (distance location0 location8) 68)
          (= (distance location8 location0) 68)
          (= (distance location0 location9) 42)
          (= (distance location9 location0) 42)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 69)
          (= (distance location2 location1) 69)
          (= (distance location1 location3) 29)
          (= (distance location3 location1) 29)
          (= (distance location1 location4) 33)
          (= (distance location4 location1) 33)
          (= (distance location1 location5) 1)
          (= (distance location5 location1) 1)
          (= (distance location1 location6) 62)
          (= (distance location6 location1) 62)
          (= (distance location1 location7) 59)
          (= (distance location7 location1) 59)
          (= (distance location1 location8) 67)
          (= (distance location8 location1) 67)
          (= (distance location1 location9) 64)
          (= (distance location9 location1) 64)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 25)
          (= (distance location3 location2) 25)
          (= (distance location2 location4) 41)
          (= (distance location4 location2) 41)
          (= (distance location2 location5) 24)
          (= (distance location5 location2) 24)
          (= (distance location2 location6) 42)
          (= (distance location6 location2) 42)
          (= (distance location2 location7) 69)
          (= (distance location7 location2) 69)
          (= (distance location2 location8) 67)
          (= (distance location8 location2) 67)
          (= (distance location2 location9) 59)
          (= (distance location9 location2) 59)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 26)
          (= (distance location4 location3) 26)
          (= (distance location3 location5) 59)
          (= (distance location5 location3) 59)
          (= (distance location3 location6) 37)
          (= (distance location6 location3) 37)
          (= (distance location3 location7) 50)
          (= (distance location7 location3) 50)
          (= (distance location3 location8) 29)
          (= (distance location8 location3) 29)
          (= (distance location3 location9) 37)
          (= (distance location9 location3) 37)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 51)
          (= (distance location5 location4) 51)
          (= (distance location4 location6) 39)
          (= (distance location6 location4) 39)
          (= (distance location4 location7) 55)
          (= (distance location7 location4) 55)
          (= (distance location4 location8) 64)
          (= (distance location8 location4) 64)
          (= (distance location4 location9) 9)
          (= (distance location9 location4) 9)
          (= (distance location4 location4) 0)
          (= (distance location5 location6) 12)
          (= (distance location6 location5) 12)
          (= (distance location5 location7) 46)
          (= (distance location7 location5) 46)
          (= (distance location5 location8) 56)
          (= (distance location8 location5) 56)
          (= (distance location5 location9) 48)
          (= (distance location9 location5) 48)
          (= (distance location5 location5) 0)
          (= (distance location6 location7) 0)
          (= (distance location7 location6) 0)
          (= (distance location6 location8) 59)
          (= (distance location8 location6) 59)
          (= (distance location6 location9) 2)
          (= (distance location9 location6) 2)
          (= (distance location6 location6) 0)
          (= (distance location7 location8) 17)
          (= (distance location8 location7) 17)
          (= (distance location7 location9) 19)
          (= (distance location9 location7) 19)
          (= (distance location7 location7) 0)
          (= (distance location8 location9) 49)
          (= (distance location9 location8) 49)
          (= (distance location8 location8) 0)
          (= (distance location9 location9) 0)
          (typev truck0 tanker)
          (typevp truck0 truck)
          (at-vehicle truck0 location4)
          (= (gas-left truck0) 287)
          (= (gpm truck0) 3)
          (= (length-v truck0) 5)
          (= (height-v truck0) 9)
          (= (width-v truck0) 1)
          (= (weight-cap-v truck0) 265)
          (= (volume-cap-v truck0) 37)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 11)
          (availablev truck0)
          (typev truck1 tanker)
          (typevp truck1 truck)
          (at-vehicle truck1 location9)
          (= (gas-left truck1) 556)
          (= (gpm truck1) 1)
          (= (length-v truck1) 9)
          (= (height-v truck1) 8)
          (= (width-v truck1) 6)
          (= (weight-cap-v truck1) 299)
          (= (volume-cap-v truck1) 302)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 29)
          (availablev truck1)
          (typev truck2 tanker)
          (typevp truck2 truck)
          (at-vehicle truck2 location5)
          (= (gas-left truck2) 587)
          (= (gpm truck2) 3)
          (= (length-v truck2) 16)
          (= (height-v truck2) 3)
          (= (width-v truck2) 1)
          (= (weight-cap-v truck2) 416)
          (= (volume-cap-v truck2) 48)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 34)
          (availablev truck2)
          (typev truck3 tanker)
          (typevp truck3 truck)
          (at-vehicle truck3 location6)
          (= (gas-left truck3) 147)
          (= (gpm truck3) 1)
          (= (length-v truck3) 11)
          (= (height-v truck3) 4)
          (= (width-v truck3) 8)
          (= (weight-cap-v truck3) 503)
          (= (volume-cap-v truck3) 246)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 17)
          (availablev truck3)
          (typev truck4 auto)
          (typevp truck4 truck)
          (at-vehicle truck4 location8)
          (= (gas-left truck4) 563)
          (= (gpm truck4) 3)
          (= (length-v truck4) 19)
          (= (height-v truck4) 1)
          (= (width-v truck4) 5)
          (= (weight-cap-v truck4) 225)
          (= (volume-cap-v truck4) 95)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 13)
          (availablev truck4)
          (typev truck5 tanker)
          (typevp truck5 truck)
          (at-vehicle truck5 location4)
          (= (gas-left truck5) 381)
          (= (gpm truck5) 2)
          (= (length-v truck5) 8)
          (= (height-v truck5) 8)
          (= (width-v truck5) 6)
          (= (weight-cap-v truck5) 41)
          (= (volume-cap-v truck5) 268)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 22)
          (availablev truck5)
          (typev truck6 hopper)
          (typevp truck6 truck)
          (at-vehicle truck6 location8)
          (= (gas-left truck6) 417)
          (= (gpm truck6) 3)
          (= (length-v truck6) 19)
          (= (height-v truck6) 5)
          (= (width-v truck6) 2)
          (= (weight-cap-v truck6) 99)
          (= (volume-cap-v truck6) 190)
          (= (weight-load-v truck6) 0)
          (= (volume-load-v truck6) 0)
          (= (weight-v truck6) 26)
          (availablev truck6)
          (typev truck7 tanker)
          (typevp truck7 truck)
          (at-vehicle truck7 location9)
          (= (gas-left truck7) 484)
          (= (gpm truck7) 3)
          (= (length-v truck7) 5)
          (= (height-v truck7) 2)
          (= (width-v truck7) 3)
          (= (weight-cap-v truck7) 270)
          (= (volume-cap-v truck7) 30)
          (= (weight-load-v truck7) 0)
          (= (volume-load-v truck7) 0)
          (= (weight-v truck7) 37)
          (availablev truck7)
          (typev truck8 tanker)
          (typevp truck8 truck)
          (at-vehicle truck8 location3)
          (= (gas-left truck8) 204)
          (= (gpm truck8) 1)
          (= (length-v truck8) 11)
          (= (height-v truck8) 2)
          (= (width-v truck8) 6)
          (= (weight-cap-v truck8) 492)
          (= (volume-cap-v truck8) 132)
          (= (weight-load-v truck8) 0)
          (= (volume-load-v truck8) 0)
          (= (weight-v truck8) 35)
          (availablev truck8)
          (typev truck9 tanker)
          (typevp truck9 truck)
          (at-vehicle truck9 location1)
          (= (gas-left truck9) 214)
          (= (gpm truck9) 3)
          (= (length-v truck9) 15)
          (= (height-v truck9) 1)
          (= (width-v truck9) 6)
          (= (weight-cap-v truck9) 192)
          (= (volume-cap-v truck9) 90)
          (= (weight-load-v truck9) 0)
          (= (volume-load-v truck9) 0)
          (= (weight-v truck9) 24)
          (availablev truck9)
          (typev train0 tanker)
          (typevp train0 train)
          (at-vehicle train0 location0)
          (= (gas-left train0) 223)
          (= (gpm train0) 3)
          (= (length-v train0) 11)
          (= (height-v train0) 6)
          (= (width-v train0) 8)
          (= (weight-cap-v train0) 240)
          (= (volume-cap-v train0) 410)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 10)
          (availablev train0)
          (typev train1 tanker)
          (typevp train1 train)
          (at-vehicle train1 location0)
          (= (gas-left train1) 542)
          (= (gpm train1) 2)
          (= (length-v train1) 6)
          (= (height-v train1) 1)
          (= (width-v train1) 5)
          (= (weight-cap-v train1) 418)
          (= (volume-cap-v train1) 30)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 17)
          (availablev train1)
          (typev train2 tanker)
          (typevp train2 train)
          (at-vehicle train2 location7)
          (= (gas-left train2) 442)
          (= (gpm train2) 2)
          (= (length-v train2) 10)
          (= (height-v train2) 7)
          (= (width-v train2) 8)
          (= (weight-cap-v train2) 37)
          (= (volume-cap-v train2) 392)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 12)
          (availablev train2)
          (typev train3 tanker)
          (typevp train3 train)
          (at-vehicle train3 location7)
          (= (gas-left train3) 103)
          (= (gpm train3) 2)
          (= (length-v train3) 10)
          (= (height-v train3) 3)
          (= (width-v train3) 4)
          (= (weight-cap-v train3) 247)
          (= (volume-cap-v train3) 120)
          (= (weight-load-v train3) 0)
          (= (volume-load-v train3) 0)
          (= (weight-v train3) 10)
          (availablev train3)
          (typev train4 tanker)
          (typevp train4 train)
          (at-vehicle train4 location7)
          (= (gas-left train4) 276)
          (= (gpm train4) 2)
          (= (length-v train4) 14)
          (= (height-v train4) 5)
          (= (width-v train4) 1)
          (= (weight-cap-v train4) 328)
          (= (volume-cap-v train4) 70)
          (= (weight-load-v train4) 0)
          (= (volume-load-v train4) 0)
          (= (weight-v train4) 35)
          (availablev train4)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location5)
          (= (gas-left airplane0) 429)
          (= (gpm airplane0) 2)
          (= (length-v airplane0) 19)
          (= (height-v airplane0) 4)
          (= (width-v airplane0) 2)
          (= (weight-cap-v airplane0) 481)
          (= (volume-cap-v airplane0) 106)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 30)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location5)
          (= (gas-left airplane1) 203)
          (= (gpm airplane1) 2)
          (= (length-v airplane1) 11)
          (= (height-v airplane1) 4)
          (= (width-v airplane1) 10)
          (= (weight-cap-v airplane1) 408)
          (= (volume-cap-v airplane1) 403)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 31)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location6)
          (= (gas-left airplane2) 328)
          (= (gpm airplane2) 2)
          (= (length-v airplane2) 10)
          (= (height-v airplane2) 7)
          (= (width-v airplane2) 2)
          (= (weight-cap-v airplane2) 73)
          (= (volume-cap-v airplane2) 140)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 13)
          (availablev airplane2)
          (typev airplane3 air)
          (typevp airplane3 airplane)
          (at-vehicle airplane3 location1)
          (= (gas-left airplane3) 115)
          (= (gpm airplane3) 1)
          (= (length-v airplane3) 11)
          (= (height-v airplane3) 3)
          (= (width-v airplane3) 8)
          (= (weight-cap-v airplane3) 332)
          (= (volume-cap-v airplane3) 184)
          (= (weight-load-v airplane3) 0)
          (= (volume-load-v airplane3) 0)
          (= (weight-v airplane3) 20)
          (availablev airplane3)
          (typev airplane4 air)
          (typevp airplane4 airplane)
          (at-vehicle airplane4 location9)
          (= (gas-left airplane4) 155)
          (= (gpm airplane4) 3)
          (= (length-v airplane4) 12)
          (= (height-v airplane4) 8)
          (= (width-v airplane4) 9)
          (= (weight-cap-v airplane4) 193)
          (= (volume-cap-v airplane4) 604)
          (= (weight-load-v airplane4) 0)
          (= (volume-load-v airplane4) 0)
          (= (weight-v airplane4) 10)
          (availablev airplane4)
          (at-equipment plane_ramp0 location1)
          (at-equipment plane_ramp1 location5)
          (at-equipment plane_ramp2 location6)
          (at-equipment plane_ramp3 location9)
          (typep package0 liquid)
          (at-packagel package0 location7)
          (= (volume-p package0) 18)
          (= (weight-p package0) 23)
          (typep package1 liquid)
          (at-packagel package1 location1)
          (= (volume-p package1) 6)
          (= (weight-p package1) 15)
          (typep package2 liquid)
          (at-packagel package2 location4)
          (= (volume-p package2) 13)
          (= (weight-p package2) 21)
          (typep package3 liquid)
          (at-packagel package3 location6)
          (= (volume-p package3) 10)
          (= (weight-p package3) 11)
          (typep package4 liquid)
          (at-packagel package4 location6)
          (= (volume-p package4) 6)
          (= (weight-p package4) 13)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 6)
          (= (weight-cap-r road_route0) 475)
          (availabler road_route0)
          (connect-city road_route1 road-route city0 city2)
          (= (height-cap-r road_route1) 29)
          (= (weight-cap-r road_route1) 240)
          (availabler road_route1)
          (connect-city road_route2 road-route city0 city3)
          (= (height-cap-r road_route2) 10)
          (= (weight-cap-r road_route2) 188)
          (availabler road_route2)
          (connect-city road_route3 road-route city1 city0)
          (= (height-cap-r road_route3) 33)
          (= (weight-cap-r road_route3) 485)
          (availabler road_route3)
          (connect-city road_route4 road-route city1 city2)
          (= (height-cap-r road_route4) 24)
          (= (weight-cap-r road_route4) 441)
          (availabler road_route4)
          (connect-city road_route5 road-route city1 city3)
          (= (height-cap-r road_route5) 8)
          (= (weight-cap-r road_route5) 358)
          (availabler road_route5)
          (connect-city road_route6 road-route city2 city0)
          (= (height-cap-r road_route6) 7)
          (= (weight-cap-r road_route6) 241)
          (availabler road_route6)
          (connect-city road_route7 road-route city2 city1)
          (= (height-cap-r road_route7) 14)
          (= (weight-cap-r road_route7) 350)
          (availabler road_route7)
          (connect-city road_route8 road-route city2 city3)
          (= (height-cap-r road_route8) 31)
          (= (weight-cap-r road_route8) 397)
          (availabler road_route8)
          (connect-city road_route9 road-route city3 city0)
          (= (height-cap-r road_route9) 15)
          (= (weight-cap-r road_route9) 442)
          (availabler road_route9)
          (connect-city road_route10 road-route city3 city2)
          (= (height-cap-r road_route10) 23)
          (= (weight-cap-r road_route10) 530)
          (availabler road_route10)
          (connect-loc rail_route0 rail-route location0 location2)
          (= (height-cap-r rail_route0) 5)
          (= (weight-cap-r rail_route0) 248)
          (serves location0 region0)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location0 location7)
          (= (height-cap-r rail_route1) 29)
          (= (weight-cap-r rail_route1) 322)
          (serves location7 region1)
          (availabler rail_route1)
          (connect-loc rail_route2 rail-route location2 location0)
          (= (height-cap-r rail_route2) 10)
          (= (weight-cap-r rail_route2) 483)
          (availabler rail_route2)
          (connect-loc rail_route3 rail-route location2 location7)
          (= (height-cap-r rail_route3) 22)
          (= (weight-cap-r rail_route3) 287)
          (serves location7 region0)
          (availabler rail_route3)
          (connect-loc rail_route4 rail-route location7 location0)
          (= (height-cap-r rail_route4) 23)
          (= (weight-cap-r rail_route4) 59)
          (availabler rail_route4)
          (connect-loc air_route0 air-route location1 location5)
          (= (height-cap-r air_route0) 11)
          (= (weight-cap-r air_route0) 69)
          (serves location5 region1)
          (availabler air_route0)
          (connect-loc air_route1 air-route location1 location6)
          (= (height-cap-r air_route1) 27)
          (= (weight-cap-r air_route1) 436)
          (availabler air_route1)
          (connect-loc air_route2 air-route location5 location1)
          (= (height-cap-r air_route2) 33)
          (= (weight-cap-r air_route2) 299)
          (availabler air_route2)
          (connect-loc air_route3 air-route location5 location6)
          (= (height-cap-r air_route3) 12)
          (= (weight-cap-r air_route3) 232)
          (availabler air_route3)
          (connect-loc air_route4 air-route location5 location9)
          (= (height-cap-r air_route4) 15)
          (= (weight-cap-r air_route4) 272)
          (availabler air_route4)
          (connect-loc air_route5 air-route location6 location1)
          (= (height-cap-r air_route5) 6)
          (= (weight-cap-r air_route5) 525)
          (availabler air_route5)
          (connect-loc air_route6 air-route location6 location5)
          (= (height-cap-r air_route6) 8)
          (= (weight-cap-r air_route6) 495)
          (availabler air_route6)
          (connect-loc air_route7 air-route location6 location9)
          (= (height-cap-r air_route7) 26)
          (= (weight-cap-r air_route7) 233)
          (availabler air_route7)
          (connect-loc air_route8 air-route location9 location1)
          (= (height-cap-r air_route8) 22)
          (= (weight-cap-r air_route8) 390)
          (availabler air_route8)
          (connect-loc air_route9 air-route location9 location5)
          (= (height-cap-r air_route9) 27)
          (= (weight-cap-r air_route9) 483)
          (availabler air_route9)
          (connect-loc air_route10 air-route location9 location6)
          (= (height-cap-r air_route10) 28)
          (= (weight-cap-r air_route10) 347)
          (availabler air_route10)
          (= (volume-load-l location0) 0)
          (= (volume-load-l location1) 6)
          (= (volume-load-l location2) 0)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 13)
          (= (volume-load-l location5) 0)
          (= (volume-load-l location6) 16)
          (= (volume-load-l location7) 18)
          (= (volume-load-l location8) 0)
          (= (volume-load-l location9) 0)
   )

   (:goal (and (delivered package0 location7)
               (delivered package1 location7)
               (delivered package2 location1)
               (delivered package3 location2)
               (delivered package4 location9)
               (clear)))

)