(define (problem problem4)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 - region
          city0 city1 - city
          location0 location1 location2 location3 location4 location5 - location
          truck0 truck1 truck2 truck3 truck4 truck5 train0 train1 train2 airplane0 airplane1 airplane2 - vehicle
          plane_ramp0 plane_ramp1 plane_ramp2 - plane-ramp
          package0 package1 package2 - package
          road_route0 road_route1 - route
          rail_route0 rail_route1 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region0)
          (= (local-height city0) 15)
          (= (local-weight city0) 344)
          (in-region city1 region0)
          (= (local-height city1) 33)
          (= (local-weight city1) 471)
          (in-city location0 city0)
          (= (height-cap-l location0) 21)
          (= (length-cap-l location0) 41)
          (= (width-cap-l location0) 30)
          (= (volume-cap-l location0) 464)
          (in-city location1 city1)
          (= (height-cap-l location1) 22)
          (= (length-cap-l location1) 13)
          (= (width-cap-l location1) 32)
          (= (volume-cap-l location1) 424)
          (tcenter location1)
          (typel location1 airport)
          (hub location1)
          (in-city location2 city0)
          (= (height-cap-l location2) 19)
          (= (length-cap-l location2) 23)
          (= (width-cap-l location2) 35)
          (= (volume-cap-l location2) 284)
          (tcenter location2)
          (typel location2 train-station)
          (availablel location2)
          (hub location2)
          (in-city location3 city1)
          (= (height-cap-l location3) 30)
          (= (length-cap-l location3) 14)
          (= (width-cap-l location3) 15)
          (= (volume-cap-l location3) 299)
          (tcenter location3)
          (typel location3 airport)
          (availablel location3)
          (hub location3)
          (in-city location4 city0)
          (= (height-cap-l location4) 34)
          (= (length-cap-l location4) 14)
          (= (width-cap-l location4) 34)
          (= (volume-cap-l location4) 289)
          (tcenter location4)
          (typel location4 train-station)
          (availablel location4)
          (in-city location5 city0)
          (= (height-cap-l location5) 14)
          (= (length-cap-l location5) 42)
          (= (width-cap-l location5) 13)
          (= (volume-cap-l location5) 333)
          (tcenter location5)
          (typel location5 airport)
          (= (distance location0 location1) 32)
          (= (distance location1 location0) 32)
          (= (distance location0 location2) 13)
          (= (distance location2 location0) 13)
          (= (distance location0 location3) 63)
          (= (distance location3 location0) 63)
          (= (distance location0 location4) 42)
          (= (distance location4 location0) 42)
          (= (distance location0 location5) 10)
          (= (distance location5 location0) 10)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 46)
          (= (distance location2 location1) 46)
          (= (distance location1 location3) 8)
          (= (distance location3 location1) 8)
          (= (distance location1 location4) 1)
          (= (distance location4 location1) 1)
          (= (distance location1 location5) 9)
          (= (distance location5 location1) 9)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 39)
          (= (distance location3 location2) 39)
          (= (distance location2 location4) 27)
          (= (distance location4 location2) 27)
          (= (distance location2 location5) 39)
          (= (distance location5 location2) 39)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 18)
          (= (distance location4 location3) 18)
          (= (distance location3 location5) 21)
          (= (distance location5 location3) 21)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 1)
          (= (distance location5 location4) 1)
          (= (distance location4 location4) 0)
          (= (distance location5 location5) 0)
          (typev truck0 regularv)
          (typevp truck0 truck)
          (at-vehicle truck0 location1)
          (= (gas-left truck0) 129)
          (= (gpm truck0) 2)
          (= (length-v truck0) 13)
          (= (height-v truck0) 6)
          (= (width-v truck0) 6)
          (= (weight-cap-v truck0) 145)
          (= (volume-cap-v truck0) 327)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 32)
          (availablev truck0)
          (typev truck1 regularv)
          (typevp truck1 truck)
          (at-vehicle truck1 location2)
          (= (gas-left truck1) 249)
          (= (gpm truck1) 1)
          (= (length-v truck1) 12)
          (= (height-v truck1) 10)
          (= (width-v truck1) 7)
          (= (weight-cap-v truck1) 39)
          (= (volume-cap-v truck1) 587)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 23)
          (availablev truck1)
          (typev truck2 regularv)
          (typevp truck2 truck)
          (at-vehicle truck2 location0)
          (= (gas-left truck2) 277)
          (= (gpm truck2) 3)
          (= (length-v truck2) 10)
          (= (height-v truck2) 7)
          (= (width-v truck2) 6)
          (= (weight-cap-v truck2) 418)
          (= (volume-cap-v truck2) 420)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 37)
          (availablev truck2)
          (typev truck3 regularv)
          (typevp truck3 truck)
          (at-vehicle truck3 location5)
          (= (gas-left truck3) 449)
          (= (gpm truck3) 3)
          (= (length-v truck3) 16)
          (= (height-v truck3) 2)
          (= (width-v truck3) 2)
          (= (weight-cap-v truck3) 448)
          (= (volume-cap-v truck3) 64)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 24)
          (availablev truck3)
          (typev truck4 regularv)
          (typevp truck4 truck)
          (at-vehicle truck4 location3)
          (= (gas-left truck4) 476)
          (= (gpm truck4) 2)
          (= (length-v truck4) 13)
          (= (height-v truck4) 9)
          (= (width-v truck4) 9)
          (= (weight-cap-v truck4) 160)
          (= (volume-cap-v truck4) 737)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 12)
          (availablev truck4)
          (typev truck5 regularv)
          (typevp truck5 truck)
          (at-vehicle truck5 location4)
          (= (gas-left truck5) 577)
          (= (gpm truck5) 1)
          (= (length-v truck5) 11)
          (= (height-v truck5) 2)
          (= (width-v truck5) 6)
          (= (weight-cap-v truck5) 337)
          (= (volume-cap-v truck5) 92)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 35)
          (availablev truck5)
          (typev train0 regularv)
          (typevp train0 train)
          (at-vehicle train0 location2)
          (= (gas-left train0) 215)
          (= (gpm train0) 1)
          (= (length-v train0) 15)
          (= (height-v train0) 1)
          (= (width-v train0) 1)
          (= (weight-cap-v train0) 350)
          (= (volume-cap-v train0) 15)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 33)
          (availablev train0)
          (typev train1 regularv)
          (typevp train1 train)
          (at-vehicle train1 location2)
          (= (gas-left train1) 397)
          (= (gpm train1) 1)
          (= (length-v train1) 6)
          (= (height-v train1) 6)
          (= (width-v train1) 2)
          (= (weight-cap-v train1) 510)
          (= (volume-cap-v train1) 72)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 30)
          (availablev train1)
          (typev train2 regularv)
          (typevp train2 train)
          (at-vehicle train2 location2)
          (= (gas-left train2) 516)
          (= (gpm train2) 3)
          (= (length-v train2) 8)
          (= (height-v train2) 8)
          (= (width-v train2) 3)
          (= (weight-cap-v train2) 330)
          (= (volume-cap-v train2) 192)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 19)
          (availablev train2)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location1)
          (= (gas-left airplane0) 59)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 13)
          (= (height-v airplane0) 7)
          (= (width-v airplane0) 1)
          (= (weight-cap-v airplane0) 120)
          (= (volume-cap-v airplane0) 91)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 15)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location1)
          (= (gas-left airplane1) 154)
          (= (gpm airplane1) 3)
          (= (length-v airplane1) 13)
          (= (height-v airplane1) 3)
          (= (width-v airplane1) 5)
          (= (weight-cap-v airplane1) 211)
          (= (volume-cap-v airplane1) 136)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 30)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location5)
          (= (gas-left airplane2) 400)
          (= (gpm airplane2) 3)
          (= (length-v airplane2) 8)
          (= (height-v airplane2) 2)
          (= (width-v airplane2) 2)
          (= (weight-cap-v airplane2) 174)
          (= (volume-cap-v airplane2) 32)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 38)
          (availablev airplane2)
          (at-equipment plane_ramp0 location1)
          (at-equipment plane_ramp1 location3)
          (at-equipment plane_ramp2 location5)
          (typep package0 mail)
          (at-packagel package0 location3)
          (= (volume-p package0) 7)
          (= (weight-p package0) 19)
          (typep package1 mail)
          (at-packagel package1 location0)
          (= (volume-p package1) 24)
          (= (weight-p package1) 23)
          (typep package2 mail)
          (at-packagel package2 location3)
          (= (volume-p package2) 15)
          (= (weight-p package2) 6)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 16)
          (= (weight-cap-r road_route0) 184)
          (availabler road_route0)
          (connect-city road_route1 road-route city1 city0)
          (= (height-cap-r road_route1) 9)
          (= (weight-cap-r road_route1) 496)
          (connect-loc rail_route0 rail-route location2 location4)
          (= (height-cap-r rail_route0) 18)
          (= (weight-cap-r rail_route0) 546)
          (serves location2 region0)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location4 location2)
          (= (height-cap-r rail_route1) 21)
          (= (weight-cap-r rail_route1) 493)
          (availabler rail_route1)
          (connect-loc air_route0 air-route location1 location3)
          (= (height-cap-r air_route0) 32)
          (= (weight-cap-r air_route0) 59)
          (serves location1 region0)
          (serves location3 region0)
          (connect-loc air_route1 air-route location1 location5)
          (= (height-cap-r air_route1) 32)
          (= (weight-cap-r air_route1) 340)
          (availabler air_route1)
          (connect-loc air_route2 air-route location3 location1)
          (= (height-cap-r air_route2) 31)
          (= (weight-cap-r air_route2) 328)
          (availabler air_route2)
          (connect-loc air_route3 air-route location3 location5)
          (= (height-cap-r air_route3) 15)
          (= (weight-cap-r air_route3) 503)
          (availabler air_route3)
          (connect-loc air_route4 air-route location5 location1)
          (= (height-cap-r air_route4) 23)
          (= (weight-cap-r air_route4) 432)
          (availabler air_route4)
          (connect-loc air_route5 air-route location5 location3)
          (= (height-cap-r air_route5) 16)
          (= (weight-cap-r air_route5) 520)
          (availabler air_route5)
          (= (volume-load-l location0) 24)
          (= (volume-load-l location1) 0)
          (= (volume-load-l location2) 0)
          (= (volume-load-l location3) 22)
          (= (volume-load-l location4) 0)
          (= (volume-load-l location5) 0)
   )

   (:goal (and (delivered package0 location5)
               (delivered package1 location0)
               (delivered package2 location0)
               (clear)))

) 