(define (problem problem2)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 region1 region2 region3 - region
          city0 city1 city2 city3 city4 city5 - city
          location0 location1 location2 location3 location4 location5 location6 location7 location8 location9 location10 location11 location12 location13 location14 location15 - location
          truck0 truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 truck11 truck12 truck13 truck14 truck15 train0 train1 train2 train3 train4 train5 train6 train7 airplane0 airplane1 airplane2 airplane3 airplane4 airplane5 airplane6 airplane7 - vehicle
          plane_ramp0 plane_ramp1 plane_ramp2 plane_ramp3 plane_ramp4 plane_ramp5 plane_ramp6 plane_ramp7 plane_ramp8 plane_ramp9 - plane-ramp
          package0 package1 package2 package3 package4 package5 package6 package7 - package
          road_route0 road_route1 road_route2 road_route3 road_route4 road_route5 road_route6 road_route7 road_route8 road_route9 road_route10 road_route11 road_route12 road_route13 road_route14 road_route15 road_route16 road_route17 road_route18 road_route19 road_route20 road_route21 road_route22 road_route23 road_route24 road_route25 road_route26 road_route27 road_route28 road_route29 - route
          rail_route0 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 air_route6 air_route7 air_route8 air_route9 air_route10 air_route11 air_route12 air_route13 air_route14 air_route15 air_route16 air_route17 air_route18 air_route19 air_route20 air_route21 air_route22 air_route23 air_route24 air_route25 air_route26 air_route27 air_route28 air_route29 air_route30 air_route31 air_route32 air_route33 air_route34 air_route35 air_route36 air_route37 air_route38 air_route39 air_route40 air_route41 air_route42 air_route43 air_route44 air_route45 air_route46 air_route47 air_route48 air_route49 air_route50 air_route51 air_route52 air_route53 air_route54 air_route55 air_route56 air_route57 air_route58 air_route59 air_route60 air_route61 air_route62 air_route63 air_route64 air_route65 air_route66 air_route67 air_route68 air_route69 air_route70 air_route71 air_route72 air_route73 air_route74 air_route75 air_route76 air_route77 air_route78 air_route79 air_route80 air_route81 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region2)
          (= (local-height city0) 32)
          (= (local-weight city0) 467)
          (in-region city1 region2)
          (= (local-height city1) 35)
          (= (local-weight city1) 191)
          (in-region city2 region3)
          (= (local-height city2) 25)
          (= (local-weight city2) 528)
          (in-region city3 region0)
          (= (local-height city3) 25)
          (= (local-weight city3) 160)
          (in-region city4 region1)
          (= (local-height city4) 12)
          (= (local-weight city4) 383)
          (in-region city5 region1)
          (= (local-height city5) 19)
          (= (local-weight city5) 476)
          (in-city location0 city2)
          (= (height-cap-l location0) 10)
          (= (length-cap-l location0) 48)
          (= (width-cap-l location0) 8)
          (= (volume-cap-l location0) 118)
          (tcenter location0)
          (typel location0 airport)
          (availablel location0)
          (hub location0)
          (in-city location1 city0)
          (= (height-cap-l location1) 19)
          (= (length-cap-l location1) 37)
          (= (width-cap-l location1) 33)
          (= (volume-cap-l location1) 153)
          (in-city location2 city4)
          (= (height-cap-l location2) 34)
          (= (length-cap-l location2) 14)
          (= (width-cap-l location2) 25)
          (= (volume-cap-l location2) 146)
          (tcenter location2)
          (typel location2 train-station)
          (availablel location2)
          (hub location2)
          (in-city location3 city5)
          (= (height-cap-l location3) 35)
          (= (length-cap-l location3) 39)
          (= (width-cap-l location3) 22)
          (= (volume-cap-l location3) 86)
          (tcenter location3)
          (typel location3 airport)
          (availablel location3)
          (in-city location4 city5)
          (= (height-cap-l location4) 28)
          (= (length-cap-l location4) 35)
          (= (width-cap-l location4) 19)
          (= (volume-cap-l location4) 222)
          (tcenter location4)
          (typel location4 airport)
          (availablel location4)
          (in-city location5 city2)
          (= (height-cap-l location5) 10)
          (= (length-cap-l location5) 45)
          (= (width-cap-l location5) 31)
          (= (volume-cap-l location5) 210)
          (in-city location6 city0)
          (= (height-cap-l location6) 20)
          (= (length-cap-l location6) 29)
          (= (width-cap-l location6) 14)
          (= (volume-cap-l location6) 423)
          (tcenter location6)
          (typel location6 airport)
          (availablel location6)
          (in-city location7 city0)
          (= (height-cap-l location7) 19)
          (= (length-cap-l location7) 24)
          (= (width-cap-l location7) 14)
          (= (volume-cap-l location7) 378)
          (tcenter location7)
          (typel location7 airport)
          (availablel location7)
          (in-city location8 city5)
          (= (height-cap-l location8) 20)
          (= (length-cap-l location8) 26)
          (= (width-cap-l location8) 8)
          (= (volume-cap-l location8) 478)
          (tcenter location8)
          (typel location8 airport)
          (availablel location8)
          (in-city location9 city2)
          (= (height-cap-l location9) 12)
          (= (length-cap-l location9) 29)
          (= (width-cap-l location9) 15)
          (= (volume-cap-l location9) 431)
          (tcenter location9)
          (typel location9 airport)
          (availablel location9)
          (hub location9)
          (in-city location10 city0)
          (= (height-cap-l location10) 20)
          (= (length-cap-l location10) 12)
          (= (width-cap-l location10) 32)
          (= (volume-cap-l location10) 168)
          (in-city location11 city2)
          (= (height-cap-l location11) 33)
          (= (length-cap-l location11) 40)
          (= (width-cap-l location11) 26)
          (= (volume-cap-l location11) 232)
          (tcenter location11)
          (typel location11 train-station)
          (availablel location11)
          (in-city location12 city1)
          (= (height-cap-l location12) 33)
          (= (length-cap-l location12) 35)
          (= (width-cap-l location12) 19)
          (= (volume-cap-l location12) 371)
          (tcenter location12)
          (typel location12 airport)
          (availablel location12)
          (hub location12)
          (in-city location13 city5)
          (= (height-cap-l location13) 36)
          (= (length-cap-l location13) 19)
          (= (width-cap-l location13) 7)
          (= (volume-cap-l location13) 465)
          (tcenter location13)
          (typel location13 airport)
          (availablel location13)
          (hub location13)
          (in-city location14 city3)
          (= (height-cap-l location14) 8)
          (= (length-cap-l location14) 13)
          (= (width-cap-l location14) 27)
          (= (volume-cap-l location14) 475)
          (in-city location15 city4)
          (= (height-cap-l location15) 10)
          (= (length-cap-l location15) 10)
          (= (width-cap-l location15) 17)
          (= (volume-cap-l location15) 407)
          (tcenter location15)
          (typel location15 airport)
          (availablel location15)
          (hub location15)
          (= (distance location0 location1) 28)
          (= (distance location1 location0) 28)
          (= (distance location0 location2) 32)
          (= (distance location2 location0) 32)
          (= (distance location0 location3) 1)
          (= (distance location3 location0) 1)
          (= (distance location0 location4) 26)
          (= (distance location4 location0) 26)
          (= (distance location0 location5) 54)
          (= (distance location5 location0) 54)
          (= (distance location0 location6) 29)
          (= (distance location6 location0) 29)
          (= (distance location0 location7) 58)
          (= (distance location7 location0) 58)
          (= (distance location0 location8) 25)
          (= (distance location8 location0) 25)
          (= (distance location0 location9) 50)
          (= (distance location9 location0) 50)
          (= (distance location0 location10) 39)
          (= (distance location10 location0) 39)
          (= (distance location0 location11) 35)
          (= (distance location11 location0) 35)
          (= (distance location0 location12) 31)
          (= (distance location12 location0) 31)
          (= (distance location0 location13) 33)
          (= (distance location13 location0) 33)
          (= (distance location0 location14) 58)
          (= (distance location14 location0) 58)
          (= (distance location0 location15) 25)
          (= (distance location15 location0) 25)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 51)
          (= (distance location2 location1) 51)
          (= (distance location1 location3) 38)
          (= (distance location3 location1) 38)
          (= (distance location1 location4) 69)
          (= (distance location4 location1) 69)
          (= (distance location1 location5) 27)
          (= (distance location5 location1) 27)
          (= (distance location1 location6) 14)
          (= (distance location6 location1) 14)
          (= (distance location1 location7) 21)
          (= (distance location7 location1) 21)
          (= (distance location1 location8) 53)
          (= (distance location8 location1) 53)
          (= (distance location1 location9) 56)
          (= (distance location9 location1) 56)
          (= (distance location1 location10) 69)
          (= (distance location10 location1) 69)
          (= (distance location1 location11) 58)
          (= (distance location11 location1) 58)
          (= (distance location1 location12) 24)
          (= (distance location12 location1) 24)
          (= (distance location1 location13) 57)
          (= (distance location13 location1) 57)
          (= (distance location1 location14) 47)
          (= (distance location14 location1) 47)
          (= (distance location1 location15) 3)
          (= (distance location15 location1) 3)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 0)
          (= (distance location3 location2) 0)
          (= (distance location2 location4) 44)
          (= (distance location4 location2) 44)
          (= (distance location2 location5) 44)
          (= (distance location5 location2) 44)
          (= (distance location2 location6) 69)
          (= (distance location6 location2) 69)
          (= (distance location2 location7) 69)
          (= (distance location7 location2) 69)
          (= (distance location2 location8) 33)
          (= (distance location8 location2) 33)
          (= (distance location2 location9) 54)
          (= (distance location9 location2) 54)
          (= (distance location2 location10) 41)
          (= (distance location10 location2) 41)
          (= (distance location2 location11) 29)
          (= (distance location11 location2) 29)
          (= (distance location2 location12) 17)
          (= (distance location12 location2) 17)
          (= (distance location2 location13) 34)
          (= (distance location13 location2) 34)
          (= (distance location2 location14) 52)
          (= (distance location14 location2) 52)
          (= (distance location2 location15) 2)
          (= (distance location15 location2) 2)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 19)
          (= (distance location4 location3) 19)
          (= (distance location3 location5) 47)
          (= (distance location5 location3) 47)
          (= (distance location3 location6) 37)
          (= (distance location6 location3) 37)
          (= (distance location3 location7) 59)
          (= (distance location7 location3) 59)
          (= (distance location3 location8) 9)
          (= (distance location8 location3) 9)
          (= (distance location3 location9) 69)
          (= (distance location9 location3) 69)
          (= (distance location3 location10) 65)
          (= (distance location10 location3) 65)
          (= (distance location3 location11) 62)
          (= (distance location11 location3) 62)
          (= (distance location3 location12) 9)
          (= (distance location12 location3) 9)
          (= (distance location3 location13) 39)
          (= (distance location13 location3) 39)
          (= (distance location3 location14) 25)
          (= (distance location14 location3) 25)
          (= (distance location3 location15) 12)
          (= (distance location15 location3) 12)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 21)
          (= (distance location5 location4) 21)
          (= (distance location4 location6) 66)
          (= (distance location6 location4) 66)
          (= (distance location4 location7) 26)
          (= (distance location7 location4) 26)
          (= (distance location4 location8) 6)
          (= (distance location8 location4) 6)
          (= (distance location4 location9) 36)
          (= (distance location9 location4) 36)
          (= (distance location4 location10) 57)
          (= (distance location10 location4) 57)
          (= (distance location4 location11) 59)
          (= (distance location11 location4) 59)
          (= (distance location4 location12) 48)
          (= (distance location12 location4) 48)
          (= (distance location4 location13) 63)
          (= (distance location13 location4) 63)
          (= (distance location4 location14) 30)
          (= (distance location14 location4) 30)
          (= (distance location4 location15) 54)
          (= (distance location15 location4) 54)
          (= (distance location4 location4) 0)
          (= (distance location5 location6) 16)
          (= (distance location6 location5) 16)
          (= (distance location5 location7) 60)
          (= (distance location7 location5) 60)
          (= (distance location5 location8) 66)
          (= (distance location8 location5) 66)
          (= (distance location5 location9) 28)
          (= (distance location9 location5) 28)
          (= (distance location5 location10) 13)
          (= (distance location10 location5) 13)
          (= (distance location5 location11) 65)
          (= (distance location11 location5) 65)
          (= (distance location5 location12) 56)
          (= (distance location12 location5) 56)
          (= (distance location5 location13) 34)
          (= (distance location13 location5) 34)
          (= (distance location5 location14) 33)
          (= (distance location14 location5) 33)
          (= (distance location5 location15) 57)
          (= (distance location15 location5) 57)
          (= (distance location5 location5) 0)
          (= (distance location6 location7) 39)
          (= (distance location7 location6) 39)
          (= (distance location6 location8) 32)
          (= (distance location8 location6) 32)
          (= (distance location6 location9) 5)
          (= (distance location9 location6) 5)
          (= (distance location6 location10) 53)
          (= (distance location10 location6) 53)
          (= (distance location6 location11) 56)
          (= (distance location11 location6) 56)
          (= (distance location6 location12) 13)
          (= (distance location12 location6) 13)
          (= (distance location6 location13) 50)
          (= (distance location13 location6) 50)
          (= (distance location6 location14) 19)
          (= (distance location14 location6) 19)
          (= (distance location6 location15) 43)
          (= (distance location15 location6) 43)
          (= (distance location6 location6) 0)
          (= (distance location7 location8) 8)
          (= (distance location8 location7) 8)
          (= (distance location7 location9) 1)
          (= (distance location9 location7) 1)
          (= (distance location7 location10) 52)
          (= (distance location10 location7) 52)
          (= (distance location7 location11) 29)
          (= (distance location11 location7) 29)
          (= (distance location7 location12) 6)
          (= (distance location12 location7) 6)
          (= (distance location7 location13) 34)
          (= (distance location13 location7) 34)
          (= (distance location7 location14) 25)
          (= (distance location14 location7) 25)
          (= (distance location7 location15) 25)
          (= (distance location15 location7) 25)
          (= (distance location7 location7) 0)
          (= (distance location8 location9) 60)
          (= (distance location9 location8) 60)
          (= (distance location8 location10) 61)
          (= (distance location10 location8) 61)
          (= (distance location8 location11) 64)
          (= (distance location11 location8) 64)
          (= (distance location8 location12) 52)
          (= (distance location12 location8) 52)
          (= (distance location8 location13) 17)
          (= (distance location13 location8) 17)
          (= (distance location8 location14) 20)
          (= (distance location14 location8) 20)
          (= (distance location8 location15) 61)
          (= (distance location15 location8) 61)
          (= (distance location8 location8) 0)
          (= (distance location9 location10) 57)
          (= (distance location10 location9) 57)
          (= (distance location9 location11) 45)
          (= (distance location11 location9) 45)
          (= (distance location9 location12) 24)
          (= (distance location12 location9) 24)
          (= (distance location9 location13) 67)
          (= (distance location13 location9) 67)
          (= (distance location9 location14) 15)
          (= (distance location14 location9) 15)
          (= (distance location9 location15) 63)
          (= (distance location15 location9) 63)
          (= (distance location9 location9) 0)
          (= (distance location10 location11) 48)
          (= (distance location11 location10) 48)
          (= (distance location10 location12) 7)
          (= (distance location12 location10) 7)
          (= (distance location10 location13) 60)
          (= (distance location13 location10) 60)
          (= (distance location10 location14) 2)
          (= (distance location14 location10) 2)
          (= (distance location10 location15) 11)
          (= (distance location15 location10) 11)
          (= (distance location10 location10) 0)
          (= (distance location11 location12) 46)
          (= (distance location12 location11) 46)
          (= (distance location11 location13) 64)
          (= (distance location13 location11) 64)
          (= (distance location11 location14) 5)
          (= (distance location14 location11) 5)
          (= (distance location11 location15) 47)
          (= (distance location15 location11) 47)
          (= (distance location11 location11) 0)
          (= (distance location12 location13) 42)
          (= (distance location13 location12) 42)
          (= (distance location12 location14) 68)
          (= (distance location14 location12) 68)
          (= (distance location12 location15) 7)
          (= (distance location15 location12) 7)
          (= (distance location12 location12) 0)
          (= (distance location13 location14) 62)
          (= (distance location14 location13) 62)
          (= (distance location13 location15) 43)
          (= (distance location15 location13) 43)
          (= (distance location13 location13) 0)
          (= (distance location14 location15) 50)
          (= (distance location15 location14) 50)
          (= (distance location14 location14) 0)
          (= (distance location15 location15) 0)
          (typev truck0 auto)
          (typevp truck0 truck)
          (at-vehicle truck0 location12)
          (= (gas-left truck0) 254)
          (= (gpm truck0) 1)
          (= (length-v truck0) 10)
          (= (height-v truck0) 5)
          (= (width-v truck0) 4)
          (= (weight-cap-v truck0) 366)
          (= (volume-cap-v truck0) 184)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 33)
          (availablev truck0)
          (typev truck1 auto)
          (typevp truck1 truck)
          (at-vehicle truck1 location1)
          (= (gas-left truck1) 575)
          (= (gpm truck1) 1)
          (= (length-v truck1) 19)
          (= (height-v truck1) 2)
          (= (width-v truck1) 2)
          (= (weight-cap-v truck1) 382)
          (= (volume-cap-v truck1) 76)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 29)
          (availablev truck1)
          (typev truck2 auto)
          (typevp truck2 truck)
          (at-vehicle truck2 location7)
          (= (gas-left truck2) 533)
          (= (gpm truck2) 1)
          (= (length-v truck2) 18)
          (= (height-v truck2) 5)
          (= (width-v truck2) 7)
          (= (weight-cap-v truck2) 71)
          (= (volume-cap-v truck2) 441)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 11)
          (availablev truck2)
          (typev truck3 auto)
          (typevp truck3 truck)
          (at-vehicle truck3 location13)
          (= (gas-left truck3) 258)
          (= (gpm truck3) 1)
          (= (length-v truck3) 12)
          (= (height-v truck3) 8)
          (= (width-v truck3) 7)
          (= (weight-cap-v truck3) 337)
          (= (volume-cap-v truck3) 470)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 36)
          (availablev truck3)
          (typev truck4 auto)
          (typevp truck4 truck)
          (at-vehicle truck4 location12)
          (= (gas-left truck4) 201)
          (= (gpm truck4) 1)
          (= (length-v truck4) 5)
          (= (height-v truck4) 10)
          (= (width-v truck4) 4)
          (= (weight-cap-v truck4) 215)
          (= (volume-cap-v truck4) 200)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 34)
          (availablev truck4)
          (typev truck5 auto)
          (typevp truck5 truck)
          (at-vehicle truck5 location12)
          (= (gas-left truck5) 576)
          (= (gpm truck5) 2)
          (= (length-v truck5) 7)
          (= (height-v truck5) 4)
          (= (width-v truck5) 2)
          (= (weight-cap-v truck5) 419)
          (= (volume-cap-v truck5) 56)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 32)
          (availablev truck5)
          (typev truck6 auto)
          (typevp truck6 truck)
          (at-vehicle truck6 location10)
          (= (gas-left truck6) 356)
          (= (gpm truck6) 2)
          (= (length-v truck6) 5)
          (= (height-v truck6) 5)
          (= (width-v truck6) 5)
          (= (weight-cap-v truck6) 475)
          (= (volume-cap-v truck6) 125)
          (= (weight-load-v truck6) 0)
          (= (volume-load-v truck6) 0)
          (= (weight-v truck6) 29)
          (availablev truck6)
          (typev truck7 auto)
          (typevp truck7 truck)
          (at-vehicle truck7 location9)
          (= (gas-left truck7) 540)
          (= (gpm truck7) 2)
          (= (length-v truck7) 7)
          (= (height-v truck7) 1)
          (= (width-v truck7) 8)
          (= (weight-cap-v truck7) 409)
          (= (volume-cap-v truck7) 56)
          (= (weight-load-v truck7) 0)
          (= (volume-load-v truck7) 0)
          (= (weight-v truck7) 14)
          (availablev truck7)
          (typev truck8 auto)
          (typevp truck8 truck)
          (at-vehicle truck8 location2)
          (= (gas-left truck8) 193)
          (= (gpm truck8) 2)
          (= (length-v truck8) 14)
          (= (height-v truck8) 8)
          (= (width-v truck8) 2)
          (= (weight-cap-v truck8) 34)
          (= (volume-cap-v truck8) 156)
          (= (weight-load-v truck8) 0)
          (= (volume-load-v truck8) 0)
          (= (weight-v truck8) 28)
          (availablev truck8)
          (typev truck9 auto)
          (typevp truck9 truck)
          (at-vehicle truck9 location1)
          (= (gas-left truck9) 278)
          (= (gpm truck9) 1)
          (= (length-v truck9) 15)
          (= (height-v truck9) 2)
          (= (width-v truck9) 6)
          (= (weight-cap-v truck9) 398)
          (= (volume-cap-v truck9) 180)
          (= (weight-load-v truck9) 0)
          (= (volume-load-v truck9) 0)
          (= (weight-v truck9) 38)
          (availablev truck9)
          (typev truck10 auto)
          (typevp truck10 truck)
          (at-vehicle truck10 location6)
          (= (gas-left truck10) 571)
          (= (gpm truck10) 2)
          (= (length-v truck10) 13)
          (= (height-v truck10) 8)
          (= (width-v truck10) 1)
          (= (weight-cap-v truck10) 110)
          (= (volume-cap-v truck10) 104)
          (= (weight-load-v truck10) 0)
          (= (volume-load-v truck10) 0)
          (= (weight-v truck10) 28)
          (availablev truck10)
          (typev truck11 auto)
          (typevp truck11 truck)
          (at-vehicle truck11 location4)
          (= (gas-left truck11) 474)
          (= (gpm truck11) 1)
          (= (length-v truck11) 17)
          (= (height-v truck11) 8)
          (= (width-v truck11) 6)
          (= (weight-cap-v truck11) 501)
          (= (volume-cap-v truck11) 571)
          (= (weight-load-v truck11) 0)
          (= (volume-load-v truck11) 0)
          (= (weight-v truck11) 35)
          (availablev truck11)
          (typev truck12 auto)
          (typevp truck12 truck)
          (at-vehicle truck12 location2)
          (= (gas-left truck12) 599)
          (= (gpm truck12) 2)
          (= (length-v truck12) 7)
          (= (height-v truck12) 4)
          (= (width-v truck12) 10)
          (= (weight-cap-v truck12) 495)
          (= (volume-cap-v truck12) 280)
          (= (weight-load-v truck12) 0)
          (= (volume-load-v truck12) 0)
          (= (weight-v truck12) 25)
          (availablev truck12)
          (typev truck13 hopper)
          (typevp truck13 truck)
          (at-vehicle truck13 location7)
          (= (gas-left truck13) 274)
          (= (gpm truck13) 2)
          (= (length-v truck13) 16)
          (= (height-v truck13) 2)
          (= (width-v truck13) 10)
          (= (weight-cap-v truck13) 235)
          (= (volume-cap-v truck13) 320)
          (= (weight-load-v truck13) 0)
          (= (volume-load-v truck13) 0)
          (= (weight-v truck13) 20)
          (availablev truck13)
          (typev truck14 auto)
          (typevp truck14 truck)
          (at-vehicle truck14 location13)
          (= (gas-left truck14) 241)
          (= (gpm truck14) 1)
          (= (length-v truck14) 19)
          (= (height-v truck14) 1)
          (= (width-v truck14) 7)
          (= (weight-cap-v truck14) 299)
          (= (volume-cap-v truck14) 133)
          (= (weight-load-v truck14) 0)
          (= (volume-load-v truck14) 0)
          (= (weight-v truck14) 27)
          (availablev truck14)
          (typev truck15 auto)
          (typevp truck15 truck)
          (at-vehicle truck15 location0)
          (= (gas-left truck15) 347)
          (= (gpm truck15) 2)
          (= (length-v truck15) 6)
          (= (height-v truck15) 9)
          (= (width-v truck15) 4)
          (= (weight-cap-v truck15) 226)
          (= (volume-cap-v truck15) 216)
          (= (weight-load-v truck15) 0)
          (= (volume-load-v truck15) 0)
          (= (weight-v truck15) 22)
          (availablev truck15)
          (typev train0 auto)
          (typevp train0 train)
          (at-vehicle train0 location2)
          (= (gas-left train0) 379)
          (= (gpm train0) 1)
          (= (length-v train0) 14)
          (= (height-v train0) 3)
          (= (width-v train0) 1)
          (= (weight-cap-v train0) 79)
          (= (volume-cap-v train0) 42)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 13)
          (availablev train0)
          (typev train1 auto)
          (typevp train1 train)
          (at-vehicle train1 location11)
          (= (gas-left train1) 167)
          (= (gpm train1) 1)
          (= (length-v train1) 17)
          (= (height-v train1) 4)
          (= (width-v train1) 8)
          (= (weight-cap-v train1) 216)
          (= (volume-cap-v train1) 380)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 30)
          (availablev train1)
          (typev train2 auto)
          (typevp train2 train)
          (at-vehicle train2 location11)
          (= (gas-left train2) 52)
          (= (gpm train2) 3)
          (= (length-v train2) 14)
          (= (height-v train2) 9)
          (= (width-v train2) 5)
          (= (weight-cap-v train2) 76)
          (= (volume-cap-v train2) 440)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 15)
          (availablev train2)
          (typev train3 auto)
          (typevp train3 train)
          (at-vehicle train3 location11)
          (= (gas-left train3) 462)
          (= (gpm train3) 3)
          (= (length-v train3) 17)
          (= (height-v train3) 7)
          (= (width-v train3) 1)
          (= (weight-cap-v train3) 429)
          (= (volume-cap-v train3) 119)
          (= (weight-load-v train3) 0)
          (= (volume-load-v train3) 0)
          (= (weight-v train3) 26)
          (availablev train3)
          (typev train4 auto)
          (typevp train4 train)
          (at-vehicle train4 location11)
          (= (gas-left train4) 315)
          (= (gpm train4) 2)
          (= (length-v train4) 19)
          (= (height-v train4) 8)
          (= (width-v train4) 6)
          (= (weight-cap-v train4) 154)
          (= (volume-cap-v train4) 638)
          (= (weight-load-v train4) 0)
          (= (volume-load-v train4) 0)
          (= (weight-v train4) 23)
          (availablev train4)
          (typev train5 auto)
          (typevp train5 train)
          (at-vehicle train5 location2)
          (= (gas-left train5) 368)
          (= (gpm train5) 3)
          (= (length-v train5) 5)
          (= (height-v train5) 10)
          (= (width-v train5) 10)
          (= (weight-cap-v train5) 209)
          (= (volume-cap-v train5) 350)
          (= (weight-load-v train5) 0)
          (= (volume-load-v train5) 0)
          (= (weight-v train5) 30)
          (availablev train5)
          (typev train6 auto)
          (typevp train6 train)
          (at-vehicle train6 location11)
          (= (gas-left train6) 236)
          (= (gpm train6) 2)
          (= (length-v train6) 5)
          (= (height-v train6) 7)
          (= (width-v train6) 4)
          (= (weight-cap-v train6) 57)
          (= (volume-cap-v train6) 98)
          (= (weight-load-v train6) 0)
          (= (volume-load-v train6) 0)
          (= (weight-v train6) 36)
          (typev train7 auto)
          (typevp train7 train)
          (at-vehicle train7 location2)
          (= (gas-left train7) 118)
          (= (gpm train7) 2)
          (= (length-v train7) 7)
          (= (height-v train7) 4)
          (= (width-v train7) 2)
          (= (weight-cap-v train7) 410)
          (= (volume-cap-v train7) 56)
          (= (weight-load-v train7) 0)
          (= (volume-load-v train7) 0)
          (= (weight-v train7) 20)
          (availablev train7)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location6)
          (= (gas-left airplane0) 534)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 13)
          (= (height-v airplane0) 6)
          (= (width-v airplane0) 3)
          (= (weight-cap-v airplane0) 69)
          (= (volume-cap-v airplane0) 163)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 15)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location9)
          (= (gas-left airplane1) 218)
          (= (gpm airplane1) 3)
          (= (length-v airplane1) 17)
          (= (height-v airplane1) 7)
          (= (width-v airplane1) 6)
          (= (weight-cap-v airplane1) 261)
          (= (volume-cap-v airplane1) 499)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 24)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location12)
          (= (gas-left airplane2) 332)
          (= (gpm airplane2) 1)
          (= (length-v airplane2) 5)
          (= (height-v airplane2) 3)
          (= (width-v airplane2) 6)
          (= (weight-cap-v airplane2) 478)
          (= (volume-cap-v airplane2) 90)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 26)
          (availablev airplane2)
          (typev airplane3 air)
          (typevp airplane3 airplane)
          (at-vehicle airplane3 location0)
          (= (gas-left airplane3) 233)
          (= (gpm airplane3) 2)
          (= (length-v airplane3) 14)
          (= (height-v airplane3) 1)
          (= (width-v airplane3) 2)
          (= (weight-cap-v airplane3) 239)
          (= (volume-cap-v airplane3) 28)
          (= (weight-load-v airplane3) 0)
          (= (volume-load-v airplane3) 0)
          (= (weight-v airplane3) 30)
          (availablev airplane3)
          (typev airplane4 air)
          (typevp airplane4 airplane)
          (at-vehicle airplane4 location0)
          (= (gas-left airplane4) 411)
          (= (gpm airplane4) 3)
          (= (length-v airplane4) 12)
          (= (height-v airplane4) 8)
          (= (width-v airplane4) 1)
          (= (weight-cap-v airplane4) 328)
          (= (volume-cap-v airplane4) 96)
          (= (weight-load-v airplane4) 0)
          (= (volume-load-v airplane4) 0)
          (= (weight-v airplane4) 26)
          (availablev airplane4)
          (typev airplane5 air)
          (typevp airplane5 airplane)
          (at-vehicle airplane5 location15)
          (= (gas-left airplane5) 126)
          (= (gpm airplane5) 3)
          (= (length-v airplane5) 10)
          (= (height-v airplane5) 9)
          (= (width-v airplane5) 10)
          (= (weight-cap-v airplane5) 336)
          (= (volume-cap-v airplane5) 630)
          (= (weight-load-v airplane5) 0)
          (= (volume-load-v airplane5) 0)
          (= (weight-v airplane5) 32)
          (availablev airplane5)
          (typev airplane6 air)
          (typevp airplane6 airplane)
          (at-vehicle airplane6 location9)
          (= (gas-left airplane6) 494)
          (= (gpm airplane6) 2)
          (= (length-v airplane6) 6)
          (= (height-v airplane6) 8)
          (= (width-v airplane6) 8)
          (= (weight-cap-v airplane6) 112)
          (= (volume-cap-v airplane6) 369)
          (= (weight-load-v airplane6) 0)
          (= (volume-load-v airplane6) 0)
          (= (weight-v airplane6) 38)
          (typev airplane7 air)
          (typevp airplane7 airplane)
          (at-vehicle airplane7 location13)
          (= (gas-left airplane7) 343)
          (= (gpm airplane7) 1)
          (= (length-v airplane7) 14)
          (= (height-v airplane7) 2)
          (= (width-v airplane7) 5)
          (= (weight-cap-v airplane7) 422)
          (= (volume-cap-v airplane7) 140)
          (= (weight-load-v airplane7) 0)
          (= (volume-load-v airplane7) 0)
          (= (weight-v airplane7) 31)
          (availablev airplane7)
          (at-equipment plane_ramp0 location0)
          (at-equipment plane_ramp1 location3)
          (at-equipment plane_ramp2 location4)
          (at-equipment plane_ramp3 location6)
          (at-equipment plane_ramp4 location7)
          (at-equipment plane_ramp5 location8)
          (at-equipment plane_ramp6 location9)
          (at-equipment plane_ramp7 location12)
          (at-equipment plane_ramp8 location13)
          (at-equipment plane_ramp9 location15)
          (typep package0 cars)
          (at-packagel package0 location2)
          (= (volume-p package0) 22)
          (= (weight-p package0) 9)
          (typep package1 cars)
          (at-packagel package1 location2)
          (= (volume-p package1) 16)
          (= (weight-p package1) 6)
          (typep package2 cars)
          (at-packagel package2 location3)
          (= (volume-p package2) 21)
          (= (weight-p package2) 9)
          (typep package3 cars)
          (at-packagel package3 location6)
          (= (volume-p package3) 23)
          (= (weight-p package3) 18)
          (typep package4 cars)
          (at-packagel package4 location9)
          (= (volume-p package4) 12)
          (= (weight-p package4) 13)
          (typep package5 cars)
          (at-packagel package5 location3)
          (= (volume-p package5) 6)
          (= (weight-p package5) 12)
          (typep package6 cars)
          (at-packagel package6 location0)
          (= (volume-p package6) 17)
          (= (weight-p package6) 24)
          (typep package7 cars)
          (at-packagel package7 location15)
          (= (volume-p package7) 18)
          (= (weight-p package7) 13)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 18)
          (= (weight-cap-r road_route0) 386)
          (availabler road_route0)
          (connect-city road_route1 road-route city0 city2)
          (= (height-cap-r road_route1) 7)
          (= (weight-cap-r road_route1) 248)
          (availabler road_route1)
          (connect-city road_route2 road-route city0 city3)
          (= (height-cap-r road_route2) 30)
          (= (weight-cap-r road_route2) 281)
          (availabler road_route2)
          (connect-city road_route3 road-route city0 city4)
          (= (height-cap-r road_route3) 17)
          (= (weight-cap-r road_route3) 77)
          (availabler road_route3)
          (connect-city road_route4 road-route city0 city5)
          (= (height-cap-r road_route4) 24)
          (= (weight-cap-r road_route4) 298)
          (availabler road_route4)
          (connect-city road_route5 road-route city1 city0)
          (= (height-cap-r road_route5) 20)
          (= (weight-cap-r road_route5) 453)
          (availabler road_route5)
          (connect-city road_route6 road-route city1 city2)
          (= (height-cap-r road_route6) 6)
          (= (weight-cap-r road_route6) 58)
          (availabler road_route6)
          (connect-city road_route7 road-route city1 city3)
          (= (height-cap-r road_route7) 24)
          (= (weight-cap-r road_route7) 448)
          (availabler road_route7)
          (connect-city road_route8 road-route city1 city4)
          (= (height-cap-r road_route8) 15)
          (= (weight-cap-r road_route8) 88)
          (availabler road_route8)
          (connect-city road_route9 road-route city1 city5)
          (= (height-cap-r road_route9) 10)
          (= (weight-cap-r road_route9) 545)
          (availabler road_route9)
          (connect-city road_route10 road-route city2 city0)
          (= (height-cap-r road_route10) 5)
          (= (weight-cap-r road_route10) 253)
          (availabler road_route10)
          (connect-city road_route11 road-route city2 city1)
          (= (height-cap-r road_route11) 7)
          (= (weight-cap-r road_route11) 408)
          (availabler road_route11)
          (connect-city road_route12 road-route city2 city3)
          (= (height-cap-r road_route12) 6)
          (= (weight-cap-r road_route12) 254)
          (availabler road_route12)
          (connect-city road_route13 road-route city2 city4)
          (= (height-cap-r road_route13) 27)
          (= (weight-cap-r road_route13) 75)
          (availabler road_route13)
          (connect-city road_route14 road-route city2 city5)
          (= (height-cap-r road_route14) 20)
          (= (weight-cap-r road_route14) 79)
          (availabler road_route14)
          (connect-city road_route15 road-route city3 city0)
          (= (height-cap-r road_route15) 15)
          (= (weight-cap-r road_route15) 304)
          (availabler road_route15)
          (connect-city road_route16 road-route city3 city1)
          (= (height-cap-r road_route16) 9)
          (= (weight-cap-r road_route16) 448)
          (availabler road_route16)
          (connect-city road_route17 road-route city3 city2)
          (= (height-cap-r road_route17) 24)
          (= (weight-cap-r road_route17) 397)
          (availabler road_route17)
          (connect-city road_route18 road-route city3 city4)
          (= (height-cap-r road_route18) 10)
          (= (weight-cap-r road_route18) 382)
          (availabler road_route18)
          (connect-city road_route19 road-route city3 city5)
          (= (height-cap-r road_route19) 7)
          (= (weight-cap-r road_route19) 472)
          (availabler road_route19)
          (connect-city road_route20 road-route city4 city0)
          (= (height-cap-r road_route20) 15)
          (= (weight-cap-r road_route20) 197)
          (availabler road_route20)
          (connect-city road_route21 road-route city4 city1)
          (= (height-cap-r road_route21) 5)
          (= (weight-cap-r road_route21) 264)
          (availabler road_route21)
          (connect-city road_route22 road-route city4 city2)
          (= (height-cap-r road_route22) 12)
          (= (weight-cap-r road_route22) 300)
          (availabler road_route22)
          (connect-city road_route23 road-route city4 city3)
          (= (height-cap-r road_route23) 30)
          (= (weight-cap-r road_route23) 179)
          (availabler road_route23)
          (connect-city road_route24 road-route city4 city5)
          (= (height-cap-r road_route24) 22)
          (= (weight-cap-r road_route24) 325)
          (availabler road_route24)
          (connect-city road_route25 road-route city5 city0)
          (= (height-cap-r road_route25) 26)
          (= (weight-cap-r road_route25) 427)
          (availabler road_route25)
          (connect-city road_route26 road-route city5 city1)
          (= (height-cap-r road_route26) 11)
          (= (weight-cap-r road_route26) 256)
          (availabler road_route26)
          (connect-city road_route27 road-route city5 city2)
          (= (height-cap-r road_route27) 10)
          (= (weight-cap-r road_route27) 201)
          (availabler road_route27)
          (connect-city road_route28 road-route city5 city3)
          (= (height-cap-r road_route28) 30)
          (= (weight-cap-r road_route28) 315)
          (availabler road_route28)
          (connect-city road_route29 road-route city5 city4)
          (= (height-cap-r road_route29) 20)
          (= (weight-cap-r road_route29) 497)
          (availabler road_route29)
          (connect-loc rail_route0 rail-route location2 location11)
          (= (height-cap-r rail_route0) 29)
          (= (weight-cap-r rail_route0) 511)
          (serves location2 region3)
          (availabler rail_route0)
          (connect-loc air_route0 air-route location0 location3)
          (= (height-cap-r air_route0) 18)
          (= (weight-cap-r air_route0) 330)
          (serves location0 region1)
          (availabler air_route0)
          (connect-loc air_route1 air-route location0 location4)
          (= (height-cap-r air_route1) 24)
          (= (weight-cap-r air_route1) 224)
          (availabler air_route1)
          (connect-loc air_route2 air-route location0 location7)
          (= (height-cap-r air_route2) 17)
          (= (weight-cap-r air_route2) 384)
          (serves location0 region2)
          (availabler air_route2)
          (connect-loc air_route3 air-route location0 location9)
          (= (height-cap-r air_route3) 27)
          (= (weight-cap-r air_route3) 531)
          (serves location0 region3)
          (serves location9 region3)
          (availabler air_route3)
          (connect-loc air_route4 air-route location0 location12)
          (= (height-cap-r air_route4) 21)
          (= (weight-cap-r air_route4) 393)
          (serves location12 region3)
          (availabler air_route4)
          (connect-loc air_route5 air-route location0 location13)
          (= (height-cap-r air_route5) 12)
          (= (weight-cap-r air_route5) 443)
          (serves location13 region3)
          (availabler air_route5)
          (connect-loc air_route6 air-route location0 location15)
          (= (height-cap-r air_route6) 24)
          (= (weight-cap-r air_route6) 500)
          (serves location15 region3)
          (availabler air_route6)
          (connect-loc air_route7 air-route location3 location0)
          (= (height-cap-r air_route7) 10)
          (= (weight-cap-r air_route7) 528)
          (availabler air_route7)
          (connect-loc air_route8 air-route location3 location4)
          (= (height-cap-r air_route8) 12)
          (= (weight-cap-r air_route8) 532)
          (availabler air_route8)
          (connect-loc air_route9 air-route location3 location6)
          (= (height-cap-r air_route9) 28)
          (= (weight-cap-r air_route9) 199)
          (availabler air_route9)
          (connect-loc air_route10 air-route location3 location7)
          (= (height-cap-r air_route10) 5)
          (= (weight-cap-r air_route10) 218)
          (connect-loc air_route11 air-route location3 location8)
          (= (height-cap-r air_route11) 19)
          (= (weight-cap-r air_route11) 280)
          (availabler air_route11)
          (connect-loc air_route12 air-route location3 location9)
          (= (height-cap-r air_route12) 34)
          (= (weight-cap-r air_route12) 352)
          (serves location9 region1)
          (availabler air_route12)
          (connect-loc air_route13 air-route location3 location12)
          (= (height-cap-r air_route13) 34)
          (= (weight-cap-r air_route13) 525)
          (serves location12 region1)
          (availabler air_route13)
          (connect-loc air_route14 air-route location3 location13)
          (= (height-cap-r air_route14) 15)
          (= (weight-cap-r air_route14) 499)
          (serves location13 region1)
          (availabler air_route14)
          (connect-loc air_route15 air-route location3 location15)
          (= (height-cap-r air_route15) 20)
          (= (weight-cap-r air_route15) 137)
          (serves location15 region1)
          (availabler air_route15)
          (connect-loc air_route16 air-route location4 location0)
          (= (height-cap-r air_route16) 19)
          (= (weight-cap-r air_route16) 410)
          (availabler air_route16)
          (connect-loc air_route17 air-route location4 location3)
          (= (height-cap-r air_route17) 18)
          (= (weight-cap-r air_route17) 113)
          (availabler air_route17)
          (connect-loc air_route18 air-route location4 location6)
          (= (height-cap-r air_route18) 24)
          (= (weight-cap-r air_route18) 274)
          (availabler air_route18)
          (connect-loc air_route19 air-route location4 location7)
          (= (height-cap-r air_route19) 9)
          (= (weight-cap-r air_route19) 350)
          (availabler air_route19)
          (connect-loc air_route20 air-route location4 location8)
          (= (height-cap-r air_route20) 6)
          (= (weight-cap-r air_route20) 75)
          (availabler air_route20)
          (connect-loc air_route21 air-route location4 location9)
          (= (height-cap-r air_route21) 27)
          (= (weight-cap-r air_route21) 90)
          (availabler air_route21)
          (connect-loc air_route22 air-route location4 location13)
          (= (height-cap-r air_route22) 27)
          (= (weight-cap-r air_route22) 240)
          (availabler air_route22)
          (connect-loc air_route23 air-route location6 location0)
          (= (height-cap-r air_route23) 23)
          (= (weight-cap-r air_route23) 538)
          (availabler air_route23)
          (connect-loc air_route24 air-route location6 location3)
          (= (height-cap-r air_route24) 14)
          (= (weight-cap-r air_route24) 411)
          (availabler air_route24)
          (connect-loc air_route25 air-route location6 location7)
          (= (height-cap-r air_route25) 27)
          (= (weight-cap-r air_route25) 367)
          (availabler air_route25)
          (connect-loc air_route26 air-route location6 location8)
          (= (height-cap-r air_route26) 8)
          (= (weight-cap-r air_route26) 182)
          (availabler air_route26)
          (connect-loc air_route27 air-route location6 location9)
          (= (height-cap-r air_route27) 6)
          (= (weight-cap-r air_route27) 498)
          (serves location9 region2)
          (availabler air_route27)
          (connect-loc air_route28 air-route location6 location12)
          (= (height-cap-r air_route28) 30)
          (= (weight-cap-r air_route28) 324)
          (serves location12 region2)
          (availabler air_route28)
          (connect-loc air_route29 air-route location6 location13)
          (= (height-cap-r air_route29) 6)
          (= (weight-cap-r air_route29) 55)
          (serves location13 region2)
          (availabler air_route29)
          (connect-loc air_route30 air-route location6 location15)
          (= (height-cap-r air_route30) 24)
          (= (weight-cap-r air_route30) 397)
          (serves location15 region2)
          (availabler air_route30)
          (connect-loc air_route31 air-route location7 location0)
          (= (height-cap-r air_route31) 28)
          (= (weight-cap-r air_route31) 349)
          (availabler air_route31)
          (connect-loc air_route32 air-route location7 location3)
          (= (height-cap-r air_route32) 5)
          (= (weight-cap-r air_route32) 285)
          (availabler air_route32)
          (connect-loc air_route33 air-route location7 location4)
          (= (height-cap-r air_route33) 16)
          (= (weight-cap-r air_route33) 346)
          (availabler air_route33)
          (connect-loc air_route34 air-route location7 location8)
          (= (height-cap-r air_route34) 34)
          (= (weight-cap-r air_route34) 397)
          (availabler air_route34)
          (connect-loc air_route35 air-route location7 location12)
          (= (height-cap-r air_route35) 16)
          (= (weight-cap-r air_route35) 429)
          (availabler air_route35)
          (connect-loc air_route36 air-route location7 location13)
          (= (height-cap-r air_route36) 28)
          (= (weight-cap-r air_route36) 328)
          (availabler air_route36)
          (connect-loc air_route37 air-route location7 location15)
          (= (height-cap-r air_route37) 15)
          (= (weight-cap-r air_route37) 374)
          (availabler air_route37)
          (connect-loc air_route38 air-route location8 location0)
          (= (height-cap-r air_route38) 17)
          (= (weight-cap-r air_route38) 226)
          (availabler air_route38)
          (connect-loc air_route39 air-route location8 location4)
          (= (height-cap-r air_route39) 18)
          (= (weight-cap-r air_route39) 407)
          (availabler air_route39)
          (connect-loc air_route40 air-route location8 location6)
          (= (height-cap-r air_route40) 5)
          (= (weight-cap-r air_route40) 198)
          (availabler air_route40)
          (connect-loc air_route41 air-route location8 location7)
          (= (height-cap-r air_route41) 22)
          (= (weight-cap-r air_route41) 55)
          (availabler air_route41)
          (connect-loc air_route42 air-route location8 location9)
          (= (height-cap-r air_route42) 7)
          (= (weight-cap-r air_route42) 337)
          (connect-loc air_route43 air-route location8 location12)
          (= (height-cap-r air_route43) 25)
          (= (weight-cap-r air_route43) 265)
          (availabler air_route43)
          (connect-loc air_route44 air-route location8 location13)
          (= (height-cap-r air_route44) 15)
          (= (weight-cap-r air_route44) 433)
          (connect-loc air_route45 air-route location8 location15)
          (= (height-cap-r air_route45) 31)
          (= (weight-cap-r air_route45) 180)
          (availabler air_route45)
          (connect-loc air_route46 air-route location9 location0)
          (= (height-cap-r air_route46) 26)
          (= (weight-cap-r air_route46) 447)
          (availabler air_route46)
          (connect-loc air_route47 air-route location9 location3)
          (= (height-cap-r air_route47) 16)
          (= (weight-cap-r air_route47) 366)
          (availabler air_route47)
          (connect-loc air_route48 air-route location9 location4)
          (= (height-cap-r air_route48) 14)
          (= (weight-cap-r air_route48) 342)
          (availabler air_route48)
          (connect-loc air_route49 air-route location9 location6)
          (= (height-cap-r air_route49) 16)
          (= (weight-cap-r air_route49) 162)
          (availabler air_route49)
          (connect-loc air_route50 air-route location9 location7)
          (= (height-cap-r air_route50) 25)
          (= (weight-cap-r air_route50) 352)
          (availabler air_route50)
          (connect-loc air_route51 air-route location9 location8)
          (= (height-cap-r air_route51) 33)
          (= (weight-cap-r air_route51) 418)
          (availabler air_route51)
          (connect-loc air_route52 air-route location9 location12)
          (= (height-cap-r air_route52) 6)
          (= (weight-cap-r air_route52) 452)
          (availabler air_route52)
          (connect-loc air_route53 air-route location9 location13)
          (= (height-cap-r air_route53) 20)
          (= (weight-cap-r air_route53) 163)
          (availabler air_route53)
          (connect-loc air_route54 air-route location9 location15)
          (= (height-cap-r air_route54) 8)
          (= (weight-cap-r air_route54) 387)
          (availabler air_route54)
          (connect-loc air_route55 air-route location12 location0)
          (= (height-cap-r air_route55) 20)
          (= (weight-cap-r air_route55) 367)
          (availabler air_route55)
          (connect-loc air_route56 air-route location12 location3)
          (= (height-cap-r air_route56) 21)
          (= (weight-cap-r air_route56) 242)
          (availabler air_route56)
          (connect-loc air_route57 air-route location12 location4)
          (= (height-cap-r air_route57) 20)
          (= (weight-cap-r air_route57) 90)
          (availabler air_route57)
          (connect-loc air_route58 air-route location12 location6)
          (= (height-cap-r air_route58) 8)
          (= (weight-cap-r air_route58) 150)
          (availabler air_route58)
          (connect-loc air_route59 air-route location12 location7)
          (= (height-cap-r air_route59) 30)
          (= (weight-cap-r air_route59) 435)
          (availabler air_route59)
          (connect-loc air_route60 air-route location12 location8)
          (= (height-cap-r air_route60) 27)
          (= (weight-cap-r air_route60) 370)
          (connect-loc air_route61 air-route location12 location9)
          (= (height-cap-r air_route61) 28)
          (= (weight-cap-r air_route61) 337)
          (availabler air_route61)
          (connect-loc air_route62 air-route location12 location13)
          (= (height-cap-r air_route62) 8)
          (= (weight-cap-r air_route62) 87)
          (availabler air_route62)
          (connect-loc air_route63 air-route location12 location15)
          (= (height-cap-r air_route63) 33)
          (= (weight-cap-r air_route63) 373)
          (availabler air_route63)
          (connect-loc air_route64 air-route location13 location0)
          (= (height-cap-r air_route64) 25)
          (= (weight-cap-r air_route64) 418)
          (availabler air_route64)
          (connect-loc air_route65 air-route location13 location3)
          (= (height-cap-r air_route65) 5)
          (= (weight-cap-r air_route65) 358)
          (availabler air_route65)
          (connect-loc air_route66 air-route location13 location4)
          (= (height-cap-r air_route66) 16)
          (= (weight-cap-r air_route66) 217)
          (availabler air_route66)
          (connect-loc air_route67 air-route location13 location6)
          (= (height-cap-r air_route67) 12)
          (= (weight-cap-r air_route67) 172)
          (availabler air_route67)
          (connect-loc air_route68 air-route location13 location7)
          (= (height-cap-r air_route68) 28)
          (= (weight-cap-r air_route68) 420)
          (availabler air_route68)
          (connect-loc air_route69 air-route location13 location8)
          (= (height-cap-r air_route69) 20)
          (= (weight-cap-r air_route69) 331)
          (availabler air_route69)
          (connect-loc air_route70 air-route location13 location9)
          (= (height-cap-r air_route70) 12)
          (= (weight-cap-r air_route70) 268)
          (availabler air_route70)
          (connect-loc air_route71 air-route location13 location12)
          (= (height-cap-r air_route71) 17)
          (= (weight-cap-r air_route71) 490)
          (availabler air_route71)
          (connect-loc air_route72 air-route location13 location15)
          (= (height-cap-r air_route72) 29)
          (= (weight-cap-r air_route72) 408)
          (availabler air_route72)
          (connect-loc air_route73 air-route location15 location0)
          (= (height-cap-r air_route73) 32)
          (= (weight-cap-r air_route73) 158)
          (availabler air_route73)
          (connect-loc air_route74 air-route location15 location3)
          (= (height-cap-r air_route74) 25)
          (= (weight-cap-r air_route74) 454)
          (availabler air_route74)
          (connect-loc air_route75 air-route location15 location4)
          (= (height-cap-r air_route75) 34)
          (= (weight-cap-r air_route75) 542)
          (availabler air_route75)
          (connect-loc air_route76 air-route location15 location6)
          (= (height-cap-r air_route76) 24)
          (= (weight-cap-r air_route76) 244)
          (availabler air_route76)
          (connect-loc air_route77 air-route location15 location7)
          (= (height-cap-r air_route77) 12)
          (= (weight-cap-r air_route77) 60)
          (availabler air_route77)
          (connect-loc air_route78 air-route location15 location8)
          (= (height-cap-r air_route78) 21)
          (= (weight-cap-r air_route78) 159)
          (availabler air_route78)
          (connect-loc air_route79 air-route location15 location9)
          (= (height-cap-r air_route79) 13)
          (= (weight-cap-r air_route79) 201)
          (availabler air_route79)
          (connect-loc air_route80 air-route location15 location12)
          (= (height-cap-r air_route80) 26)
          (= (weight-cap-r air_route80) 461)
          (availabler air_route80)
          (connect-loc air_route81 air-route location15 location13)
          (= (height-cap-r air_route81) 22)
          (= (weight-cap-r air_route81) 498)
          (availabler air_route81)
          (= (volume-load-l location0) 17)
          (= (volume-load-l location1) 0)
          (= (volume-load-l location2) 38)
          (= (volume-load-l location3) 27)
          (= (volume-load-l location4) 0)
          (= (volume-load-l location5) 0)
          (= (volume-load-l location6) 23)
          (= (volume-load-l location7) 0)
          (= (volume-load-l location8) 0)
          (= (volume-load-l location9) 12)
          (= (volume-load-l location10) 0)
          (= (volume-load-l location11) 0)
          (= (volume-load-l location12) 0)
          (= (volume-load-l location13) 0)
          (= (volume-load-l location14) 0)
          (= (volume-load-l location15) 18)
   )

   (:goal (and (delivered package0 location0)
               (delivered package1 location6)
               (delivered package2 location4)
               (delivered package3 location4)
               (delivered package4 location7)
               (delivered package5 location15)
               (delivered package6 location6)
               (delivered package7 location15)
               (clear)))

)