(define (problem problem3)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 - region
          city0 city1 - city
          location0 location1 location2 location3 location4 location5 - location
          truck0 truck1 truck2 truck3 truck4 truck5 train0 train1 train2 airplane0 airplane1 airplane2 - vehicle
          plane_ramp0 plane_ramp1 plane_ramp2 - plane-ramp
          package0 package1 package2 - package
          road_route0 road_route1 - route
          rail_route0 rail_route1 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region0)
          (= (local-height city0) 8)
          (= (local-weight city0) 236)
          (in-region city1 region0)
          (= (local-height city1) 21)
          (= (local-weight city1) 174)
          (in-city location0 city0)
          (= (height-cap-l location0) 27)
          (= (length-cap-l location0) 24)
          (= (width-cap-l location0) 36)
          (= (volume-cap-l location0) 337)
          (tcenter location0)
          (typel location0 airport)
          (availablel location0)
          (hub location0)
          (in-city location1 city1)
          (= (height-cap-l location1) 17)
          (= (length-cap-l location1) 27)
          (= (width-cap-l location1) 17)
          (= (volume-cap-l location1) 483)
          (tcenter location1)
          (typel location1 train-station)
          (availablel location1)
          (hub location1)
          (in-city location2 city0)
          (= (height-cap-l location2) 26)
          (= (length-cap-l location2) 32)
          (= (width-cap-l location2) 11)
          (= (volume-cap-l location2) 315)
          (tcenter location2)
          (typel location2 airport)
          (availablel location2)
          (hub location2)
          (in-city location3 city0)
          (= (height-cap-l location3) 31)
          (= (length-cap-l location3) 44)
          (= (width-cap-l location3) 34)
          (= (volume-cap-l location3) 59)
          (in-city location4 city0)
          (= (height-cap-l location4) 13)
          (= (length-cap-l location4) 19)
          (= (width-cap-l location4) 20)
          (= (volume-cap-l location4) 249)
          (tcenter location4)
          (typel location4 train-station)
          (availablel location4)
          (in-city location5 city0)
          (= (height-cap-l location5) 14)
          (= (length-cap-l location5) 26)
          (= (width-cap-l location5) 33)
          (= (volume-cap-l location5) 448)
          (tcenter location5)
          (typel location5 airport)
          (availablel location5)
          (= (distance location0 location1) 54)
          (= (distance location1 location0) 54)
          (= (distance location0 location2) 12)
          (= (distance location2 location0) 12)
          (= (distance location0 location3) 57)
          (= (distance location3 location0) 57)
          (= (distance location0 location4) 27)
          (= (distance location4 location0) 27)
          (= (distance location0 location5) 40)
          (= (distance location5 location0) 40)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 59)
          (= (distance location2 location1) 59)
          (= (distance location1 location3) 39)
          (= (distance location3 location1) 39)
          (= (distance location1 location4) 32)
          (= (distance location4 location1) 32)
          (= (distance location1 location5) 10)
          (= (distance location5 location1) 10)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 38)
          (= (distance location3 location2) 38)
          (= (distance location2 location4) 41)
          (= (distance location4 location2) 41)
          (= (distance location2 location5) 2)
          (= (distance location5 location2) 2)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 14)
          (= (distance location4 location3) 14)
          (= (distance location3 location5) 2)
          (= (distance location5 location3) 2)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 26)
          (= (distance location5 location4) 26)
          (= (distance location4 location4) 0)
          (= (distance location5 location5) 0)
          (typev truck0 regularv)
          (typevp truck0 truck)
          (at-vehicle truck0 location3)
          (= (gas-left truck0) 313)
          (= (gpm truck0) 2)
          (= (length-v truck0) 13)
          (= (height-v truck0) 8)
          (= (width-v truck0) 9)
          (= (weight-cap-v truck0) 76)
          (= (volume-cap-v truck0) 655)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 13)
          (availablev truck0)
          (typev truck1 regularv)
          (typevp truck1 truck)
          (at-vehicle truck1 location3)
          (= (gas-left truck1) 466)
          (= (gpm truck1) 1)
          (= (length-v truck1) 8)
          (= (height-v truck1) 4)
          (= (width-v truck1) 9)
          (= (weight-cap-v truck1) 227)
          (= (volume-cap-v truck1) 281)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 34)
          (availablev truck1)
          (typev truck2 regularv)
          (typevp truck2 truck)
          (at-vehicle truck2 location2)
          (= (gas-left truck2) 322)
          (= (gpm truck2) 2)
          (= (length-v truck2) 5)
          (= (height-v truck2) 7)
          (= (width-v truck2) 9)
          (= (weight-cap-v truck2) 60)
          (= (volume-cap-v truck2) 225)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 10)
          (availablev truck2)
          (typev truck3 regularv)
          (typevp truck3 truck)
          (at-vehicle truck3 location3)
          (= (gas-left truck3) 170)
          (= (gpm truck3) 3)
          (= (length-v truck3) 18)
          (= (height-v truck3) 1)
          (= (width-v truck3) 3)
          (= (weight-cap-v truck3) 400)
          (= (volume-cap-v truck3) 54)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 33)
          (typev truck4 regularv)
          (typevp truck4 truck)
          (at-vehicle truck4 location2)
          (= (gas-left truck4) 336)
          (= (gpm truck4) 2)
          (= (length-v truck4) 7)
          (= (height-v truck4) 8)
          (= (width-v truck4) 6)
          (= (weight-cap-v truck4) 132)
          (= (volume-cap-v truck4) 336)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 27)
          (availablev truck4)
          (typev truck5 regularv)
          (typevp truck5 truck)
          (at-vehicle truck5 location4)
          (= (gas-left truck5) 432)
          (= (gpm truck5) 3)
          (= (length-v truck5) 19)
          (= (height-v truck5) 5)
          (= (width-v truck5) 4)
          (= (weight-cap-v truck5) 296)
          (= (volume-cap-v truck5) 266)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 14)
          (availablev truck5)
          (typev train0 regularv)
          (typevp train0 train)
          (at-vehicle train0 location1)
          (= (gas-left train0) 232)
          (= (gpm train0) 1)
          (= (length-v train0) 17)
          (= (height-v train0) 8)
          (= (width-v train0) 10)
          (= (weight-cap-v train0) 425)
          (= (volume-cap-v train0) 951)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 24)
          (availablev train0)
          (typev train1 regularv)
          (typevp train1 train)
          (at-vehicle train1 location1)
          (= (gas-left train1) 255)
          (= (gpm train1) 3)
          (= (length-v train1) 7)
          (= (height-v train1) 2)
          (= (width-v train1) 8)
          (= (weight-cap-v train1) 133)
          (= (volume-cap-v train1) 112)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 12)
          (availablev train1)
          (typev train2 regularv)
          (typevp train2 train)
          (at-vehicle train2 location4)
          (= (gas-left train2) 50)
          (= (gpm train2) 1)
          (= (length-v train2) 9)
          (= (height-v train2) 7)
          (= (width-v train2) 7)
          (= (weight-cap-v train2) 459)
          (= (volume-cap-v train2) 308)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 15)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location5)
          (= (gas-left airplane0) 124)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 18)
          (= (height-v airplane0) 2)
          (= (width-v airplane0) 5)
          (= (weight-cap-v airplane0) 469)
          (= (volume-cap-v airplane0) 180)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 28)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location5)
          (= (gas-left airplane1) 265)
          (= (gpm airplane1) 2)
          (= (length-v airplane1) 14)
          (= (height-v airplane1) 1)
          (= (width-v airplane1) 10)
          (= (weight-cap-v airplane1) 473)
          (= (volume-cap-v airplane1) 97)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 11)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location5)
          (= (gas-left airplane2) 268)
          (= (gpm airplane2) 1)
          (= (length-v airplane2) 15)
          (= (height-v airplane2) 4)
          (= (width-v airplane2) 5)
          (= (weight-cap-v airplane2) 422)
          (= (volume-cap-v airplane2) 210)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 28)
          (availablev airplane2)
          (at-equipment plane_ramp0 location0)
          (at-equipment plane_ramp1 location2)
          (at-equipment plane_ramp2 location5)
          (typep package0 regularp)
          (at-packagel package0 location2)
          (= (volume-p package0) 19)
          (= (weight-p package0) 17)
          (typep package1 regularp)
          (at-packagel package1 location0)
          (= (volume-p package1) 8)
          (= (weight-p package1) 14)
          (typep package2 regularp)
          (at-packagel package2 location5)
          (= (volume-p package2) 19)
          (= (weight-p package2) 21)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 22)
          (= (weight-cap-r road_route0) 115)
          (availabler road_route0)
          (connect-city road_route1 road-route city1 city0)
          (= (height-cap-r road_route1) 21)
          (= (weight-cap-r road_route1) 145)
          (availabler road_route1)
          (connect-loc rail_route0 rail-route location1 location4)
          (= (height-cap-r rail_route0) 13)
          (= (weight-cap-r rail_route0) 323)
          (serves location1 region0)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location4 location1)
          (= (height-cap-r rail_route1) 25)
          (= (weight-cap-r rail_route1) 384)
          (availabler rail_route1)
          (connect-loc air_route0 air-route location0 location2)
          (= (height-cap-r air_route0) 15)
          (= (weight-cap-r air_route0) 346)
          (serves location0 region0)
          (serves location2 region0)
          (connect-loc air_route1 air-route location0 location5)
          (= (height-cap-r air_route1) 31)
          (= (weight-cap-r air_route1) 471)
          (availabler air_route1)
          (connect-loc air_route2 air-route location2 location0)
          (= (height-cap-r air_route2) 33)
          (= (weight-cap-r air_route2) 55)
          (availabler air_route2)
          (connect-loc air_route3 air-route location2 location5)
          (= (height-cap-r air_route3) 22)
          (= (weight-cap-r air_route3) 373)
          (availabler air_route3)
          (connect-loc air_route4 air-route location5 location0)
          (= (height-cap-r air_route4) 24)
          (= (weight-cap-r air_route4) 450)
          (availabler air_route4)
          (connect-loc air_route5 air-route location5 location2)
          (= (height-cap-r air_route5) 15)
          (= (weight-cap-r air_route5) 395)
          (availabler air_route5)
          (= (volume-load-l location0) 8)
          (= (volume-load-l location1) 0)
          (= (volume-load-l location2) 19)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 0)
          (= (volume-load-l location5) 19)
   )

   (:goal (and (delivered package0 location1)
               (delivered package1 location5)
               (delivered package2 location1)
               (clear)))

)