(define (problem problem3)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 region1 region2 region3 - region
          city0 city1 city2 city3 city4 city5 - city
          location0 location1 location2 location3 location4 location5 location6 location7 location8 location9 location10 location11 location12 location13 location14 location15 - location
          truck0 truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 truck11 truck12 truck13 truck14 truck15 train0 train1 train2 train3 train4 train5 train6 train7 airplane0 airplane1 airplane2 airplane3 airplane4 airplane5 airplane6 airplane7 - vehicle
          crane0 crane1 crane2 crane3 crane4 crane5 crane6 crane7 crane8 crane9 crane10 crane11 crane12 crane13 crane14 crane15 - crane
          plane_ramp0 plane_ramp1 plane_ramp2 plane_ramp3 - plane-ramp
          package0 package1 package2 package3 package4 package5 package6 package7 - package
          road_route0 road_route1 road_route2 road_route3 road_route4 road_route5 road_route6 road_route7 road_route8 road_route9 road_route10 road_route11 road_route12 road_route13 road_route14 road_route15 road_route16 road_route17 road_route18 road_route19 road_route20 road_route21 road_route22 road_route23 road_route24 road_route25 road_route26 - route
          rail_route0 rail_route1 rail_route2 rail_route3 rail_route4 rail_route5 rail_route6 rail_route7 rail_route8 rail_route9 rail_route10 rail_route11 rail_route12 rail_route13 rail_route14 rail_route15 rail_route16 rail_route17 rail_route18 rail_route19 rail_route20 rail_route21 rail_route22 rail_route23 rail_route24 rail_route25 rail_route26 rail_route27 rail_route28 rail_route29 rail_route30 rail_route31 rail_route32 rail_route33 rail_route34 rail_route35 rail_route36 rail_route37 rail_route38 rail_route39 rail_route40 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 air_route6 air_route7 air_route8 air_route9 air_route10 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region1)
          (= (local-height city0) 22)
          (= (local-weight city0) 63)
          (in-region city1 region2)
          (= (local-height city1) 9)
          (= (local-weight city1) 133)
          (in-region city2 region2)
          (= (local-height city2) 27)
          (= (local-weight city2) 329)
          (in-region city3 region3)
          (= (local-height city3) 17)
          (= (local-weight city3) 126)
          (in-region city4 region2)
          (= (local-height city4) 34)
          (= (local-weight city4) 389)
          (in-region city5 region0)
          (= (local-height city5) 7)
          (= (local-weight city5) 243)
          (in-city location0 city0)
          (= (height-cap-l location0) 29)
          (= (length-cap-l location0) 43)
          (= (width-cap-l location0) 17)
          (= (volume-cap-l location0) 440)
          (tcenter location0)
          (typel location0 train-station)
          (availablel location0)
          (hub location0)
          (in-city location1 city4)
          (= (height-cap-l location1) 26)
          (= (length-cap-l location1) 21)
          (= (width-cap-l location1) 13)
          (= (volume-cap-l location1) 450)
          (tcenter location1)
          (typel location1 train-station)
          (availablel location1)
          (hub location1)
          (in-city location2 city2)
          (= (height-cap-l location2) 22)
          (= (length-cap-l location2) 22)
          (= (width-cap-l location2) 29)
          (= (volume-cap-l location2) 425)
          (in-city location3 city0)
          (= (height-cap-l location3) 15)
          (= (length-cap-l location3) 19)
          (= (width-cap-l location3) 13)
          (= (volume-cap-l location3) 461)
          (tcenter location3)
          (typel location3 train-station)
          (availablel location3)
          (hub location3)
          (in-city location4 city5)
          (= (height-cap-l location4) 16)
          (= (length-cap-l location4) 43)
          (= (width-cap-l location4) 15)
          (= (volume-cap-l location4) 462)
          (tcenter location4)
          (typel location4 airport)
          (availablel location4)
          (hub location4)
          (in-city location5 city4)
          (= (height-cap-l location5) 29)
          (= (length-cap-l location5) 47)
          (= (width-cap-l location5) 20)
          (= (volume-cap-l location5) 214)
          (tcenter location5)
          (typel location5 airport)
          (availablel location5)
          (hub location5)
          (in-city location6 city2)
          (= (height-cap-l location6) 13)
          (= (length-cap-l location6) 48)
          (= (width-cap-l location6) 12)
          (= (volume-cap-l location6) 76)
          (in-city location7 city1)
          (= (height-cap-l location7) 23)
          (= (length-cap-l location7) 29)
          (= (width-cap-l location7) 33)
          (= (volume-cap-l location7) 366)
          (tcenter location7)
          (typel location7 airport)
          (availablel location7)
          (in-city location8 city2)
          (= (height-cap-l location8) 10)
          (= (length-cap-l location8) 13)
          (= (width-cap-l location8) 26)
          (= (volume-cap-l location8) 371)
          (tcenter location8)
          (typel location8 train-station)
          (availablel location8)
          (in-city location9 city2)
          (= (height-cap-l location9) 18)
          (= (length-cap-l location9) 29)
          (= (width-cap-l location9) 34)
          (= (volume-cap-l location9) 460)
          (tcenter location9)
          (typel location9 train-station)
          (availablel location9)
          (in-city location10 city4)
          (= (height-cap-l location10) 25)
          (= (length-cap-l location10) 24)
          (= (width-cap-l location10) 28)
          (= (volume-cap-l location10) 229)
          (tcenter location10)
          (typel location10 train-station)
          (availablel location10)
          (hub location10)
          (in-city location11 city1)
          (= (height-cap-l location11) 26)
          (= (length-cap-l location11) 11)
          (= (width-cap-l location11) 21)
          (= (volume-cap-l location11) 324)
          (in-city location12 city2)
          (= (height-cap-l location12) 32)
          (= (length-cap-l location12) 21)
          (= (width-cap-l location12) 14)
          (= (volume-cap-l location12) 152)
          (tcenter location12)
          (typel location12 airport)
          (in-city location13 city1)
          (= (height-cap-l location13) 9)
          (= (length-cap-l location13) 18)
          (= (width-cap-l location13) 34)
          (= (volume-cap-l location13) 352)
          (in-city location14 city3)
          (= (height-cap-l location14) 28)
          (= (length-cap-l location14) 31)
          (= (width-cap-l location14) 19)
          (= (volume-cap-l location14) 395)
          (in-city location15 city3)
          (= (height-cap-l location15) 8)
          (= (length-cap-l location15) 20)
          (= (width-cap-l location15) 25)
          (= (volume-cap-l location15) 91)
          (tcenter location15)
          (typel location15 train-station)
          (availablel location15)
          (= (distance location0 location1) 51)
          (= (distance location1 location0) 51)
          (= (distance location0 location2) 14)
          (= (distance location2 location0) 14)
          (= (distance location0 location3) 64)
          (= (distance location3 location0) 64)
          (= (distance location0 location4) 24)
          (= (distance location4 location0) 24)
          (= (distance location0 location5) 19)
          (= (distance location5 location0) 19)
          (= (distance location0 location6) 0)
          (= (distance location6 location0) 0)
          (= (distance location0 location7) 20)
          (= (distance location7 location0) 20)
          (= (distance location0 location8) 5)
          (= (distance location8 location0) 5)
          (= (distance location0 location9) 10)
          (= (distance location9 location0) 10)
          (= (distance location0 location10) 41)
          (= (distance location10 location0) 41)
          (= (distance location0 location11) 23)
          (= (distance location11 location0) 23)
          (= (distance location0 location12) 37)
          (= (distance location12 location0) 37)
          (= (distance location0 location13) 25)
          (= (distance location13 location0) 25)
          (= (distance location0 location14) 28)
          (= (distance location14 location0) 28)
          (= (distance location0 location15) 5)
          (= (distance location15 location0) 5)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 63)
          (= (distance location2 location1) 63)
          (= (distance location1 location3) 30)
          (= (distance location3 location1) 30)
          (= (distance location1 location4) 57)
          (= (distance location4 location1) 57)
          (= (distance location1 location5) 41)
          (= (distance location5 location1) 41)
          (= (distance location1 location6) 20)
          (= (distance location6 location1) 20)
          (= (distance location1 location7) 6)
          (= (distance location7 location1) 6)
          (= (distance location1 location8) 30)
          (= (distance location8 location1) 30)
          (= (distance location1 location9) 69)
          (= (distance location9 location1) 69)
          (= (distance location1 location10) 17)
          (= (distance location10 location1) 17)
          (= (distance location1 location11) 53)
          (= (distance location11 location1) 53)
          (= (distance location1 location12) 14)
          (= (distance location12 location1) 14)
          (= (distance location1 location13) 26)
          (= (distance location13 location1) 26)
          (= (distance location1 location14) 7)
          (= (distance location14 location1) 7)
          (= (distance location1 location15) 63)
          (= (distance location15 location1) 63)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 17)
          (= (distance location3 location2) 17)
          (= (distance location2 location4) 41)
          (= (distance location4 location2) 41)
          (= (distance location2 location5) 36)
          (= (distance location5 location2) 36)
          (= (distance location2 location6) 33)
          (= (distance location6 location2) 33)
          (= (distance location2 location7) 1)
          (= (distance location7 location2) 1)
          (= (distance location2 location8) 66)
          (= (distance location8 location2) 66)
          (= (distance location2 location9) 15)
          (= (distance location9 location2) 15)
          (= (distance location2 location10) 5)
          (= (distance location10 location2) 5)
          (= (distance location2 location11) 9)
          (= (distance location11 location2) 9)
          (= (distance location2 location12) 34)
          (= (distance location12 location2) 34)
          (= (distance location2 location13) 55)
          (= (distance location13 location2) 55)
          (= (distance location2 location14) 6)
          (= (distance location14 location2) 6)
          (= (distance location2 location15) 68)
          (= (distance location15 location2) 68)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 16)
          (= (distance location4 location3) 16)
          (= (distance location3 location5) 19)
          (= (distance location5 location3) 19)
          (= (distance location3 location6) 45)
          (= (distance location6 location3) 45)
          (= (distance location3 location7) 35)
          (= (distance location7 location3) 35)
          (= (distance location3 location8) 17)
          (= (distance location8 location3) 17)
          (= (distance location3 location9) 31)
          (= (distance location9 location3) 31)
          (= (distance location3 location10) 67)
          (= (distance location10 location3) 67)
          (= (distance location3 location11) 65)
          (= (distance location11 location3) 65)
          (= (distance location3 location12) 44)
          (= (distance location12 location3) 44)
          (= (distance location3 location13) 16)
          (= (distance location13 location3) 16)
          (= (distance location3 location14) 25)
          (= (distance location14 location3) 25)
          (= (distance location3 location15) 26)
          (= (distance location15 location3) 26)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 11)
          (= (distance location5 location4) 11)
          (= (distance location4 location6) 68)
          (= (distance location6 location4) 68)
          (= (distance location4 location7) 67)
          (= (distance location7 location4) 67)
          (= (distance location4 location8) 22)
          (= (distance location8 location4) 22)
          (= (distance location4 location9) 39)
          (= (distance location9 location4) 39)
          (= (distance location4 location10) 29)
          (= (distance location10 location4) 29)
          (= (distance location4 location11) 58)
          (= (distance location11 location4) 58)
          (= (distance location4 location12) 53)
          (= (distance location12 location4) 53)
          (= (distance location4 location13) 35)
          (= (distance location13 location4) 35)
          (= (distance location4 location14) 63)
          (= (distance location14 location4) 63)
          (= (distance location4 location15) 67)
          (= (distance location15 location4) 67)
          (= (distance location4 location4) 0)
          (= (distance location5 location6) 6)
          (= (distance location6 location5) 6)
          (= (distance location5 location7) 64)
          (= (distance location7 location5) 64)
          (= (distance location5 location8) 35)
          (= (distance location8 location5) 35)
          (= (distance location5 location9) 64)
          (= (distance location9 location5) 64)
          (= (distance location5 location10) 22)
          (= (distance location10 location5) 22)
          (= (distance location5 location11) 22)
          (= (distance location11 location5) 22)
          (= (distance location5 location12) 36)
          (= (distance location12 location5) 36)
          (= (distance location5 location13) 52)
          (= (distance location13 location5) 52)
          (= (distance location5 location14) 15)
          (= (distance location14 location5) 15)
          (= (distance location5 location15) 54)
          (= (distance location15 location5) 54)
          (= (distance location5 location5) 0)
          (= (distance location6 location7) 51)
          (= (distance location7 location6) 51)
          (= (distance location6 location8) 10)
          (= (distance location8 location6) 10)
          (= (distance location6 location9) 0)
          (= (distance location9 location6) 0)
          (= (distance location6 location10) 27)
          (= (distance location10 location6) 27)
          (= (distance location6 location11) 7)
          (= (distance location11 location6) 7)
          (= (distance location6 location12) 62)
          (= (distance location12 location6) 62)
          (= (distance location6 location13) 21)
          (= (distance location13 location6) 21)
          (= (distance location6 location14) 27)
          (= (distance location14 location6) 27)
          (= (distance location6 location15) 21)
          (= (distance location15 location6) 21)
          (= (distance location6 location6) 0)
          (= (distance location7 location8) 51)
          (= (distance location8 location7) 51)
          (= (distance location7 location9) 44)
          (= (distance location9 location7) 44)
          (= (distance location7 location10) 18)
          (= (distance location10 location7) 18)
          (= (distance location7 location11) 44)
          (= (distance location11 location7) 44)
          (= (distance location7 location12) 44)
          (= (distance location12 location7) 44)
          (= (distance location7 location13) 23)
          (= (distance location13 location7) 23)
          (= (distance location7 location14) 7)
          (= (distance location14 location7) 7)
          (= (distance location7 location15) 19)
          (= (distance location15 location7) 19)
          (= (distance location7 location7) 0)
          (= (distance location8 location9) 29)
          (= (distance location9 location8) 29)
          (= (distance location8 location10) 40)
          (= (distance location10 location8) 40)
          (= (distance location8 location11) 37)
          (= (distance location11 location8) 37)
          (= (distance location8 location12) 23)
          (= (distance location12 location8) 23)
          (= (distance location8 location13) 54)
          (= (distance location13 location8) 54)
          (= (distance location8 location14) 8)
          (= (distance location14 location8) 8)
          (= (distance location8 location15) 47)
          (= (distance location15 location8) 47)
          (= (distance location8 location8) 0)
          (= (distance location9 location10) 6)
          (= (distance location10 location9) 6)
          (= (distance location9 location11) 12)
          (= (distance location11 location9) 12)
          (= (distance location9 location12) 65)
          (= (distance location12 location9) 65)
          (= (distance location9 location13) 32)
          (= (distance location13 location9) 32)
          (= (distance location9 location14) 23)
          (= (distance location14 location9) 23)
          (= (distance location9 location15) 14)
          (= (distance location15 location9) 14)
          (= (distance location9 location9) 0)
          (= (distance location10 location11) 57)
          (= (distance location11 location10) 57)
          (= (distance location10 location12) 16)
          (= (distance location12 location10) 16)
          (= (distance location10 location13) 28)
          (= (distance location13 location10) 28)
          (= (distance location10 location14) 51)
          (= (distance location14 location10) 51)
          (= (distance location10 location15) 6)
          (= (distance location15 location10) 6)
          (= (distance location10 location10) 0)
          (= (distance location11 location12) 59)
          (= (distance location12 location11) 59)
          (= (distance location11 location13) 35)
          (= (distance location13 location11) 35)
          (= (distance location11 location14) 25)
          (= (distance location14 location11) 25)
          (= (distance location11 location15) 18)
          (= (distance location15 location11) 18)
          (= (distance location11 location11) 0)
          (= (distance location12 location13) 64)
          (= (distance location13 location12) 64)
          (= (distance location12 location14) 23)
          (= (distance location14 location12) 23)
          (= (distance location12 location15) 6)
          (= (distance location15 location12) 6)
          (= (distance location12 location12) 0)
          (= (distance location13 location14) 21)
          (= (distance location14 location13) 21)
          (= (distance location13 location15) 49)
          (= (distance location15 location13) 49)
          (= (distance location13 location13) 0)
          (= (distance location14 location15) 19)
          (= (distance location15 location14) 19)
          (= (distance location14 location14) 0)
          (= (distance location15 location15) 0)
          (typev truck0 flatbed)
          (typevp truck0 truck)
          (at-vehicle truck0 location0)
          (= (gas-left truck0) 294)
          (= (gpm truck0) 3)
          (= (length-v truck0) 8)
          (= (height-v truck0) 6)
          (= (width-v truck0) 5)
          (= (weight-cap-v truck0) 522)
          (= (volume-cap-v truck0) 240)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 19)
          (availablev truck0)
          (typev truck1 flatbed)
          (typevp truck1 truck)
          (at-vehicle truck1 location1)
          (= (gas-left truck1) 361)
          (= (gpm truck1) 1)
          (= (length-v truck1) 12)
          (= (height-v truck1) 2)
          (= (width-v truck1) 6)
          (= (weight-cap-v truck1) 42)
          (= (volume-cap-v truck1) 100)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 30)
          (availablev truck1)
          (typev truck2 flatbed)
          (typevp truck2 truck)
          (at-vehicle truck2 location10)
          (= (gas-left truck2) 226)
          (= (gpm truck2) 3)
          (= (length-v truck2) 5)
          (= (height-v truck2) 7)
          (= (width-v truck2) 5)
          (= (weight-cap-v truck2) 195)
          (= (volume-cap-v truck2) 122)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 23)
          (availablev truck2)
          (typev truck3 flatbed)
          (typevp truck3 truck)
          (at-vehicle truck3 location8)
          (= (gas-left truck3) 338)
          (= (gpm truck3) 2)
          (= (length-v truck3) 5)
          (= (height-v truck3) 7)
          (= (width-v truck3) 3)
          (= (weight-cap-v truck3) 185)
          (= (volume-cap-v truck3) 105)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 22)
          (availablev truck3)
          (typev truck4 flatbed)
          (typevp truck4 truck)
          (at-vehicle truck4 location12)
          (= (gas-left truck4) 404)
          (= (gpm truck4) 1)
          (= (length-v truck4) 8)
          (= (height-v truck4) 9)
          (= (width-v truck4) 10)
          (= (weight-cap-v truck4) 193)
          (= (volume-cap-v truck4) 504)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 38)
          (availablev truck4)
          (typev truck5 flatbed)
          (typevp truck5 truck)
          (at-vehicle truck5 location14)
          (= (gas-left truck5) 485)
          (= (gpm truck5) 1)
          (= (length-v truck5) 19)
          (= (height-v truck5) 9)
          (= (width-v truck5) 8)
          (= (weight-cap-v truck5) 334)
          (= (volume-cap-v truck5) 957)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 32)
          (availablev truck5)
          (typev truck6 flatbed)
          (typevp truck6 truck)
          (at-vehicle truck6 location6)
          (= (gas-left truck6) 383)
          (= (gpm truck6) 1)
          (= (length-v truck6) 9)
          (= (height-v truck6) 9)
          (= (width-v truck6) 6)
          (= (weight-cap-v truck6) 91)
          (= (volume-cap-v truck6) 340)
          (= (weight-load-v truck6) 0)
          (= (volume-load-v truck6) 0)
          (= (weight-v truck6) 34)
          (availablev truck6)
          (typev truck7 flatbed)
          (typevp truck7 truck)
          (at-vehicle truck7 location3)
          (= (gas-left truck7) 131)
          (= (gpm truck7) 2)
          (= (length-v truck7) 14)
          (= (height-v truck7) 3)
          (= (width-v truck7) 9)
          (= (weight-cap-v truck7) 261)
          (= (volume-cap-v truck7) 264)
          (= (weight-load-v truck7) 0)
          (= (volume-load-v truck7) 0)
          (= (weight-v truck7) 30)
          (availablev truck7)
          (typev truck8 flatbed)
          (typevp truck8 truck)
          (at-vehicle truck8 location14)
          (= (gas-left truck8) 441)
          (= (gpm truck8) 3)
          (= (length-v truck8) 10)
          (= (height-v truck8) 8)
          (= (width-v truck8) 2)
          (= (weight-cap-v truck8) 65)
          (= (volume-cap-v truck8) 154)
          (= (weight-load-v truck8) 0)
          (= (volume-load-v truck8) 0)
          (= (weight-v truck8) 17)
          (availablev truck8)
          (typev truck9 flatbed)
          (typevp truck9 truck)
          (at-vehicle truck9 location6)
          (= (gas-left truck9) 395)
          (= (gpm truck9) 2)
          (= (length-v truck9) 12)
          (= (height-v truck9) 5)
          (= (width-v truck9) 1)
          (= (weight-cap-v truck9) 229)
          (= (volume-cap-v truck9) 60)
          (= (weight-load-v truck9) 0)
          (= (volume-load-v truck9) 0)
          (= (weight-v truck9) 17)
          (availablev truck9)
          (typev truck10 flatbed)
          (typevp truck10 truck)
          (at-vehicle truck10 location9)
          (= (gas-left truck10) 217)
          (= (gpm truck10) 2)
          (= (length-v truck10) 7)
          (= (height-v truck10) 10)
          (= (width-v truck10) 4)
          (= (weight-cap-v truck10) 91)
          (= (volume-cap-v truck10) 195)
          (= (weight-load-v truck10) 0)
          (= (volume-load-v truck10) 0)
          (= (weight-v truck10) 24)
          (availablev truck10)
          (typev truck11 flatbed)
          (typevp truck11 truck)
          (at-vehicle truck11 location7)
          (= (gas-left truck11) 448)
          (= (gpm truck11) 3)
          (= (length-v truck11) 8)
          (= (height-v truck11) 6)
          (= (width-v truck11) 1)
          (= (weight-cap-v truck11) 117)
          (= (volume-cap-v truck11) 48)
          (= (weight-load-v truck11) 0)
          (= (volume-load-v truck11) 0)
          (= (weight-v truck11) 10)
          (availablev truck11)
          (typev truck12 flatbed)
          (typevp truck12 truck)
          (at-vehicle truck12 location4)
          (= (gas-left truck12) 282)
          (= (gpm truck12) 1)
          (= (length-v truck12) 7)
          (= (height-v truck12) 3)
          (= (width-v truck12) 3)
          (= (weight-cap-v truck12) 455)
          (= (volume-cap-v truck12) 63)
          (= (weight-load-v truck12) 0)
          (= (volume-load-v truck12) 0)
          (= (weight-v truck12) 21)
          (availablev truck12)
          (typev truck13 flatbed)
          (typevp truck13 truck)
          (at-vehicle truck13 location9)
          (= (gas-left truck13) 122)
          (= (gpm truck13) 2)
          (= (length-v truck13) 5)
          (= (height-v truck13) 9)
          (= (width-v truck13) 2)
          (= (weight-cap-v truck13) 221)
          (= (volume-cap-v truck13) 90)
          (= (weight-load-v truck13) 0)
          (= (volume-load-v truck13) 0)
          (= (weight-v truck13) 27)
          (availablev truck13)
          (typev truck14 flatbed)
          (typevp truck14 truck)
          (at-vehicle truck14 location10)
          (= (gas-left truck14) 268)
          (= (gpm truck14) 1)
          (= (length-v truck14) 12)
          (= (height-v truck14) 3)
          (= (width-v truck14) 3)
          (= (weight-cap-v truck14) 322)
          (= (volume-cap-v truck14) 108)
          (= (weight-load-v truck14) 0)
          (= (volume-load-v truck14) 0)
          (= (weight-v truck14) 16)
          (availablev truck14)
          (typev truck15 flatbed)
          (typevp truck15 truck)
          (at-vehicle truck15 location13)
          (= (gas-left truck15) 167)
          (= (gpm truck15) 3)
          (= (length-v truck15) 5)
          (= (height-v truck15) 9)
          (= (width-v truck15) 5)
          (= (weight-cap-v truck15) 471)
          (= (volume-cap-v truck15) 225)
          (= (weight-load-v truck15) 0)
          (= (volume-load-v truck15) 0)
          (= (weight-v truck15) 19)
          (availablev truck15)
          (typev train0 flatbed)
          (typevp train0 train)
          (at-vehicle train0 location1)
          (= (gas-left train0) 289)
          (= (gpm train0) 3)
          (= (length-v train0) 14)
          (= (height-v train0) 5)
          (= (width-v train0) 3)
          (= (weight-cap-v train0) 470)
          (= (volume-cap-v train0) 204)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 29)
          (availablev train0)
          (typev train1 auto)
          (typevp train1 train)
          (at-vehicle train1 location15)
          (= (gas-left train1) 66)
          (= (gpm train1) 2)
          (= (length-v train1) 15)
          (= (height-v train1) 5)
          (= (width-v train1) 10)
          (= (weight-cap-v train1) 202)
          (= (volume-cap-v train1) 525)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 17)
          (availablev train1)
          (typev train2 flatbed)
          (typevp train2 train)
          (at-vehicle train2 location10)
          (= (gas-left train2) 227)
          (= (gpm train2) 2)
          (= (length-v train2) 13)
          (= (height-v train2) 4)
          (= (width-v train2) 9)
          (= (weight-cap-v train2) 254)
          (= (volume-cap-v train2) 327)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 17)
          (availablev train2)
          (typev train3 flatbed)
          (typevp train3 train)
          (at-vehicle train3 location10)
          (= (gas-left train3) 137)
          (= (gpm train3) 3)
          (= (length-v train3) 17)
          (= (height-v train3) 10)
          (= (width-v train3) 7)
          (= (weight-cap-v train3) 273)
          (= (volume-cap-v train3) 832)
          (= (weight-load-v train3) 0)
          (= (volume-load-v train3) 0)
          (= (weight-v train3) 27)
          (availablev train3)
          (typev train4 flatbed)
          (typevp train4 train)
          (at-vehicle train4 location8)
          (= (gas-left train4) 524)
          (= (gpm train4) 3)
          (= (length-v train4) 13)
          (= (height-v train4) 4)
          (= (width-v train4) 4)
          (= (weight-cap-v train4) 46)
          (= (volume-cap-v train4) 208)
          (= (weight-load-v train4) 0)
          (= (volume-load-v train4) 0)
          (= (weight-v train4) 32)
          (availablev train4)
          (typev train5 flatbed)
          (typevp train5 train)
          (at-vehicle train5 location10)
          (= (gas-left train5) 331)
          (= (gpm train5) 3)
          (= (length-v train5) 16)
          (= (height-v train5) 2)
          (= (width-v train5) 2)
          (= (weight-cap-v train5) 429)
          (= (volume-cap-v train5) 64)
          (= (weight-load-v train5) 0)
          (= (volume-load-v train5) 0)
          (= (weight-v train5) 37)
          (availablev train5)
          (typev train6 flatbed)
          (typevp train6 train)
          (at-vehicle train6 location8)
          (= (gas-left train6) 395)
          (= (gpm train6) 3)
          (= (length-v train6) 13)
          (= (height-v train6) 9)
          (= (width-v train6) 9)
          (= (weight-cap-v train6) 408)
          (= (volume-cap-v train6) 737)
          (= (weight-load-v train6) 0)
          (= (volume-load-v train6) 0)
          (= (weight-v train6) 21)
          (availablev train6)
          (typev train7 flatbed)
          (typevp train7 train)
          (at-vehicle train7 location15)
          (= (gas-left train7) 224)
          (= (gpm train7) 1)
          (= (length-v train7) 13)
          (= (height-v train7) 4)
          (= (width-v train7) 7)
          (= (weight-cap-v train7) 233)
          (= (volume-cap-v train7) 254)
          (= (weight-load-v train7) 0)
          (= (volume-load-v train7) 0)
          (= (weight-v train7) 27)
          (availablev train7)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location5)
          (= (gas-left airplane0) 526)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 14)
          (= (height-v airplane0) 9)
          (= (width-v airplane0) 1)
          (= (weight-cap-v airplane0) 329)
          (= (volume-cap-v airplane0) 126)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 18)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location4)
          (= (gas-left airplane1) 544)
          (= (gpm airplane1) 3)
          (= (length-v airplane1) 19)
          (= (height-v airplane1) 7)
          (= (width-v airplane1) 8)
          (= (weight-cap-v airplane1) 287)
          (= (volume-cap-v airplane1) 744)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 35)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location4)
          (= (gas-left airplane2) 182)
          (= (gpm airplane2) 3)
          (= (length-v airplane2) 14)
          (= (height-v airplane2) 6)
          (= (width-v airplane2) 6)
          (= (weight-cap-v airplane2) 518)
          (= (volume-cap-v airplane2) 352)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 39)
          (availablev airplane2)
          (typev airplane3 air)
          (typevp airplane3 airplane)
          (at-vehicle airplane3 location4)
          (= (gas-left airplane3) 299)
          (= (gpm airplane3) 2)
          (= (length-v airplane3) 7)
          (= (height-v airplane3) 2)
          (= (width-v airplane3) 10)
          (= (weight-cap-v airplane3) 192)
          (= (volume-cap-v airplane3) 114)
          (= (weight-load-v airplane3) 0)
          (= (volume-load-v airplane3) 0)
          (= (weight-v airplane3) 28)
          (availablev airplane3)
          (typev airplane4 air)
          (typevp airplane4 airplane)
          (at-vehicle airplane4 location5)
          (= (gas-left airplane4) 376)
          (= (gpm airplane4) 1)
          (= (length-v airplane4) 6)
          (= (height-v airplane4) 2)
          (= (width-v airplane4) 7)
          (= (weight-cap-v airplane4) 221)
          (= (volume-cap-v airplane4) 84)
          (= (weight-load-v airplane4) 0)
          (= (volume-load-v airplane4) 0)
          (= (weight-v airplane4) 24)
          (availablev airplane4)
          (typev airplane5 air)
          (typevp airplane5 airplane)
          (at-vehicle airplane5 location5)
          (= (gas-left airplane5) 238)
          (= (gpm airplane5) 1)
          (= (length-v airplane5) 13)
          (= (height-v airplane5) 10)
          (= (width-v airplane5) 9)
          (= (weight-cap-v airplane5) 355)
          (= (volume-cap-v airplane5) 818)
          (= (weight-load-v airplane5) 0)
          (= (volume-load-v airplane5) 0)
          (= (weight-v airplane5) 13)
          (availablev airplane5)
          (typev airplane6 air)
          (typevp airplane6 airplane)
          (at-vehicle airplane6 location12)
          (= (gas-left airplane6) 417)
          (= (gpm airplane6) 1)
          (= (length-v airplane6) 16)
          (= (height-v airplane6) 7)
          (= (width-v airplane6) 5)
          (= (weight-cap-v airplane6) 490)
          (= (volume-cap-v airplane6) 392)
          (= (weight-load-v airplane6) 0)
          (= (volume-load-v airplane6) 0)
          (= (weight-v airplane6) 11)
          (availablev airplane6)
          (typev airplane7 air)
          (typevp airplane7 airplane)
          (at-vehicle airplane7 location7)
          (= (gas-left airplane7) 63)
          (= (gpm airplane7) 1)
          (= (length-v airplane7) 13)
          (= (height-v airplane7) 4)
          (= (width-v airplane7) 1)
          (= (weight-cap-v airplane7) 66)
          (= (volume-cap-v airplane7) 52)
          (= (weight-load-v airplane7) 0)
          (= (volume-load-v airplane7) 0)
          (= (weight-v airplane7) 39)
          (availablev airplane7)
          (at-equipment crane0 location0)
          (empty crane0)
          (= (weight-cap-c crane0) 70)
          (= (volume-cap-c crane0) 64)
          (at-equipment crane1 location1)
          (empty crane1)
          (= (weight-cap-c crane1) 461)
          (= (volume-cap-c crane1) 87)
          (at-equipment crane2 location2)
          (empty crane2)
          (= (weight-cap-c crane2) 349)
          (= (volume-cap-c crane2) 265)
          (at-equipment crane3 location3)
          (empty crane3)
          (= (weight-cap-c crane3) 53)
          (= (volume-cap-c crane3) 183)
          (at-equipment crane4 location4)
          (empty crane4)
          (= (weight-cap-c crane4) 196)
          (= (volume-cap-c crane4) 89)
          (at-equipment crane5 location5)
          (empty crane5)
          (= (weight-cap-c crane5) 444)
          (= (volume-cap-c crane5) 260)
          (at-equipment crane6 location6)
          (empty crane6)
          (= (weight-cap-c crane6) 419)
          (= (volume-cap-c crane6) 253)
          (at-equipment crane7 location7)
          (empty crane7)
          (= (weight-cap-c crane7) 411)
          (= (volume-cap-c crane7) 172)
          (at-equipment crane8 location8)
          (empty crane8)
          (= (weight-cap-c crane8) 271)
          (= (volume-cap-c crane8) 181)
          (at-equipment crane9 location9)
          (empty crane9)
          (= (weight-cap-c crane9) 95)
          (= (volume-cap-c crane9) 370)
          (at-equipment crane10 location10)
          (empty crane10)
          (= (weight-cap-c crane10) 441)
          (= (volume-cap-c crane10) 54)
          (at-equipment crane11 location11)
          (empty crane11)
          (= (weight-cap-c crane11) 211)
          (= (volume-cap-c crane11) 138)
          (at-equipment crane12 location12)
          (empty crane12)
          (= (weight-cap-c crane12) 61)
          (= (volume-cap-c crane12) 176)
          (at-equipment crane13 location13)
          (empty crane13)
          (= (weight-cap-c crane13) 188)
          (= (volume-cap-c crane13) 86)
          (at-equipment crane14 location14)
          (empty crane14)
          (= (weight-cap-c crane14) 130)
          (= (volume-cap-c crane14) 461)
          (at-equipment crane15 location15)
          (empty crane15)
          (= (weight-cap-c crane15) 448)
          (= (volume-cap-c crane15) 67)
          (at-equipment plane_ramp0 location4)
          (at-equipment plane_ramp1 location5)
          (at-equipment plane_ramp2 location7)
          (at-equipment plane_ramp3 location12)
          (typep package0 bulky)
          (at-packagel package0 location13)
          (= (volume-p package0) 5)
          (= (weight-p package0) 19)
          (typep package1 bulky)
          (at-packagel package1 location6)
          (= (volume-p package1) 5)
          (= (weight-p package1) 16)
          (typep package2 bulky)
          (at-packagel package2 location1)
          (= (volume-p package2) 18)
          (= (weight-p package2) 18)
          (typep package3 bulky)
          (at-packagel package3 location0)
          (= (volume-p package3) 9)
          (= (weight-p package3) 23)
          (typep package4 bulky)
          (at-packagel package4 location12)
          (= (volume-p package4) 15)
          (= (weight-p package4) 12)
          (typep package5 bulky)
          (at-packagel package5 location13)
          (= (volume-p package5) 20)
          (= (weight-p package5) 24)
          (typep package6 bulky)
          (at-packagel package6 location2)
          (= (volume-p package6) 15)
          (= (weight-p package6) 11)
          (typep package7 bulky)
          (at-packagel package7 location14)
          (= (volume-p package7) 19)
          (= (weight-p package7) 19)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 27)
          (= (weight-cap-r road_route0) 390)
          (availabler road_route0)
          (connect-city road_route1 road-route city0 city2)
          (= (height-cap-r road_route1) 12)
          (= (weight-cap-r road_route1) 59)
          (availabler road_route1)
          (connect-city road_route2 road-route city0 city4)
          (= (height-cap-r road_route2) 11)
          (= (weight-cap-r road_route2) 184)
          (availabler road_route2)
          (connect-city road_route3 road-route city0 city5)
          (= (height-cap-r road_route3) 18)
          (= (weight-cap-r road_route3) 62)
          (availabler road_route3)
          (connect-city road_route4 road-route city1 city0)
          (= (height-cap-r road_route4) 24)
          (= (weight-cap-r road_route4) 472)
          (availabler road_route4)
          (connect-city road_route5 road-route city1 city2)
          (= (height-cap-r road_route5) 11)
          (= (weight-cap-r road_route5) 304)
          (availabler road_route5)
          (connect-city road_route6 road-route city1 city3)
          (= (height-cap-r road_route6) 5)
          (= (weight-cap-r road_route6) 137)
          (availabler road_route6)
          (connect-city road_route7 road-route city1 city4)
          (= (height-cap-r road_route7) 10)
          (= (weight-cap-r road_route7) 114)
          (availabler road_route7)
          (connect-city road_route8 road-route city1 city5)
          (= (height-cap-r road_route8) 34)
          (= (weight-cap-r road_route8) 295)
          (availabler road_route8)
          (connect-city road_route9 road-route city2 city0)
          (= (height-cap-r road_route9) 11)
          (= (weight-cap-r road_route9) 447)
          (availabler road_route9)
          (connect-city road_route10 road-route city2 city3)
          (= (height-cap-r road_route10) 23)
          (= (weight-cap-r road_route10) 546)
          (availabler road_route10)
          (connect-city road_route11 road-route city2 city4)
          (= (height-cap-r road_route11) 25)
          (= (weight-cap-r road_route11) 152)
          (availabler road_route11)
          (connect-city road_route12 road-route city2 city5)
          (= (height-cap-r road_route12) 13)
          (= (weight-cap-r road_route12) 88)
          (availabler road_route12)
          (connect-city road_route13 road-route city3 city0)
          (= (height-cap-r road_route13) 8)
          (= (weight-cap-r road_route13) 89)
          (availabler road_route13)
          (connect-city road_route14 road-route city3 city1)
          (= (height-cap-r road_route14) 33)
          (= (weight-cap-r road_route14) 317)
          (availabler road_route14)
          (connect-city road_route15 road-route city3 city2)
          (= (height-cap-r road_route15) 17)
          (= (weight-cap-r road_route15) 543)
          (availabler road_route15)
          (connect-city road_route16 road-route city3 city4)
          (= (height-cap-r road_route16) 24)
          (= (weight-cap-r road_route16) 142)
          (availabler road_route16)
          (connect-city road_route17 road-route city3 city5)
          (= (height-cap-r road_route17) 17)
          (= (weight-cap-r road_route17) 480)
          (availabler road_route17)
          (connect-city road_route18 road-route city4 city0)
          (= (height-cap-r road_route18) 19)
          (= (weight-cap-r road_route18) 291)
          (availabler road_route18)
          (connect-city road_route19 road-route city4 city1)
          (= (height-cap-r road_route19) 15)
          (= (weight-cap-r road_route19) 178)
          (availabler road_route19)
          (connect-city road_route20 road-route city4 city2)
          (= (height-cap-r road_route20) 34)
          (= (weight-cap-r road_route20) 172)
          (availabler road_route20)
          (connect-city road_route21 road-route city4 city3)
          (= (height-cap-r road_route21) 14)
          (= (weight-cap-r road_route21) 128)
          (availabler road_route21)
          (connect-city road_route22 road-route city5 city0)
          (= (height-cap-r road_route22) 18)
          (= (weight-cap-r road_route22) 428)
          (availabler road_route22)
          (connect-city road_route23 road-route city5 city1)
          (= (height-cap-r road_route23) 28)
          (= (weight-cap-r road_route23) 386)
          (availabler road_route23)
          (connect-city road_route24 road-route city5 city2)
          (= (height-cap-r road_route24) 8)
          (= (weight-cap-r road_route24) 200)
          (availabler road_route24)
          (connect-city road_route25 road-route city5 city3)
          (= (height-cap-r road_route25) 17)
          (= (weight-cap-r road_route25) 96)
          (availabler road_route25)
          (connect-city road_route26 road-route city5 city4)
          (= (height-cap-r road_route26) 9)
          (= (weight-cap-r road_route26) 121)
          (availabler road_route26)
          (connect-loc rail_route0 rail-route location0 location1)
          (= (height-cap-r rail_route0) 26)
          (= (weight-cap-r rail_route0) 505)
          (serves location0 region2)
          (serves location1 region1)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location0 location3)
          (= (height-cap-r rail_route1) 5)
          (= (weight-cap-r rail_route1) 536)
          (serves location0 region1)
          (serves location3 region1)
          (availabler rail_route1)
          (connect-loc rail_route2 rail-route location0 location8)
          (= (height-cap-r rail_route2) 22)
          (= (weight-cap-r rail_route2) 460)
          (availabler rail_route2)
          (connect-loc rail_route3 rail-route location0 location9)
          (= (height-cap-r rail_route3) 19)
          (= (weight-cap-r rail_route3) 299)
          (availabler rail_route3)
          (connect-loc rail_route4 rail-route location0 location10)
          (= (height-cap-r rail_route4) 7)
          (= (weight-cap-r rail_route4) 150)
          (serves location10 region1)
          (availabler rail_route4)
          (connect-loc rail_route5 rail-route location0 location15)
          (= (height-cap-r rail_route5) 22)
          (= (weight-cap-r rail_route5) 421)
          (serves location0 region3)
          (availabler rail_route5)
          (connect-loc rail_route6 rail-route location1 location0)
          (= (height-cap-r rail_route6) 27)
          (= (weight-cap-r rail_route6) 179)
          (availabler rail_route6)
          (connect-loc rail_route7 rail-route location1 location3)
          (= (height-cap-r rail_route7) 25)
          (= (weight-cap-r rail_route7) 191)
          (serves location3 region2)
          (availabler rail_route7)
          (connect-loc rail_route8 rail-route location1 location8)
          (= (height-cap-r rail_route8) 7)
          (= (weight-cap-r rail_route8) 496)
          (serves location1 region2)
          (availabler rail_route8)
          (connect-loc rail_route9 rail-route location1 location9)
          (= (height-cap-r rail_route9) 25)
          (= (weight-cap-r rail_route9) 304)
          (availabler rail_route9)
          (connect-loc rail_route10 rail-route location1 location10)
          (= (height-cap-r rail_route10) 12)
          (= (weight-cap-r rail_route10) 264)
          (serves location10 region2)
          (availabler rail_route10)
          (connect-loc rail_route11 rail-route location1 location15)
          (= (height-cap-r rail_route11) 7)
          (= (weight-cap-r rail_route11) 165)
          (serves location1 region3)
          (availabler rail_route11)
          (connect-loc rail_route12 rail-route location3 location0)
          (= (height-cap-r rail_route12) 20)
          (= (weight-cap-r rail_route12) 406)
          (availabler rail_route12)
          (connect-loc rail_route13 rail-route location3 location1)
          (= (height-cap-r rail_route13) 29)
          (= (weight-cap-r rail_route13) 125)
          (availabler rail_route13)
          (connect-loc rail_route14 rail-route location3 location8)
          (= (height-cap-r rail_route14) 25)
          (= (weight-cap-r rail_route14) 155)
          (availabler rail_route14)
          (connect-loc rail_route15 rail-route location3 location9)
          (= (height-cap-r rail_route15) 34)
          (= (weight-cap-r rail_route15) 95)
          (availabler rail_route15)
          (connect-loc rail_route16 rail-route location3 location10)
          (= (height-cap-r rail_route16) 9)
          (= (weight-cap-r rail_route16) 90)
          (availabler rail_route16)
          (connect-loc rail_route17 rail-route location3 location15)
          (= (height-cap-r rail_route17) 8)
          (= (weight-cap-r rail_route17) 530)
          (serves location3 region3)
          (availabler rail_route17)
          (connect-loc rail_route18 rail-route location8 location0)
          (= (height-cap-r rail_route18) 17)
          (= (weight-cap-r rail_route18) 256)
          (availabler rail_route18)
          (connect-loc rail_route19 rail-route location8 location1)
          (= (height-cap-r rail_route19) 13)
          (= (weight-cap-r rail_route19) 484)
          (availabler rail_route19)
          (connect-loc rail_route20 rail-route location8 location3)
          (= (height-cap-r rail_route20) 8)
          (= (weight-cap-r rail_route20) 81)
          (availabler rail_route20)
          (connect-loc rail_route21 rail-route location8 location9)
          (= (height-cap-r rail_route21) 5)
          (= (weight-cap-r rail_route21) 477)
          (availabler rail_route21)
          (connect-loc rail_route22 rail-route location8 location10)
          (= (height-cap-r rail_route22) 16)
          (= (weight-cap-r rail_route22) 435)
          (availabler rail_route22)
          (connect-loc rail_route23 rail-route location8 location15)
          (= (height-cap-r rail_route23) 31)
          (= (weight-cap-r rail_route23) 115)
          (availabler rail_route23)
          (connect-loc rail_route24 rail-route location9 location0)
          (= (height-cap-r rail_route24) 12)
          (= (weight-cap-r rail_route24) 309)
          (availabler rail_route24)
          (connect-loc rail_route25 rail-route location9 location1)
          (= (height-cap-r rail_route25) 23)
          (= (weight-cap-r rail_route25) 481)
          (availabler rail_route25)
          (connect-loc rail_route26 rail-route location9 location8)
          (= (height-cap-r rail_route26) 14)
          (= (weight-cap-r rail_route26) 350)
          (availabler rail_route26)
          (connect-loc rail_route27 rail-route location9 location10)
          (= (height-cap-r rail_route27) 29)
          (= (weight-cap-r rail_route27) 525)
          (availabler rail_route27)
          (connect-loc rail_route28 rail-route location9 location15)
          (= (height-cap-r rail_route28) 31)
          (= (weight-cap-r rail_route28) 58)
          (availabler rail_route28)
          (connect-loc rail_route29 rail-route location10 location0)
          (= (height-cap-r rail_route29) 17)
          (= (weight-cap-r rail_route29) 139)
          (availabler rail_route29)
          (connect-loc rail_route30 rail-route location10 location1)
          (= (height-cap-r rail_route30) 27)
          (= (weight-cap-r rail_route30) 248)
          (availabler rail_route30)
          (connect-loc rail_route31 rail-route location10 location3)
          (= (height-cap-r rail_route31) 8)
          (= (weight-cap-r rail_route31) 291)
          (connect-loc rail_route32 rail-route location10 location8)
          (= (height-cap-r rail_route32) 7)
          (= (weight-cap-r rail_route32) 55)
          (availabler rail_route32)
          (connect-loc rail_route33 rail-route location10 location9)
          (= (height-cap-r rail_route33) 33)
          (= (weight-cap-r rail_route33) 309)
          (availabler rail_route33)
          (connect-loc rail_route34 rail-route location10 location15)
          (= (height-cap-r rail_route34) 6)
          (= (weight-cap-r rail_route34) 394)
          (serves location10 region3)
          (availabler rail_route34)
          (connect-loc rail_route35 rail-route location15 location0)
          (= (height-cap-r rail_route35) 30)
          (= (weight-cap-r rail_route35) 533)
          (availabler rail_route35)
          (connect-loc rail_route36 rail-route location15 location1)
          (= (height-cap-r rail_route36) 12)
          (= (weight-cap-r rail_route36) 422)
          (availabler rail_route36)
          (connect-loc rail_route37 rail-route location15 location3)
          (= (height-cap-r rail_route37) 9)
          (= (weight-cap-r rail_route37) 310)
          (availabler rail_route37)
          (connect-loc rail_route38 rail-route location15 location8)
          (= (height-cap-r rail_route38) 11)
          (= (weight-cap-r rail_route38) 402)
          (availabler rail_route38)
          (connect-loc rail_route39 rail-route location15 location9)
          (= (height-cap-r rail_route39) 33)
          (= (weight-cap-r rail_route39) 334)
          (availabler rail_route39)
          (connect-loc rail_route40 rail-route location15 location10)
          (= (height-cap-r rail_route40) 15)
          (= (weight-cap-r rail_route40) 390)
          (availabler rail_route40)
          (connect-loc air_route0 air-route location4 location5)
          (= (height-cap-r air_route0) 26)
          (= (weight-cap-r air_route0) 318)
          (serves location4 region2)
          (serves location5 region0)
          (availabler air_route0)
          (connect-loc air_route1 air-route location4 location7)
          (= (height-cap-r air_route1) 10)
          (= (weight-cap-r air_route1) 299)
          (availabler air_route1)
          (connect-loc air_route2 air-route location4 location12)
          (= (height-cap-r air_route2) 14)
          (= (weight-cap-r air_route2) 114)
          (availabler air_route2)
          (connect-loc air_route3 air-route location5 location4)
          (= (height-cap-r air_route3) 26)
          (= (weight-cap-r air_route3) 503)
          (availabler air_route3)
          (connect-loc air_route4 air-route location5 location7)
          (= (height-cap-r air_route4) 26)
          (= (weight-cap-r air_route4) 509)
          (serves location5 region2)
          (availabler air_route4)
          (connect-loc air_route5 air-route location5 location12)
          (= (height-cap-r air_route5) 33)
          (= (weight-cap-r air_route5) 299)
          (availabler air_route5)
          (connect-loc air_route6 air-route location7 location4)
          (= (height-cap-r air_route6) 33)
          (= (weight-cap-r air_route6) 73)
          (availabler air_route6)
          (connect-loc air_route7 air-route location7 location5)
          (= (height-cap-r air_route7) 22)
          (= (weight-cap-r air_route7) 125)
          (availabler air_route7)
          (connect-loc air_route8 air-route location7 location12)
          (= (height-cap-r air_route8) 15)
          (= (weight-cap-r air_route8) 521)
          (availabler air_route8)
          (connect-loc air_route9 air-route location12 location4)
          (= (height-cap-r air_route9) 25)
          (= (weight-cap-r air_route9) 108)
          (availabler air_route9)
          (connect-loc air_route10 air-route location12 location5)
          (= (height-cap-r air_route10) 18)
          (= (weight-cap-r air_route10) 233)
          (availabler air_route10)
          (= (volume-load-l location0) 9)
          (= (volume-load-l location1) 18)
          (= (volume-load-l location2) 15)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 0)
          (= (volume-load-l location5) 0)
          (= (volume-load-l location6) 5)
          (= (volume-load-l location7) 0)
          (= (volume-load-l location8) 0)
          (= (volume-load-l location9) 0)
          (= (volume-load-l location10) 0)
          (= (volume-load-l location11) 0)
          (= (volume-load-l location12) 15)
          (= (volume-load-l location13) 25)
          (= (volume-load-l location14) 19)
          (= (volume-load-l location15) 0)
   )

   (:goal (and (delivered package0 location5)
               (delivered package1 location14)
               (delivered package2 location1)
               (delivered package3 location4)
               (delivered package4 location9)
               (delivered package5 location2)
               (delivered package6 location15)
               (delivered package7 location8)
               (clear)))

)