(define (problem problem1)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 region1 region2 region3 - region
          city0 city1 city2 city3 city4 city5 - city
          location0 location1 location2 location3 location4 location5 location6 location7 location8 location9 location10 location11 location12 location13 location14 location15 - location
          truck0 truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 truck11 truck12 truck13 truck14 truck15 train0 train1 train2 train3 train4 train5 train6 train7 airplane0 airplane1 airplane2 airplane3 airplane4 airplane5 airplane6 airplane7 - vehicle
          plane_ramp0 plane_ramp1 plane_ramp2 plane_ramp3 plane_ramp4 plane_ramp5 - plane-ramp
          package0 package1 package2 package3 package4 package5 package6 package7 - package
          road_route0 road_route1 road_route2 road_route3 road_route4 road_route5 road_route6 road_route7 road_route8 road_route9 road_route10 road_route11 road_route12 road_route13 road_route14 road_route15 road_route16 road_route17 road_route18 road_route19 road_route20 road_route21 road_route22 road_route23 road_route24 road_route25 road_route26 road_route27 - route
          rail_route0 rail_route1 rail_route2 rail_route3 rail_route4 rail_route5 rail_route6 rail_route7 rail_route8 rail_route9 rail_route10 rail_route11 rail_route12 rail_route13 rail_route14 rail_route15 rail_route16 rail_route17 rail_route18 rail_route19 rail_route20 rail_route21 rail_route22 rail_route23 rail_route24 rail_route25 rail_route26 rail_route27 rail_route28 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 air_route6 air_route7 air_route8 air_route9 air_route10 air_route11 air_route12 air_route13 air_route14 air_route15 air_route16 air_route17 air_route18 air_route19 air_route20 air_route21 air_route22 air_route23 air_route24 air_route25 air_route26 air_route27 air_route28 air_route29 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region1)
          (= (local-height city0) 35)
          (= (local-weight city0) 58)
          (in-region city1 region3)
          (= (local-height city1) 29)
          (= (local-weight city1) 123)
          (in-region city2 region1)
          (= (local-height city2) 21)
          (= (local-weight city2) 325)
          (in-region city3 region0)
          (= (local-height city3) 18)
          (= (local-weight city3) 543)
          (in-region city4 region0)
          (= (local-height city4) 11)
          (= (local-weight city4) 74)
          (in-region city5 region0)
          (= (local-height city5) 32)
          (= (local-weight city5) 329)
          (in-city location0 city4)
          (= (height-cap-l location0) 12)
          (= (length-cap-l location0) 11)
          (= (width-cap-l location0) 14)
          (= (volume-cap-l location0) 171)
          (in-city location1 city1)
          (= (height-cap-l location1) 30)
          (= (length-cap-l location1) 44)
          (= (width-cap-l location1) 26)
          (= (volume-cap-l location1) 240)
          (tcenter location1)
          (typel location1 train-station)
          (availablel location1)
          (in-city location2 city5)
          (= (height-cap-l location2) 21)
          (= (length-cap-l location2) 37)
          (= (width-cap-l location2) 10)
          (= (volume-cap-l location2) 282)
          (tcenter location2)
          (typel location2 train-station)
          (availablel location2)
          (in-city location3 city4)
          (= (height-cap-l location3) 35)
          (= (length-cap-l location3) 16)
          (= (width-cap-l location3) 24)
          (= (volume-cap-l location3) 434)
          (tcenter location3)
          (typel location3 airport)
          (availablel location3)
          (hub location3)
          (in-city location4 city4)
          (= (height-cap-l location4) 23)
          (= (length-cap-l location4) 15)
          (= (width-cap-l location4) 21)
          (= (volume-cap-l location4) 494)
          (tcenter location4)
          (typel location4 train-station)
          (availablel location4)
          (hub location4)
          (in-city location5 city3)
          (= (height-cap-l location5) 16)
          (= (length-cap-l location5) 47)
          (= (width-cap-l location5) 30)
          (= (volume-cap-l location5) 345)
          (tcenter location5)
          (typel location5 airport)
          (availablel location5)
          (hub location5)
          (in-city location6 city3)
          (= (height-cap-l location6) 24)
          (= (length-cap-l location6) 31)
          (= (width-cap-l location6) 11)
          (= (volume-cap-l location6) 519)
          (tcenter location6)
          (typel location6 train-station)
          (availablel location6)
          (hub location6)
          (in-city location7 city2)
          (= (height-cap-l location7) 29)
          (= (length-cap-l location7) 23)
          (= (width-cap-l location7) 16)
          (= (volume-cap-l location7) 172)
          (tcenter location7)
          (typel location7 train-station)
          (availablel location7)
          (hub location7)
          (in-city location8 city5)
          (= (height-cap-l location8) 16)
          (= (length-cap-l location8) 24)
          (= (width-cap-l location8) 30)
          (= (volume-cap-l location8) 119)
          (tcenter location8)
          (typel location8 train-station)
          (availablel location8)
          (hub location8)
          (in-city location9 city1)
          (= (height-cap-l location9) 18)
          (= (length-cap-l location9) 22)
          (= (width-cap-l location9) 24)
          (= (volume-cap-l location9) 297)
          (tcenter location9)
          (typel location9 airport)
          (availablel location9)
          (hub location9)
          (in-city location10 city0)
          (= (height-cap-l location10) 24)
          (= (length-cap-l location10) 35)
          (= (width-cap-l location10) 28)
          (= (volume-cap-l location10) 520)
          (in-city location11 city5)
          (= (height-cap-l location11) 18)
          (= (length-cap-l location11) 17)
          (= (width-cap-l location11) 12)
          (= (volume-cap-l location11) 298)
          (in-city location12 city0)
          (= (height-cap-l location12) 36)
          (= (length-cap-l location12) 41)
          (= (width-cap-l location12) 20)
          (= (volume-cap-l location12) 313)
          (tcenter location12)
          (typel location12 airport)
          (availablel location12)
          (in-city location13 city3)
          (= (height-cap-l location13) 17)
          (= (length-cap-l location13) 32)
          (= (width-cap-l location13) 24)
          (= (volume-cap-l location13) 152)
          (tcenter location13)
          (typel location13 airport)
          (availablel location13)
          (hub location13)
          (in-city location14 city1)
          (= (height-cap-l location14) 34)
          (= (length-cap-l location14) 33)
          (= (width-cap-l location14) 36)
          (= (volume-cap-l location14) 283)
          (tcenter location14)
          (typel location14 airport)
          (availablel location14)
          (hub location14)
          (in-city location15 city3)
          (= (height-cap-l location15) 33)
          (= (length-cap-l location15) 37)
          (= (width-cap-l location15) 28)
          (= (volume-cap-l location15) 110)
          (= (distance location0 location1) 31)
          (= (distance location1 location0) 31)
          (= (distance location0 location2) 30)
          (= (distance location2 location0) 30)
          (= (distance location0 location3) 62)
          (= (distance location3 location0) 62)
          (= (distance location0 location4) 0)
          (= (distance location4 location0) 0)
          (= (distance location0 location5) 69)
          (= (distance location5 location0) 69)
          (= (distance location0 location6) 31)
          (= (distance location6 location0) 31)
          (= (distance location0 location7) 10)
          (= (distance location7 location0) 10)
          (= (distance location0 location8) 44)
          (= (distance location8 location0) 44)
          (= (distance location0 location9) 61)
          (= (distance location9 location0) 61)
          (= (distance location0 location10) 3)
          (= (distance location10 location0) 3)
          (= (distance location0 location11) 25)
          (= (distance location11 location0) 25)
          (= (distance location0 location12) 1)
          (= (distance location12 location0) 1)
          (= (distance location0 location13) 10)
          (= (distance location13 location0) 10)
          (= (distance location0 location14) 22)
          (= (distance location14 location0) 22)
          (= (distance location0 location15) 2)
          (= (distance location15 location0) 2)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 42)
          (= (distance location2 location1) 42)
          (= (distance location1 location3) 14)
          (= (distance location3 location1) 14)
          (= (distance location1 location4) 42)
          (= (distance location4 location1) 42)
          (= (distance location1 location5) 46)
          (= (distance location5 location1) 46)
          (= (distance location1 location6) 61)
          (= (distance location6 location1) 61)
          (= (distance location1 location7) 9)
          (= (distance location7 location1) 9)
          (= (distance location1 location8) 34)
          (= (distance location8 location1) 34)
          (= (distance location1 location9) 59)
          (= (distance location9 location1) 59)
          (= (distance location1 location10) 16)
          (= (distance location10 location1) 16)
          (= (distance location1 location11) 22)
          (= (distance location11 location1) 22)
          (= (distance location1 location12) 22)
          (= (distance location12 location1) 22)
          (= (distance location1 location13) 61)
          (= (distance location13 location1) 61)
          (= (distance location1 location14) 36)
          (= (distance location14 location1) 36)
          (= (distance location1 location15) 33)
          (= (distance location15 location1) 33)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 51)
          (= (distance location3 location2) 51)
          (= (distance location2 location4) 12)
          (= (distance location4 location2) 12)
          (= (distance location2 location5) 53)
          (= (distance location5 location2) 53)
          (= (distance location2 location6) 0)
          (= (distance location6 location2) 0)
          (= (distance location2 location7) 6)
          (= (distance location7 location2) 6)
          (= (distance location2 location8) 51)
          (= (distance location8 location2) 51)
          (= (distance location2 location9) 39)
          (= (distance location9 location2) 39)
          (= (distance location2 location10) 43)
          (= (distance location10 location2) 43)
          (= (distance location2 location11) 69)
          (= (distance location11 location2) 69)
          (= (distance location2 location12) 20)
          (= (distance location12 location2) 20)
          (= (distance location2 location13) 14)
          (= (distance location13 location2) 14)
          (= (distance location2 location14) 31)
          (= (distance location14 location2) 31)
          (= (distance location2 location15) 33)
          (= (distance location15 location2) 33)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 48)
          (= (distance location4 location3) 48)
          (= (distance location3 location5) 0)
          (= (distance location5 location3) 0)
          (= (distance location3 location6) 61)
          (= (distance location6 location3) 61)
          (= (distance location3 location7) 55)
          (= (distance location7 location3) 55)
          (= (distance location3 location8) 45)
          (= (distance location8 location3) 45)
          (= (distance location3 location9) 63)
          (= (distance location9 location3) 63)
          (= (distance location3 location10) 15)
          (= (distance location10 location3) 15)
          (= (distance location3 location11) 32)
          (= (distance location11 location3) 32)
          (= (distance location3 location12) 54)
          (= (distance location12 location3) 54)
          (= (distance location3 location13) 16)
          (= (distance location13 location3) 16)
          (= (distance location3 location14) 4)
          (= (distance location14 location3) 4)
          (= (distance location3 location15) 32)
          (= (distance location15 location3) 32)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 68)
          (= (distance location5 location4) 68)
          (= (distance location4 location6) 25)
          (= (distance location6 location4) 25)
          (= (distance location4 location7) 45)
          (= (distance location7 location4) 45)
          (= (distance location4 location8) 69)
          (= (distance location8 location4) 69)
          (= (distance location4 location9) 26)
          (= (distance location9 location4) 26)
          (= (distance location4 location10) 53)
          (= (distance location10 location4) 53)
          (= (distance location4 location11) 35)
          (= (distance location11 location4) 35)
          (= (distance location4 location12) 3)
          (= (distance location12 location4) 3)
          (= (distance location4 location13) 46)
          (= (distance location13 location4) 46)
          (= (distance location4 location14) 19)
          (= (distance location14 location4) 19)
          (= (distance location4 location15) 18)
          (= (distance location15 location4) 18)
          (= (distance location4 location4) 0)
          (= (distance location5 location6) 33)
          (= (distance location6 location5) 33)
          (= (distance location5 location7) 3)
          (= (distance location7 location5) 3)
          (= (distance location5 location8) 37)
          (= (distance location8 location5) 37)
          (= (distance location5 location9) 23)
          (= (distance location9 location5) 23)
          (= (distance location5 location10) 25)
          (= (distance location10 location5) 25)
          (= (distance location5 location11) 12)
          (= (distance location11 location5) 12)
          (= (distance location5 location12) 44)
          (= (distance location12 location5) 44)
          (= (distance location5 location13) 10)
          (= (distance location13 location5) 10)
          (= (distance location5 location14) 36)
          (= (distance location14 location5) 36)
          (= (distance location5 location15) 21)
          (= (distance location15 location5) 21)
          (= (distance location5 location5) 0)
          (= (distance location6 location7) 46)
          (= (distance location7 location6) 46)
          (= (distance location6 location8) 5)
          (= (distance location8 location6) 5)
          (= (distance location6 location9) 49)
          (= (distance location9 location6) 49)
          (= (distance location6 location10) 2)
          (= (distance location10 location6) 2)
          (= (distance location6 location11) 41)
          (= (distance location11 location6) 41)
          (= (distance location6 location12) 45)
          (= (distance location12 location6) 45)
          (= (distance location6 location13) 51)
          (= (distance location13 location6) 51)
          (= (distance location6 location14) 54)
          (= (distance location14 location6) 54)
          (= (distance location6 location15) 54)
          (= (distance location15 location6) 54)
          (= (distance location6 location6) 0)
          (= (distance location7 location8) 69)
          (= (distance location8 location7) 69)
          (= (distance location7 location9) 62)
          (= (distance location9 location7) 62)
          (= (distance location7 location10) 37)
          (= (distance location10 location7) 37)
          (= (distance location7 location11) 2)
          (= (distance location11 location7) 2)
          (= (distance location7 location12) 57)
          (= (distance location12 location7) 57)
          (= (distance location7 location13) 24)
          (= (distance location13 location7) 24)
          (= (distance location7 location14) 9)
          (= (distance location14 location7) 9)
          (= (distance location7 location15) 47)
          (= (distance location15 location7) 47)
          (= (distance location7 location7) 0)
          (= (distance location8 location9) 63)
          (= (distance location9 location8) 63)
          (= (distance location8 location10) 56)
          (= (distance location10 location8) 56)
          (= (distance location8 location11) 61)
          (= (distance location11 location8) 61)
          (= (distance location8 location12) 60)
          (= (distance location12 location8) 60)
          (= (distance location8 location13) 31)
          (= (distance location13 location8) 31)
          (= (distance location8 location14) 65)
          (= (distance location14 location8) 65)
          (= (distance location8 location15) 57)
          (= (distance location15 location8) 57)
          (= (distance location8 location8) 0)
          (= (distance location9 location10) 51)
          (= (distance location10 location9) 51)
          (= (distance location9 location11) 9)
          (= (distance location11 location9) 9)
          (= (distance location9 location12) 45)
          (= (distance location12 location9) 45)
          (= (distance location9 location13) 69)
          (= (distance location13 location9) 69)
          (= (distance location9 location14) 23)
          (= (distance location14 location9) 23)
          (= (distance location9 location15) 38)
          (= (distance location15 location9) 38)
          (= (distance location9 location9) 0)
          (= (distance location10 location11) 42)
          (= (distance location11 location10) 42)
          (= (distance location10 location12) 34)
          (= (distance location12 location10) 34)
          (= (distance location10 location13) 15)
          (= (distance location13 location10) 15)
          (= (distance location10 location14) 63)
          (= (distance location14 location10) 63)
          (= (distance location10 location15) 28)
          (= (distance location15 location10) 28)
          (= (distance location10 location10) 0)
          (= (distance location11 location12) 51)
          (= (distance location12 location11) 51)
          (= (distance location11 location13) 14)
          (= (distance location13 location11) 14)
          (= (distance location11 location14) 53)
          (= (distance location14 location11) 53)
          (= (distance location11 location15) 20)
          (= (distance location15 location11) 20)
          (= (distance location11 location11) 0)
          (= (distance location12 location13) 41)
          (= (distance location13 location12) 41)
          (= (distance location12 location14) 49)
          (= (distance location14 location12) 49)
          (= (distance location12 location15) 33)
          (= (distance location15 location12) 33)
          (= (distance location12 location12) 0)
          (= (distance location13 location14) 34)
          (= (distance location14 location13) 34)
          (= (distance location13 location15) 24)
          (= (distance location15 location13) 24)
          (= (distance location13 location13) 0)
          (= (distance location14 location15) 10)
          (= (distance location15 location14) 10)
          (= (distance location14 location14) 0)
          (= (distance location15 location15) 0)
          (typev truck0 regularv)
          (typevp truck0 truck)
          (at-vehicle truck0 location14)
          (= (gas-left truck0) 542)
          (= (gpm truck0) 1)
          (= (length-v truck0) 13)
          (= (height-v truck0) 9)
          (= (width-v truck0) 8)
          (= (weight-cap-v truck0) 80)
          (= (volume-cap-v truck0) 655)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 27)
          (availablev truck0)
          (typev truck1 regularv)
          (typevp truck1 truck)
          (at-vehicle truck1 location9)
          (= (gas-left truck1) 199)
          (= (gpm truck1) 2)
          (= (length-v truck1) 17)
          (= (height-v truck1) 8)
          (= (width-v truck1) 5)
          (= (weight-cap-v truck1) 184)
          (= (volume-cap-v truck1) 475)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 32)
          (availablev truck1)
          (typev truck2 regularv)
          (typevp truck2 truck)
          (at-vehicle truck2 location9)
          (= (gas-left truck2) 291)
          (= (gpm truck2) 1)
          (= (length-v truck2) 12)
          (= (height-v truck2) 1)
          (= (width-v truck2) 3)
          (= (weight-cap-v truck2) 245)
          (= (volume-cap-v truck2) 36)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 37)
          (availablev truck2)
          (typev truck3 regularv)
          (typevp truck3 truck)
          (at-vehicle truck3 location8)
          (= (gas-left truck3) 277)
          (= (gpm truck3) 3)
          (= (length-v truck3) 12)
          (= (height-v truck3) 1)
          (= (width-v truck3) 2)
          (= (weight-cap-v truck3) 321)
          (= (volume-cap-v truck3) 24)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 25)
          (availablev truck3)
          (typev truck4 regularv)
          (typevp truck4 truck)
          (at-vehicle truck4 location7)
          (= (gas-left truck4) 122)
          (= (gpm truck4) 3)
          (= (length-v truck4) 12)
          (= (height-v truck4) 7)
          (= (width-v truck4) 3)
          (= (weight-cap-v truck4) 207)
          (= (volume-cap-v truck4) 215)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 27)
          (availablev truck4)
          (typev truck5 regularv)
          (typevp truck5 truck)
          (at-vehicle truck5 location15)
          (= (gas-left truck5) 409)
          (= (gpm truck5) 2)
          (= (length-v truck5) 12)
          (= (height-v truck5) 10)
          (= (width-v truck5) 3)
          (= (weight-cap-v truck5) 160)
          (= (volume-cap-v truck5) 251)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 22)
          (availablev truck5)
          (typev truck6 regularv)
          (typevp truck6 truck)
          (at-vehicle truck6 location0)
          (= (gas-left truck6) 355)
          (= (gpm truck6) 1)
          (= (length-v truck6) 11)
          (= (height-v truck6) 6)
          (= (width-v truck6) 4)
          (= (weight-cap-v truck6) 161)
          (= (volume-cap-v truck6) 184)
          (= (weight-load-v truck6) 0)
          (= (volume-load-v truck6) 0)
          (= (weight-v truck6) 33)
          (availablev truck6)
          (typev truck7 flatbed)
          (typevp truck7 truck)
          (at-vehicle truck7 location14)
          (= (gas-left truck7) 397)
          (= (gpm truck7) 3)
          (= (length-v truck7) 5)
          (= (height-v truck7) 5)
          (= (width-v truck7) 9)
          (= (weight-cap-v truck7) 205)
          (= (volume-cap-v truck7) 225)
          (= (weight-load-v truck7) 0)
          (= (volume-load-v truck7) 0)
          (= (weight-v truck7) 30)
          (availablev truck7)
          (typev truck8 regularv)
          (typevp truck8 truck)
          (at-vehicle truck8 location15)
          (= (gas-left truck8) 440)
          (= (gpm truck8) 1)
          (= (length-v truck8) 18)
          (= (height-v truck8) 1)
          (= (width-v truck8) 5)
          (= (weight-cap-v truck8) 78)
          (= (volume-cap-v truck8) 90)
          (= (weight-load-v truck8) 0)
          (= (volume-load-v truck8) 0)
          (= (weight-v truck8) 13)
          (availablev truck8)
          (typev truck9 hopper)
          (typevp truck9 truck)
          (at-vehicle truck9 location9)
          (= (gas-left truck9) 163)
          (= (gpm truck9) 2)
          (= (length-v truck9) 10)
          (= (height-v truck9) 9)
          (= (width-v truck9) 3)
          (= (weight-cap-v truck9) 380)
          (= (volume-cap-v truck9) 270)
          (= (weight-load-v truck9) 0)
          (= (volume-load-v truck9) 0)
          (= (weight-v truck9) 17)
          (availablev truck9)
          (typev truck10 regularv)
          (typevp truck10 truck)
          (at-vehicle truck10 location14)
          (= (gas-left truck10) 224)
          (= (gpm truck10) 1)
          (= (length-v truck10) 13)
          (= (height-v truck10) 3)
          (= (width-v truck10) 2)
          (= (weight-cap-v truck10) 293)
          (= (volume-cap-v truck10) 78)
          (= (weight-load-v truck10) 0)
          (= (volume-load-v truck10) 0)
          (= (weight-v truck10) 32)
          (availablev truck10)
          (typev truck11 regularv)
          (typevp truck11 truck)
          (at-vehicle truck11 location6)
          (= (gas-left truck11) 451)
          (= (gpm truck11) 2)
          (= (length-v truck11) 7)
          (= (height-v truck11) 9)
          (= (width-v truck11) 1)
          (= (weight-cap-v truck11) 352)
          (= (volume-cap-v truck11) 63)
          (= (weight-load-v truck11) 0)
          (= (volume-load-v truck11) 0)
          (= (weight-v truck11) 38)
          (availablev truck11)
          (typev truck12 regularv)
          (typevp truck12 truck)
          (at-vehicle truck12 location11)
          (= (gas-left truck12) 282)
          (= (gpm truck12) 3)
          (= (length-v truck12) 17)
          (= (height-v truck12) 8)
          (= (width-v truck12) 6)
          (= (weight-cap-v truck12) 345)
          (= (volume-cap-v truck12) 571)
          (= (weight-load-v truck12) 0)
          (= (volume-load-v truck12) 0)
          (= (weight-v truck12) 37)
          (availablev truck12)
          (typev truck13 regularv)
          (typevp truck13 truck)
          (at-vehicle truck13 location14)
          (= (gas-left truck13) 164)
          (= (gpm truck13) 2)
          (= (length-v truck13) 16)
          (= (height-v truck13) 6)
          (= (width-v truck13) 5)
          (= (weight-cap-v truck13) 229)
          (= (volume-cap-v truck13) 336)
          (= (weight-load-v truck13) 0)
          (= (volume-load-v truck13) 0)
          (= (weight-v truck13) 25)
          (availablev truck13)
          (typev truck14 regularv)
          (typevp truck14 truck)
          (at-vehicle truck14 location7)
          (= (gas-left truck14) 293)
          (= (gpm truck14) 1)
          (= (length-v truck14) 13)
          (= (height-v truck14) 10)
          (= (width-v truck14) 5)
          (= (weight-cap-v truck14) 109)
          (= (volume-cap-v truck14) 455)
          (= (weight-load-v truck14) 0)
          (= (volume-load-v truck14) 0)
          (= (weight-v truck14) 23)
          (availablev truck14)
          (typev truck15 regularv)
          (typevp truck15 truck)
          (at-vehicle truck15 location14)
          (= (gas-left truck15) 298)
          (= (gpm truck15) 3)
          (= (length-v truck15) 9)
          (= (height-v truck15) 2)
          (= (width-v truck15) 8)
          (= (weight-cap-v truck15) 489)
          (= (volume-cap-v truck15) 144)
          (= (weight-load-v truck15) 0)
          (= (volume-load-v truck15) 0)
          (= (weight-v truck15) 29)
          (availablev truck15)
          (typev train0 hopper)
          (typevp train0 train)
          (at-vehicle train0 location1)
          (= (gas-left train0) 270)
          (= (gpm train0) 1)
          (= (length-v train0) 6)
          (= (height-v train0) 2)
          (= (width-v train0) 4)
          (= (weight-cap-v train0) 135)
          (= (volume-cap-v train0) 48)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 22)
          (availablev train0)
          (typev train1 regularv)
          (typevp train1 train)
          (at-vehicle train1 location6)
          (= (gas-left train1) 157)
          (= (gpm train1) 1)
          (= (length-v train1) 5)
          (= (height-v train1) 5)
          (= (width-v train1) 4)
          (= (weight-cap-v train1) 34)
          (= (volume-cap-v train1) 70)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 17)
          (availablev train1)
          (typev train2 regularv)
          (typevp train2 train)
          (at-vehicle train2 location2)
          (= (gas-left train2) 473)
          (= (gpm train2) 3)
          (= (length-v train2) 19)
          (= (height-v train2) 9)
          (= (width-v train2) 6)
          (= (weight-cap-v train2) 389)
          (= (volume-cap-v train2) 718)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 12)
          (availablev train2)
          (typev train3 tanker)
          (typevp train3 train)
          (at-vehicle train3 location1)
          (= (gas-left train3) 497)
          (= (gpm train3) 2)
          (= (length-v train3) 10)
          (= (height-v train3) 8)
          (= (width-v train3) 10)
          (= (weight-cap-v train3) 440)
          (= (volume-cap-v train3) 560)
          (= (weight-load-v train3) 0)
          (= (volume-load-v train3) 0)
          (= (weight-v train3) 16)
          (typev train4 regularv)
          (typevp train4 train)
          (at-vehicle train4 location2)
          (= (gas-left train4) 92)
          (= (gpm train4) 1)
          (= (length-v train4) 8)
          (= (height-v train4) 9)
          (= (width-v train4) 7)
          (= (weight-cap-v train4) 152)
          (= (volume-cap-v train4) 352)
          (= (weight-load-v train4) 0)
          (= (volume-load-v train4) 0)
          (= (weight-v train4) 14)
          (availablev train4)
          (typev train5 regularv)
          (typevp train5 train)
          (at-vehicle train5 location6)
          (= (gas-left train5) 528)
          (= (gpm train5) 1)
          (= (length-v train5) 9)
          (= (height-v train5) 7)
          (= (width-v train5) 10)
          (= (weight-cap-v train5) 43)
          (= (volume-cap-v train5) 441)
          (= (weight-load-v train5) 0)
          (= (volume-load-v train5) 0)
          (= (weight-v train5) 13)
          (availablev train5)
          (typev train6 regularv)
          (typevp train6 train)
          (at-vehicle train6 location8)
          (= (gas-left train6) 351)
          (= (gpm train6) 3)
          (= (length-v train6) 10)
          (= (height-v train6) 1)
          (= (width-v train6) 3)
          (= (weight-cap-v train6) 218)
          (= (volume-cap-v train6) 30)
          (= (weight-load-v train6) 0)
          (= (volume-load-v train6) 0)
          (= (weight-v train6) 38)
          (availablev train6)
          (typev train7 regularv)
          (typevp train7 train)
          (at-vehicle train7 location8)
          (= (gas-left train7) 326)
          (= (gpm train7) 2)
          (= (length-v train7) 16)
          (= (height-v train7) 3)
          (= (width-v train7) 9)
          (= (weight-cap-v train7) 308)
          (= (volume-cap-v train7) 368)
          (= (weight-load-v train7) 0)
          (= (volume-load-v train7) 0)
          (= (weight-v train7) 14)
          (availablev train7)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location14)
          (= (gas-left airplane0) 290)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 17)
          (= (height-v airplane0) 8)
          (= (width-v airplane0) 6)
          (= (weight-cap-v airplane0) 251)
          (= (volume-cap-v airplane0) 571)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 17)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location14)
          (= (gas-left airplane1) 522)
          (= (gpm airplane1) 3)
          (= (length-v airplane1) 19)
          (= (height-v airplane1) 6)
          (= (width-v airplane1) 3)
          (= (weight-cap-v airplane1) 366)
          (= (volume-cap-v airplane1) 342)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 27)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location9)
          (= (gas-left airplane2) 184)
          (= (gpm airplane2) 2)
          (= (length-v airplane2) 19)
          (= (height-v airplane2) 6)
          (= (width-v airplane2) 3)
          (= (weight-cap-v airplane2) 188)
          (= (volume-cap-v airplane2) 326)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 27)
          (typev airplane3 air)
          (typevp airplane3 airplane)
          (at-vehicle airplane3 location14)
          (= (gas-left airplane3) 117)
          (= (gpm airplane3) 1)
          (= (length-v airplane3) 17)
          (= (height-v airplane3) 5)
          (= (width-v airplane3) 10)
          (= (weight-cap-v airplane3) 525)
          (= (volume-cap-v airplane3) 594)
          (= (weight-load-v airplane3) 0)
          (= (volume-load-v airplane3) 0)
          (= (weight-v airplane3) 23)
          (typev airplane4 air)
          (typevp airplane4 airplane)
          (at-vehicle airplane4 location3)
          (= (gas-left airplane4) 340)
          (= (gpm airplane4) 2)
          (= (length-v airplane4) 6)
          (= (height-v airplane4) 2)
          (= (width-v airplane4) 2)
          (= (weight-cap-v airplane4) 346)
          (= (volume-cap-v airplane4) 24)
          (= (weight-load-v airplane4) 0)
          (= (volume-load-v airplane4) 0)
          (= (weight-v airplane4) 35)
          (availablev airplane4)
          (typev airplane5 air)
          (typevp airplane5 airplane)
          (at-vehicle airplane5 location3)
          (= (gas-left airplane5) 479)
          (= (gpm airplane5) 2)
          (= (length-v airplane5) 16)
          (= (height-v airplane5) 9)
          (= (width-v airplane5) 4)
          (= (weight-cap-v airplane5) 372)
          (= (volume-cap-v airplane5) 403)
          (= (weight-load-v airplane5) 0)
          (= (volume-load-v airplane5) 0)
          (= (weight-v airplane5) 36)
          (availablev airplane5)
          (typev airplane6 air)
          (typevp airplane6 airplane)
          (at-vehicle airplane6 location14)
          (= (gas-left airplane6) 518)
          (= (gpm airplane6) 2)
          (= (length-v airplane6) 17)
          (= (height-v airplane6) 10)
          (= (width-v airplane6) 4)
          (= (weight-cap-v airplane6) 101)
          (= (volume-cap-v airplane6) 475)
          (= (weight-load-v airplane6) 0)
          (= (volume-load-v airplane6) 0)
          (= (weight-v airplane6) 19)
          (availablev airplane6)
          (typev airplane7 air)
          (typevp airplane7 airplane)
          (at-vehicle airplane7 location13)
          (= (gas-left airplane7) 97)
          (= (gpm airplane7) 1)
          (= (length-v airplane7) 14)
          (= (height-v airplane7) 3)
          (= (width-v airplane7) 4)
          (= (weight-cap-v airplane7) 450)
          (= (volume-cap-v airplane7) 168)
          (= (weight-load-v airplane7) 0)
          (= (volume-load-v airplane7) 0)
          (= (weight-v airplane7) 27)
          (availablev airplane7)
          (at-equipment plane_ramp0 location3)
          (at-equipment plane_ramp1 location5)
          (at-equipment plane_ramp2 location9)
          (at-equipment plane_ramp3 location12)
          (at-equipment plane_ramp4 location13)
          (at-equipment plane_ramp5 location14)
          (typep package0 mail)
          (at-packagel package0 location1)
          (= (volume-p package0) 5)
          (= (weight-p package0) 7)
          (typep package1 mail)
          (at-packagel package1 location5)
          (= (volume-p package1) 22)
          (= (weight-p package1) 7)
          (typep package2 mail)
          (at-packagel package2 location8)
          (= (volume-p package2) 7)
          (= (weight-p package2) 14)
          (typep package3 mail)
          (at-packagel package3 location5)
          (= (volume-p package3) 14)
          (= (weight-p package3) 16)
          (typep package4 mail)
          (at-packagel package4 location13)
          (= (volume-p package4) 19)
          (= (weight-p package4) 8)
          (typep package5 mail)
          (at-packagel package5 location6)
          (= (volume-p package5) 12)
          (= (weight-p package5) 6)
          (typep package6 mail)
          (at-packagel package6 location11)
          (= (volume-p package6) 21)
          (= (weight-p package6) 23)
          (typep package7 mail)
          (at-packagel package7 location12)
          (= (volume-p package7) 21)
          (= (weight-p package7) 21)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 25)
          (= (weight-cap-r road_route0) 315)
          (availabler road_route0)
          (connect-city road_route1 road-route city0 city2)
          (= (height-cap-r road_route1) 9)
          (= (weight-cap-r road_route1) 230)
          (availabler road_route1)
          (connect-city road_route2 road-route city0 city3)
          (= (height-cap-r road_route2) 31)
          (= (weight-cap-r road_route2) 63)
          (availabler road_route2)
          (connect-city road_route3 road-route city0 city4)
          (= (height-cap-r road_route3) 11)
          (= (weight-cap-r road_route3) 60)
          (connect-city road_route4 road-route city0 city5)
          (= (height-cap-r road_route4) 26)
          (= (weight-cap-r road_route4) 162)
          (availabler road_route4)
          (connect-city road_route5 road-route city1 city0)
          (= (height-cap-r road_route5) 7)
          (= (weight-cap-r road_route5) 278)
          (availabler road_route5)
          (connect-city road_route6 road-route city1 city2)
          (= (height-cap-r road_route6) 15)
          (= (weight-cap-r road_route6) 448)
          (availabler road_route6)
          (connect-city road_route7 road-route city1 city3)
          (= (height-cap-r road_route7) 11)
          (= (weight-cap-r road_route7) 385)
          (availabler road_route7)
          (connect-city road_route8 road-route city1 city4)
          (= (height-cap-r road_route8) 9)
          (= (weight-cap-r road_route8) 491)
          (availabler road_route8)
          (connect-city road_route9 road-route city1 city5)
          (= (height-cap-r road_route9) 33)
          (= (weight-cap-r road_route9) 549)
          (availabler road_route9)
          (connect-city road_route10 road-route city2 city0)
          (= (height-cap-r road_route10) 9)
          (= (weight-cap-r road_route10) 434)
          (availabler road_route10)
          (connect-city road_route11 road-route city2 city1)
          (= (height-cap-r road_route11) 24)
          (= (weight-cap-r road_route11) 309)
          (availabler road_route11)
          (connect-city road_route12 road-route city2 city3)
          (= (height-cap-r road_route12) 30)
          (= (weight-cap-r road_route12) 461)
          (availabler road_route12)
          (connect-city road_route13 road-route city2 city4)
          (= (height-cap-r road_route13) 33)
          (= (weight-cap-r road_route13) 81)
          (availabler road_route13)
          (connect-city road_route14 road-route city3 city0)
          (= (height-cap-r road_route14) 32)
          (= (weight-cap-r road_route14) 96)
          (availabler road_route14)
          (connect-city road_route15 road-route city3 city1)
          (= (height-cap-r road_route15) 10)
          (= (weight-cap-r road_route15) 270)
          (availabler road_route15)
          (connect-city road_route16 road-route city3 city2)
          (= (height-cap-r road_route16) 30)
          (= (weight-cap-r road_route16) 300)
          (availabler road_route16)
          (connect-city road_route17 road-route city3 city4)
          (= (height-cap-r road_route17) 26)
          (= (weight-cap-r road_route17) 514)
          (connect-city road_route18 road-route city4 city0)
          (= (height-cap-r road_route18) 23)
          (= (weight-cap-r road_route18) 539)
          (availabler road_route18)
          (connect-city road_route19 road-route city4 city1)
          (= (height-cap-r road_route19) 15)
          (= (weight-cap-r road_route19) 526)
          (availabler road_route19)
          (connect-city road_route20 road-route city4 city2)
          (= (height-cap-r road_route20) 8)
          (= (weight-cap-r road_route20) 282)
          (availabler road_route20)
          (connect-city road_route21 road-route city4 city3)
          (= (height-cap-r road_route21) 23)
          (= (weight-cap-r road_route21) 160)
          (availabler road_route21)
          (connect-city road_route22 road-route city4 city5)
          (= (height-cap-r road_route22) 28)
          (= (weight-cap-r road_route22) 328)
          (availabler road_route22)
          (connect-city road_route23 road-route city5 city0)
          (= (height-cap-r road_route23) 15)
          (= (weight-cap-r road_route23) 89)
          (availabler road_route23)
          (connect-city road_route24 road-route city5 city1)
          (= (height-cap-r road_route24) 15)
          (= (weight-cap-r road_route24) 86)
          (availabler road_route24)
          (connect-city road_route25 road-route city5 city2)
          (= (height-cap-r road_route25) 13)
          (= (weight-cap-r road_route25) 268)
          (availabler road_route25)
          (connect-city road_route26 road-route city5 city3)
          (= (height-cap-r road_route26) 12)
          (= (weight-cap-r road_route26) 308)
          (connect-city road_route27 road-route city5 city4)
          (= (height-cap-r road_route27) 5)
          (= (weight-cap-r road_route27) 257)
          (availabler road_route27)
          (connect-loc rail_route0 rail-route location1 location2)
          (= (height-cap-r rail_route0) 17)
          (= (weight-cap-r rail_route0) 73)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location1 location4)
          (= (height-cap-r rail_route1) 15)
          (= (weight-cap-r rail_route1) 303)
          (serves location4 region3)
          (availabler rail_route1)
          (connect-loc rail_route2 rail-route location1 location6)
          (= (height-cap-r rail_route2) 31)
          (= (weight-cap-r rail_route2) 539)
          (serves location6 region3)
          (availabler rail_route2)
          (connect-loc rail_route3 rail-route location1 location7)
          (= (height-cap-r rail_route3) 27)
          (= (weight-cap-r rail_route3) 475)
          (serves location7 region3)
          (availabler rail_route3)
          (connect-loc rail_route4 rail-route location1 location8)
          (= (height-cap-r rail_route4) 26)
          (= (weight-cap-r rail_route4) 276)
          (serves location8 region3)
          (availabler rail_route4)
          (connect-loc rail_route5 rail-route location2 location1)
          (= (height-cap-r rail_route5) 8)
          (= (weight-cap-r rail_route5) 162)
          (availabler rail_route5)
          (connect-loc rail_route6 rail-route location2 location4)
          (= (height-cap-r rail_route6) 13)
          (= (weight-cap-r rail_route6) 65)
          (serves location4 region0)
          (availabler rail_route6)
          (connect-loc rail_route7 rail-route location2 location6)
          (= (height-cap-r rail_route7) 21)
          (= (weight-cap-r rail_route7) 431)
          (serves location6 region0)
          (availabler rail_route7)
          (connect-loc rail_route8 rail-route location2 location7)
          (= (height-cap-r rail_route8) 10)
          (= (weight-cap-r rail_route8) 208)
          (serves location7 region0)
          (availabler rail_route8)
          (connect-loc rail_route9 rail-route location2 location8)
          (= (height-cap-r rail_route9) 6)
          (= (weight-cap-r rail_route9) 332)
          (serves location8 region0)
          (availabler rail_route9)
          (connect-loc rail_route10 rail-route location4 location1)
          (= (height-cap-r rail_route10) 16)
          (= (weight-cap-r rail_route10) 506)
          (connect-loc rail_route11 rail-route location4 location2)
          (= (height-cap-r rail_route11) 32)
          (= (weight-cap-r rail_route11) 369)
          (connect-loc rail_route12 rail-route location4 location6)
          (= (height-cap-r rail_route12) 7)
          (= (weight-cap-r rail_route12) 184)
          (availabler rail_route12)
          (connect-loc rail_route13 rail-route location4 location7)
          (= (height-cap-r rail_route13) 29)
          (= (weight-cap-r rail_route13) 480)
          (serves location4 region1)
          (availabler rail_route13)
          (connect-loc rail_route14 rail-route location4 location8)
          (= (height-cap-r rail_route14) 18)
          (= (weight-cap-r rail_route14) 173)
          (connect-loc rail_route15 rail-route location6 location1)
          (= (height-cap-r rail_route15) 22)
          (= (weight-cap-r rail_route15) 505)
          (availabler rail_route15)
          (connect-loc rail_route16 rail-route location6 location2)
          (= (height-cap-r rail_route16) 26)
          (= (weight-cap-r rail_route16) 285)
          (availabler rail_route16)
          (connect-loc rail_route17 rail-route location6 location4)
          (= (height-cap-r rail_route17) 30)
          (= (weight-cap-r rail_route17) 235)
          (availabler rail_route17)
          (connect-loc rail_route18 rail-route location6 location7)
          (= (height-cap-r rail_route18) 17)
          (= (weight-cap-r rail_route18) 440)
          (serves location6 region1)
          (availabler rail_route18)
          (connect-loc rail_route19 rail-route location6 location8)
          (= (height-cap-r rail_route19) 27)
          (= (weight-cap-r rail_route19) 255)
          (availabler rail_route19)
          (connect-loc rail_route20 rail-route location7 location1)
          (= (height-cap-r rail_route20) 15)
          (= (weight-cap-r rail_route20) 216)
          (connect-loc rail_route21 rail-route location7 location2)
          (= (height-cap-r rail_route21) 28)
          (= (weight-cap-r rail_route21) 436)
          (availabler rail_route21)
          (connect-loc rail_route22 rail-route location7 location4)
          (= (height-cap-r rail_route22) 30)
          (= (weight-cap-r rail_route22) 148)
          (connect-loc rail_route23 rail-route location7 location6)
          (= (height-cap-r rail_route23) 22)
          (= (weight-cap-r rail_route23) 548)
          (availabler rail_route23)
          (connect-loc rail_route24 rail-route location7 location8)
          (= (height-cap-r rail_route24) 11)
          (= (weight-cap-r rail_route24) 299)
          (serves location8 region1)
          (availabler rail_route24)
          (connect-loc rail_route25 rail-route location8 location1)
          (= (height-cap-r rail_route25) 30)
          (= (weight-cap-r rail_route25) 75)
          (availabler rail_route25)
          (connect-loc rail_route26 rail-route location8 location4)
          (= (height-cap-r rail_route26) 17)
          (= (weight-cap-r rail_route26) 485)
          (availabler rail_route26)
          (connect-loc rail_route27 rail-route location8 location6)
          (= (height-cap-r rail_route27) 30)
          (= (weight-cap-r rail_route27) 429)
          (availabler rail_route27)
          (connect-loc rail_route28 rail-route location8 location7)
          (= (height-cap-r rail_route28) 24)
          (= (weight-cap-r rail_route28) 508)
          (availabler rail_route28)
          (connect-loc air_route0 air-route location3 location5)
          (= (height-cap-r air_route0) 14)
          (= (weight-cap-r air_route0) 466)
          (serves location3 region0)
          (serves location5 region0)
          (connect-loc air_route1 air-route location3 location9)
          (= (height-cap-r air_route1) 5)
          (= (weight-cap-r air_route1) 67)
          (serves location3 region3)
          (serves location9 region0)
          (availabler air_route1)
          (connect-loc air_route2 air-route location3 location12)
          (= (height-cap-r air_route2) 32)
          (= (weight-cap-r air_route2) 208)
          (serves location3 region1)
          (availabler air_route2)
          (connect-loc air_route3 air-route location3 location13)
          (= (height-cap-r air_route3) 20)
          (= (weight-cap-r air_route3) 232)
          (serves location13 region0)
          (availabler air_route3)
          (connect-loc air_route4 air-route location3 location14)
          (= (height-cap-r air_route4) 5)
          (= (weight-cap-r air_route4) 531)
          (serves location14 region0)
          (availabler air_route4)
          (connect-loc air_route5 air-route location5 location3)
          (= (height-cap-r air_route5) 34)
          (= (weight-cap-r air_route5) 430)
          (availabler air_route5)
          (connect-loc air_route6 air-route location5 location9)
          (= (height-cap-r air_route6) 6)
          (= (weight-cap-r air_route6) 145)
          (serves location5 region3)
          (availabler air_route6)
          (connect-loc air_route7 air-route location5 location12)
          (= (height-cap-r air_route7) 30)
          (= (weight-cap-r air_route7) 303)
          (serves location5 region1)
          (availabler air_route7)
          (connect-loc air_route8 air-route location5 location13)
          (= (height-cap-r air_route8) 5)
          (= (weight-cap-r air_route8) 69)
          (availabler air_route8)
          (connect-loc air_route9 air-route location5 location14)
          (= (height-cap-r air_route9) 32)
          (= (weight-cap-r air_route9) 419)
          (availabler air_route9)
          (connect-loc air_route10 air-route location9 location3)
          (= (height-cap-r air_route10) 11)
          (= (weight-cap-r air_route10) 442)
          (availabler air_route10)
          (connect-loc air_route11 air-route location9 location5)
          (= (height-cap-r air_route11) 16)
          (= (weight-cap-r air_route11) 309)
          (availabler air_route11)
          (connect-loc air_route12 air-route location9 location12)
          (= (height-cap-r air_route12) 13)
          (= (weight-cap-r air_route12) 195)
          (serves location9 region1)
          (availabler air_route12)
          (connect-loc air_route13 air-route location9 location13)
          (= (height-cap-r air_route13) 9)
          (= (weight-cap-r air_route13) 453)
          (serves location13 region3)
          (availabler air_route13)
          (connect-loc air_route14 air-route location9 location14)
          (= (height-cap-r air_route14) 18)
          (= (weight-cap-r air_route14) 284)
          (serves location9 region3)
          (serves location14 region3)
          (availabler air_route14)
          (connect-loc air_route15 air-route location12 location3)
          (= (height-cap-r air_route15) 33)
          (= (weight-cap-r air_route15) 447)
          (availabler air_route15)
          (connect-loc air_route16 air-route location12 location5)
          (= (height-cap-r air_route16) 8)
          (= (weight-cap-r air_route16) 255)
          (availabler air_route16)
          (connect-loc air_route17 air-route location12 location9)
          (= (height-cap-r air_route17) 21)
          (= (weight-cap-r air_route17) 210)
          (availabler air_route17)
          (connect-loc air_route18 air-route location12 location13)
          (= (height-cap-r air_route18) 5)
          (= (weight-cap-r air_route18) 94)
          (serves location13 region1)
          (availabler air_route18)
          (connect-loc air_route19 air-route location12 location14)
          (= (height-cap-r air_route19) 20)
          (= (weight-cap-r air_route19) 228)
          (serves location14 region1)
          (connect-loc air_route20 air-route location13 location3)
          (= (height-cap-r air_route20) 10)
          (= (weight-cap-r air_route20) 381)
          (availabler air_route20)
          (connect-loc air_route21 air-route location13 location5)
          (= (height-cap-r air_route21) 16)
          (= (weight-cap-r air_route21) 425)
          (availabler air_route21)
          (connect-loc air_route22 air-route location13 location9)
          (= (height-cap-r air_route22) 6)
          (= (weight-cap-r air_route22) 449)
          (availabler air_route22)
          (connect-loc air_route23 air-route location13 location12)
          (= (height-cap-r air_route23) 14)
          (= (weight-cap-r air_route23) 419)
          (availabler air_route23)
          (connect-loc air_route24 air-route location13 location14)
          (= (height-cap-r air_route24) 11)
          (= (weight-cap-r air_route24) 329)
          (availabler air_route24)
          (connect-loc air_route25 air-route location14 location3)
          (= (height-cap-r air_route25) 19)
          (= (weight-cap-r air_route25) 518)
          (availabler air_route25)
          (connect-loc air_route26 air-route location14 location5)
          (= (height-cap-r air_route26) 19)
          (= (weight-cap-r air_route26) 407)
          (availabler air_route26)
          (connect-loc air_route27 air-route location14 location9)
          (= (height-cap-r air_route27) 5)
          (= (weight-cap-r air_route27) 434)
          (availabler air_route27)
          (connect-loc air_route28 air-route location14 location12)
          (= (height-cap-r air_route28) 10)
          (= (weight-cap-r air_route28) 353)
          (availabler air_route28)
          (connect-loc air_route29 air-route location14 location13)
          (= (height-cap-r air_route29) 28)
          (= (weight-cap-r air_route29) 334)
          (availabler air_route29)
          (= (volume-load-l location0) 0)
          (= (volume-load-l location1) 5)
          (= (volume-load-l location2) 0)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 0)
          (= (volume-load-l location5) 36)
          (= (volume-load-l location6) 12)
          (= (volume-load-l location7) 0)
          (= (volume-load-l location8) 7)
          (= (volume-load-l location9) 0)
          (= (volume-load-l location10) 0)
          (= (volume-load-l location11) 21)
          (= (volume-load-l location12) 21)
          (= (volume-load-l location13) 19)
          (= (volume-load-l location14) 0)
          (= (volume-load-l location15) 0)
   )

   (:goal (and (delivered package0 location7)
               (delivered package1 location0)
               (delivered package2 location11)
               (delivered package3 location11)
               (delivered package4 location13)
               (delivered package5 location10)
               (delivered package6 location13)
               (delivered package7 location10)
               (clear)))

)