(define (problem problem0)
   (:domain UM-Translog-2)
   (:requirements :typing :adl :equality :negative-preconditions :existential-preconditions :universal-preconditions :fluents)
   (:objects region0 region1 - region
          city0 city1 city2 city3 - city
          location0 location1 location2 location3 location4 location5 location6 location7 location8 location9 - location
          truck0 truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 train0 train1 train2 train3 train4 airplane0 airplane1 airplane2 airplane3 airplane4 - vehicle
          crane0 crane1 crane2 crane3 crane4 crane5 crane6 crane7 crane8 crane9 - crane
          plane_ramp0 plane_ramp1 plane_ramp2 - plane-ramp
          package0 package1 package2 package3 package4 - package
          road_route0 road_route1 road_route2 road_route3 road_route4 road_route5 road_route6 road_route7 road_route8 road_route9 road_route10 - route
          rail_route0 rail_route1 - route
          air_route0 air_route1 air_route2 air_route3 air_route4 air_route5 - route
   )
   (:init (pv-compatible regularp regularv)
          (pv-compatible bulky flatbed)
          (pv-compatible liquid tanker)
          (pv-compatible cars auto)
          (pv-compatible regularp air)
          (pv-compatible mail air)
          (pv-compatible mail regularv)
          (pv-compatible granular hopper)
          (rv-compatible air-route airplane)
          (rv-compatible rail-route train)
          (rv-compatible road-route truck)

          (in-region city0 region0)
          (= (local-height city0) 21)
          (= (local-weight city0) 491)
          (in-region city1 region1)
          (= (local-height city1) 33)
          (= (local-weight city1) 465)
          (in-region city2 region1)
          (= (local-height city2) 30)
          (= (local-weight city2) 120)
          (in-region city3 region1)
          (= (local-height city3) 28)
          (= (local-weight city3) 518)
          (in-city location0 city2)
          (= (height-cap-l location0) 22)
          (= (length-cap-l location0) 11)
          (= (width-cap-l location0) 13)
          (= (volume-cap-l location0) 393)
          (in-city location1 city0)
          (= (height-cap-l location1) 20)
          (= (length-cap-l location1) 38)
          (= (width-cap-l location1) 8)
          (= (volume-cap-l location1) 194)
          (tcenter location1)
          (typel location1 airport)
          (availablel location1)
          (hub location1)
          (in-city location2 city0)
          (= (height-cap-l location2) 11)
          (= (length-cap-l location2) 26)
          (= (width-cap-l location2) 32)
          (= (volume-cap-l location2) 159)
          (tcenter location2)
          (typel location2 train-station)
          (availablel location2)
          (hub location2)
          (in-city location3 city3)
          (= (height-cap-l location3) 13)
          (= (length-cap-l location3) 29)
          (= (width-cap-l location3) 26)
          (= (volume-cap-l location3) 464)
          (tcenter location3)
          (typel location3 airport)
          (availablel location3)
          (in-city location4 city1)
          (= (height-cap-l location4) 13)
          (= (length-cap-l location4) 14)
          (= (width-cap-l location4) 23)
          (= (volume-cap-l location4) 134)
          (in-city location5 city1)
          (= (height-cap-l location5) 8)
          (= (length-cap-l location5) 28)
          (= (width-cap-l location5) 18)
          (= (volume-cap-l location5) 517)
          (in-city location6 city0)
          (= (height-cap-l location6) 31)
          (= (length-cap-l location6) 32)
          (= (width-cap-l location6) 27)
          (= (volume-cap-l location6) 130)
          (tcenter location6)
          (typel location6 train-station)
          (availablel location6)
          (hub location6)
          (in-city location7 city2)
          (= (height-cap-l location7) 32)
          (= (length-cap-l location7) 11)
          (= (width-cap-l location7) 9)
          (= (volume-cap-l location7) 301)
          (in-city location8 city3)
          (= (height-cap-l location8) 20)
          (= (length-cap-l location8) 17)
          (= (width-cap-l location8) 13)
          (= (volume-cap-l location8) 423)
          (in-city location9 city1)
          (= (height-cap-l location9) 24)
          (= (length-cap-l location9) 36)
          (= (width-cap-l location9) 32)
          (= (volume-cap-l location9) 242)
          (tcenter location9)
          (typel location9 airport)
          (availablel location9)
          (= (distance location0 location1) 25)
          (= (distance location1 location0) 25)
          (= (distance location0 location2) 4)
          (= (distance location2 location0) 4)
          (= (distance location0 location3) 43)
          (= (distance location3 location0) 43)
          (= (distance location0 location4) 65)
          (= (distance location4 location0) 65)
          (= (distance location0 location5) 57)
          (= (distance location5 location0) 57)
          (= (distance location0 location6) 44)
          (= (distance location6 location0) 44)
          (= (distance location0 location7) 3)
          (= (distance location7 location0) 3)
          (= (distance location0 location8) 6)
          (= (distance location8 location0) 6)
          (= (distance location0 location9) 14)
          (= (distance location9 location0) 14)
          (= (distance location0 location0) 0)
          (= (distance location1 location2) 39)
          (= (distance location2 location1) 39)
          (= (distance location1 location3) 35)
          (= (distance location3 location1) 35)
          (= (distance location1 location4) 59)
          (= (distance location4 location1) 59)
          (= (distance location1 location5) 29)
          (= (distance location5 location1) 29)
          (= (distance location1 location6) 13)
          (= (distance location6 location1) 13)
          (= (distance location1 location7) 33)
          (= (distance location7 location1) 33)
          (= (distance location1 location8) 42)
          (= (distance location8 location1) 42)
          (= (distance location1 location9) 16)
          (= (distance location9 location1) 16)
          (= (distance location1 location1) 0)
          (= (distance location2 location3) 26)
          (= (distance location3 location2) 26)
          (= (distance location2 location4) 14)
          (= (distance location4 location2) 14)
          (= (distance location2 location5) 57)
          (= (distance location5 location2) 57)
          (= (distance location2 location6) 66)
          (= (distance location6 location2) 66)
          (= (distance location2 location7) 53)
          (= (distance location7 location2) 53)
          (= (distance location2 location8) 62)
          (= (distance location8 location2) 62)
          (= (distance location2 location9) 10)
          (= (distance location9 location2) 10)
          (= (distance location2 location2) 0)
          (= (distance location3 location4) 55)
          (= (distance location4 location3) 55)
          (= (distance location3 location5) 39)
          (= (distance location5 location3) 39)
          (= (distance location3 location6) 53)
          (= (distance location6 location3) 53)
          (= (distance location3 location7) 24)
          (= (distance location7 location3) 24)
          (= (distance location3 location8) 16)
          (= (distance location8 location3) 16)
          (= (distance location3 location9) 62)
          (= (distance location9 location3) 62)
          (= (distance location3 location3) 0)
          (= (distance location4 location5) 44)
          (= (distance location5 location4) 44)
          (= (distance location4 location6) 40)
          (= (distance location6 location4) 40)
          (= (distance location4 location7) 65)
          (= (distance location7 location4) 65)
          (= (distance location4 location8) 44)
          (= (distance location8 location4) 44)
          (= (distance location4 location9) 21)
          (= (distance location9 location4) 21)
          (= (distance location4 location4) 0)
          (= (distance location5 location6) 52)
          (= (distance location6 location5) 52)
          (= (distance location5 location7) 36)
          (= (distance location7 location5) 36)
          (= (distance location5 location8) 4)
          (= (distance location8 location5) 4)
          (= (distance location5 location9) 2)
          (= (distance location9 location5) 2)
          (= (distance location5 location5) 0)
          (= (distance location6 location7) 34)
          (= (distance location7 location6) 34)
          (= (distance location6 location8) 40)
          (= (distance location8 location6) 40)
          (= (distance location6 location9) 20)
          (= (distance location9 location6) 20)
          (= (distance location6 location6) 0)
          (= (distance location7 location8) 55)
          (= (distance location8 location7) 55)
          (= (distance location7 location9) 58)
          (= (distance location9 location7) 58)
          (= (distance location7 location7) 0)
          (= (distance location8 location9) 17)
          (= (distance location9 location8) 17)
          (= (distance location8 location8) 0)
          (= (distance location9 location9) 0)
          (typev truck0 flatbed)
          (typevp truck0 truck)
          (at-vehicle truck0 location3)
          (= (gas-left truck0) 146)
          (= (gpm truck0) 3)
          (= (length-v truck0) 6)
          (= (height-v truck0) 4)
          (= (width-v truck0) 2)
          (= (weight-cap-v truck0) 370)
          (= (volume-cap-v truck0) 48)
          (= (weight-load-v truck0) 0)
          (= (volume-load-v truck0) 0)
          (= (weight-v truck0) 24)
          (availablev truck0)
          (typev truck1 flatbed)
          (typevp truck1 truck)
          (at-vehicle truck1 location9)
          (= (gas-left truck1) 418)
          (= (gpm truck1) 3)
          (= (length-v truck1) 9)
          (= (height-v truck1) 6)
          (= (width-v truck1) 4)
          (= (weight-cap-v truck1) 219)
          (= (volume-cap-v truck1) 151)
          (= (weight-load-v truck1) 0)
          (= (volume-load-v truck1) 0)
          (= (weight-v truck1) 18)
          (availablev truck1)
          (typev truck2 flatbed)
          (typevp truck2 truck)
          (at-vehicle truck2 location1)
          (= (gas-left truck2) 322)
          (= (gpm truck2) 3)
          (= (length-v truck2) 7)
          (= (height-v truck2) 7)
          (= (width-v truck2) 8)
          (= (weight-cap-v truck2) 525)
          (= (volume-cap-v truck2) 392)
          (= (weight-load-v truck2) 0)
          (= (volume-load-v truck2) 0)
          (= (weight-v truck2) 32)
          (availablev truck2)
          (typev truck3 hopper)
          (typevp truck3 truck)
          (at-vehicle truck3 location2)
          (= (gas-left truck3) 259)
          (= (gpm truck3) 1)
          (= (length-v truck3) 18)
          (= (height-v truck3) 10)
          (= (width-v truck3) 8)
          (= (weight-cap-v truck3) 82)
          (= (volume-cap-v truck3) 1008)
          (= (weight-load-v truck3) 0)
          (= (volume-load-v truck3) 0)
          (= (weight-v truck3) 37)
          (availablev truck3)
          (typev truck4 flatbed)
          (typevp truck4 truck)
          (at-vehicle truck4 location8)
          (= (gas-left truck4) 145)
          (= (gpm truck4) 2)
          (= (length-v truck4) 14)
          (= (height-v truck4) 3)
          (= (width-v truck4) 3)
          (= (weight-cap-v truck4) 111)
          (= (volume-cap-v truck4) 126)
          (= (weight-load-v truck4) 0)
          (= (volume-load-v truck4) 0)
          (= (weight-v truck4) 30)
          (availablev truck4)
          (typev truck5 flatbed)
          (typevp truck5 truck)
          (at-vehicle truck5 location8)
          (= (gas-left truck5) 441)
          (= (gpm truck5) 1)
          (= (length-v truck5) 13)
          (= (height-v truck5) 6)
          (= (width-v truck5) 10)
          (= (weight-cap-v truck5) 389)
          (= (volume-cap-v truck5) 546)
          (= (weight-load-v truck5) 0)
          (= (volume-load-v truck5) 0)
          (= (weight-v truck5) 38)
          (availablev truck5)
          (typev truck6 flatbed)
          (typevp truck6 truck)
          (at-vehicle truck6 location1)
          (= (gas-left truck6) 136)
          (= (gpm truck6) 3)
          (= (length-v truck6) 18)
          (= (height-v truck6) 7)
          (= (width-v truck6) 2)
          (= (weight-cap-v truck6) 217)
          (= (volume-cap-v truck6) 176)
          (= (weight-load-v truck6) 0)
          (= (volume-load-v truck6) 0)
          (= (weight-v truck6) 19)
          (availablev truck6)
          (typev truck7 flatbed)
          (typevp truck7 truck)
          (at-vehicle truck7 location1)
          (= (gas-left truck7) 409)
          (= (gpm truck7) 1)
          (= (length-v truck7) 5)
          (= (height-v truck7) 3)
          (= (width-v truck7) 8)
          (= (weight-cap-v truck7) 172)
          (= (volume-cap-v truck7) 84)
          (= (weight-load-v truck7) 0)
          (= (volume-load-v truck7) 0)
          (= (weight-v truck7) 18)
          (availablev truck7)
          (typev truck8 flatbed)
          (typevp truck8 truck)
          (at-vehicle truck8 location1)
          (= (gas-left truck8) 140)
          (= (gpm truck8) 3)
          (= (length-v truck8) 17)
          (= (height-v truck8) 3)
          (= (width-v truck8) 8)
          (= (weight-cap-v truck8) 60)
          (= (volume-cap-v truck8) 285)
          (= (weight-load-v truck8) 0)
          (= (volume-load-v truck8) 0)
          (= (weight-v truck8) 19)
          (availablev truck8)
          (typev truck9 flatbed)
          (typevp truck9 truck)
          (at-vehicle truck9 location2)
          (= (gas-left truck9) 177)
          (= (gpm truck9) 3)
          (= (length-v truck9) 6)
          (= (height-v truck9) 7)
          (= (width-v truck9) 4)
          (= (weight-cap-v truck9) 247)
          (= (volume-cap-v truck9) 168)
          (= (weight-load-v truck9) 0)
          (= (volume-load-v truck9) 0)
          (= (weight-v truck9) 27)
          (availablev truck9)
          (typev train0 flatbed)
          (typevp train0 train)
          (at-vehicle train0 location6)
          (= (gas-left train0) 162)
          (= (gpm train0) 1)
          (= (length-v train0) 14)
          (= (height-v train0) 3)
          (= (width-v train0) 5)
          (= (weight-cap-v train0) 261)
          (= (volume-cap-v train0) 149)
          (= (weight-load-v train0) 0)
          (= (volume-load-v train0) 0)
          (= (weight-v train0) 10)
          (availablev train0)
          (typev train1 flatbed)
          (typevp train1 train)
          (at-vehicle train1 location2)
          (= (gas-left train1) 200)
          (= (gpm train1) 2)
          (= (length-v train1) 19)
          (= (height-v train1) 5)
          (= (width-v train1) 4)
          (= (weight-cap-v train1) 66)
          (= (volume-cap-v train1) 380)
          (= (weight-load-v train1) 0)
          (= (volume-load-v train1) 0)
          (= (weight-v train1) 28)
          (availablev train1)
          (typev train2 flatbed)
          (typevp train2 train)
          (at-vehicle train2 location2)
          (= (gas-left train2) 450)
          (= (gpm train2) 3)
          (= (length-v train2) 11)
          (= (height-v train2) 7)
          (= (width-v train2) 4)
          (= (weight-cap-v train2) 435)
          (= (volume-cap-v train2) 308)
          (= (weight-load-v train2) 0)
          (= (volume-load-v train2) 0)
          (= (weight-v train2) 13)
          (availablev train2)
          (typev train3 flatbed)
          (typevp train3 train)
          (at-vehicle train3 location2)
          (= (gas-left train3) 414)
          (= (gpm train3) 3)
          (= (length-v train3) 16)
          (= (height-v train3) 7)
          (= (width-v train3) 1)
          (= (weight-cap-v train3) 435)
          (= (volume-cap-v train3) 112)
          (= (weight-load-v train3) 0)
          (= (volume-load-v train3) 0)
          (= (weight-v train3) 30)
          (availablev train3)
          (typev train4 flatbed)
          (typevp train4 train)
          (at-vehicle train4 location6)
          (= (gas-left train4) 97)
          (= (gpm train4) 2)
          (= (length-v train4) 19)
          (= (height-v train4) 3)
          (= (width-v train4) 5)
          (= (weight-cap-v train4) 471)
          (= (volume-cap-v train4) 199)
          (= (weight-load-v train4) 0)
          (= (volume-load-v train4) 0)
          (= (weight-v train4) 29)
          (availablev train4)
          (typev airplane0 air)
          (typevp airplane0 airplane)
          (at-vehicle airplane0 location3)
          (= (gas-left airplane0) 482)
          (= (gpm airplane0) 1)
          (= (length-v airplane0) 9)
          (= (height-v airplane0) 7)
          (= (width-v airplane0) 8)
          (= (weight-cap-v airplane0) 162)
          (= (volume-cap-v airplane0) 352)
          (= (weight-load-v airplane0) 0)
          (= (volume-load-v airplane0) 0)
          (= (weight-v airplane0) 36)
          (availablev airplane0)
          (typev airplane1 air)
          (typevp airplane1 airplane)
          (at-vehicle airplane1 location1)
          (= (gas-left airplane1) 420)
          (= (gpm airplane1) 1)
          (= (length-v airplane1) 5)
          (= (height-v airplane1) 10)
          (= (width-v airplane1) 8)
          (= (weight-cap-v airplane1) 506)
          (= (volume-cap-v airplane1) 280)
          (= (weight-load-v airplane1) 0)
          (= (volume-load-v airplane1) 0)
          (= (weight-v airplane1) 39)
          (availablev airplane1)
          (typev airplane2 air)
          (typevp airplane2 airplane)
          (at-vehicle airplane2 location9)
          (= (gas-left airplane2) 398)
          (= (gpm airplane2) 3)
          (= (length-v airplane2) 6)
          (= (height-v airplane2) 9)
          (= (width-v airplane2) 2)
          (= (weight-cap-v airplane2) 352)
          (= (volume-cap-v airplane2) 106)
          (= (weight-load-v airplane2) 0)
          (= (volume-load-v airplane2) 0)
          (= (weight-v airplane2) 22)
          (availablev airplane2)
          (typev airplane3 air)
          (typevp airplane3 airplane)
          (at-vehicle airplane3 location9)
          (= (gas-left airplane3) 107)
          (= (gpm airplane3) 1)
          (= (length-v airplane3) 11)
          (= (height-v airplane3) 8)
          (= (width-v airplane3) 5)
          (= (weight-cap-v airplane3) 121)
          (= (volume-cap-v airplane3) 308)
          (= (weight-load-v airplane3) 0)
          (= (volume-load-v airplane3) 0)
          (= (weight-v airplane3) 28)
          (availablev airplane3)
          (typev airplane4 air)
          (typevp airplane4 airplane)
          (at-vehicle airplane4 location1)
          (= (gas-left airplane4) 78)
          (= (gpm airplane4) 2)
          (= (length-v airplane4) 12)
          (= (height-v airplane4) 2)
          (= (width-v airplane4) 8)
          (= (weight-cap-v airplane4) 491)
          (= (volume-cap-v airplane4) 134)
          (= (weight-load-v airplane4) 0)
          (= (volume-load-v airplane4) 0)
          (= (weight-v airplane4) 35)
          (availablev airplane4)
          (at-equipment crane0 location0)
          (empty crane0)
          (= (weight-cap-c crane0) 480)
          (= (volume-cap-c crane0) 416)
          (at-equipment crane1 location1)
          (empty crane1)
          (= (weight-cap-c crane1) 464)
          (= (volume-cap-c crane1) 141)
          (at-equipment crane2 location2)
          (empty crane2)
          (= (weight-cap-c crane2) 235)
          (= (volume-cap-c crane2) 67)
          (at-equipment crane3 location3)
          (empty crane3)
          (= (weight-cap-c crane3) 198)
          (= (volume-cap-c crane3) 344)
          (at-equipment crane4 location4)
          (empty crane4)
          (= (weight-cap-c crane4) 106)
          (= (volume-cap-c crane4) 37)
          (at-equipment crane5 location5)
          (empty crane5)
          (= (weight-cap-c crane5) 275)
          (= (volume-cap-c crane5) 509)
          (at-equipment crane6 location6)
          (empty crane6)
          (= (weight-cap-c crane6) 263)
          (= (volume-cap-c crane6) 400)
          (at-equipment crane7 location7)
          (empty crane7)
          (= (weight-cap-c crane7) 354)
          (= (volume-cap-c crane7) 202)
          (at-equipment crane8 location8)
          (empty crane8)
          (= (weight-cap-c crane8) 354)
          (= (volume-cap-c crane8) 325)
          (at-equipment crane9 location9)
          (empty crane9)
          (= (weight-cap-c crane9) 52)
          (= (volume-cap-c crane9) 364)
          (at-equipment plane_ramp0 location1)
          (at-equipment plane_ramp1 location3)
          (at-equipment plane_ramp2 location9)
          (typep package0 bulky)
          (at-packagel package0 location0)
          (= (volume-p package0) 6)
          (= (weight-p package0) 21)
          (typep package1 bulky)
          (at-packagel package1 location2)
          (= (volume-p package1) 15)
          (= (weight-p package1) 18)
          (typep package2 bulky)
          (at-packagel package2 location4)
          (= (volume-p package2) 19)
          (= (weight-p package2) 5)
          (typep package3 bulky)
          (at-packagel package3 location7)
          (= (volume-p package3) 17)
          (= (weight-p package3) 22)
          (typep package4 bulky)
          (at-packagel package4 location5)
          (= (volume-p package4) 24)
          (= (weight-p package4) 20)
          (connect-city road_route0 road-route city0 city1)
          (= (height-cap-r road_route0) 29)
          (= (weight-cap-r road_route0) 233)
          (availabler road_route0)
          (connect-city road_route1 road-route city0 city2)
          (= (height-cap-r road_route1) 20)
          (= (weight-cap-r road_route1) 238)
          (availabler road_route1)
          (connect-city road_route2 road-route city0 city3)
          (= (height-cap-r road_route2) 29)
          (= (weight-cap-r road_route2) 549)
          (availabler road_route2)
          (connect-city road_route3 road-route city1 city0)
          (= (height-cap-r road_route3) 30)
          (= (weight-cap-r road_route3) 107)
          (availabler road_route3)
          (connect-city road_route4 road-route city1 city3)
          (= (height-cap-r road_route4) 20)
          (= (weight-cap-r road_route4) 349)
          (availabler road_route4)
          (connect-city road_route5 road-route city2 city0)
          (= (height-cap-r road_route5) 21)
          (= (weight-cap-r road_route5) 261)
          (availabler road_route5)
          (connect-city road_route6 road-route city2 city1)
          (= (height-cap-r road_route6) 7)
          (= (weight-cap-r road_route6) 236)
          (availabler road_route6)
          (connect-city road_route7 road-route city2 city3)
          (= (height-cap-r road_route7) 24)
          (= (weight-cap-r road_route7) 496)
          (availabler road_route7)
          (connect-city road_route8 road-route city3 city0)
          (= (height-cap-r road_route8) 32)
          (= (weight-cap-r road_route8) 451)
          (connect-city road_route9 road-route city3 city1)
          (= (height-cap-r road_route9) 31)
          (= (weight-cap-r road_route9) 512)
          (availabler road_route9)
          (connect-city road_route10 road-route city3 city2)
          (= (height-cap-r road_route10) 34)
          (= (weight-cap-r road_route10) 163)
          (availabler road_route10)
          (connect-loc rail_route0 rail-route location2 location6)
          (= (height-cap-r rail_route0) 10)
          (= (weight-cap-r rail_route0) 339)
          (serves location2 region0)
          (serves location6 region0)
          (availabler rail_route0)
          (connect-loc rail_route1 rail-route location6 location2)
          (= (height-cap-r rail_route1) 10)
          (= (weight-cap-r rail_route1) 431)
          (availabler rail_route1)
          (connect-loc air_route0 air-route location1 location3)
          (= (height-cap-r air_route0) 9)
          (= (weight-cap-r air_route0) 75)
          (serves location1 region1)
          (availabler air_route0)
          (connect-loc air_route1 air-route location1 location9)
          (= (height-cap-r air_route1) 12)
          (= (weight-cap-r air_route1) 148)
          (availabler air_route1)
          (connect-loc air_route2 air-route location3 location1)
          (= (height-cap-r air_route2) 20)
          (= (weight-cap-r air_route2) 271)
          (connect-loc air_route3 air-route location3 location9)
          (= (height-cap-r air_route3) 30)
          (= (weight-cap-r air_route3) 445)
          (availabler air_route3)
          (connect-loc air_route4 air-route location9 location1)
          (= (height-cap-r air_route4) 34)
          (= (weight-cap-r air_route4) 310)
          (availabler air_route4)
          (connect-loc air_route5 air-route location9 location3)
          (= (height-cap-r air_route5) 22)
          (= (weight-cap-r air_route5) 409)
          (availabler air_route5)
          (= (volume-load-l location0) 6)
          (= (volume-load-l location1) 0)
          (= (volume-load-l location2) 15)
          (= (volume-load-l location3) 0)
          (= (volume-load-l location4) 19)
          (= (volume-load-l location5) 24)
          (= (volume-load-l location6) 0)
          (= (volume-load-l location7) 17)
          (= (volume-load-l location8) 0)
          (= (volume-load-l location9) 0)
   )

   (:goal (and (delivered package0 location8)
               (delivered package1 location1)
               (delivered package2 location2)
               (delivered package3 location8)
               (delivered package4 location6)
               (clear)))

)