(in-package :shop2-user)

(defproblem STRIPS-SAT-X-1 adlSat
  (
    ;;;
    ;;;  facts
    ;;;
    (SATELLITE SATELLITE0)
    (INSTRUMENT INSTRUMENT0)
    (INSTRUMENT INSTRUMENT1)
    (MODE INFRARED0)
    (MODE INFRARED1)
    (MODE IMAGE2)
    (DIRECTION GROUNDSTATION1)
    (DIRECTION STAR0)
    (DIRECTION GROUNDSTATION2)
    (DIRECTION PLANET3)
    (DIRECTION PLANET4)
    (DIRECTION PHENOMENON5)
    (DIRECTION PHENOMENON6)
    (DIRECTION STAR7)
    ;;;
    ;;;  initial states
    ;;;
    (SUPPORTS INSTRUMENT0 INFRARED1)
    (SUPPORTS INSTRUMENT0 INFRARED0)
    (CALIBRATION_TARGET INSTRUMENT0 STAR0)
    (SUPPORTS INSTRUMENT1 IMAGE2)
    (SUPPORTS INSTRUMENT1 INFRARED1)
    (SUPPORTS INSTRUMENT1 INFRARED0)
    (CALIBRATION_TARGET INSTRUMENT1 GROUNDSTATION2)
    (ON_BOARD INSTRUMENT0 SATELLITE0)
    (ON_BOARD INSTRUMENT1 SATELLITE0)
    (POWER_AVAIL SATELLITE0)
    (POINTING SATELLITE0 PLANET4)
  )
  ;;;
  ;;; goals
  ;;;
  (:ordered 
    (:TASK HAVE_IMAGE PLANET3 INFRARED0)
    (:TASK HAVE_IMAGE PLANET4 INFRARED0)
    (:TASK HAVE_IMAGE PHENOMENON5 IMAGE2)
    (:TASK HAVE_IMAGE PHENOMENON6 INFRARED0)
    (:TASK HAVE_IMAGE STAR7 INFRARED0)
  )
)
