(in-package :shop-user)

#.(make-problem 'OS-SEQUENCEDSTRIPS-P30_2 'OPENSTACKS-SEQUENCEDSTRIPS-ADL-INCLUDED '((NEXT-COUNT
                                                                                      N0
                                                                                      N1)
                                                                                     (NEXT-COUNT
                                                                                      N1
                                                                                      N2)
                                                                                     (NEXT-COUNT
                                                                                      N2
                                                                                      N3)
                                                                                     (NEXT-COUNT
                                                                                      N3
                                                                                      N4)
                                                                                     (NEXT-COUNT
                                                                                      N4
                                                                                      N5)
                                                                                     (NEXT-COUNT
                                                                                      N5
                                                                                      N6)
                                                                                     (NEXT-COUNT
                                                                                      N6
                                                                                      N7)
                                                                                     (NEXT-COUNT
                                                                                      N7
                                                                                      N8)
                                                                                     (NEXT-COUNT
                                                                                      N8
                                                                                      N9)
                                                                                     (NEXT-COUNT
                                                                                      N9
                                                                                      N10)
                                                                                     (NEXT-COUNT
                                                                                      N10
                                                                                      N11)
                                                                                     (NEXT-COUNT
                                                                                      N11
                                                                                      N12)
                                                                                     (NEXT-COUNT
                                                                                      N12
                                                                                      N13)
                                                                                     (NEXT-COUNT
                                                                                      N13
                                                                                      N14)
                                                                                     (NEXT-COUNT
                                                                                      N14
                                                                                      N15)
                                                                                     (NEXT-COUNT
                                                                                      N15
                                                                                      N16)
                                                                                     (NEXT-COUNT
                                                                                      N16
                                                                                      N17)
                                                                                     (NEXT-COUNT
                                                                                      N17
                                                                                      N18)
                                                                                     (NEXT-COUNT
                                                                                      N18
                                                                                      N19)
                                                                                     (NEXT-COUNT
                                                                                      N19
                                                                                      N20)
                                                                                     (NEXT-COUNT
                                                                                      N20
                                                                                      N21)
                                                                                     (NEXT-COUNT
                                                                                      N21
                                                                                      N22)
                                                                                     (NEXT-COUNT
                                                                                      N22
                                                                                      N23)
                                                                                     (NEXT-COUNT
                                                                                      N23
                                                                                      N24)
                                                                                     (NEXT-COUNT
                                                                                      N24
                                                                                      N25)
                                                                                     (NEXT-COUNT
                                                                                      N25
                                                                                      N26)
                                                                                     (NEXT-COUNT
                                                                                      N26
                                                                                      N27)
                                                                                     (NEXT-COUNT
                                                                                      N27
                                                                                      N28)
                                                                                     (NEXT-COUNT
                                                                                      N28
                                                                                      N29)
                                                                                     (NEXT-COUNT
                                                                                      N29
                                                                                      N30)
                                                                                     (STACKS-AVAIL
                                                                                      N0)
                                                                                     (WAITING
                                                                                      O1)
                                                                                     (INCLUDES
                                                                                      O1
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O1
                                                                                      P11)
                                                                                     (WAITING
                                                                                      O2)
                                                                                     (INCLUDES
                                                                                      O2
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O3)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P19)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P21)
                                                                                     (WAITING
                                                                                      O4)
                                                                                     (INCLUDES
                                                                                      O4
                                                                                      P15)
                                                                                     (WAITING
                                                                                      O5)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P18)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P23)
                                                                                     (WAITING
                                                                                      O6)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P26)
                                                                                     (WAITING
                                                                                      O7)
                                                                                     (INCLUDES
                                                                                      O7
                                                                                      P12)
                                                                                     (WAITING
                                                                                      O8)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P4)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P29)
                                                                                     (WAITING
                                                                                      O9)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P2)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P8)
                                                                                     (WAITING
                                                                                      O10)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P20)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P27)
                                                                                     (WAITING
                                                                                      O11)
                                                                                     (INCLUDES
                                                                                      O11
                                                                                      P9)
                                                                                     (INCLUDES
                                                                                      O11
                                                                                      P25)
                                                                                     (WAITING
                                                                                      O12)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P2)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P5)
                                                                                     (WAITING
                                                                                      O13)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O14)
                                                                                     (INCLUDES
                                                                                      O14
                                                                                      P29)
                                                                                     (WAITING
                                                                                      O15)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P5)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P6)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P8)
                                                                                     (WAITING
                                                                                      O16)
                                                                                     (INCLUDES
                                                                                      O16
                                                                                      P12)
                                                                                     (WAITING
                                                                                      O17)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P25)
                                                                                     (WAITING
                                                                                      O18)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P11)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P18)
                                                                                     (WAITING
                                                                                      O19)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O20)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P14)
                                                                                     (WAITING
                                                                                      O21)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P18)
                                                                                     (WAITING
                                                                                      O22)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P13)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P14)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P17)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P22)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P26)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P30)
                                                                                     (WAITING
                                                                                      O23)
                                                                                     (INCLUDES
                                                                                      O23
                                                                                      P21)
                                                                                     (WAITING
                                                                                      O24)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P15)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P21)
                                                                                     (WAITING
                                                                                      O25)
                                                                                     (INCLUDES
                                                                                      O25
                                                                                      P2)
                                                                                     (WAITING
                                                                                      O26)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P1)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P16)
                                                                                     (WAITING
                                                                                      O27)
                                                                                     (INCLUDES
                                                                                      O27
                                                                                      P17)
                                                                                     (INCLUDES
                                                                                      O27
                                                                                      P24)
                                                                                     (INCLUDES
                                                                                      O27
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O28)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P2)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P8)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O29)
                                                                                     (INCLUDES
                                                                                      O29
                                                                                      P12)
                                                                                     (WAITING
                                                                                      O30)
                                                                                     (INCLUDES
                                                                                      O30
                                                                                      P26)
                                                                                     (=
                                                                                      (TOTAL-COST)
                                                                                      0)
                                                                                     (COUNT
                                                                                      N0)
                                                                                     (COUNT
                                                                                      N1)
                                                                                     (COUNT
                                                                                      N2)
                                                                                     (COUNT
                                                                                      N3)
                                                                                     (COUNT
                                                                                      N4)
                                                                                     (COUNT
                                                                                      N5)
                                                                                     (COUNT
                                                                                      N6)
                                                                                     (COUNT
                                                                                      N7)
                                                                                     (COUNT
                                                                                      N8)
                                                                                     (COUNT
                                                                                      N9)
                                                                                     (COUNT
                                                                                      N10)
                                                                                     (COUNT
                                                                                      N11)
                                                                                     (COUNT
                                                                                      N12)
                                                                                     (COUNT
                                                                                      N13)
                                                                                     (COUNT
                                                                                      N14)
                                                                                     (COUNT
                                                                                      N15)
                                                                                     (COUNT
                                                                                      N16)
                                                                                     (COUNT
                                                                                      N17)
                                                                                     (COUNT
                                                                                      N18)
                                                                                     (COUNT
                                                                                      N19)
                                                                                     (COUNT
                                                                                      N20)
                                                                                     (COUNT
                                                                                      N21)
                                                                                     (COUNT
                                                                                      N22)
                                                                                     (COUNT
                                                                                      N23)
                                                                                     (COUNT
                                                                                      N24)
                                                                                     (COUNT
                                                                                      N25)
                                                                                     (COUNT
                                                                                      N26)
                                                                                     (COUNT
                                                                                      N27)
                                                                                     (COUNT
                                                                                      N28)
                                                                                     (COUNT
                                                                                      N29)
                                                                                     (COUNT
                                                                                      N30)
                                                                                     (ORDER
                                                                                      O1)
                                                                                     (ORDER
                                                                                      O2)
                                                                                     (ORDER
                                                                                      O3)
                                                                                     (ORDER
                                                                                      O4)
                                                                                     (ORDER
                                                                                      O5)
                                                                                     (ORDER
                                                                                      O6)
                                                                                     (ORDER
                                                                                      O7)
                                                                                     (ORDER
                                                                                      O8)
                                                                                     (ORDER
                                                                                      O9)
                                                                                     (ORDER
                                                                                      O10)
                                                                                     (ORDER
                                                                                      O11)
                                                                                     (ORDER
                                                                                      O12)
                                                                                     (ORDER
                                                                                      O13)
                                                                                     (ORDER
                                                                                      O14)
                                                                                     (ORDER
                                                                                      O15)
                                                                                     (ORDER
                                                                                      O16)
                                                                                     (ORDER
                                                                                      O17)
                                                                                     (ORDER
                                                                                      O18)
                                                                                     (ORDER
                                                                                      O19)
                                                                                     (ORDER
                                                                                      O20)
                                                                                     (ORDER
                                                                                      O21)
                                                                                     (ORDER
                                                                                      O22)
                                                                                     (ORDER
                                                                                      O23)
                                                                                     (ORDER
                                                                                      O24)
                                                                                     (ORDER
                                                                                      O25)
                                                                                     (ORDER
                                                                                      O26)
                                                                                     (ORDER
                                                                                      O27)
                                                                                     (ORDER
                                                                                      O28)
                                                                                     (ORDER
                                                                                      O29)
                                                                                     (ORDER
                                                                                      O30)
                                                                                     (PRODUCT
                                                                                      P1)
                                                                                     (PRODUCT
                                                                                      P2)
                                                                                     (PRODUCT
                                                                                      P3)
                                                                                     (PRODUCT
                                                                                      P4)
                                                                                     (PRODUCT
                                                                                      P5)
                                                                                     (PRODUCT
                                                                                      P6)
                                                                                     (PRODUCT
                                                                                      P7)
                                                                                     (PRODUCT
                                                                                      P8)
                                                                                     (PRODUCT
                                                                                      P9)
                                                                                     (PRODUCT
                                                                                      P10)
                                                                                     (PRODUCT
                                                                                      P11)
                                                                                     (PRODUCT
                                                                                      P12)
                                                                                     (PRODUCT
                                                                                      P13)
                                                                                     (PRODUCT
                                                                                      P14)
                                                                                     (PRODUCT
                                                                                      P15)
                                                                                     (PRODUCT
                                                                                      P16)
                                                                                     (PRODUCT
                                                                                      P17)
                                                                                     (PRODUCT
                                                                                      P18)
                                                                                     (PRODUCT
                                                                                      P19)
                                                                                     (PRODUCT
                                                                                      P20)
                                                                                     (PRODUCT
                                                                                      P21)
                                                                                     (PRODUCT
                                                                                      P22)
                                                                                     (PRODUCT
                                                                                      P23)
                                                                                     (PRODUCT
                                                                                      P24)
                                                                                     (PRODUCT
                                                                                      P25)
                                                                                     (PRODUCT
                                                                                      P26)
                                                                                     (PRODUCT
                                                                                      P27)
                                                                                     (PRODUCT
                                                                                      P28)
                                                                                     (PRODUCT
                                                                                      P29)
                                                                                     (PRODUCT
                                                                                      P30)
                                                                                     (:GOAL
                                                                                      (AND
                                                                                       (SHIPPED
                                                                                        O1)
                                                                                       (SHIPPED
                                                                                        O2)
                                                                                       (SHIPPED
                                                                                        O3)
                                                                                       (SHIPPED
                                                                                        O4)
                                                                                       (SHIPPED
                                                                                        O5)
                                                                                       (SHIPPED
                                                                                        O6)
                                                                                       (SHIPPED
                                                                                        O7)
                                                                                       (SHIPPED
                                                                                        O8)
                                                                                       (SHIPPED
                                                                                        O9)
                                                                                       (SHIPPED
                                                                                        O10)
                                                                                       (SHIPPED
                                                                                        O11)
                                                                                       (SHIPPED
                                                                                        O12)
                                                                                       (SHIPPED
                                                                                        O13)
                                                                                       (SHIPPED
                                                                                        O14)
                                                                                       (SHIPPED
                                                                                        O15)
                                                                                       (SHIPPED
                                                                                        O16)
                                                                                       (SHIPPED
                                                                                        O17)
                                                                                       (SHIPPED
                                                                                        O18)
                                                                                       (SHIPPED
                                                                                        O19)
                                                                                       (SHIPPED
                                                                                        O20)
                                                                                       (SHIPPED
                                                                                        O21)
                                                                                       (SHIPPED
                                                                                        O22)
                                                                                       (SHIPPED
                                                                                        O23)
                                                                                       (SHIPPED
                                                                                        O24)
                                                                                       (SHIPPED
                                                                                        O25)
                                                                                       (SHIPPED
                                                                                        O26)
                                                                                       (SHIPPED
                                                                                        O27)
                                                                                       (SHIPPED
                                                                                        O28)
                                                                                       (SHIPPED
                                                                                        O29)
                                                                                       (SHIPPED
                                                                                        O30)))) '(:TASK
                                                                                                  PLAN)) 