(in-package :shop-user)

#.(make-problem 'OS-SEQUENCEDSTRIPS-P50_2 'OPENSTACKS-SEQUENCEDSTRIPS-ADL-INCLUDED '((NEXT-COUNT
                                                                                      N0
                                                                                      N1)
                                                                                     (NEXT-COUNT
                                                                                      N1
                                                                                      N2)
                                                                                     (NEXT-COUNT
                                                                                      N2
                                                                                      N3)
                                                                                     (NEXT-COUNT
                                                                                      N3
                                                                                      N4)
                                                                                     (NEXT-COUNT
                                                                                      N4
                                                                                      N5)
                                                                                     (NEXT-COUNT
                                                                                      N5
                                                                                      N6)
                                                                                     (NEXT-COUNT
                                                                                      N6
                                                                                      N7)
                                                                                     (NEXT-COUNT
                                                                                      N7
                                                                                      N8)
                                                                                     (NEXT-COUNT
                                                                                      N8
                                                                                      N9)
                                                                                     (NEXT-COUNT
                                                                                      N9
                                                                                      N10)
                                                                                     (NEXT-COUNT
                                                                                      N10
                                                                                      N11)
                                                                                     (NEXT-COUNT
                                                                                      N11
                                                                                      N12)
                                                                                     (NEXT-COUNT
                                                                                      N12
                                                                                      N13)
                                                                                     (NEXT-COUNT
                                                                                      N13
                                                                                      N14)
                                                                                     (NEXT-COUNT
                                                                                      N14
                                                                                      N15)
                                                                                     (NEXT-COUNT
                                                                                      N15
                                                                                      N16)
                                                                                     (NEXT-COUNT
                                                                                      N16
                                                                                      N17)
                                                                                     (NEXT-COUNT
                                                                                      N17
                                                                                      N18)
                                                                                     (NEXT-COUNT
                                                                                      N18
                                                                                      N19)
                                                                                     (NEXT-COUNT
                                                                                      N19
                                                                                      N20)
                                                                                     (NEXT-COUNT
                                                                                      N20
                                                                                      N21)
                                                                                     (NEXT-COUNT
                                                                                      N21
                                                                                      N22)
                                                                                     (NEXT-COUNT
                                                                                      N22
                                                                                      N23)
                                                                                     (NEXT-COUNT
                                                                                      N23
                                                                                      N24)
                                                                                     (NEXT-COUNT
                                                                                      N24
                                                                                      N25)
                                                                                     (NEXT-COUNT
                                                                                      N25
                                                                                      N26)
                                                                                     (NEXT-COUNT
                                                                                      N26
                                                                                      N27)
                                                                                     (NEXT-COUNT
                                                                                      N27
                                                                                      N28)
                                                                                     (NEXT-COUNT
                                                                                      N28
                                                                                      N29)
                                                                                     (NEXT-COUNT
                                                                                      N29
                                                                                      N30)
                                                                                     (NEXT-COUNT
                                                                                      N30
                                                                                      N31)
                                                                                     (NEXT-COUNT
                                                                                      N31
                                                                                      N32)
                                                                                     (NEXT-COUNT
                                                                                      N32
                                                                                      N33)
                                                                                     (NEXT-COUNT
                                                                                      N33
                                                                                      N34)
                                                                                     (NEXT-COUNT
                                                                                      N34
                                                                                      N35)
                                                                                     (NEXT-COUNT
                                                                                      N35
                                                                                      N36)
                                                                                     (NEXT-COUNT
                                                                                      N36
                                                                                      N37)
                                                                                     (NEXT-COUNT
                                                                                      N37
                                                                                      N38)
                                                                                     (NEXT-COUNT
                                                                                      N38
                                                                                      N39)
                                                                                     (NEXT-COUNT
                                                                                      N39
                                                                                      N40)
                                                                                     (NEXT-COUNT
                                                                                      N40
                                                                                      N41)
                                                                                     (NEXT-COUNT
                                                                                      N41
                                                                                      N42)
                                                                                     (NEXT-COUNT
                                                                                      N42
                                                                                      N43)
                                                                                     (NEXT-COUNT
                                                                                      N43
                                                                                      N44)
                                                                                     (NEXT-COUNT
                                                                                      N44
                                                                                      N45)
                                                                                     (NEXT-COUNT
                                                                                      N45
                                                                                      N46)
                                                                                     (NEXT-COUNT
                                                                                      N46
                                                                                      N47)
                                                                                     (NEXT-COUNT
                                                                                      N47
                                                                                      N48)
                                                                                     (NEXT-COUNT
                                                                                      N48
                                                                                      N49)
                                                                                     (NEXT-COUNT
                                                                                      N49
                                                                                      N50)
                                                                                     (STACKS-AVAIL
                                                                                      N0)
                                                                                     (WAITING
                                                                                      O1)
                                                                                     (INCLUDES
                                                                                      O1
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O1
                                                                                      P15)
                                                                                     (WAITING
                                                                                      O2)
                                                                                     (INCLUDES
                                                                                      O2
                                                                                      P6)
                                                                                     (WAITING
                                                                                      O3)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P9)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O4)
                                                                                     (INCLUDES
                                                                                      O4
                                                                                      P35)
                                                                                     (INCLUDES
                                                                                      O4
                                                                                      P44)
                                                                                     (WAITING
                                                                                      O5)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P34)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P48)
                                                                                     (WAITING
                                                                                      O6)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P8)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P17)
                                                                                     (WAITING
                                                                                      O7)
                                                                                     (INCLUDES
                                                                                      O7
                                                                                      P37)
                                                                                     (INCLUDES
                                                                                      O7
                                                                                      P42)
                                                                                     (WAITING
                                                                                      O8)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P8)
                                                                                     (WAITING
                                                                                      O9)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P6)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P13)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P23)
                                                                                     (WAITING
                                                                                      O10)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P20)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P32)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P35)
                                                                                     (WAITING
                                                                                      O11)
                                                                                     (INCLUDES
                                                                                      O11
                                                                                      P43)
                                                                                     (WAITING
                                                                                      O12)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P20)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P33)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P38)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P43)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P45)
                                                                                     (WAITING
                                                                                      O13)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P14)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P46)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P48)
                                                                                     (WAITING
                                                                                      O14)
                                                                                     (INCLUDES
                                                                                      O14
                                                                                      P23)
                                                                                     (WAITING
                                                                                      O15)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P30)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P38)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P49)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P50)
                                                                                     (WAITING
                                                                                      O16)
                                                                                     (INCLUDES
                                                                                      O16
                                                                                      P2)
                                                                                     (INCLUDES
                                                                                      O16
                                                                                      P23)
                                                                                     (INCLUDES
                                                                                      O16
                                                                                      P29)
                                                                                     (WAITING
                                                                                      O17)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P24)
                                                                                     (WAITING
                                                                                      O18)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P19)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P25)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P26)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P37)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P47)
                                                                                     (WAITING
                                                                                      O19)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P22)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P35)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P42)
                                                                                     (WAITING
                                                                                      O20)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P4)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P18)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P19)
                                                                                     (WAITING
                                                                                      O21)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P1)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O22)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P5)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P12)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P27)
                                                                                     (WAITING
                                                                                      O23)
                                                                                     (INCLUDES
                                                                                      O23
                                                                                      P46)
                                                                                     (WAITING
                                                                                      O24)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P33)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P41)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P47)
                                                                                     (WAITING
                                                                                      O25)
                                                                                     (INCLUDES
                                                                                      O25
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O26)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P38)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P40)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P41)
                                                                                     (WAITING
                                                                                      O27)
                                                                                     (INCLUDES
                                                                                      O27
                                                                                      P19)
                                                                                     (WAITING
                                                                                      O28)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P12)
                                                                                     (WAITING
                                                                                      O29)
                                                                                     (INCLUDES
                                                                                      O29
                                                                                      P38)
                                                                                     (WAITING
                                                                                      O30)
                                                                                     (INCLUDES
                                                                                      O30
                                                                                      P32)
                                                                                     (INCLUDES
                                                                                      O30
                                                                                      P46)
                                                                                     (WAITING
                                                                                      O31)
                                                                                     (INCLUDES
                                                                                      O31
                                                                                      P11)
                                                                                     (INCLUDES
                                                                                      O31
                                                                                      P26)
                                                                                     (WAITING
                                                                                      O32)
                                                                                     (INCLUDES
                                                                                      O32
                                                                                      P29)
                                                                                     (INCLUDES
                                                                                      O32
                                                                                      P36)
                                                                                     (WAITING
                                                                                      O33)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P12)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P18)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P19)
                                                                                     (WAITING
                                                                                      O34)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P28)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P39)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P42)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P49)
                                                                                     (WAITING
                                                                                      O35)
                                                                                     (INCLUDES
                                                                                      O35
                                                                                      P12)
                                                                                     (INCLUDES
                                                                                      O35
                                                                                      P25)
                                                                                     (INCLUDES
                                                                                      O35
                                                                                      P41)
                                                                                     (WAITING
                                                                                      O36)
                                                                                     (INCLUDES
                                                                                      O36
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O36
                                                                                      P20)
                                                                                     (WAITING
                                                                                      O37)
                                                                                     (INCLUDES
                                                                                      O37
                                                                                      P8)
                                                                                     (WAITING
                                                                                      O38)
                                                                                     (INCLUDES
                                                                                      O38
                                                                                      P19)
                                                                                     (INCLUDES
                                                                                      O38
                                                                                      P26)
                                                                                     (WAITING
                                                                                      O39)
                                                                                     (INCLUDES
                                                                                      O39
                                                                                      P9)
                                                                                     (INCLUDES
                                                                                      O39
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O39
                                                                                      P37)
                                                                                     (INCLUDES
                                                                                      O39
                                                                                      P38)
                                                                                     (WAITING
                                                                                      O40)
                                                                                     (INCLUDES
                                                                                      O40
                                                                                      P6)
                                                                                     (INCLUDES
                                                                                      O40
                                                                                      P15)
                                                                                     (INCLUDES
                                                                                      O40
                                                                                      P17)
                                                                                     (INCLUDES
                                                                                      O40
                                                                                      P24)
                                                                                     (WAITING
                                                                                      O41)
                                                                                     (INCLUDES
                                                                                      O41
                                                                                      P12)
                                                                                     (INCLUDES
                                                                                      O41
                                                                                      P13)
                                                                                     (WAITING
                                                                                      O42)
                                                                                     (INCLUDES
                                                                                      O42
                                                                                      P26)
                                                                                     (WAITING
                                                                                      O43)
                                                                                     (INCLUDES
                                                                                      O43
                                                                                      P33)
                                                                                     (INCLUDES
                                                                                      O43
                                                                                      P35)
                                                                                     (INCLUDES
                                                                                      O43
                                                                                      P46)
                                                                                     (WAITING
                                                                                      O44)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P17)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P21)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P28)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P29)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P31)
                                                                                     (INCLUDES
                                                                                      O44
                                                                                      P38)
                                                                                     (WAITING
                                                                                      O45)
                                                                                     (INCLUDES
                                                                                      O45
                                                                                      P44)
                                                                                     (WAITING
                                                                                      O46)
                                                                                     (INCLUDES
                                                                                      O46
                                                                                      P22)
                                                                                     (INCLUDES
                                                                                      O46
                                                                                      P25)
                                                                                     (WAITING
                                                                                      O47)
                                                                                     (INCLUDES
                                                                                      O47
                                                                                      P42)
                                                                                     (WAITING
                                                                                      O48)
                                                                                     (INCLUDES
                                                                                      O48
                                                                                      P42)
                                                                                     (WAITING
                                                                                      O49)
                                                                                     (INCLUDES
                                                                                      O49
                                                                                      P12)
                                                                                     (INCLUDES
                                                                                      O49
                                                                                      P15)
                                                                                     (WAITING
                                                                                      O50)
                                                                                     (INCLUDES
                                                                                      O50
                                                                                      P11)
                                                                                     (INCLUDES
                                                                                      O50
                                                                                      P39)
                                                                                     (=
                                                                                      (TOTAL-COST)
                                                                                      0)
                                                                                     (COUNT
                                                                                      N0)
                                                                                     (COUNT
                                                                                      N1)
                                                                                     (COUNT
                                                                                      N2)
                                                                                     (COUNT
                                                                                      N3)
                                                                                     (COUNT
                                                                                      N4)
                                                                                     (COUNT
                                                                                      N5)
                                                                                     (COUNT
                                                                                      N6)
                                                                                     (COUNT
                                                                                      N7)
                                                                                     (COUNT
                                                                                      N8)
                                                                                     (COUNT
                                                                                      N9)
                                                                                     (COUNT
                                                                                      N10)
                                                                                     (COUNT
                                                                                      N11)
                                                                                     (COUNT
                                                                                      N12)
                                                                                     (COUNT
                                                                                      N13)
                                                                                     (COUNT
                                                                                      N14)
                                                                                     (COUNT
                                                                                      N15)
                                                                                     (COUNT
                                                                                      N16)
                                                                                     (COUNT
                                                                                      N17)
                                                                                     (COUNT
                                                                                      N18)
                                                                                     (COUNT
                                                                                      N19)
                                                                                     (COUNT
                                                                                      N20)
                                                                                     (COUNT
                                                                                      N21)
                                                                                     (COUNT
                                                                                      N22)
                                                                                     (COUNT
                                                                                      N23)
                                                                                     (COUNT
                                                                                      N24)
                                                                                     (COUNT
                                                                                      N25)
                                                                                     (COUNT
                                                                                      N26)
                                                                                     (COUNT
                                                                                      N27)
                                                                                     (COUNT
                                                                                      N28)
                                                                                     (COUNT
                                                                                      N29)
                                                                                     (COUNT
                                                                                      N30)
                                                                                     (COUNT
                                                                                      N31)
                                                                                     (COUNT
                                                                                      N32)
                                                                                     (COUNT
                                                                                      N33)
                                                                                     (COUNT
                                                                                      N34)
                                                                                     (COUNT
                                                                                      N35)
                                                                                     (COUNT
                                                                                      N36)
                                                                                     (COUNT
                                                                                      N37)
                                                                                     (COUNT
                                                                                      N38)
                                                                                     (COUNT
                                                                                      N39)
                                                                                     (COUNT
                                                                                      N40)
                                                                                     (COUNT
                                                                                      N41)
                                                                                     (COUNT
                                                                                      N42)
                                                                                     (COUNT
                                                                                      N43)
                                                                                     (COUNT
                                                                                      N44)
                                                                                     (COUNT
                                                                                      N45)
                                                                                     (COUNT
                                                                                      N46)
                                                                                     (COUNT
                                                                                      N47)
                                                                                     (COUNT
                                                                                      N48)
                                                                                     (COUNT
                                                                                      N49)
                                                                                     (COUNT
                                                                                      N50)
                                                                                     (ORDER
                                                                                      O1)
                                                                                     (ORDER
                                                                                      O2)
                                                                                     (ORDER
                                                                                      O3)
                                                                                     (ORDER
                                                                                      O4)
                                                                                     (ORDER
                                                                                      O5)
                                                                                     (ORDER
                                                                                      O6)
                                                                                     (ORDER
                                                                                      O7)
                                                                                     (ORDER
                                                                                      O8)
                                                                                     (ORDER
                                                                                      O9)
                                                                                     (ORDER
                                                                                      O10)
                                                                                     (ORDER
                                                                                      O11)
                                                                                     (ORDER
                                                                                      O12)
                                                                                     (ORDER
                                                                                      O13)
                                                                                     (ORDER
                                                                                      O14)
                                                                                     (ORDER
                                                                                      O15)
                                                                                     (ORDER
                                                                                      O16)
                                                                                     (ORDER
                                                                                      O17)
                                                                                     (ORDER
                                                                                      O18)
                                                                                     (ORDER
                                                                                      O19)
                                                                                     (ORDER
                                                                                      O20)
                                                                                     (ORDER
                                                                                      O21)
                                                                                     (ORDER
                                                                                      O22)
                                                                                     (ORDER
                                                                                      O23)
                                                                                     (ORDER
                                                                                      O24)
                                                                                     (ORDER
                                                                                      O25)
                                                                                     (ORDER
                                                                                      O26)
                                                                                     (ORDER
                                                                                      O27)
                                                                                     (ORDER
                                                                                      O28)
                                                                                     (ORDER
                                                                                      O29)
                                                                                     (ORDER
                                                                                      O30)
                                                                                     (ORDER
                                                                                      O31)
                                                                                     (ORDER
                                                                                      O32)
                                                                                     (ORDER
                                                                                      O33)
                                                                                     (ORDER
                                                                                      O34)
                                                                                     (ORDER
                                                                                      O35)
                                                                                     (ORDER
                                                                                      O36)
                                                                                     (ORDER
                                                                                      O37)
                                                                                     (ORDER
                                                                                      O38)
                                                                                     (ORDER
                                                                                      O39)
                                                                                     (ORDER
                                                                                      O40)
                                                                                     (ORDER
                                                                                      O41)
                                                                                     (ORDER
                                                                                      O42)
                                                                                     (ORDER
                                                                                      O43)
                                                                                     (ORDER
                                                                                      O44)
                                                                                     (ORDER
                                                                                      O45)
                                                                                     (ORDER
                                                                                      O46)
                                                                                     (ORDER
                                                                                      O47)
                                                                                     (ORDER
                                                                                      O48)
                                                                                     (ORDER
                                                                                      O49)
                                                                                     (ORDER
                                                                                      O50)
                                                                                     (PRODUCT
                                                                                      P1)
                                                                                     (PRODUCT
                                                                                      P2)
                                                                                     (PRODUCT
                                                                                      P3)
                                                                                     (PRODUCT
                                                                                      P4)
                                                                                     (PRODUCT
                                                                                      P5)
                                                                                     (PRODUCT
                                                                                      P6)
                                                                                     (PRODUCT
                                                                                      P7)
                                                                                     (PRODUCT
                                                                                      P8)
                                                                                     (PRODUCT
                                                                                      P9)
                                                                                     (PRODUCT
                                                                                      P10)
                                                                                     (PRODUCT
                                                                                      P11)
                                                                                     (PRODUCT
                                                                                      P12)
                                                                                     (PRODUCT
                                                                                      P13)
                                                                                     (PRODUCT
                                                                                      P14)
                                                                                     (PRODUCT
                                                                                      P15)
                                                                                     (PRODUCT
                                                                                      P16)
                                                                                     (PRODUCT
                                                                                      P17)
                                                                                     (PRODUCT
                                                                                      P18)
                                                                                     (PRODUCT
                                                                                      P19)
                                                                                     (PRODUCT
                                                                                      P20)
                                                                                     (PRODUCT
                                                                                      P21)
                                                                                     (PRODUCT
                                                                                      P22)
                                                                                     (PRODUCT
                                                                                      P23)
                                                                                     (PRODUCT
                                                                                      P24)
                                                                                     (PRODUCT
                                                                                      P25)
                                                                                     (PRODUCT
                                                                                      P26)
                                                                                     (PRODUCT
                                                                                      P27)
                                                                                     (PRODUCT
                                                                                      P28)
                                                                                     (PRODUCT
                                                                                      P29)
                                                                                     (PRODUCT
                                                                                      P30)
                                                                                     (PRODUCT
                                                                                      P31)
                                                                                     (PRODUCT
                                                                                      P32)
                                                                                     (PRODUCT
                                                                                      P33)
                                                                                     (PRODUCT
                                                                                      P34)
                                                                                     (PRODUCT
                                                                                      P35)
                                                                                     (PRODUCT
                                                                                      P36)
                                                                                     (PRODUCT
                                                                                      P37)
                                                                                     (PRODUCT
                                                                                      P38)
                                                                                     (PRODUCT
                                                                                      P39)
                                                                                     (PRODUCT
                                                                                      P40)
                                                                                     (PRODUCT
                                                                                      P41)
                                                                                     (PRODUCT
                                                                                      P42)
                                                                                     (PRODUCT
                                                                                      P43)
                                                                                     (PRODUCT
                                                                                      P44)
                                                                                     (PRODUCT
                                                                                      P45)
                                                                                     (PRODUCT
                                                                                      P46)
                                                                                     (PRODUCT
                                                                                      P47)
                                                                                     (PRODUCT
                                                                                      P48)
                                                                                     (PRODUCT
                                                                                      P49)
                                                                                     (PRODUCT
                                                                                      P50)
                                                                                     (:GOAL
                                                                                      (AND
                                                                                       (SHIPPED
                                                                                        O1)
                                                                                       (SHIPPED
                                                                                        O2)
                                                                                       (SHIPPED
                                                                                        O3)
                                                                                       (SHIPPED
                                                                                        O4)
                                                                                       (SHIPPED
                                                                                        O5)
                                                                                       (SHIPPED
                                                                                        O6)
                                                                                       (SHIPPED
                                                                                        O7)
                                                                                       (SHIPPED
                                                                                        O8)
                                                                                       (SHIPPED
                                                                                        O9)
                                                                                       (SHIPPED
                                                                                        O10)
                                                                                       (SHIPPED
                                                                                        O11)
                                                                                       (SHIPPED
                                                                                        O12)
                                                                                       (SHIPPED
                                                                                        O13)
                                                                                       (SHIPPED
                                                                                        O14)
                                                                                       (SHIPPED
                                                                                        O15)
                                                                                       (SHIPPED
                                                                                        O16)
                                                                                       (SHIPPED
                                                                                        O17)
                                                                                       (SHIPPED
                                                                                        O18)
                                                                                       (SHIPPED
                                                                                        O19)
                                                                                       (SHIPPED
                                                                                        O20)
                                                                                       (SHIPPED
                                                                                        O21)
                                                                                       (SHIPPED
                                                                                        O22)
                                                                                       (SHIPPED
                                                                                        O23)
                                                                                       (SHIPPED
                                                                                        O24)
                                                                                       (SHIPPED
                                                                                        O25)
                                                                                       (SHIPPED
                                                                                        O26)
                                                                                       (SHIPPED
                                                                                        O27)
                                                                                       (SHIPPED
                                                                                        O28)
                                                                                       (SHIPPED
                                                                                        O29)
                                                                                       (SHIPPED
                                                                                        O30)
                                                                                       (SHIPPED
                                                                                        O31)
                                                                                       (SHIPPED
                                                                                        O32)
                                                                                       (SHIPPED
                                                                                        O33)
                                                                                       (SHIPPED
                                                                                        O34)
                                                                                       (SHIPPED
                                                                                        O35)
                                                                                       (SHIPPED
                                                                                        O36)
                                                                                       (SHIPPED
                                                                                        O37)
                                                                                       (SHIPPED
                                                                                        O38)
                                                                                       (SHIPPED
                                                                                        O39)
                                                                                       (SHIPPED
                                                                                        O40)
                                                                                       (SHIPPED
                                                                                        O41)
                                                                                       (SHIPPED
                                                                                        O42)
                                                                                       (SHIPPED
                                                                                        O43)
                                                                                       (SHIPPED
                                                                                        O44)
                                                                                       (SHIPPED
                                                                                        O45)
                                                                                       (SHIPPED
                                                                                        O46)
                                                                                       (SHIPPED
                                                                                        O47)
                                                                                       (SHIPPED
                                                                                        O48)
                                                                                       (SHIPPED
                                                                                        O49)
                                                                                       (SHIPPED
                                                                                        O50)))) '(:TASK
                                                                                                  PLAN)) 