(define (problem roverprob2413) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint14)
	(visible waypoint14 waypoint0)
	(visible waypoint0 waypoint37)
	(visible waypoint37 waypoint0)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint37)
	(visible waypoint37 waypoint1)
	(visible waypoint2 waypoint7)
	(visible waypoint7 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint17)
	(visible waypoint17 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint3 waypoint20)
	(visible waypoint20 waypoint3)
	(visible waypoint4 waypoint12)
	(visible waypoint12 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint22 waypoint4)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint27)
	(visible waypoint27 waypoint5)
	(visible waypoint5 waypoint32)
	(visible waypoint32 waypoint5)
	(visible waypoint5 waypoint34)
	(visible waypoint34 waypoint5)
	(visible waypoint5 waypoint37)
	(visible waypoint37 waypoint5)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint13)
	(visible waypoint13 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint7 waypoint15)
	(visible waypoint15 waypoint7)
	(visible waypoint7 waypoint30)
	(visible waypoint30 waypoint7)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint12)
	(visible waypoint12 waypoint8)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint9)
	(visible waypoint9 waypoint28)
	(visible waypoint28 waypoint9)
	(visible waypoint9 waypoint29)
	(visible waypoint29 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint9)
	(visible waypoint10 waypoint4)
	(visible waypoint4 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint31)
	(visible waypoint31 waypoint11)
	(visible waypoint12 waypoint1)
	(visible waypoint1 waypoint12)
	(visible waypoint12 waypoint3)
	(visible waypoint3 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint9)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint17)
	(visible waypoint17 waypoint12)
	(visible waypoint12 waypoint36)
	(visible waypoint36 waypoint12)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint13 waypoint25)
	(visible waypoint25 waypoint13)
	(visible waypoint13 waypoint34)
	(visible waypoint34 waypoint13)
	(visible waypoint14 waypoint3)
	(visible waypoint3 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint23)
	(visible waypoint23 waypoint14)
	(visible waypoint14 waypoint33)
	(visible waypoint33 waypoint14)
	(visible waypoint14 waypoint38)
	(visible waypoint38 waypoint14)
	(visible waypoint15 waypoint5)
	(visible waypoint5 waypoint15)
	(visible waypoint15 waypoint13)
	(visible waypoint13 waypoint15)
	(visible waypoint15 waypoint14)
	(visible waypoint14 waypoint15)
	(visible waypoint15 waypoint20)
	(visible waypoint20 waypoint15)
	(visible waypoint15 waypoint26)
	(visible waypoint26 waypoint15)
	(visible waypoint15 waypoint28)
	(visible waypoint28 waypoint15)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint5)
	(visible waypoint5 waypoint16)
	(visible waypoint16 waypoint8)
	(visible waypoint8 waypoint16)
	(visible waypoint16 waypoint13)
	(visible waypoint13 waypoint16)
	(visible waypoint16 waypoint18)
	(visible waypoint18 waypoint16)
	(visible waypoint16 waypoint19)
	(visible waypoint19 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint20 waypoint16)
	(visible waypoint16 waypoint29)
	(visible waypoint29 waypoint16)
	(visible waypoint17 waypoint1)
	(visible waypoint1 waypoint17)
	(visible waypoint17 waypoint13)
	(visible waypoint13 waypoint17)
	(visible waypoint17 waypoint22)
	(visible waypoint22 waypoint17)
	(visible waypoint17 waypoint35)
	(visible waypoint35 waypoint17)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint39)
	(visible waypoint39 waypoint18)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint19)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint11)
	(visible waypoint11 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint19)
	(visible waypoint19 waypoint20)
	(visible waypoint20 waypoint30)
	(visible waypoint30 waypoint20)
	(visible waypoint21 waypoint6)
	(visible waypoint6 waypoint21)
	(visible waypoint21 waypoint30)
	(visible waypoint30 waypoint21)
	(visible waypoint21 waypoint36)
	(visible waypoint36 waypoint21)
	(visible waypoint22 waypoint1)
	(visible waypoint1 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint12)
	(visible waypoint12 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint23 waypoint7)
	(visible waypoint7 waypoint23)
	(visible waypoint23 waypoint27)
	(visible waypoint27 waypoint23)
	(visible waypoint23 waypoint31)
	(visible waypoint31 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint23 waypoint35)
	(visible waypoint35 waypoint23)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint24 waypoint34)
	(visible waypoint34 waypoint24)
	(visible waypoint25 waypoint2)
	(visible waypoint2 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint25 waypoint24)
	(visible waypoint24 waypoint25)
	(visible waypoint25 waypoint28)
	(visible waypoint28 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint37)
	(visible waypoint37 waypoint25)
	(visible waypoint25 waypoint39)
	(visible waypoint39 waypoint25)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint17)
	(visible waypoint17 waypoint26)
	(visible waypoint26 waypoint21)
	(visible waypoint21 waypoint26)
	(visible waypoint26 waypoint35)
	(visible waypoint35 waypoint26)
	(visible waypoint27 waypoint8)
	(visible waypoint8 waypoint27)
	(visible waypoint27 waypoint12)
	(visible waypoint12 waypoint27)
	(visible waypoint27 waypoint14)
	(visible waypoint14 waypoint27)
	(visible waypoint27 waypoint25)
	(visible waypoint25 waypoint27)
	(visible waypoint27 waypoint28)
	(visible waypoint28 waypoint27)
	(visible waypoint27 waypoint30)
	(visible waypoint30 waypoint27)
	(visible waypoint28 waypoint2)
	(visible waypoint2 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint17)
	(visible waypoint17 waypoint28)
	(visible waypoint28 waypoint23)
	(visible waypoint23 waypoint28)
	(visible waypoint29 waypoint6)
	(visible waypoint6 waypoint29)
	(visible waypoint29 waypoint14)
	(visible waypoint14 waypoint29)
	(visible waypoint29 waypoint20)
	(visible waypoint20 waypoint29)
	(visible waypoint30 waypoint5)
	(visible waypoint5 waypoint30)
	(visible waypoint30 waypoint6)
	(visible waypoint6 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint16)
	(visible waypoint16 waypoint30)
	(visible waypoint30 waypoint23)
	(visible waypoint23 waypoint30)
	(visible waypoint30 waypoint26)
	(visible waypoint26 waypoint30)
	(visible waypoint30 waypoint31)
	(visible waypoint31 waypoint30)
	(visible waypoint31 waypoint13)
	(visible waypoint13 waypoint31)
	(visible waypoint31 waypoint34)
	(visible waypoint34 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint14)
	(visible waypoint14 waypoint32)
	(visible waypoint32 waypoint17)
	(visible waypoint17 waypoint32)
	(visible waypoint32 waypoint33)
	(visible waypoint33 waypoint32)
	(visible waypoint33 waypoint7)
	(visible waypoint7 waypoint33)
	(visible waypoint33 waypoint20)
	(visible waypoint20 waypoint33)
	(visible waypoint33 waypoint24)
	(visible waypoint24 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint36)
	(visible waypoint36 waypoint33)
	(visible waypoint34 waypoint2)
	(visible waypoint2 waypoint34)
	(visible waypoint34 waypoint37)
	(visible waypoint37 waypoint34)
	(visible waypoint34 waypoint39)
	(visible waypoint39 waypoint34)
	(visible waypoint35 waypoint27)
	(visible waypoint27 waypoint35)
	(visible waypoint35 waypoint30)
	(visible waypoint30 waypoint35)
	(visible waypoint36 waypoint19)
	(visible waypoint19 waypoint36)
	(visible waypoint36 waypoint20)
	(visible waypoint20 waypoint36)
	(visible waypoint36 waypoint23)
	(visible waypoint23 waypoint36)
	(visible waypoint36 waypoint29)
	(visible waypoint29 waypoint36)
	(visible waypoint36 waypoint31)
	(visible waypoint31 waypoint36)
	(visible waypoint37 waypoint9)
	(visible waypoint9 waypoint37)
	(visible waypoint37 waypoint13)
	(visible waypoint13 waypoint37)
	(visible waypoint37 waypoint19)
	(visible waypoint19 waypoint37)
	(visible waypoint37 waypoint20)
	(visible waypoint20 waypoint37)
	(visible waypoint37 waypoint33)
	(visible waypoint33 waypoint37)
	(visible waypoint37 waypoint39)
	(visible waypoint39 waypoint37)
	(visible waypoint38 waypoint5)
	(visible waypoint5 waypoint38)
	(visible waypoint38 waypoint6)
	(visible waypoint6 waypoint38)
	(visible waypoint38 waypoint22)
	(visible waypoint22 waypoint38)
	(visible waypoint38 waypoint39)
	(visible waypoint39 waypoint38)
	(visible waypoint39 waypoint1)
	(visible waypoint1 waypoint39)
	(visible waypoint39 waypoint2)
	(visible waypoint2 waypoint39)
	(visible waypoint39 waypoint6)
	(visible waypoint6 waypoint39)
	(visible waypoint39 waypoint16)
	(visible waypoint16 waypoint39)
	(visible waypoint39 waypoint20)
	(visible waypoint20 waypoint39)
	(visible waypoint39 waypoint23)
	(visible waypoint23 waypoint39)
	(visible waypoint39 waypoint33)
	(visible waypoint33 waypoint39)
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_lander general waypoint2)
	(channel_free general)
	(at rover0 waypoint4)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint4 waypoint5)
	(can_traverse rover0 waypoint5 waypoint4)
	(can_traverse rover0 waypoint4 waypoint13)
	(can_traverse rover0 waypoint13 waypoint4)
	(can_traverse rover0 waypoint4 waypoint20)
	(can_traverse rover0 waypoint20 waypoint4)
	(can_traverse rover0 waypoint4 waypoint22)
	(can_traverse rover0 waypoint22 waypoint4)
	(can_traverse rover0 waypoint5 waypoint1)
	(can_traverse rover0 waypoint1 waypoint5)
	(can_traverse rover0 waypoint5 waypoint8)
	(can_traverse rover0 waypoint8 waypoint5)
	(can_traverse rover0 waypoint5 waypoint10)
	(can_traverse rover0 waypoint10 waypoint5)
	(can_traverse rover0 waypoint5 waypoint12)
	(can_traverse rover0 waypoint12 waypoint5)
	(can_traverse rover0 waypoint5 waypoint15)
	(can_traverse rover0 waypoint15 waypoint5)
	(can_traverse rover0 waypoint5 waypoint16)
	(can_traverse rover0 waypoint16 waypoint5)
	(can_traverse rover0 waypoint5 waypoint30)
	(can_traverse rover0 waypoint30 waypoint5)
	(can_traverse rover0 waypoint5 waypoint32)
	(can_traverse rover0 waypoint32 waypoint5)
	(can_traverse rover0 waypoint5 waypoint37)
	(can_traverse rover0 waypoint37 waypoint5)
	(can_traverse rover0 waypoint13 waypoint6)
	(can_traverse rover0 waypoint6 waypoint13)
	(can_traverse rover0 waypoint13 waypoint9)
	(can_traverse rover0 waypoint9 waypoint13)
	(can_traverse rover0 waypoint13 waypoint14)
	(can_traverse rover0 waypoint14 waypoint13)
	(can_traverse rover0 waypoint13 waypoint17)
	(can_traverse rover0 waypoint17 waypoint13)
	(can_traverse rover0 waypoint13 waypoint23)
	(can_traverse rover0 waypoint23 waypoint13)
	(can_traverse rover0 waypoint13 waypoint25)
	(can_traverse rover0 waypoint25 waypoint13)
	(can_traverse rover0 waypoint13 waypoint31)
	(can_traverse rover0 waypoint31 waypoint13)
	(can_traverse rover0 waypoint13 waypoint34)
	(can_traverse rover0 waypoint34 waypoint13)
	(can_traverse rover0 waypoint20 waypoint11)
	(can_traverse rover0 waypoint11 waypoint20)
	(can_traverse rover0 waypoint20 waypoint19)
	(can_traverse rover0 waypoint19 waypoint20)
	(can_traverse rover0 waypoint20 waypoint29)
	(can_traverse rover0 waypoint29 waypoint20)
	(can_traverse rover0 waypoint20 waypoint33)
	(can_traverse rover0 waypoint33 waypoint20)
	(can_traverse rover0 waypoint20 waypoint39)
	(can_traverse rover0 waypoint39 waypoint20)
	(can_traverse rover0 waypoint22 waypoint38)
	(can_traverse rover0 waypoint38 waypoint22)
	(can_traverse rover0 waypoint8 waypoint0)
	(can_traverse rover0 waypoint0 waypoint8)
	(can_traverse rover0 waypoint8 waypoint27)
	(can_traverse rover0 waypoint27 waypoint8)
	(can_traverse rover0 waypoint12 waypoint3)
	(can_traverse rover0 waypoint3 waypoint12)
	(can_traverse rover0 waypoint12 waypoint36)
	(can_traverse rover0 waypoint36 waypoint12)
	(can_traverse rover0 waypoint15 waypoint7)
	(can_traverse rover0 waypoint7 waypoint15)
	(can_traverse rover0 waypoint15 waypoint26)
	(can_traverse rover0 waypoint26 waypoint15)
	(can_traverse rover0 waypoint15 waypoint28)
	(can_traverse rover0 waypoint28 waypoint15)
	(can_traverse rover0 waypoint16 waypoint18)
	(can_traverse rover0 waypoint18 waypoint16)
	(can_traverse rover0 waypoint30 waypoint21)
	(can_traverse rover0 waypoint21 waypoint30)
	(can_traverse rover0 waypoint6 waypoint24)
	(can_traverse rover0 waypoint24 waypoint6)
	(can_traverse rover0 waypoint14 waypoint2)
	(can_traverse rover0 waypoint2 waypoint14)
	(at rover1 waypoint16)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint16 waypoint0)
	(can_traverse rover1 waypoint0 waypoint16)
	(can_traverse rover1 waypoint16 waypoint5)
	(can_traverse rover1 waypoint5 waypoint16)
	(can_traverse rover1 waypoint16 waypoint8)
	(can_traverse rover1 waypoint8 waypoint16)
	(can_traverse rover1 waypoint16 waypoint13)
	(can_traverse rover1 waypoint13 waypoint16)
	(can_traverse rover1 waypoint16 waypoint18)
	(can_traverse rover1 waypoint18 waypoint16)
	(can_traverse rover1 waypoint16 waypoint30)
	(can_traverse rover1 waypoint30 waypoint16)
	(can_traverse rover1 waypoint16 waypoint39)
	(can_traverse rover1 waypoint39 waypoint16)
	(can_traverse rover1 waypoint0 waypoint6)
	(can_traverse rover1 waypoint6 waypoint0)
	(can_traverse rover1 waypoint0 waypoint10)
	(can_traverse rover1 waypoint10 waypoint0)
	(can_traverse rover1 waypoint0 waypoint14)
	(can_traverse rover1 waypoint14 waypoint0)
	(can_traverse rover1 waypoint0 waypoint37)
	(can_traverse rover1 waypoint37 waypoint0)
	(can_traverse rover1 waypoint5 waypoint3)
	(can_traverse rover1 waypoint3 waypoint5)
	(can_traverse rover1 waypoint5 waypoint9)
	(can_traverse rover1 waypoint9 waypoint5)
	(can_traverse rover1 waypoint5 waypoint15)
	(can_traverse rover1 waypoint15 waypoint5)
	(can_traverse rover1 waypoint5 waypoint32)
	(can_traverse rover1 waypoint32 waypoint5)
	(can_traverse rover1 waypoint5 waypoint34)
	(can_traverse rover1 waypoint34 waypoint5)
	(can_traverse rover1 waypoint5 waypoint38)
	(can_traverse rover1 waypoint38 waypoint5)
	(can_traverse rover1 waypoint8 waypoint7)
	(can_traverse rover1 waypoint7 waypoint8)
	(can_traverse rover1 waypoint8 waypoint12)
	(can_traverse rover1 waypoint12 waypoint8)
	(can_traverse rover1 waypoint8 waypoint27)
	(can_traverse rover1 waypoint27 waypoint8)
	(can_traverse rover1 waypoint13 waypoint4)
	(can_traverse rover1 waypoint4 waypoint13)
	(can_traverse rover1 waypoint13 waypoint22)
	(can_traverse rover1 waypoint22 waypoint13)
	(can_traverse rover1 waypoint13 waypoint23)
	(can_traverse rover1 waypoint23 waypoint13)
	(can_traverse rover1 waypoint13 waypoint25)
	(can_traverse rover1 waypoint25 waypoint13)
	(can_traverse rover1 waypoint13 waypoint31)
	(can_traverse rover1 waypoint31 waypoint13)
	(can_traverse rover1 waypoint30 waypoint20)
	(can_traverse rover1 waypoint20 waypoint30)
	(can_traverse rover1 waypoint30 waypoint21)
	(can_traverse rover1 waypoint21 waypoint30)
	(can_traverse rover1 waypoint30 waypoint35)
	(can_traverse rover1 waypoint35 waypoint30)
	(can_traverse rover1 waypoint39 waypoint2)
	(can_traverse rover1 waypoint2 waypoint39)
	(can_traverse rover1 waypoint39 waypoint33)
	(can_traverse rover1 waypoint33 waypoint39)
	(can_traverse rover1 waypoint6 waypoint24)
	(can_traverse rover1 waypoint24 waypoint6)
	(can_traverse rover1 waypoint10 waypoint19)
	(can_traverse rover1 waypoint19 waypoint10)
	(can_traverse rover1 waypoint14 waypoint17)
	(can_traverse rover1 waypoint17 waypoint14)
	(can_traverse rover1 waypoint14 waypoint26)
	(can_traverse rover1 waypoint26 waypoint14)
	(can_traverse rover1 waypoint14 waypoint29)
	(can_traverse rover1 waypoint29 waypoint14)
	(can_traverse rover1 waypoint37 waypoint1)
	(can_traverse rover1 waypoint1 waypoint37)
	(can_traverse rover1 waypoint9 waypoint11)
	(can_traverse rover1 waypoint11 waypoint9)
	(can_traverse rover1 waypoint9 waypoint28)
	(can_traverse rover1 waypoint28 waypoint9)
	(can_traverse rover1 waypoint12 waypoint36)
	(can_traverse rover1 waypoint36 waypoint12)
	(at rover2 waypoint3)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint3 waypoint0)
	(can_traverse rover2 waypoint0 waypoint3)
	(can_traverse rover2 waypoint3 waypoint5)
	(can_traverse rover2 waypoint5 waypoint3)
	(can_traverse rover2 waypoint3 waypoint6)
	(can_traverse rover2 waypoint6 waypoint3)
	(can_traverse rover2 waypoint3 waypoint7)
	(can_traverse rover2 waypoint7 waypoint3)
	(can_traverse rover2 waypoint3 waypoint10)
	(can_traverse rover2 waypoint10 waypoint3)
	(can_traverse rover2 waypoint3 waypoint11)
	(can_traverse rover2 waypoint11 waypoint3)
	(can_traverse rover2 waypoint3 waypoint14)
	(can_traverse rover2 waypoint14 waypoint3)
	(can_traverse rover2 waypoint3 waypoint20)
	(can_traverse rover2 waypoint20 waypoint3)
	(can_traverse rover2 waypoint0 waypoint16)
	(can_traverse rover2 waypoint16 waypoint0)
	(can_traverse rover2 waypoint0 waypoint37)
	(can_traverse rover2 waypoint37 waypoint0)
	(can_traverse rover2 waypoint5 waypoint9)
	(can_traverse rover2 waypoint9 waypoint5)
	(can_traverse rover2 waypoint5 waypoint12)
	(can_traverse rover2 waypoint12 waypoint5)
	(can_traverse rover2 waypoint5 waypoint15)
	(can_traverse rover2 waypoint15 waypoint5)
	(can_traverse rover2 waypoint5 waypoint27)
	(can_traverse rover2 waypoint27 waypoint5)
	(can_traverse rover2 waypoint5 waypoint32)
	(can_traverse rover2 waypoint32 waypoint5)
	(can_traverse rover2 waypoint5 waypoint34)
	(can_traverse rover2 waypoint34 waypoint5)
	(can_traverse rover2 waypoint5 waypoint38)
	(can_traverse rover2 waypoint38 waypoint5)
	(can_traverse rover2 waypoint6 waypoint13)
	(can_traverse rover2 waypoint13 waypoint6)
	(can_traverse rover2 waypoint6 waypoint18)
	(can_traverse rover2 waypoint18 waypoint6)
	(can_traverse rover2 waypoint6 waypoint29)
	(can_traverse rover2 waypoint29 waypoint6)
	(can_traverse rover2 waypoint6 waypoint39)
	(can_traverse rover2 waypoint39 waypoint6)
	(can_traverse rover2 waypoint7 waypoint2)
	(can_traverse rover2 waypoint2 waypoint7)
	(can_traverse rover2 waypoint7 waypoint8)
	(can_traverse rover2 waypoint8 waypoint7)
	(can_traverse rover2 waypoint7 waypoint23)
	(can_traverse rover2 waypoint23 waypoint7)
	(can_traverse rover2 waypoint7 waypoint30)
	(can_traverse rover2 waypoint30 waypoint7)
	(can_traverse rover2 waypoint7 waypoint33)
	(can_traverse rover2 waypoint33 waypoint7)
	(can_traverse rover2 waypoint10 waypoint4)
	(can_traverse rover2 waypoint4 waypoint10)
	(can_traverse rover2 waypoint10 waypoint19)
	(can_traverse rover2 waypoint19 waypoint10)
	(can_traverse rover2 waypoint11 waypoint31)
	(can_traverse rover2 waypoint31 waypoint11)
	(can_traverse rover2 waypoint14 waypoint1)
	(can_traverse rover2 waypoint1 waypoint14)
	(can_traverse rover2 waypoint14 waypoint17)
	(can_traverse rover2 waypoint17 waypoint14)
	(can_traverse rover2 waypoint14 waypoint24)
	(can_traverse rover2 waypoint24 waypoint14)
	(can_traverse rover2 waypoint20 waypoint36)
	(can_traverse rover2 waypoint36 waypoint20)
	(can_traverse rover2 waypoint37 waypoint25)
	(can_traverse rover2 waypoint25 waypoint37)
	(can_traverse rover2 waypoint9 waypoint28)
	(can_traverse rover2 waypoint28 waypoint9)
	(can_traverse rover2 waypoint12 waypoint22)
	(can_traverse rover2 waypoint22 waypoint12)
	(can_traverse rover2 waypoint15 waypoint26)
	(can_traverse rover2 waypoint26 waypoint15)
	(can_traverse rover2 waypoint27 waypoint35)
	(can_traverse rover2 waypoint35 waypoint27)
	(at rover3 waypoint4)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint4 waypoint5)
	(can_traverse rover3 waypoint5 waypoint4)
	(can_traverse rover3 waypoint4 waypoint10)
	(can_traverse rover3 waypoint10 waypoint4)
	(can_traverse rover3 waypoint4 waypoint12)
	(can_traverse rover3 waypoint12 waypoint4)
	(can_traverse rover3 waypoint4 waypoint13)
	(can_traverse rover3 waypoint13 waypoint4)
	(can_traverse rover3 waypoint4 waypoint20)
	(can_traverse rover3 waypoint20 waypoint4)
	(can_traverse rover3 waypoint4 waypoint22)
	(can_traverse rover3 waypoint22 waypoint4)
	(can_traverse rover3 waypoint5 waypoint3)
	(can_traverse rover3 waypoint3 waypoint5)
	(can_traverse rover3 waypoint5 waypoint8)
	(can_traverse rover3 waypoint8 waypoint5)
	(can_traverse rover3 waypoint5 waypoint9)
	(can_traverse rover3 waypoint9 waypoint5)
	(can_traverse rover3 waypoint5 waypoint15)
	(can_traverse rover3 waypoint15 waypoint5)
	(can_traverse rover3 waypoint5 waypoint16)
	(can_traverse rover3 waypoint16 waypoint5)
	(can_traverse rover3 waypoint5 waypoint30)
	(can_traverse rover3 waypoint30 waypoint5)
	(can_traverse rover3 waypoint5 waypoint32)
	(can_traverse rover3 waypoint32 waypoint5)
	(can_traverse rover3 waypoint5 waypoint38)
	(can_traverse rover3 waypoint38 waypoint5)
	(can_traverse rover3 waypoint10 waypoint19)
	(can_traverse rover3 waypoint19 waypoint10)
	(can_traverse rover3 waypoint12 waypoint1)
	(can_traverse rover3 waypoint1 waypoint12)
	(can_traverse rover3 waypoint12 waypoint6)
	(can_traverse rover3 waypoint6 waypoint12)
	(can_traverse rover3 waypoint12 waypoint17)
	(can_traverse rover3 waypoint17 waypoint12)
	(can_traverse rover3 waypoint12 waypoint27)
	(can_traverse rover3 waypoint27 waypoint12)
	(can_traverse rover3 waypoint12 waypoint36)
	(can_traverse rover3 waypoint36 waypoint12)
	(can_traverse rover3 waypoint13 waypoint14)
	(can_traverse rover3 waypoint14 waypoint13)
	(can_traverse rover3 waypoint13 waypoint25)
	(can_traverse rover3 waypoint25 waypoint13)
	(can_traverse rover3 waypoint13 waypoint31)
	(can_traverse rover3 waypoint31 waypoint13)
	(can_traverse rover3 waypoint13 waypoint34)
	(can_traverse rover3 waypoint34 waypoint13)
	(can_traverse rover3 waypoint13 waypoint37)
	(can_traverse rover3 waypoint37 waypoint13)
	(can_traverse rover3 waypoint20 waypoint29)
	(can_traverse rover3 waypoint29 waypoint20)
	(can_traverse rover3 waypoint20 waypoint39)
	(can_traverse rover3 waypoint39 waypoint20)
	(can_traverse rover3 waypoint22 waypoint24)
	(can_traverse rover3 waypoint24 waypoint22)
	(can_traverse rover3 waypoint3 waypoint0)
	(can_traverse rover3 waypoint0 waypoint3)
	(can_traverse rover3 waypoint3 waypoint7)
	(can_traverse rover3 waypoint7 waypoint3)
	(can_traverse rover3 waypoint3 waypoint11)
	(can_traverse rover3 waypoint11 waypoint3)
	(can_traverse rover3 waypoint8 waypoint18)
	(can_traverse rover3 waypoint18 waypoint8)
	(can_traverse rover3 waypoint9 waypoint28)
	(can_traverse rover3 waypoint28 waypoint9)
	(can_traverse rover3 waypoint9 waypoint33)
	(can_traverse rover3 waypoint33 waypoint9)
	(can_traverse rover3 waypoint15 waypoint26)
	(can_traverse rover3 waypoint26 waypoint15)
	(can_traverse rover3 waypoint30 waypoint21)
	(can_traverse rover3 waypoint21 waypoint30)
	(can_traverse rover3 waypoint30 waypoint35)
	(can_traverse rover3 waypoint35 waypoint30)
	(can_traverse rover3 waypoint17 waypoint2)
	(can_traverse rover3 waypoint2 waypoint17)
	(can_traverse rover3 waypoint14 waypoint23)
	(can_traverse rover3 waypoint23 waypoint14)
	(at rover4 waypoint0)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint0 waypoint3)
	(can_traverse rover4 waypoint3 waypoint0)
	(can_traverse rover4 waypoint0 waypoint8)
	(can_traverse rover4 waypoint8 waypoint0)
	(can_traverse rover4 waypoint0 waypoint10)
	(can_traverse rover4 waypoint10 waypoint0)
	(can_traverse rover4 waypoint0 waypoint14)
	(can_traverse rover4 waypoint14 waypoint0)
	(can_traverse rover4 waypoint0 waypoint16)
	(can_traverse rover4 waypoint16 waypoint0)
	(can_traverse rover4 waypoint3 waypoint5)
	(can_traverse rover4 waypoint5 waypoint3)
	(can_traverse rover4 waypoint3 waypoint7)
	(can_traverse rover4 waypoint7 waypoint3)
	(can_traverse rover4 waypoint3 waypoint12)
	(can_traverse rover4 waypoint12 waypoint3)
	(can_traverse rover4 waypoint3 waypoint20)
	(can_traverse rover4 waypoint20 waypoint3)
	(can_traverse rover4 waypoint8 waypoint18)
	(can_traverse rover4 waypoint18 waypoint8)
	(can_traverse rover4 waypoint8 waypoint22)
	(can_traverse rover4 waypoint22 waypoint8)
	(can_traverse rover4 waypoint10 waypoint19)
	(can_traverse rover4 waypoint19 waypoint10)
	(can_traverse rover4 waypoint14 waypoint1)
	(can_traverse rover4 waypoint1 waypoint14)
	(can_traverse rover4 waypoint14 waypoint13)
	(can_traverse rover4 waypoint13 waypoint14)
	(can_traverse rover4 waypoint14 waypoint15)
	(can_traverse rover4 waypoint15 waypoint14)
	(can_traverse rover4 waypoint14 waypoint17)
	(can_traverse rover4 waypoint17 waypoint14)
	(can_traverse rover4 waypoint14 waypoint24)
	(can_traverse rover4 waypoint24 waypoint14)
	(can_traverse rover4 waypoint14 waypoint26)
	(can_traverse rover4 waypoint26 waypoint14)
	(can_traverse rover4 waypoint14 waypoint29)
	(can_traverse rover4 waypoint29 waypoint14)
	(can_traverse rover4 waypoint14 waypoint30)
	(can_traverse rover4 waypoint30 waypoint14)
	(can_traverse rover4 waypoint14 waypoint32)
	(can_traverse rover4 waypoint32 waypoint14)
	(can_traverse rover4 waypoint14 waypoint38)
	(can_traverse rover4 waypoint38 waypoint14)
	(can_traverse rover4 waypoint16 waypoint39)
	(can_traverse rover4 waypoint39 waypoint16)
	(can_traverse rover4 waypoint5 waypoint4)
	(can_traverse rover4 waypoint4 waypoint5)
	(can_traverse rover4 waypoint5 waypoint27)
	(can_traverse rover4 waypoint27 waypoint5)
	(can_traverse rover4 waypoint5 waypoint34)
	(can_traverse rover4 waypoint34 waypoint5)
	(can_traverse rover4 waypoint7 waypoint2)
	(can_traverse rover4 waypoint2 waypoint7)
	(can_traverse rover4 waypoint7 waypoint9)
	(can_traverse rover4 waypoint9 waypoint7)
	(can_traverse rover4 waypoint7 waypoint25)
	(can_traverse rover4 waypoint25 waypoint7)
	(can_traverse rover4 waypoint7 waypoint33)
	(can_traverse rover4 waypoint33 waypoint7)
	(can_traverse rover4 waypoint12 waypoint36)
	(can_traverse rover4 waypoint36 waypoint12)
	(can_traverse rover4 waypoint20 waypoint37)
	(can_traverse rover4 waypoint37 waypoint20)
	(can_traverse rover4 waypoint18 waypoint6)
	(can_traverse rover4 waypoint6 waypoint18)
	(can_traverse rover4 waypoint13 waypoint31)
	(can_traverse rover4 waypoint31 waypoint13)
	(can_traverse rover4 waypoint15 waypoint28)
	(can_traverse rover4 waypoint28 waypoint15)
	(can_traverse rover4 waypoint26 waypoint21)
	(can_traverse rover4 waypoint21 waypoint26)
	(can_traverse rover4 waypoint26 waypoint35)
	(can_traverse rover4 waypoint35 waypoint26)
	(can_traverse rover4 waypoint39 waypoint23)
	(can_traverse rover4 waypoint23 waypoint39)
	(can_traverse rover4 waypoint9 waypoint11)
	(can_traverse rover4 waypoint11 waypoint9)
	(at rover5 waypoint10)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint10 waypoint0)
	(can_traverse rover5 waypoint0 waypoint10)
	(can_traverse rover5 waypoint10 waypoint4)
	(can_traverse rover5 waypoint4 waypoint10)
	(can_traverse rover5 waypoint10 waypoint19)
	(can_traverse rover5 waypoint19 waypoint10)
	(can_traverse rover5 waypoint0 waypoint6)
	(can_traverse rover5 waypoint6 waypoint0)
	(can_traverse rover5 waypoint0 waypoint8)
	(can_traverse rover5 waypoint8 waypoint0)
	(can_traverse rover5 waypoint0 waypoint14)
	(can_traverse rover5 waypoint14 waypoint0)
	(can_traverse rover5 waypoint0 waypoint16)
	(can_traverse rover5 waypoint16 waypoint0)
	(can_traverse rover5 waypoint0 waypoint37)
	(can_traverse rover5 waypoint37 waypoint0)
	(can_traverse rover5 waypoint4 waypoint12)
	(can_traverse rover5 waypoint12 waypoint4)
	(can_traverse rover5 waypoint4 waypoint13)
	(can_traverse rover5 waypoint13 waypoint4)
	(can_traverse rover5 waypoint4 waypoint20)
	(can_traverse rover5 waypoint20 waypoint4)
	(can_traverse rover5 waypoint4 waypoint22)
	(can_traverse rover5 waypoint22 waypoint4)
	(can_traverse rover5 waypoint19 waypoint36)
	(can_traverse rover5 waypoint36 waypoint19)
	(can_traverse rover5 waypoint6 waypoint3)
	(can_traverse rover5 waypoint3 waypoint6)
	(can_traverse rover5 waypoint6 waypoint18)
	(can_traverse rover5 waypoint18 waypoint6)
	(can_traverse rover5 waypoint6 waypoint21)
	(can_traverse rover5 waypoint21 waypoint6)
	(can_traverse rover5 waypoint6 waypoint24)
	(can_traverse rover5 waypoint24 waypoint6)
	(can_traverse rover5 waypoint6 waypoint29)
	(can_traverse rover5 waypoint29 waypoint6)
	(can_traverse rover5 waypoint6 waypoint38)
	(can_traverse rover5 waypoint38 waypoint6)
	(can_traverse rover5 waypoint6 waypoint39)
	(can_traverse rover5 waypoint39 waypoint6)
	(can_traverse rover5 waypoint8 waypoint5)
	(can_traverse rover5 waypoint5 waypoint8)
	(can_traverse rover5 waypoint14 waypoint1)
	(can_traverse rover5 waypoint1 waypoint14)
	(can_traverse rover5 waypoint14 waypoint2)
	(can_traverse rover5 waypoint2 waypoint14)
	(can_traverse rover5 waypoint14 waypoint15)
	(can_traverse rover5 waypoint15 waypoint14)
	(can_traverse rover5 waypoint14 waypoint23)
	(can_traverse rover5 waypoint23 waypoint14)
	(can_traverse rover5 waypoint14 waypoint26)
	(can_traverse rover5 waypoint26 waypoint14)
	(can_traverse rover5 waypoint14 waypoint27)
	(can_traverse rover5 waypoint27 waypoint14)
	(can_traverse rover5 waypoint14 waypoint30)
	(can_traverse rover5 waypoint30 waypoint14)
	(can_traverse rover5 waypoint14 waypoint32)
	(can_traverse rover5 waypoint32 waypoint14)
	(can_traverse rover5 waypoint14 waypoint33)
	(can_traverse rover5 waypoint33 waypoint14)
	(can_traverse rover5 waypoint37 waypoint9)
	(can_traverse rover5 waypoint9 waypoint37)
	(can_traverse rover5 waypoint37 waypoint34)
	(can_traverse rover5 waypoint34 waypoint37)
	(can_traverse rover5 waypoint12 waypoint17)
	(can_traverse rover5 waypoint17 waypoint12)
	(can_traverse rover5 waypoint13 waypoint25)
	(can_traverse rover5 waypoint25 waypoint13)
	(can_traverse rover5 waypoint13 waypoint31)
	(can_traverse rover5 waypoint31 waypoint13)
	(can_traverse rover5 waypoint20 waypoint11)
	(can_traverse rover5 waypoint11 waypoint20)
	(on_board camera0 rover3)
	(calibration_target camera0 objective9)
	(supports camera0 colour)
	(on_board camera1 rover3)
	(calibration_target camera1 objective2)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover4)
	(calibration_target camera2 objective3)
	(supports camera2 colour)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover1)
	(calibration_target camera3 objective8)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover5)
	(calibration_target camera4 objective1)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective6)
	(supports camera5 low_res)
	(on_board camera6 rover2)
	(calibration_target camera6 objective5)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover2)
	(calibration_target camera7 objective9)
	(supports camera7 high_res)
	(visible_from objective0 waypoint0)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint24)
	(visible_from objective1 waypoint25)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint18)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint17)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint26)
	(visible_from objective5 waypoint27)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint31)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint11)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint18)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint20)
	(visible_from objective6 waypoint21)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint6)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint8)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint10)
	(visible_from objective8 waypoint0)
	(visible_from objective8 waypoint1)
	(visible_from objective8 waypoint2)
	(visible_from objective8 waypoint3)
	(visible_from objective8 waypoint4)
	(visible_from objective8 waypoint5)
	(visible_from objective8 waypoint6)
	(visible_from objective8 waypoint7)
	(visible_from objective8 waypoint8)
	(visible_from objective8 waypoint9)
	(visible_from objective8 waypoint10)
	(visible_from objective8 waypoint11)
	(visible_from objective8 waypoint12)
	(visible_from objective8 waypoint13)
	(visible_from objective8 waypoint14)
	(visible_from objective8 waypoint15)
	(visible_from objective8 waypoint16)
	(visible_from objective8 waypoint17)
	(visible_from objective8 waypoint18)
	(visible_from objective8 waypoint19)
	(visible_from objective8 waypoint20)
	(visible_from objective8 waypoint21)
	(visible_from objective8 waypoint22)
	(visible_from objective8 waypoint23)
	(visible_from objective9 waypoint0)
	(visible_from objective9 waypoint1)
	(visible_from objective9 waypoint2)
	(visible_from objective9 waypoint3)
	(visible_from objective9 waypoint4)
	(visible_from objective9 waypoint5)
	(visible_from objective9 waypoint6)
	(visible_from objective9 waypoint7)
	(visible_from objective9 waypoint8)
	(visible_from objective9 waypoint9)
	(visible_from objective9 waypoint10)
	(visible_from objective9 waypoint11)
	(visible_from objective9 waypoint12)
	(visible_from objective9 waypoint13)
	(visible_from objective9 waypoint14)
	(visible_from objective9 waypoint15)
	(visible_from objective9 waypoint16)
	(visible_from objective9 waypoint17)
	(visible_from objective9 waypoint18)
	(visible_from objective9 waypoint19)
	(visible_from objective9 waypoint20)
	(visible_from objective9 waypoint21)
	(visible_from objective9 waypoint22)
	(visible_from objective9 waypoint23)
	(visible_from objective9 waypoint24)
	(visible_from objective9 waypoint25)
)

(:goal (and
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint38)
(communicated_rock_data waypoint14)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint25)
(communicated_image_data objective6 low_res)
(communicated_image_data objective9 high_res)
(communicated_image_data objective8 high_res)
(communicated_image_data objective3 high_res)
(communicated_image_data objective1 low_res)
	)
)

(:metric minimize (total-time))
)
