(define (problem roverprob2435) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint21)
	(visible waypoint21 waypoint0)
	(visible waypoint0 waypoint22)
	(visible waypoint22 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint6)
	(visible waypoint6 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint26)
	(visible waypoint26 waypoint1)
	(visible waypoint1 waypoint27)
	(visible waypoint27 waypoint1)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint11)
	(visible waypoint11 waypoint2)
	(visible waypoint2 waypoint21)
	(visible waypoint21 waypoint2)
	(visible waypoint2 waypoint24)
	(visible waypoint24 waypoint2)
	(visible waypoint2 waypoint27)
	(visible waypoint27 waypoint2)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint13)
	(visible waypoint13 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint3)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint9)
	(visible waypoint9 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint14)
	(visible waypoint14 waypoint4)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint27)
	(visible waypoint27 waypoint5)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint6)
	(visible waypoint6 waypoint27)
	(visible waypoint27 waypoint6)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint23)
	(visible waypoint23 waypoint7)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint26)
	(visible waypoint26 waypoint8)
	(visible waypoint8 waypoint28)
	(visible waypoint28 waypoint8)
	(visible waypoint9 waypoint1)
	(visible waypoint1 waypoint9)
	(visible waypoint9 waypoint10)
	(visible waypoint10 waypoint9)
	(visible waypoint9 waypoint20)
	(visible waypoint20 waypoint9)
	(visible waypoint9 waypoint25)
	(visible waypoint25 waypoint9)
	(visible waypoint10 waypoint1)
	(visible waypoint1 waypoint10)
	(visible waypoint10 waypoint7)
	(visible waypoint7 waypoint10)
	(visible waypoint10 waypoint12)
	(visible waypoint12 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint18)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint27)
	(visible waypoint27 waypoint10)
	(visible waypoint10 waypoint28)
	(visible waypoint28 waypoint10)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint10)
	(visible waypoint10 waypoint11)
	(visible waypoint11 waypoint18)
	(visible waypoint18 waypoint11)
	(visible waypoint12 waypoint3)
	(visible waypoint3 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint23)
	(visible waypoint23 waypoint12)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint15)
	(visible waypoint15 waypoint13)
	(visible waypoint13 waypoint21)
	(visible waypoint21 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint25)
	(visible waypoint25 waypoint15)
	(visible waypoint15 waypoint26)
	(visible waypoint26 waypoint15)
	(visible waypoint15 waypoint28)
	(visible waypoint28 waypoint15)
	(visible waypoint16 waypoint10)
	(visible waypoint10 waypoint16)
	(visible waypoint16 waypoint11)
	(visible waypoint11 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint14)
	(visible waypoint14 waypoint16)
	(visible waypoint16 waypoint17)
	(visible waypoint17 waypoint16)
	(visible waypoint16 waypoint18)
	(visible waypoint18 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint17 waypoint1)
	(visible waypoint1 waypoint17)
	(visible waypoint17 waypoint4)
	(visible waypoint4 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint20)
	(visible waypoint20 waypoint17)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint23)
	(visible waypoint23 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint19 waypoint0)
	(visible waypoint0 waypoint19)
	(visible waypoint19 waypoint2)
	(visible waypoint2 waypoint19)
	(visible waypoint19 waypoint9)
	(visible waypoint9 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint18)
	(visible waypoint18 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint23)
	(visible waypoint23 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint21 waypoint4)
	(visible waypoint4 waypoint21)
	(visible waypoint21 waypoint5)
	(visible waypoint5 waypoint21)
	(visible waypoint21 waypoint12)
	(visible waypoint12 waypoint21)
	(visible waypoint21 waypoint14)
	(visible waypoint14 waypoint21)
	(visible waypoint21 waypoint15)
	(visible waypoint15 waypoint21)
	(visible waypoint21 waypoint18)
	(visible waypoint18 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint24)
	(visible waypoint24 waypoint21)
	(visible waypoint21 waypoint26)
	(visible waypoint26 waypoint21)
	(visible waypoint22 waypoint2)
	(visible waypoint2 waypoint22)
	(visible waypoint22 waypoint26)
	(visible waypoint26 waypoint22)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint17)
	(visible waypoint17 waypoint23)
	(visible waypoint24 waypoint0)
	(visible waypoint0 waypoint24)
	(visible waypoint24 waypoint1)
	(visible waypoint1 waypoint24)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint25 waypoint0)
	(visible waypoint0 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint26 waypoint2)
	(visible waypoint2 waypoint26)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint29)
	(visible waypoint29 waypoint26)
	(visible waypoint27 waypoint9)
	(visible waypoint9 waypoint27)
	(visible waypoint27 waypoint25)
	(visible waypoint25 waypoint27)
	(visible waypoint27 waypoint28)
	(visible waypoint28 waypoint27)
	(visible waypoint28 waypoint3)
	(visible waypoint3 waypoint28)
	(visible waypoint28 waypoint5)
	(visible waypoint5 waypoint28)
	(visible waypoint28 waypoint9)
	(visible waypoint9 waypoint28)
	(visible waypoint28 waypoint18)
	(visible waypoint18 waypoint28)
	(visible waypoint29 waypoint0)
	(visible waypoint0 waypoint29)
	(visible waypoint29 waypoint20)
	(visible waypoint20 waypoint29)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_rock_sample waypoint18)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint27)
	(at_lander general waypoint17)
	(channel_free general)
	(at rover0 waypoint2)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(can_traverse rover0 waypoint2 waypoint4)
	(can_traverse rover0 waypoint4 waypoint2)
	(can_traverse rover0 waypoint2 waypoint5)
	(can_traverse rover0 waypoint5 waypoint2)
	(can_traverse rover0 waypoint2 waypoint6)
	(can_traverse rover0 waypoint6 waypoint2)
	(can_traverse rover0 waypoint2 waypoint11)
	(can_traverse rover0 waypoint11 waypoint2)
	(can_traverse rover0 waypoint2 waypoint19)
	(can_traverse rover0 waypoint19 waypoint2)
	(can_traverse rover0 waypoint2 waypoint22)
	(can_traverse rover0 waypoint22 waypoint2)
	(can_traverse rover0 waypoint2 waypoint24)
	(can_traverse rover0 waypoint24 waypoint2)
	(can_traverse rover0 waypoint2 waypoint27)
	(can_traverse rover0 waypoint27 waypoint2)
	(can_traverse rover0 waypoint4 waypoint8)
	(can_traverse rover0 waypoint8 waypoint4)
	(can_traverse rover0 waypoint4 waypoint9)
	(can_traverse rover0 waypoint9 waypoint4)
	(can_traverse rover0 waypoint4 waypoint13)
	(can_traverse rover0 waypoint13 waypoint4)
	(can_traverse rover0 waypoint4 waypoint17)
	(can_traverse rover0 waypoint17 waypoint4)
	(can_traverse rover0 waypoint4 waypoint21)
	(can_traverse rover0 waypoint21 waypoint4)
	(can_traverse rover0 waypoint5 waypoint7)
	(can_traverse rover0 waypoint7 waypoint5)
	(can_traverse rover0 waypoint5 waypoint28)
	(can_traverse rover0 waypoint28 waypoint5)
	(can_traverse rover0 waypoint6 waypoint14)
	(can_traverse rover0 waypoint14 waypoint6)
	(can_traverse rover0 waypoint6 waypoint25)
	(can_traverse rover0 waypoint25 waypoint6)
	(can_traverse rover0 waypoint11 waypoint10)
	(can_traverse rover0 waypoint10 waypoint11)
	(can_traverse rover0 waypoint11 waypoint16)
	(can_traverse rover0 waypoint16 waypoint11)
	(can_traverse rover0 waypoint19 waypoint0)
	(can_traverse rover0 waypoint0 waypoint19)
	(can_traverse rover0 waypoint19 waypoint12)
	(can_traverse rover0 waypoint12 waypoint19)
	(can_traverse rover0 waypoint19 waypoint18)
	(can_traverse rover0 waypoint18 waypoint19)
	(can_traverse rover0 waypoint22 waypoint26)
	(can_traverse rover0 waypoint26 waypoint22)
	(can_traverse rover0 waypoint24 waypoint1)
	(can_traverse rover0 waypoint1 waypoint24)
	(can_traverse rover0 waypoint9 waypoint20)
	(can_traverse rover0 waypoint20 waypoint9)
	(can_traverse rover0 waypoint13 waypoint15)
	(can_traverse rover0 waypoint15 waypoint13)
	(can_traverse rover0 waypoint7 waypoint3)
	(can_traverse rover0 waypoint3 waypoint7)
	(can_traverse rover0 waypoint7 waypoint23)
	(can_traverse rover0 waypoint23 waypoint7)
	(at rover1 waypoint5)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint5 waypoint1)
	(can_traverse rover1 waypoint1 waypoint5)
	(can_traverse rover1 waypoint5 waypoint2)
	(can_traverse rover1 waypoint2 waypoint5)
	(can_traverse rover1 waypoint5 waypoint8)
	(can_traverse rover1 waypoint8 waypoint5)
	(can_traverse rover1 waypoint5 waypoint21)
	(can_traverse rover1 waypoint21 waypoint5)
	(can_traverse rover1 waypoint5 waypoint24)
	(can_traverse rover1 waypoint24 waypoint5)
	(can_traverse rover1 waypoint5 waypoint27)
	(can_traverse rover1 waypoint27 waypoint5)
	(can_traverse rover1 waypoint1 waypoint0)
	(can_traverse rover1 waypoint0 waypoint1)
	(can_traverse rover1 waypoint1 waypoint6)
	(can_traverse rover1 waypoint6 waypoint1)
	(can_traverse rover1 waypoint1 waypoint9)
	(can_traverse rover1 waypoint9 waypoint1)
	(can_traverse rover1 waypoint1 waypoint10)
	(can_traverse rover1 waypoint10 waypoint1)
	(can_traverse rover1 waypoint1 waypoint16)
	(can_traverse rover1 waypoint16 waypoint1)
	(can_traverse rover1 waypoint1 waypoint17)
	(can_traverse rover1 waypoint17 waypoint1)
	(can_traverse rover1 waypoint1 waypoint26)
	(can_traverse rover1 waypoint26 waypoint1)
	(can_traverse rover1 waypoint2 waypoint4)
	(can_traverse rover1 waypoint4 waypoint2)
	(can_traverse rover1 waypoint2 waypoint11)
	(can_traverse rover1 waypoint11 waypoint2)
	(can_traverse rover1 waypoint2 waypoint18)
	(can_traverse rover1 waypoint18 waypoint2)
	(can_traverse rover1 waypoint2 waypoint19)
	(can_traverse rover1 waypoint19 waypoint2)
	(can_traverse rover1 waypoint2 waypoint22)
	(can_traverse rover1 waypoint22 waypoint2)
	(can_traverse rover1 waypoint8 waypoint28)
	(can_traverse rover1 waypoint28 waypoint8)
	(can_traverse rover1 waypoint21 waypoint12)
	(can_traverse rover1 waypoint12 waypoint21)
	(can_traverse rover1 waypoint21 waypoint13)
	(can_traverse rover1 waypoint13 waypoint21)
	(can_traverse rover1 waypoint21 waypoint14)
	(can_traverse rover1 waypoint14 waypoint21)
	(can_traverse rover1 waypoint21 waypoint15)
	(can_traverse rover1 waypoint15 waypoint21)
	(can_traverse rover1 waypoint27 waypoint25)
	(can_traverse rover1 waypoint25 waypoint27)
	(can_traverse rover1 waypoint0 waypoint20)
	(can_traverse rover1 waypoint20 waypoint0)
	(can_traverse rover1 waypoint0 waypoint29)
	(can_traverse rover1 waypoint29 waypoint0)
	(can_traverse rover1 waypoint10 waypoint7)
	(can_traverse rover1 waypoint7 waypoint10)
	(can_traverse rover1 waypoint10 waypoint23)
	(can_traverse rover1 waypoint23 waypoint10)
	(can_traverse rover1 waypoint26 waypoint3)
	(can_traverse rover1 waypoint3 waypoint26)
	(at rover2 waypoint18)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint18 waypoint0)
	(can_traverse rover2 waypoint0 waypoint18)
	(can_traverse rover2 waypoint18 waypoint6)
	(can_traverse rover2 waypoint6 waypoint18)
	(can_traverse rover2 waypoint18 waypoint10)
	(can_traverse rover2 waypoint10 waypoint18)
	(can_traverse rover2 waypoint18 waypoint16)
	(can_traverse rover2 waypoint16 waypoint18)
	(can_traverse rover2 waypoint18 waypoint17)
	(can_traverse rover2 waypoint17 waypoint18)
	(can_traverse rover2 waypoint18 waypoint21)
	(can_traverse rover2 waypoint21 waypoint18)
	(can_traverse rover2 waypoint18 waypoint23)
	(can_traverse rover2 waypoint23 waypoint18)
	(can_traverse rover2 waypoint18 waypoint24)
	(can_traverse rover2 waypoint24 waypoint18)
	(can_traverse rover2 waypoint18 waypoint28)
	(can_traverse rover2 waypoint28 waypoint18)
	(can_traverse rover2 waypoint0 waypoint1)
	(can_traverse rover2 waypoint1 waypoint0)
	(can_traverse rover2 waypoint0 waypoint8)
	(can_traverse rover2 waypoint8 waypoint0)
	(can_traverse rover2 waypoint0 waypoint15)
	(can_traverse rover2 waypoint15 waypoint0)
	(can_traverse rover2 waypoint0 waypoint19)
	(can_traverse rover2 waypoint19 waypoint0)
	(can_traverse rover2 waypoint0 waypoint22)
	(can_traverse rover2 waypoint22 waypoint0)
	(can_traverse rover2 waypoint0 waypoint25)
	(can_traverse rover2 waypoint25 waypoint0)
	(can_traverse rover2 waypoint6 waypoint2)
	(can_traverse rover2 waypoint2 waypoint6)
	(can_traverse rover2 waypoint6 waypoint4)
	(can_traverse rover2 waypoint4 waypoint6)
	(can_traverse rover2 waypoint6 waypoint11)
	(can_traverse rover2 waypoint11 waypoint6)
	(can_traverse rover2 waypoint6 waypoint27)
	(can_traverse rover2 waypoint27 waypoint6)
	(can_traverse rover2 waypoint10 waypoint9)
	(can_traverse rover2 waypoint9 waypoint10)
	(can_traverse rover2 waypoint10 waypoint13)
	(can_traverse rover2 waypoint13 waypoint10)
	(can_traverse rover2 waypoint16 waypoint12)
	(can_traverse rover2 waypoint12 waypoint16)
	(can_traverse rover2 waypoint16 waypoint14)
	(can_traverse rover2 waypoint14 waypoint16)
	(can_traverse rover2 waypoint16 waypoint26)
	(can_traverse rover2 waypoint26 waypoint16)
	(can_traverse rover2 waypoint17 waypoint20)
	(can_traverse rover2 waypoint20 waypoint17)
	(can_traverse rover2 waypoint21 waypoint5)
	(can_traverse rover2 waypoint5 waypoint21)
	(can_traverse rover2 waypoint23 waypoint7)
	(can_traverse rover2 waypoint7 waypoint23)
	(can_traverse rover2 waypoint28 waypoint3)
	(can_traverse rover2 waypoint3 waypoint28)
	(at rover3 waypoint27)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint27 waypoint1)
	(can_traverse rover3 waypoint1 waypoint27)
	(can_traverse rover3 waypoint27 waypoint6)
	(can_traverse rover3 waypoint6 waypoint27)
	(can_traverse rover3 waypoint27 waypoint9)
	(can_traverse rover3 waypoint9 waypoint27)
	(can_traverse rover3 waypoint27 waypoint10)
	(can_traverse rover3 waypoint10 waypoint27)
	(can_traverse rover3 waypoint27 waypoint25)
	(can_traverse rover3 waypoint25 waypoint27)
	(can_traverse rover3 waypoint1 waypoint0)
	(can_traverse rover3 waypoint0 waypoint1)
	(can_traverse rover3 waypoint1 waypoint5)
	(can_traverse rover3 waypoint5 waypoint1)
	(can_traverse rover3 waypoint1 waypoint16)
	(can_traverse rover3 waypoint16 waypoint1)
	(can_traverse rover3 waypoint1 waypoint17)
	(can_traverse rover3 waypoint17 waypoint1)
	(can_traverse rover3 waypoint1 waypoint24)
	(can_traverse rover3 waypoint24 waypoint1)
	(can_traverse rover3 waypoint1 waypoint26)
	(can_traverse rover3 waypoint26 waypoint1)
	(can_traverse rover3 waypoint6 waypoint2)
	(can_traverse rover3 waypoint2 waypoint6)
	(can_traverse rover3 waypoint6 waypoint14)
	(can_traverse rover3 waypoint14 waypoint6)
	(can_traverse rover3 waypoint6 waypoint15)
	(can_traverse rover3 waypoint15 waypoint6)
	(can_traverse rover3 waypoint9 waypoint4)
	(can_traverse rover3 waypoint4 waypoint9)
	(can_traverse rover3 waypoint9 waypoint19)
	(can_traverse rover3 waypoint19 waypoint9)
	(can_traverse rover3 waypoint9 waypoint20)
	(can_traverse rover3 waypoint20 waypoint9)
	(can_traverse rover3 waypoint9 waypoint28)
	(can_traverse rover3 waypoint28 waypoint9)
	(can_traverse rover3 waypoint10 waypoint7)
	(can_traverse rover3 waypoint7 waypoint10)
	(can_traverse rover3 waypoint10 waypoint11)
	(can_traverse rover3 waypoint11 waypoint10)
	(can_traverse rover3 waypoint10 waypoint18)
	(can_traverse rover3 waypoint18 waypoint10)
	(can_traverse rover3 waypoint10 waypoint23)
	(can_traverse rover3 waypoint23 waypoint10)
	(can_traverse rover3 waypoint0 waypoint8)
	(can_traverse rover3 waypoint8 waypoint0)
	(can_traverse rover3 waypoint0 waypoint21)
	(can_traverse rover3 waypoint21 waypoint0)
	(can_traverse rover3 waypoint0 waypoint22)
	(can_traverse rover3 waypoint22 waypoint0)
	(can_traverse rover3 waypoint0 waypoint29)
	(can_traverse rover3 waypoint29 waypoint0)
	(can_traverse rover3 waypoint16 waypoint12)
	(can_traverse rover3 waypoint12 waypoint16)
	(can_traverse rover3 waypoint26 waypoint3)
	(can_traverse rover3 waypoint3 waypoint26)
	(can_traverse rover3 waypoint4 waypoint13)
	(can_traverse rover3 waypoint13 waypoint4)
	(at rover4 waypoint7)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint7 waypoint3)
	(can_traverse rover4 waypoint3 waypoint7)
	(can_traverse rover4 waypoint7 waypoint5)
	(can_traverse rover4 waypoint5 waypoint7)
	(can_traverse rover4 waypoint7 waypoint10)
	(can_traverse rover4 waypoint10 waypoint7)
	(can_traverse rover4 waypoint7 waypoint12)
	(can_traverse rover4 waypoint12 waypoint7)
	(can_traverse rover4 waypoint7 waypoint13)
	(can_traverse rover4 waypoint13 waypoint7)
	(can_traverse rover4 waypoint7 waypoint23)
	(can_traverse rover4 waypoint23 waypoint7)
	(can_traverse rover4 waypoint3 waypoint26)
	(can_traverse rover4 waypoint26 waypoint3)
	(can_traverse rover4 waypoint5 waypoint2)
	(can_traverse rover4 waypoint2 waypoint5)
	(can_traverse rover4 waypoint5 waypoint21)
	(can_traverse rover4 waypoint21 waypoint5)
	(can_traverse rover4 waypoint5 waypoint27)
	(can_traverse rover4 waypoint27 waypoint5)
	(can_traverse rover4 waypoint5 waypoint28)
	(can_traverse rover4 waypoint28 waypoint5)
	(can_traverse rover4 waypoint10 waypoint18)
	(can_traverse rover4 waypoint18 waypoint10)
	(can_traverse rover4 waypoint12 waypoint16)
	(can_traverse rover4 waypoint16 waypoint12)
	(can_traverse rover4 waypoint13 waypoint4)
	(can_traverse rover4 waypoint4 waypoint13)
	(can_traverse rover4 waypoint13 waypoint15)
	(can_traverse rover4 waypoint15 waypoint13)
	(can_traverse rover4 waypoint23 waypoint17)
	(can_traverse rover4 waypoint17 waypoint23)
	(can_traverse rover4 waypoint23 waypoint20)
	(can_traverse rover4 waypoint20 waypoint23)
	(can_traverse rover4 waypoint26 waypoint1)
	(can_traverse rover4 waypoint1 waypoint26)
	(can_traverse rover4 waypoint26 waypoint14)
	(can_traverse rover4 waypoint14 waypoint26)
	(can_traverse rover4 waypoint26 waypoint22)
	(can_traverse rover4 waypoint22 waypoint26)
	(can_traverse rover4 waypoint2 waypoint6)
	(can_traverse rover4 waypoint6 waypoint2)
	(can_traverse rover4 waypoint2 waypoint11)
	(can_traverse rover4 waypoint11 waypoint2)
	(can_traverse rover4 waypoint2 waypoint19)
	(can_traverse rover4 waypoint19 waypoint2)
	(can_traverse rover4 waypoint2 waypoint24)
	(can_traverse rover4 waypoint24 waypoint2)
	(can_traverse rover4 waypoint21 waypoint0)
	(can_traverse rover4 waypoint0 waypoint21)
	(can_traverse rover4 waypoint27 waypoint25)
	(can_traverse rover4 waypoint25 waypoint27)
	(can_traverse rover4 waypoint28 waypoint8)
	(can_traverse rover4 waypoint8 waypoint28)
	(can_traverse rover4 waypoint28 waypoint9)
	(can_traverse rover4 waypoint9 waypoint28)
	(can_traverse rover4 waypoint20 waypoint29)
	(can_traverse rover4 waypoint29 waypoint20)
	(at rover5 waypoint7)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint7 waypoint3)
	(can_traverse rover5 waypoint3 waypoint7)
	(can_traverse rover5 waypoint7 waypoint10)
	(can_traverse rover5 waypoint10 waypoint7)
	(can_traverse rover5 waypoint7 waypoint12)
	(can_traverse rover5 waypoint12 waypoint7)
	(can_traverse rover5 waypoint7 waypoint23)
	(can_traverse rover5 waypoint23 waypoint7)
	(can_traverse rover5 waypoint3 waypoint13)
	(can_traverse rover5 waypoint13 waypoint3)
	(can_traverse rover5 waypoint3 waypoint26)
	(can_traverse rover5 waypoint26 waypoint3)
	(can_traverse rover5 waypoint3 waypoint28)
	(can_traverse rover5 waypoint28 waypoint3)
	(can_traverse rover5 waypoint10 waypoint9)
	(can_traverse rover5 waypoint9 waypoint10)
	(can_traverse rover5 waypoint10 waypoint11)
	(can_traverse rover5 waypoint11 waypoint10)
	(can_traverse rover5 waypoint10 waypoint16)
	(can_traverse rover5 waypoint16 waypoint10)
	(can_traverse rover5 waypoint10 waypoint18)
	(can_traverse rover5 waypoint18 waypoint10)
	(can_traverse rover5 waypoint10 waypoint27)
	(can_traverse rover5 waypoint27 waypoint10)
	(can_traverse rover5 waypoint12 waypoint19)
	(can_traverse rover5 waypoint19 waypoint12)
	(can_traverse rover5 waypoint12 waypoint21)
	(can_traverse rover5 waypoint21 waypoint12)
	(can_traverse rover5 waypoint23 waypoint17)
	(can_traverse rover5 waypoint17 waypoint23)
	(can_traverse rover5 waypoint23 waypoint20)
	(can_traverse rover5 waypoint20 waypoint23)
	(can_traverse rover5 waypoint13 waypoint4)
	(can_traverse rover5 waypoint4 waypoint13)
	(can_traverse rover5 waypoint13 waypoint8)
	(can_traverse rover5 waypoint8 waypoint13)
	(can_traverse rover5 waypoint26 waypoint1)
	(can_traverse rover5 waypoint1 waypoint26)
	(can_traverse rover5 waypoint26 waypoint2)
	(can_traverse rover5 waypoint2 waypoint26)
	(can_traverse rover5 waypoint26 waypoint14)
	(can_traverse rover5 waypoint14 waypoint26)
	(can_traverse rover5 waypoint26 waypoint15)
	(can_traverse rover5 waypoint15 waypoint26)
	(can_traverse rover5 waypoint26 waypoint22)
	(can_traverse rover5 waypoint22 waypoint26)
	(can_traverse rover5 waypoint26 waypoint29)
	(can_traverse rover5 waypoint29 waypoint26)
	(can_traverse rover5 waypoint11 waypoint6)
	(can_traverse rover5 waypoint6 waypoint11)
	(can_traverse rover5 waypoint16 waypoint24)
	(can_traverse rover5 waypoint24 waypoint16)
	(can_traverse rover5 waypoint18 waypoint0)
	(can_traverse rover5 waypoint0 waypoint18)
	(can_traverse rover5 waypoint19 waypoint25)
	(can_traverse rover5 waypoint25 waypoint19)
	(can_traverse rover5 waypoint21 waypoint5)
	(can_traverse rover5 waypoint5 waypoint21)
	(at rover6 waypoint23)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(can_traverse rover6 waypoint23 waypoint7)
	(can_traverse rover6 waypoint7 waypoint23)
	(can_traverse rover6 waypoint23 waypoint12)
	(can_traverse rover6 waypoint12 waypoint23)
	(can_traverse rover6 waypoint23 waypoint13)
	(can_traverse rover6 waypoint13 waypoint23)
	(can_traverse rover6 waypoint23 waypoint17)
	(can_traverse rover6 waypoint17 waypoint23)
	(can_traverse rover6 waypoint23 waypoint18)
	(can_traverse rover6 waypoint18 waypoint23)
	(can_traverse rover6 waypoint7 waypoint5)
	(can_traverse rover6 waypoint5 waypoint7)
	(can_traverse rover6 waypoint7 waypoint10)
	(can_traverse rover6 waypoint10 waypoint7)
	(can_traverse rover6 waypoint7 waypoint20)
	(can_traverse rover6 waypoint20 waypoint7)
	(can_traverse rover6 waypoint12 waypoint3)
	(can_traverse rover6 waypoint3 waypoint12)
	(can_traverse rover6 waypoint12 waypoint24)
	(can_traverse rover6 waypoint24 waypoint12)
	(can_traverse rover6 waypoint13 waypoint4)
	(can_traverse rover6 waypoint4 waypoint13)
	(can_traverse rover6 waypoint13 waypoint21)
	(can_traverse rover6 waypoint21 waypoint13)
	(can_traverse rover6 waypoint17 waypoint16)
	(can_traverse rover6 waypoint16 waypoint17)
	(can_traverse rover6 waypoint18 waypoint0)
	(can_traverse rover6 waypoint0 waypoint18)
	(can_traverse rover6 waypoint18 waypoint6)
	(can_traverse rover6 waypoint6 waypoint18)
	(can_traverse rover6 waypoint18 waypoint19)
	(can_traverse rover6 waypoint19 waypoint18)
	(can_traverse rover6 waypoint18 waypoint28)
	(can_traverse rover6 waypoint28 waypoint18)
	(can_traverse rover6 waypoint5 waypoint2)
	(can_traverse rover6 waypoint2 waypoint5)
	(can_traverse rover6 waypoint5 waypoint27)
	(can_traverse rover6 waypoint27 waypoint5)
	(can_traverse rover6 waypoint10 waypoint9)
	(can_traverse rover6 waypoint9 waypoint10)
	(can_traverse rover6 waypoint10 waypoint11)
	(can_traverse rover6 waypoint11 waypoint10)
	(can_traverse rover6 waypoint20 waypoint25)
	(can_traverse rover6 waypoint25 waypoint20)
	(can_traverse rover6 waypoint20 waypoint26)
	(can_traverse rover6 waypoint26 waypoint20)
	(can_traverse rover6 waypoint20 waypoint29)
	(can_traverse rover6 waypoint29 waypoint20)
	(can_traverse rover6 waypoint4 waypoint8)
	(can_traverse rover6 waypoint8 waypoint4)
	(at rover7 waypoint12)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint12 waypoint3)
	(can_traverse rover7 waypoint3 waypoint12)
	(can_traverse rover7 waypoint12 waypoint7)
	(can_traverse rover7 waypoint7 waypoint12)
	(can_traverse rover7 waypoint12 waypoint10)
	(can_traverse rover7 waypoint10 waypoint12)
	(can_traverse rover7 waypoint12 waypoint16)
	(can_traverse rover7 waypoint16 waypoint12)
	(can_traverse rover7 waypoint12 waypoint19)
	(can_traverse rover7 waypoint19 waypoint12)
	(can_traverse rover7 waypoint12 waypoint23)
	(can_traverse rover7 waypoint23 waypoint12)
	(can_traverse rover7 waypoint12 waypoint24)
	(can_traverse rover7 waypoint24 waypoint12)
	(can_traverse rover7 waypoint3 waypoint13)
	(can_traverse rover7 waypoint13 waypoint3)
	(can_traverse rover7 waypoint3 waypoint26)
	(can_traverse rover7 waypoint26 waypoint3)
	(can_traverse rover7 waypoint3 waypoint28)
	(can_traverse rover7 waypoint28 waypoint3)
	(can_traverse rover7 waypoint7 waypoint5)
	(can_traverse rover7 waypoint5 waypoint7)
	(can_traverse rover7 waypoint7 waypoint20)
	(can_traverse rover7 waypoint20 waypoint7)
	(can_traverse rover7 waypoint10 waypoint9)
	(can_traverse rover7 waypoint9 waypoint10)
	(can_traverse rover7 waypoint10 waypoint11)
	(can_traverse rover7 waypoint11 waypoint10)
	(can_traverse rover7 waypoint10 waypoint18)
	(can_traverse rover7 waypoint18 waypoint10)
	(can_traverse rover7 waypoint10 waypoint27)
	(can_traverse rover7 waypoint27 waypoint10)
	(can_traverse rover7 waypoint16 waypoint1)
	(can_traverse rover7 waypoint1 waypoint16)
	(can_traverse rover7 waypoint19 waypoint0)
	(can_traverse rover7 waypoint0 waypoint19)
	(can_traverse rover7 waypoint19 waypoint2)
	(can_traverse rover7 waypoint2 waypoint19)
	(can_traverse rover7 waypoint19 waypoint21)
	(can_traverse rover7 waypoint21 waypoint19)
	(can_traverse rover7 waypoint23 waypoint17)
	(can_traverse rover7 waypoint17 waypoint23)
	(can_traverse rover7 waypoint13 waypoint8)
	(can_traverse rover7 waypoint8 waypoint13)
	(can_traverse rover7 waypoint13 waypoint15)
	(can_traverse rover7 waypoint15 waypoint13)
	(can_traverse rover7 waypoint26 waypoint14)
	(can_traverse rover7 waypoint14 waypoint26)
	(can_traverse rover7 waypoint26 waypoint22)
	(can_traverse rover7 waypoint22 waypoint26)
	(can_traverse rover7 waypoint26 waypoint29)
	(can_traverse rover7 waypoint29 waypoint26)
	(can_traverse rover7 waypoint20 waypoint25)
	(can_traverse rover7 waypoint25 waypoint20)
	(can_traverse rover7 waypoint11 waypoint6)
	(can_traverse rover7 waypoint6 waypoint11)
	(on_board camera0 rover3)
	(calibration_target camera0 objective5)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover1)
	(calibration_target camera1 objective5)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover5)
	(calibration_target camera2 objective4)
	(supports camera2 low_res)
	(on_board camera3 rover4)
	(calibration_target camera3 objective5)
	(supports camera3 low_res)
	(on_board camera4 rover3)
	(calibration_target camera4 objective3)
	(supports camera4 high_res)
	(on_board camera5 rover3)
	(calibration_target camera5 objective6)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover2)
	(calibration_target camera6 objective4)
	(supports camera6 high_res)
	(on_board camera7 rover3)
	(calibration_target camera7 objective1)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover5)
	(calibration_target camera8 objective0)
	(supports camera8 colour)
	(on_board camera9 rover5)
	(calibration_target camera9 objective0)
	(supports camera9 high_res)
	(supports camera9 low_res)
	(on_board camera10 rover7)
	(calibration_target camera10 objective9)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint26)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint29)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint17)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint11)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective8 waypoint0)
	(visible_from objective8 waypoint1)
	(visible_from objective8 waypoint2)
	(visible_from objective9 waypoint0)
	(visible_from objective9 waypoint1)
	(visible_from objective9 waypoint2)
	(visible_from objective9 waypoint3)
	(visible_from objective9 waypoint4)
	(visible_from objective9 waypoint5)
	(visible_from objective9 waypoint6)
	(visible_from objective9 waypoint7)
	(visible_from objective9 waypoint8)
	(visible_from objective9 waypoint9)
)

(:goal (and
(communicated_soil_data waypoint5)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint23)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint26)
(communicated_soil_data waypoint2)
(communicated_rock_data waypoint27)
(communicated_rock_data waypoint19)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint20)
(communicated_rock_data waypoint22)
(communicated_image_data objective2 low_res)
(communicated_image_data objective6 low_res)
(communicated_image_data objective3 low_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective3 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective2 high_res)
	)
)

(:metric minimize (total-time))
)
