(define (problem roverprob5621) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint0)
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint0)
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint29)
	(visible waypoint29 waypoint0)
	(visible waypoint1 waypoint24)
	(visible waypoint24 waypoint1)
	(visible waypoint1 waypoint29)
	(visible waypoint29 waypoint1)
	(visible waypoint1 waypoint35)
	(visible waypoint35 waypoint1)
	(visible waypoint1 waypoint43)
	(visible waypoint43 waypoint1)
	(visible waypoint2 waypoint33)
	(visible waypoint33 waypoint2)
	(visible waypoint2 waypoint42)
	(visible waypoint42 waypoint2)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint16)
	(visible waypoint16 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint32)
	(visible waypoint32 waypoint3)
	(visible waypoint3 waypoint43)
	(visible waypoint43 waypoint3)
	(visible waypoint4 waypoint16)
	(visible waypoint16 waypoint4)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint43)
	(visible waypoint43 waypoint4)
	(visible waypoint5 waypoint15)
	(visible waypoint15 waypoint5)
	(visible waypoint5 waypoint19)
	(visible waypoint19 waypoint5)
	(visible waypoint5 waypoint25)
	(visible waypoint25 waypoint5)
	(visible waypoint5 waypoint40)
	(visible waypoint40 waypoint5)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint47)
	(visible waypoint47 waypoint6)
	(visible waypoint7 waypoint22)
	(visible waypoint22 waypoint7)
	(visible waypoint7 waypoint30)
	(visible waypoint30 waypoint7)
	(visible waypoint7 waypoint40)
	(visible waypoint40 waypoint7)
	(visible waypoint7 waypoint49)
	(visible waypoint49 waypoint7)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint43)
	(visible waypoint43 waypoint8)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint9)
	(visible waypoint9 waypoint35)
	(visible waypoint35 waypoint9)
	(visible waypoint9 waypoint41)
	(visible waypoint41 waypoint9)
	(visible waypoint10 waypoint14)
	(visible waypoint14 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint10 waypoint32)
	(visible waypoint32 waypoint10)
	(visible waypoint10 waypoint35)
	(visible waypoint35 waypoint10)
	(visible waypoint10 waypoint37)
	(visible waypoint37 waypoint10)
	(visible waypoint10 waypoint44)
	(visible waypoint44 waypoint10)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint21)
	(visible waypoint21 waypoint11)
	(visible waypoint11 waypoint43)
	(visible waypoint43 waypoint11)
	(visible waypoint12 waypoint2)
	(visible waypoint2 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint8)
	(visible waypoint8 waypoint12)
	(visible waypoint12 waypoint31)
	(visible waypoint31 waypoint12)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint19)
	(visible waypoint19 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint13 waypoint32)
	(visible waypoint32 waypoint13)
	(visible waypoint13 waypoint37)
	(visible waypoint37 waypoint13)
	(visible waypoint13 waypoint39)
	(visible waypoint39 waypoint13)
	(visible waypoint13 waypoint40)
	(visible waypoint40 waypoint13)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint46)
	(visible waypoint46 waypoint14)
	(visible waypoint15 waypoint11)
	(visible waypoint11 waypoint15)
	(visible waypoint15 waypoint29)
	(visible waypoint29 waypoint15)
	(visible waypoint15 waypoint35)
	(visible waypoint35 waypoint15)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint32)
	(visible waypoint32 waypoint16)
	(visible waypoint16 waypoint34)
	(visible waypoint34 waypoint16)
	(visible waypoint16 waypoint37)
	(visible waypoint37 waypoint16)
	(visible waypoint16 waypoint46)
	(visible waypoint46 waypoint16)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint15)
	(visible waypoint15 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint30)
	(visible waypoint30 waypoint17)
	(visible waypoint17 waypoint43)
	(visible waypoint43 waypoint17)
	(visible waypoint17 waypoint45)
	(visible waypoint45 waypoint17)
	(visible waypoint17 waypoint48)
	(visible waypoint48 waypoint17)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint25)
	(visible waypoint25 waypoint18)
	(visible waypoint18 waypoint26)
	(visible waypoint26 waypoint18)
	(visible waypoint18 waypoint36)
	(visible waypoint36 waypoint18)
	(visible waypoint18 waypoint42)
	(visible waypoint42 waypoint18)
	(visible waypoint18 waypoint43)
	(visible waypoint43 waypoint18)
	(visible waypoint18 waypoint49)
	(visible waypoint49 waypoint18)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint23)
	(visible waypoint23 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint43)
	(visible waypoint43 waypoint19)
	(visible waypoint19 waypoint44)
	(visible waypoint44 waypoint19)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint31)
	(visible waypoint31 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint20)
	(visible waypoint21 waypoint7)
	(visible waypoint7 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint30)
	(visible waypoint30 waypoint21)
	(visible waypoint21 waypoint43)
	(visible waypoint43 waypoint21)
	(visible waypoint22 waypoint25)
	(visible waypoint25 waypoint22)
	(visible waypoint22 waypoint38)
	(visible waypoint38 waypoint22)
	(visible waypoint22 waypoint41)
	(visible waypoint41 waypoint22)
	(visible waypoint23 waypoint11)
	(visible waypoint11 waypoint23)
	(visible waypoint23 waypoint25)
	(visible waypoint25 waypoint23)
	(visible waypoint23 waypoint30)
	(visible waypoint30 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint24 waypoint2)
	(visible waypoint2 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint44)
	(visible waypoint44 waypoint24)
	(visible waypoint25 waypoint6)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint15)
	(visible waypoint15 waypoint25)
	(visible waypoint25 waypoint28)
	(visible waypoint28 waypoint25)
	(visible waypoint25 waypoint35)
	(visible waypoint35 waypoint25)
	(visible waypoint25 waypoint36)
	(visible waypoint36 waypoint25)
	(visible waypoint26 waypoint0)
	(visible waypoint0 waypoint26)
	(visible waypoint26 waypoint9)
	(visible waypoint9 waypoint26)
	(visible waypoint26 waypoint23)
	(visible waypoint23 waypoint26)
	(visible waypoint26 waypoint25)
	(visible waypoint25 waypoint26)
	(visible waypoint26 waypoint44)
	(visible waypoint44 waypoint26)
	(visible waypoint27 waypoint32)
	(visible waypoint32 waypoint27)
	(visible waypoint27 waypoint33)
	(visible waypoint33 waypoint27)
	(visible waypoint27 waypoint34)
	(visible waypoint34 waypoint27)
	(visible waypoint28 waypoint0)
	(visible waypoint0 waypoint28)
	(visible waypoint28 waypoint24)
	(visible waypoint24 waypoint28)
	(visible waypoint29 waypoint17)
	(visible waypoint17 waypoint29)
	(visible waypoint29 waypoint34)
	(visible waypoint34 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint29 waypoint41)
	(visible waypoint41 waypoint29)
	(visible waypoint30 waypoint3)
	(visible waypoint3 waypoint30)
	(visible waypoint30 waypoint5)
	(visible waypoint5 waypoint30)
	(visible waypoint30 waypoint8)
	(visible waypoint8 waypoint30)
	(visible waypoint30 waypoint28)
	(visible waypoint28 waypoint30)
	(visible waypoint30 waypoint33)
	(visible waypoint33 waypoint30)
	(visible waypoint30 waypoint45)
	(visible waypoint45 waypoint30)
	(visible waypoint31 waypoint13)
	(visible waypoint13 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint31 waypoint41)
	(visible waypoint41 waypoint31)
	(visible waypoint32 waypoint18)
	(visible waypoint18 waypoint32)
	(visible waypoint32 waypoint19)
	(visible waypoint19 waypoint32)
	(visible waypoint32 waypoint21)
	(visible waypoint21 waypoint32)
	(visible waypoint32 waypoint24)
	(visible waypoint24 waypoint32)
	(visible waypoint32 waypoint34)
	(visible waypoint34 waypoint32)
	(visible waypoint32 waypoint36)
	(visible waypoint36 waypoint32)
	(visible waypoint32 waypoint49)
	(visible waypoint49 waypoint32)
	(visible waypoint33 waypoint0)
	(visible waypoint0 waypoint33)
	(visible waypoint33 waypoint21)
	(visible waypoint21 waypoint33)
	(visible waypoint33 waypoint22)
	(visible waypoint22 waypoint33)
	(visible waypoint33 waypoint44)
	(visible waypoint44 waypoint33)
	(visible waypoint34 waypoint1)
	(visible waypoint1 waypoint34)
	(visible waypoint34 waypoint21)
	(visible waypoint21 waypoint34)
	(visible waypoint35 waypoint4)
	(visible waypoint4 waypoint35)
	(visible waypoint35 waypoint17)
	(visible waypoint17 waypoint35)
	(visible waypoint35 waypoint18)
	(visible waypoint18 waypoint35)
	(visible waypoint35 waypoint23)
	(visible waypoint23 waypoint35)
	(visible waypoint35 waypoint28)
	(visible waypoint28 waypoint35)
	(visible waypoint35 waypoint37)
	(visible waypoint37 waypoint35)
	(visible waypoint36 waypoint2)
	(visible waypoint2 waypoint36)
	(visible waypoint36 waypoint20)
	(visible waypoint20 waypoint36)
	(visible waypoint36 waypoint37)
	(visible waypoint37 waypoint36)
	(visible waypoint36 waypoint38)
	(visible waypoint38 waypoint36)
	(visible waypoint37 waypoint8)
	(visible waypoint8 waypoint37)
	(visible waypoint37 waypoint30)
	(visible waypoint30 waypoint37)
	(visible waypoint37 waypoint32)
	(visible waypoint32 waypoint37)
	(visible waypoint37 waypoint34)
	(visible waypoint34 waypoint37)
	(visible waypoint37 waypoint46)
	(visible waypoint46 waypoint37)
	(visible waypoint38 waypoint3)
	(visible waypoint3 waypoint38)
	(visible waypoint38 waypoint11)
	(visible waypoint11 waypoint38)
	(visible waypoint38 waypoint15)
	(visible waypoint15 waypoint38)
	(visible waypoint38 waypoint19)
	(visible waypoint19 waypoint38)
	(visible waypoint39 waypoint18)
	(visible waypoint18 waypoint39)
	(visible waypoint39 waypoint22)
	(visible waypoint22 waypoint39)
	(visible waypoint39 waypoint25)
	(visible waypoint25 waypoint39)
	(visible waypoint39 waypoint26)
	(visible waypoint26 waypoint39)
	(visible waypoint39 waypoint36)
	(visible waypoint36 waypoint39)
	(visible waypoint40 waypoint14)
	(visible waypoint14 waypoint40)
	(visible waypoint40 waypoint37)
	(visible waypoint37 waypoint40)
	(visible waypoint41 waypoint1)
	(visible waypoint1 waypoint41)
	(visible waypoint41 waypoint20)
	(visible waypoint20 waypoint41)
	(visible waypoint41 waypoint34)
	(visible waypoint34 waypoint41)
	(visible waypoint41 waypoint35)
	(visible waypoint35 waypoint41)
	(visible waypoint41 waypoint39)
	(visible waypoint39 waypoint41)
	(visible waypoint42 waypoint11)
	(visible waypoint11 waypoint42)
	(visible waypoint42 waypoint13)
	(visible waypoint13 waypoint42)
	(visible waypoint42 waypoint16)
	(visible waypoint16 waypoint42)
	(visible waypoint42 waypoint31)
	(visible waypoint31 waypoint42)
	(visible waypoint42 waypoint36)
	(visible waypoint36 waypoint42)
	(visible waypoint42 waypoint39)
	(visible waypoint39 waypoint42)
	(visible waypoint42 waypoint41)
	(visible waypoint41 waypoint42)
	(visible waypoint42 waypoint44)
	(visible waypoint44 waypoint42)
	(visible waypoint43 waypoint7)
	(visible waypoint7 waypoint43)
	(visible waypoint43 waypoint13)
	(visible waypoint13 waypoint43)
	(visible waypoint43 waypoint14)
	(visible waypoint14 waypoint43)
	(visible waypoint43 waypoint37)
	(visible waypoint37 waypoint43)
	(visible waypoint43 waypoint42)
	(visible waypoint42 waypoint43)
	(visible waypoint44 waypoint8)
	(visible waypoint8 waypoint44)
	(visible waypoint44 waypoint11)
	(visible waypoint11 waypoint44)
	(visible waypoint44 waypoint22)
	(visible waypoint22 waypoint44)
	(visible waypoint44 waypoint30)
	(visible waypoint30 waypoint44)
	(visible waypoint44 waypoint49)
	(visible waypoint49 waypoint44)
	(visible waypoint45 waypoint11)
	(visible waypoint11 waypoint45)
	(visible waypoint45 waypoint20)
	(visible waypoint20 waypoint45)
	(visible waypoint45 waypoint27)
	(visible waypoint27 waypoint45)
	(visible waypoint45 waypoint39)
	(visible waypoint39 waypoint45)
	(visible waypoint45 waypoint47)
	(visible waypoint47 waypoint45)
	(visible waypoint46 waypoint22)
	(visible waypoint22 waypoint46)
	(visible waypoint46 waypoint43)
	(visible waypoint43 waypoint46)
	(visible waypoint46 waypoint47)
	(visible waypoint47 waypoint46)
	(visible waypoint46 waypoint48)
	(visible waypoint48 waypoint46)
	(visible waypoint47 waypoint3)
	(visible waypoint3 waypoint47)
	(visible waypoint47 waypoint9)
	(visible waypoint9 waypoint47)
	(visible waypoint47 waypoint25)
	(visible waypoint25 waypoint47)
	(visible waypoint48 waypoint6)
	(visible waypoint6 waypoint48)
	(visible waypoint48 waypoint10)
	(visible waypoint10 waypoint48)
	(visible waypoint48 waypoint14)
	(visible waypoint14 waypoint48)
	(visible waypoint48 waypoint21)
	(visible waypoint21 waypoint48)
	(visible waypoint48 waypoint26)
	(visible waypoint26 waypoint48)
	(visible waypoint49 waypoint20)
	(visible waypoint20 waypoint49)
	(visible waypoint49 waypoint23)
	(visible waypoint23 waypoint49)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint42)
	(at_rock_sample waypoint43)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_lander general waypoint36)
	(channel_free general)
	(at rover0 waypoint0)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint0 waypoint4)
	(can_traverse rover0 waypoint4 waypoint0)
	(can_traverse rover0 waypoint0 waypoint5)
	(can_traverse rover0 waypoint5 waypoint0)
	(can_traverse rover0 waypoint0 waypoint6)
	(can_traverse rover0 waypoint6 waypoint0)
	(can_traverse rover0 waypoint0 waypoint11)
	(can_traverse rover0 waypoint11 waypoint0)
	(can_traverse rover0 waypoint0 waypoint12)
	(can_traverse rover0 waypoint12 waypoint0)
	(can_traverse rover0 waypoint0 waypoint26)
	(can_traverse rover0 waypoint26 waypoint0)
	(can_traverse rover0 waypoint0 waypoint28)
	(can_traverse rover0 waypoint28 waypoint0)
	(can_traverse rover0 waypoint0 waypoint29)
	(can_traverse rover0 waypoint29 waypoint0)
	(can_traverse rover0 waypoint0 waypoint33)
	(can_traverse rover0 waypoint33 waypoint0)
	(can_traverse rover0 waypoint4 waypoint3)
	(can_traverse rover0 waypoint3 waypoint4)
	(can_traverse rover0 waypoint4 waypoint16)
	(can_traverse rover0 waypoint16 waypoint4)
	(can_traverse rover0 waypoint4 waypoint19)
	(can_traverse rover0 waypoint19 waypoint4)
	(can_traverse rover0 waypoint4 waypoint20)
	(can_traverse rover0 waypoint20 waypoint4)
	(can_traverse rover0 waypoint5 waypoint14)
	(can_traverse rover0 waypoint14 waypoint5)
	(can_traverse rover0 waypoint5 waypoint15)
	(can_traverse rover0 waypoint15 waypoint5)
	(can_traverse rover0 waypoint5 waypoint17)
	(can_traverse rover0 waypoint17 waypoint5)
	(can_traverse rover0 waypoint5 waypoint25)
	(can_traverse rover0 waypoint25 waypoint5)
	(can_traverse rover0 waypoint5 waypoint30)
	(can_traverse rover0 waypoint30 waypoint5)
	(can_traverse rover0 waypoint5 waypoint40)
	(can_traverse rover0 waypoint40 waypoint5)
	(can_traverse rover0 waypoint6 waypoint18)
	(can_traverse rover0 waypoint18 waypoint6)
	(can_traverse rover0 waypoint11 waypoint23)
	(can_traverse rover0 waypoint23 waypoint11)
	(can_traverse rover0 waypoint11 waypoint38)
	(can_traverse rover0 waypoint38 waypoint11)
	(can_traverse rover0 waypoint11 waypoint43)
	(can_traverse rover0 waypoint43 waypoint11)
	(can_traverse rover0 waypoint11 waypoint44)
	(can_traverse rover0 waypoint44 waypoint11)
	(can_traverse rover0 waypoint11 waypoint45)
	(can_traverse rover0 waypoint45 waypoint11)
	(can_traverse rover0 waypoint12 waypoint8)
	(can_traverse rover0 waypoint8 waypoint12)
	(can_traverse rover0 waypoint12 waypoint31)
	(can_traverse rover0 waypoint31 waypoint12)
	(can_traverse rover0 waypoint26 waypoint9)
	(can_traverse rover0 waypoint9 waypoint26)
	(can_traverse rover0 waypoint26 waypoint39)
	(can_traverse rover0 waypoint39 waypoint26)
	(can_traverse rover0 waypoint26 waypoint48)
	(can_traverse rover0 waypoint48 waypoint26)
	(can_traverse rover0 waypoint28 waypoint24)
	(can_traverse rover0 waypoint24 waypoint28)
	(can_traverse rover0 waypoint29 waypoint1)
	(can_traverse rover0 waypoint1 waypoint29)
	(can_traverse rover0 waypoint29 waypoint41)
	(can_traverse rover0 waypoint41 waypoint29)
	(can_traverse rover0 waypoint33 waypoint2)
	(can_traverse rover0 waypoint2 waypoint33)
	(can_traverse rover0 waypoint33 waypoint21)
	(can_traverse rover0 waypoint21 waypoint33)
	(can_traverse rover0 waypoint33 waypoint22)
	(can_traverse rover0 waypoint22 waypoint33)
	(can_traverse rover0 waypoint33 waypoint27)
	(can_traverse rover0 waypoint27 waypoint33)
	(can_traverse rover0 waypoint16 waypoint32)
	(can_traverse rover0 waypoint32 waypoint16)
	(can_traverse rover0 waypoint16 waypoint34)
	(can_traverse rover0 waypoint34 waypoint16)
	(can_traverse rover0 waypoint16 waypoint37)
	(can_traverse rover0 waypoint37 waypoint16)
	(can_traverse rover0 waypoint16 waypoint42)
	(can_traverse rover0 waypoint42 waypoint16)
	(can_traverse rover0 waypoint16 waypoint46)
	(can_traverse rover0 waypoint46 waypoint16)
	(can_traverse rover0 waypoint19 waypoint13)
	(can_traverse rover0 waypoint13 waypoint19)
	(can_traverse rover0 waypoint20 waypoint36)
	(can_traverse rover0 waypoint36 waypoint20)
	(can_traverse rover0 waypoint14 waypoint10)
	(can_traverse rover0 waypoint10 waypoint14)
	(can_traverse rover0 waypoint15 waypoint35)
	(can_traverse rover0 waypoint35 waypoint15)
	(can_traverse rover0 waypoint30 waypoint7)
	(can_traverse rover0 waypoint7 waypoint30)
	(can_traverse rover0 waypoint23 waypoint49)
	(can_traverse rover0 waypoint49 waypoint23)
	(can_traverse rover0 waypoint45 waypoint47)
	(can_traverse rover0 waypoint47 waypoint45)
	(at rover1 waypoint46)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint46 waypoint14)
	(can_traverse rover1 waypoint14 waypoint46)
	(can_traverse rover1 waypoint46 waypoint37)
	(can_traverse rover1 waypoint37 waypoint46)
	(can_traverse rover1 waypoint46 waypoint47)
	(can_traverse rover1 waypoint47 waypoint46)
	(can_traverse rover1 waypoint46 waypoint48)
	(can_traverse rover1 waypoint48 waypoint46)
	(can_traverse rover1 waypoint14 waypoint5)
	(can_traverse rover1 waypoint5 waypoint14)
	(can_traverse rover1 waypoint14 waypoint13)
	(can_traverse rover1 waypoint13 waypoint14)
	(can_traverse rover1 waypoint14 waypoint30)
	(can_traverse rover1 waypoint30 waypoint14)
	(can_traverse rover1 waypoint14 waypoint43)
	(can_traverse rover1 waypoint43 waypoint14)
	(can_traverse rover1 waypoint37 waypoint16)
	(can_traverse rover1 waypoint16 waypoint37)
	(can_traverse rover1 waypoint37 waypoint34)
	(can_traverse rover1 waypoint34 waypoint37)
	(can_traverse rover1 waypoint37 waypoint35)
	(can_traverse rover1 waypoint35 waypoint37)
	(can_traverse rover1 waypoint37 waypoint40)
	(can_traverse rover1 waypoint40 waypoint37)
	(can_traverse rover1 waypoint47 waypoint3)
	(can_traverse rover1 waypoint3 waypoint47)
	(can_traverse rover1 waypoint47 waypoint6)
	(can_traverse rover1 waypoint6 waypoint47)
	(can_traverse rover1 waypoint47 waypoint45)
	(can_traverse rover1 waypoint45 waypoint47)
	(can_traverse rover1 waypoint48 waypoint21)
	(can_traverse rover1 waypoint21 waypoint48)
	(can_traverse rover1 waypoint48 waypoint26)
	(can_traverse rover1 waypoint26 waypoint48)
	(can_traverse rover1 waypoint5 waypoint0)
	(can_traverse rover1 waypoint0 waypoint5)
	(can_traverse rover1 waypoint5 waypoint12)
	(can_traverse rover1 waypoint12 waypoint5)
	(can_traverse rover1 waypoint5 waypoint15)
	(can_traverse rover1 waypoint15 waypoint5)
	(can_traverse rover1 waypoint5 waypoint17)
	(can_traverse rover1 waypoint17 waypoint5)
	(can_traverse rover1 waypoint5 waypoint19)
	(can_traverse rover1 waypoint19 waypoint5)
	(can_traverse rover1 waypoint5 waypoint25)
	(can_traverse rover1 waypoint25 waypoint5)
	(can_traverse rover1 waypoint13 waypoint8)
	(can_traverse rover1 waypoint8 waypoint13)
	(can_traverse rover1 waypoint13 waypoint10)
	(can_traverse rover1 waypoint10 waypoint13)
	(can_traverse rover1 waypoint13 waypoint23)
	(can_traverse rover1 waypoint23 waypoint13)
	(can_traverse rover1 waypoint13 waypoint31)
	(can_traverse rover1 waypoint31 waypoint13)
	(can_traverse rover1 waypoint13 waypoint39)
	(can_traverse rover1 waypoint39 waypoint13)
	(can_traverse rover1 waypoint13 waypoint42)
	(can_traverse rover1 waypoint42 waypoint13)
	(can_traverse rover1 waypoint30 waypoint7)
	(can_traverse rover1 waypoint7 waypoint30)
	(can_traverse rover1 waypoint30 waypoint28)
	(can_traverse rover1 waypoint28 waypoint30)
	(can_traverse rover1 waypoint30 waypoint33)
	(can_traverse rover1 waypoint33 waypoint30)
	(can_traverse rover1 waypoint30 waypoint44)
	(can_traverse rover1 waypoint44 waypoint30)
	(can_traverse rover1 waypoint43 waypoint1)
	(can_traverse rover1 waypoint1 waypoint43)
	(can_traverse rover1 waypoint43 waypoint11)
	(can_traverse rover1 waypoint11 waypoint43)
	(can_traverse rover1 waypoint43 waypoint18)
	(can_traverse rover1 waypoint18 waypoint43)
	(can_traverse rover1 waypoint16 waypoint4)
	(can_traverse rover1 waypoint4 waypoint16)
	(can_traverse rover1 waypoint16 waypoint32)
	(can_traverse rover1 waypoint32 waypoint16)
	(can_traverse rover1 waypoint34 waypoint9)
	(can_traverse rover1 waypoint9 waypoint34)
	(can_traverse rover1 waypoint34 waypoint29)
	(can_traverse rover1 waypoint29 waypoint34)
	(can_traverse rover1 waypoint34 waypoint41)
	(can_traverse rover1 waypoint41 waypoint34)
	(can_traverse rover1 waypoint45 waypoint27)
	(can_traverse rover1 waypoint27 waypoint45)
	(can_traverse rover1 waypoint15 waypoint38)
	(can_traverse rover1 waypoint38 waypoint15)
	(can_traverse rover1 waypoint25 waypoint36)
	(can_traverse rover1 waypoint36 waypoint25)
	(can_traverse rover1 waypoint10 waypoint20)
	(can_traverse rover1 waypoint20 waypoint10)
	(can_traverse rover1 waypoint10 waypoint22)
	(can_traverse rover1 waypoint22 waypoint10)
	(can_traverse rover1 waypoint23 waypoint49)
	(can_traverse rover1 waypoint49 waypoint23)
	(can_traverse rover1 waypoint42 waypoint2)
	(can_traverse rover1 waypoint2 waypoint42)
	(can_traverse rover1 waypoint44 waypoint24)
	(can_traverse rover1 waypoint24 waypoint44)
	(at rover2 waypoint11)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint11 waypoint0)
	(can_traverse rover2 waypoint0 waypoint11)
	(can_traverse rover2 waypoint11 waypoint3)
	(can_traverse rover2 waypoint3 waypoint11)
	(can_traverse rover2 waypoint11 waypoint9)
	(can_traverse rover2 waypoint9 waypoint11)
	(can_traverse rover2 waypoint11 waypoint15)
	(can_traverse rover2 waypoint15 waypoint11)
	(can_traverse rover2 waypoint11 waypoint21)
	(can_traverse rover2 waypoint21 waypoint11)
	(can_traverse rover2 waypoint11 waypoint23)
	(can_traverse rover2 waypoint23 waypoint11)
	(can_traverse rover2 waypoint11 waypoint38)
	(can_traverse rover2 waypoint38 waypoint11)
	(can_traverse rover2 waypoint11 waypoint42)
	(can_traverse rover2 waypoint42 waypoint11)
	(can_traverse rover2 waypoint11 waypoint43)
	(can_traverse rover2 waypoint43 waypoint11)
	(can_traverse rover2 waypoint11 waypoint44)
	(can_traverse rover2 waypoint44 waypoint11)
	(can_traverse rover2 waypoint11 waypoint45)
	(can_traverse rover2 waypoint45 waypoint11)
	(can_traverse rover2 waypoint0 waypoint4)
	(can_traverse rover2 waypoint4 waypoint0)
	(can_traverse rover2 waypoint0 waypoint5)
	(can_traverse rover2 waypoint5 waypoint0)
	(can_traverse rover2 waypoint0 waypoint12)
	(can_traverse rover2 waypoint12 waypoint0)
	(can_traverse rover2 waypoint0 waypoint26)
	(can_traverse rover2 waypoint26 waypoint0)
	(can_traverse rover2 waypoint0 waypoint28)
	(can_traverse rover2 waypoint28 waypoint0)
	(can_traverse rover2 waypoint0 waypoint29)
	(can_traverse rover2 waypoint29 waypoint0)
	(can_traverse rover2 waypoint0 waypoint33)
	(can_traverse rover2 waypoint33 waypoint0)
	(can_traverse rover2 waypoint3 waypoint8)
	(can_traverse rover2 waypoint8 waypoint3)
	(can_traverse rover2 waypoint3 waypoint16)
	(can_traverse rover2 waypoint16 waypoint3)
	(can_traverse rover2 waypoint3 waypoint19)
	(can_traverse rover2 waypoint19 waypoint3)
	(can_traverse rover2 waypoint3 waypoint30)
	(can_traverse rover2 waypoint30 waypoint3)
	(can_traverse rover2 waypoint3 waypoint32)
	(can_traverse rover2 waypoint32 waypoint3)
	(can_traverse rover2 waypoint9 waypoint2)
	(can_traverse rover2 waypoint2 waypoint9)
	(can_traverse rover2 waypoint9 waypoint47)
	(can_traverse rover2 waypoint47 waypoint9)
	(can_traverse rover2 waypoint21 waypoint7)
	(can_traverse rover2 waypoint7 waypoint21)
	(can_traverse rover2 waypoint21 waypoint34)
	(can_traverse rover2 waypoint34 waypoint21)
	(can_traverse rover2 waypoint21 waypoint48)
	(can_traverse rover2 waypoint48 waypoint21)
	(can_traverse rover2 waypoint23 waypoint13)
	(can_traverse rover2 waypoint13 waypoint23)
	(can_traverse rover2 waypoint23 waypoint25)
	(can_traverse rover2 waypoint25 waypoint23)
	(can_traverse rover2 waypoint23 waypoint35)
	(can_traverse rover2 waypoint35 waypoint23)
	(can_traverse rover2 waypoint23 waypoint49)
	(can_traverse rover2 waypoint49 waypoint23)
	(can_traverse rover2 waypoint38 waypoint22)
	(can_traverse rover2 waypoint22 waypoint38)
	(can_traverse rover2 waypoint38 waypoint36)
	(can_traverse rover2 waypoint36 waypoint38)
	(can_traverse rover2 waypoint42 waypoint18)
	(can_traverse rover2 waypoint18 waypoint42)
	(can_traverse rover2 waypoint42 waypoint39)
	(can_traverse rover2 waypoint39 waypoint42)
	(can_traverse rover2 waypoint42 waypoint41)
	(can_traverse rover2 waypoint41 waypoint42)
	(can_traverse rover2 waypoint43 waypoint1)
	(can_traverse rover2 waypoint1 waypoint43)
	(can_traverse rover2 waypoint43 waypoint14)
	(can_traverse rover2 waypoint14 waypoint43)
	(can_traverse rover2 waypoint43 waypoint17)
	(can_traverse rover2 waypoint17 waypoint43)
	(can_traverse rover2 waypoint43 waypoint37)
	(can_traverse rover2 waypoint37 waypoint43)
	(can_traverse rover2 waypoint44 waypoint24)
	(can_traverse rover2 waypoint24 waypoint44)
	(can_traverse rover2 waypoint45 waypoint20)
	(can_traverse rover2 waypoint20 waypoint45)
	(can_traverse rover2 waypoint5 waypoint40)
	(can_traverse rover2 waypoint40 waypoint5)
	(can_traverse rover2 waypoint12 waypoint6)
	(can_traverse rover2 waypoint6 waypoint12)
	(can_traverse rover2 waypoint12 waypoint31)
	(can_traverse rover2 waypoint31 waypoint12)
	(can_traverse rover2 waypoint33 waypoint27)
	(can_traverse rover2 waypoint27 waypoint33)
	(can_traverse rover2 waypoint16 waypoint46)
	(can_traverse rover2 waypoint46 waypoint16)
	(can_traverse rover2 waypoint48 waypoint10)
	(can_traverse rover2 waypoint10 waypoint48)
	(at rover3 waypoint47)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint47 waypoint3)
	(can_traverse rover3 waypoint3 waypoint47)
	(can_traverse rover3 waypoint47 waypoint9)
	(can_traverse rover3 waypoint9 waypoint47)
	(can_traverse rover3 waypoint47 waypoint25)
	(can_traverse rover3 waypoint25 waypoint47)
	(can_traverse rover3 waypoint47 waypoint45)
	(can_traverse rover3 waypoint45 waypoint47)
	(can_traverse rover3 waypoint3 waypoint4)
	(can_traverse rover3 waypoint4 waypoint3)
	(can_traverse rover3 waypoint3 waypoint8)
	(can_traverse rover3 waypoint8 waypoint3)
	(can_traverse rover3 waypoint3 waypoint11)
	(can_traverse rover3 waypoint11 waypoint3)
	(can_traverse rover3 waypoint3 waypoint16)
	(can_traverse rover3 waypoint16 waypoint3)
	(can_traverse rover3 waypoint3 waypoint19)
	(can_traverse rover3 waypoint19 waypoint3)
	(can_traverse rover3 waypoint3 waypoint30)
	(can_traverse rover3 waypoint30 waypoint3)
	(can_traverse rover3 waypoint3 waypoint32)
	(can_traverse rover3 waypoint32 waypoint3)
	(can_traverse rover3 waypoint3 waypoint43)
	(can_traverse rover3 waypoint43 waypoint3)
	(can_traverse rover3 waypoint9 waypoint0)
	(can_traverse rover3 waypoint0 waypoint9)
	(can_traverse rover3 waypoint9 waypoint6)
	(can_traverse rover3 waypoint6 waypoint9)
	(can_traverse rover3 waypoint9 waypoint34)
	(can_traverse rover3 waypoint34 waypoint9)
	(can_traverse rover3 waypoint9 waypoint35)
	(can_traverse rover3 waypoint35 waypoint9)
	(can_traverse rover3 waypoint9 waypoint41)
	(can_traverse rover3 waypoint41 waypoint9)
	(can_traverse rover3 waypoint25 waypoint14)
	(can_traverse rover3 waypoint14 waypoint25)
	(can_traverse rover3 waypoint25 waypoint15)
	(can_traverse rover3 waypoint15 waypoint25)
	(can_traverse rover3 waypoint25 waypoint18)
	(can_traverse rover3 waypoint18 waypoint25)
	(can_traverse rover3 waypoint25 waypoint22)
	(can_traverse rover3 waypoint22 waypoint25)
	(can_traverse rover3 waypoint25 waypoint23)
	(can_traverse rover3 waypoint23 waypoint25)
	(can_traverse rover3 waypoint25 waypoint28)
	(can_traverse rover3 waypoint28 waypoint25)
	(can_traverse rover3 waypoint25 waypoint36)
	(can_traverse rover3 waypoint36 waypoint25)
	(can_traverse rover3 waypoint45 waypoint17)
	(can_traverse rover3 waypoint17 waypoint45)
	(can_traverse rover3 waypoint4 waypoint20)
	(can_traverse rover3 waypoint20 waypoint4)
	(can_traverse rover3 waypoint8 waypoint12)
	(can_traverse rover3 waypoint12 waypoint8)
	(can_traverse rover3 waypoint8 waypoint13)
	(can_traverse rover3 waypoint13 waypoint8)
	(can_traverse rover3 waypoint8 waypoint37)
	(can_traverse rover3 waypoint37 waypoint8)
	(can_traverse rover3 waypoint11 waypoint21)
	(can_traverse rover3 waypoint21 waypoint11)
	(can_traverse rover3 waypoint11 waypoint44)
	(can_traverse rover3 waypoint44 waypoint11)
	(can_traverse rover3 waypoint16 waypoint42)
	(can_traverse rover3 waypoint42 waypoint16)
	(can_traverse rover3 waypoint16 waypoint46)
	(can_traverse rover3 waypoint46 waypoint16)
	(can_traverse rover3 waypoint19 waypoint1)
	(can_traverse rover3 waypoint1 waypoint19)
	(can_traverse rover3 waypoint19 waypoint5)
	(can_traverse rover3 waypoint5 waypoint19)
	(can_traverse rover3 waypoint19 waypoint38)
	(can_traverse rover3 waypoint38 waypoint19)
	(can_traverse rover3 waypoint30 waypoint7)
	(can_traverse rover3 waypoint7 waypoint30)
	(can_traverse rover3 waypoint30 waypoint33)
	(can_traverse rover3 waypoint33 waypoint30)
	(can_traverse rover3 waypoint32 waypoint24)
	(can_traverse rover3 waypoint24 waypoint32)
	(can_traverse rover3 waypoint0 waypoint26)
	(can_traverse rover3 waypoint26 waypoint0)
	(can_traverse rover3 waypoint0 waypoint29)
	(can_traverse rover3 waypoint29 waypoint0)
	(can_traverse rover3 waypoint6 waypoint48)
	(can_traverse rover3 waypoint48 waypoint6)
	(can_traverse rover3 waypoint34 waypoint27)
	(can_traverse rover3 waypoint27 waypoint34)
	(can_traverse rover3 waypoint41 waypoint39)
	(can_traverse rover3 waypoint39 waypoint41)
	(can_traverse rover3 waypoint14 waypoint10)
	(can_traverse rover3 waypoint10 waypoint14)
	(can_traverse rover3 waypoint36 waypoint2)
	(can_traverse rover3 waypoint2 waypoint36)
	(can_traverse rover3 waypoint20 waypoint31)
	(can_traverse rover3 waypoint31 waypoint20)
	(can_traverse rover3 waypoint20 waypoint49)
	(can_traverse rover3 waypoint49 waypoint20)
	(can_traverse rover3 waypoint13 waypoint40)
	(can_traverse rover3 waypoint40 waypoint13)
	(at rover4 waypoint26)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint26 waypoint0)
	(can_traverse rover4 waypoint0 waypoint26)
	(can_traverse rover4 waypoint26 waypoint25)
	(can_traverse rover4 waypoint25 waypoint26)
	(can_traverse rover4 waypoint26 waypoint39)
	(can_traverse rover4 waypoint39 waypoint26)
	(can_traverse rover4 waypoint26 waypoint44)
	(can_traverse rover4 waypoint44 waypoint26)
	(can_traverse rover4 waypoint0 waypoint4)
	(can_traverse rover4 waypoint4 waypoint0)
	(can_traverse rover4 waypoint0 waypoint5)
	(can_traverse rover4 waypoint5 waypoint0)
	(can_traverse rover4 waypoint0 waypoint6)
	(can_traverse rover4 waypoint6 waypoint0)
	(can_traverse rover4 waypoint0 waypoint9)
	(can_traverse rover4 waypoint9 waypoint0)
	(can_traverse rover4 waypoint0 waypoint12)
	(can_traverse rover4 waypoint12 waypoint0)
	(can_traverse rover4 waypoint0 waypoint28)
	(can_traverse rover4 waypoint28 waypoint0)
	(can_traverse rover4 waypoint0 waypoint29)
	(can_traverse rover4 waypoint29 waypoint0)
	(can_traverse rover4 waypoint0 waypoint33)
	(can_traverse rover4 waypoint33 waypoint0)
	(can_traverse rover4 waypoint25 waypoint14)
	(can_traverse rover4 waypoint14 waypoint25)
	(can_traverse rover4 waypoint25 waypoint16)
	(can_traverse rover4 waypoint16 waypoint25)
	(can_traverse rover4 waypoint25 waypoint18)
	(can_traverse rover4 waypoint18 waypoint25)
	(can_traverse rover4 waypoint25 waypoint19)
	(can_traverse rover4 waypoint19 waypoint25)
	(can_traverse rover4 waypoint25 waypoint22)
	(can_traverse rover4 waypoint22 waypoint25)
	(can_traverse rover4 waypoint25 waypoint35)
	(can_traverse rover4 waypoint35 waypoint25)
	(can_traverse rover4 waypoint25 waypoint36)
	(can_traverse rover4 waypoint36 waypoint25)
	(can_traverse rover4 waypoint25 waypoint47)
	(can_traverse rover4 waypoint47 waypoint25)
	(can_traverse rover4 waypoint39 waypoint13)
	(can_traverse rover4 waypoint13 waypoint39)
	(can_traverse rover4 waypoint39 waypoint45)
	(can_traverse rover4 waypoint45 waypoint39)
	(can_traverse rover4 waypoint44 waypoint8)
	(can_traverse rover4 waypoint8 waypoint44)
	(can_traverse rover4 waypoint44 waypoint10)
	(can_traverse rover4 waypoint10 waypoint44)
	(can_traverse rover4 waypoint44 waypoint11)
	(can_traverse rover4 waypoint11 waypoint44)
	(can_traverse rover4 waypoint44 waypoint24)
	(can_traverse rover4 waypoint24 waypoint44)
	(can_traverse rover4 waypoint44 waypoint30)
	(can_traverse rover4 waypoint30 waypoint44)
	(can_traverse rover4 waypoint44 waypoint42)
	(can_traverse rover4 waypoint42 waypoint44)
	(can_traverse rover4 waypoint4 waypoint3)
	(can_traverse rover4 waypoint3 waypoint4)
	(can_traverse rover4 waypoint4 waypoint20)
	(can_traverse rover4 waypoint20 waypoint4)
	(can_traverse rover4 waypoint4 waypoint43)
	(can_traverse rover4 waypoint43 waypoint4)
	(can_traverse rover4 waypoint6 waypoint48)
	(can_traverse rover4 waypoint48 waypoint6)
	(can_traverse rover4 waypoint9 waypoint2)
	(can_traverse rover4 waypoint2 waypoint9)
	(can_traverse rover4 waypoint9 waypoint34)
	(can_traverse rover4 waypoint34 waypoint9)
	(can_traverse rover4 waypoint9 waypoint41)
	(can_traverse rover4 waypoint41 waypoint9)
	(can_traverse rover4 waypoint29 waypoint1)
	(can_traverse rover4 waypoint1 waypoint29)
	(can_traverse rover4 waypoint29 waypoint17)
	(can_traverse rover4 waypoint17 waypoint29)
	(can_traverse rover4 waypoint33 waypoint27)
	(can_traverse rover4 waypoint27 waypoint33)
	(can_traverse rover4 waypoint14 waypoint40)
	(can_traverse rover4 waypoint40 waypoint14)
	(can_traverse rover4 waypoint14 waypoint46)
	(can_traverse rover4 waypoint46 waypoint14)
	(can_traverse rover4 waypoint16 waypoint32)
	(can_traverse rover4 waypoint32 waypoint16)
	(can_traverse rover4 waypoint16 waypoint37)
	(can_traverse rover4 waypoint37 waypoint16)
	(can_traverse rover4 waypoint18 waypoint49)
	(can_traverse rover4 waypoint49 waypoint18)
	(can_traverse rover4 waypoint19 waypoint23)
	(can_traverse rover4 waypoint23 waypoint19)
	(can_traverse rover4 waypoint19 waypoint38)
	(can_traverse rover4 waypoint38 waypoint19)
	(can_traverse rover4 waypoint22 waypoint7)
	(can_traverse rover4 waypoint7 waypoint22)
	(can_traverse rover4 waypoint13 waypoint31)
	(can_traverse rover4 waypoint31 waypoint13)
	(can_traverse rover4 waypoint11 waypoint15)
	(can_traverse rover4 waypoint15 waypoint11)
	(can_traverse rover4 waypoint11 waypoint21)
	(can_traverse rover4 waypoint21 waypoint11)
	(at rover5 waypoint37)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint37 waypoint8)
	(can_traverse rover5 waypoint8 waypoint37)
	(can_traverse rover5 waypoint37 waypoint13)
	(can_traverse rover5 waypoint13 waypoint37)
	(can_traverse rover5 waypoint37 waypoint30)
	(can_traverse rover5 waypoint30 waypoint37)
	(can_traverse rover5 waypoint37 waypoint34)
	(can_traverse rover5 waypoint34 waypoint37)
	(can_traverse rover5 waypoint37 waypoint35)
	(can_traverse rover5 waypoint35 waypoint37)
	(can_traverse rover5 waypoint37 waypoint36)
	(can_traverse rover5 waypoint36 waypoint37)
	(can_traverse rover5 waypoint37 waypoint43)
	(can_traverse rover5 waypoint43 waypoint37)
	(can_traverse rover5 waypoint37 waypoint46)
	(can_traverse rover5 waypoint46 waypoint37)
	(can_traverse rover5 waypoint8 waypoint3)
	(can_traverse rover5 waypoint3 waypoint8)
	(can_traverse rover5 waypoint8 waypoint12)
	(can_traverse rover5 waypoint12 waypoint8)
	(can_traverse rover5 waypoint8 waypoint44)
	(can_traverse rover5 waypoint44 waypoint8)
	(can_traverse rover5 waypoint13 waypoint1)
	(can_traverse rover5 waypoint1 waypoint13)
	(can_traverse rover5 waypoint13 waypoint10)
	(can_traverse rover5 waypoint10 waypoint13)
	(can_traverse rover5 waypoint13 waypoint23)
	(can_traverse rover5 waypoint23 waypoint13)
	(can_traverse rover5 waypoint13 waypoint31)
	(can_traverse rover5 waypoint31 waypoint13)
	(can_traverse rover5 waypoint13 waypoint32)
	(can_traverse rover5 waypoint32 waypoint13)
	(can_traverse rover5 waypoint13 waypoint39)
	(can_traverse rover5 waypoint39 waypoint13)
	(can_traverse rover5 waypoint13 waypoint40)
	(can_traverse rover5 waypoint40 waypoint13)
	(can_traverse rover5 waypoint13 waypoint42)
	(can_traverse rover5 waypoint42 waypoint13)
	(can_traverse rover5 waypoint30 waypoint7)
	(can_traverse rover5 waypoint7 waypoint30)
	(can_traverse rover5 waypoint30 waypoint21)
	(can_traverse rover5 waypoint21 waypoint30)
	(can_traverse rover5 waypoint30 waypoint28)
	(can_traverse rover5 waypoint28 waypoint30)
	(can_traverse rover5 waypoint30 waypoint33)
	(can_traverse rover5 waypoint33 waypoint30)
	(can_traverse rover5 waypoint30 waypoint45)
	(can_traverse rover5 waypoint45 waypoint30)
	(can_traverse rover5 waypoint34 waypoint9)
	(can_traverse rover5 waypoint9 waypoint34)
	(can_traverse rover5 waypoint34 waypoint16)
	(can_traverse rover5 waypoint16 waypoint34)
	(can_traverse rover5 waypoint34 waypoint27)
	(can_traverse rover5 waypoint27 waypoint34)
	(can_traverse rover5 waypoint34 waypoint29)
	(can_traverse rover5 waypoint29 waypoint34)
	(can_traverse rover5 waypoint34 waypoint41)
	(can_traverse rover5 waypoint41 waypoint34)
	(can_traverse rover5 waypoint35 waypoint4)
	(can_traverse rover5 waypoint4 waypoint35)
	(can_traverse rover5 waypoint35 waypoint17)
	(can_traverse rover5 waypoint17 waypoint35)
	(can_traverse rover5 waypoint36 waypoint2)
	(can_traverse rover5 waypoint2 waypoint36)
	(can_traverse rover5 waypoint36 waypoint18)
	(can_traverse rover5 waypoint18 waypoint36)
	(can_traverse rover5 waypoint36 waypoint20)
	(can_traverse rover5 waypoint20 waypoint36)
	(can_traverse rover5 waypoint36 waypoint25)
	(can_traverse rover5 waypoint25 waypoint36)
	(can_traverse rover5 waypoint36 waypoint38)
	(can_traverse rover5 waypoint38 waypoint36)
	(can_traverse rover5 waypoint43 waypoint11)
	(can_traverse rover5 waypoint11 waypoint43)
	(can_traverse rover5 waypoint43 waypoint14)
	(can_traverse rover5 waypoint14 waypoint43)
	(can_traverse rover5 waypoint46 waypoint22)
	(can_traverse rover5 waypoint22 waypoint46)
	(can_traverse rover5 waypoint46 waypoint47)
	(can_traverse rover5 waypoint47 waypoint46)
	(can_traverse rover5 waypoint46 waypoint48)
	(can_traverse rover5 waypoint48 waypoint46)
	(can_traverse rover5 waypoint3 waypoint19)
	(can_traverse rover5 waypoint19 waypoint3)
	(can_traverse rover5 waypoint12 waypoint0)
	(can_traverse rover5 waypoint0 waypoint12)
	(can_traverse rover5 waypoint12 waypoint5)
	(can_traverse rover5 waypoint5 waypoint12)
	(can_traverse rover5 waypoint44 waypoint26)
	(can_traverse rover5 waypoint26 waypoint44)
	(can_traverse rover5 waypoint44 waypoint49)
	(can_traverse rover5 waypoint49 waypoint44)
	(can_traverse rover5 waypoint1 waypoint24)
	(can_traverse rover5 waypoint24 waypoint1)
	(can_traverse rover5 waypoint9 waypoint6)
	(can_traverse rover5 waypoint6 waypoint9)
	(can_traverse rover5 waypoint29 waypoint15)
	(can_traverse rover5 waypoint15 waypoint29)
	(at rover6 waypoint14)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(can_traverse rover6 waypoint14 waypoint5)
	(can_traverse rover6 waypoint5 waypoint14)
	(can_traverse rover6 waypoint14 waypoint10)
	(can_traverse rover6 waypoint10 waypoint14)
	(can_traverse rover6 waypoint14 waypoint25)
	(can_traverse rover6 waypoint25 waypoint14)
	(can_traverse rover6 waypoint14 waypoint30)
	(can_traverse rover6 waypoint30 waypoint14)
	(can_traverse rover6 waypoint14 waypoint46)
	(can_traverse rover6 waypoint46 waypoint14)
	(can_traverse rover6 waypoint14 waypoint48)
	(can_traverse rover6 waypoint48 waypoint14)
	(can_traverse rover6 waypoint5 waypoint0)
	(can_traverse rover6 waypoint0 waypoint5)
	(can_traverse rover6 waypoint5 waypoint12)
	(can_traverse rover6 waypoint12 waypoint5)
	(can_traverse rover6 waypoint5 waypoint15)
	(can_traverse rover6 waypoint15 waypoint5)
	(can_traverse rover6 waypoint5 waypoint19)
	(can_traverse rover6 waypoint19 waypoint5)
	(can_traverse rover6 waypoint5 waypoint40)
	(can_traverse rover6 waypoint40 waypoint5)
	(can_traverse rover6 waypoint10 waypoint13)
	(can_traverse rover6 waypoint13 waypoint10)
	(can_traverse rover6 waypoint10 waypoint20)
	(can_traverse rover6 waypoint20 waypoint10)
	(can_traverse rover6 waypoint10 waypoint22)
	(can_traverse rover6 waypoint22 waypoint10)
	(can_traverse rover6 waypoint10 waypoint32)
	(can_traverse rover6 waypoint32 waypoint10)
	(can_traverse rover6 waypoint10 waypoint35)
	(can_traverse rover6 waypoint35 waypoint10)
	(can_traverse rover6 waypoint10 waypoint37)
	(can_traverse rover6 waypoint37 waypoint10)
	(can_traverse rover6 waypoint10 waypoint44)
	(can_traverse rover6 waypoint44 waypoint10)
	(can_traverse rover6 waypoint25 waypoint6)
	(can_traverse rover6 waypoint6 waypoint25)
	(can_traverse rover6 waypoint25 waypoint16)
	(can_traverse rover6 waypoint16 waypoint25)
	(can_traverse rover6 waypoint25 waypoint18)
	(can_traverse rover6 waypoint18 waypoint25)
	(can_traverse rover6 waypoint25 waypoint47)
	(can_traverse rover6 waypoint47 waypoint25)
	(can_traverse rover6 waypoint30 waypoint3)
	(can_traverse rover6 waypoint3 waypoint30)
	(can_traverse rover6 waypoint30 waypoint7)
	(can_traverse rover6 waypoint7 waypoint30)
	(can_traverse rover6 waypoint30 waypoint8)
	(can_traverse rover6 waypoint8 waypoint30)
	(can_traverse rover6 waypoint30 waypoint33)
	(can_traverse rover6 waypoint33 waypoint30)
	(can_traverse rover6 waypoint46 waypoint43)
	(can_traverse rover6 waypoint43 waypoint46)
	(can_traverse rover6 waypoint48 waypoint17)
	(can_traverse rover6 waypoint17 waypoint48)
	(can_traverse rover6 waypoint48 waypoint21)
	(can_traverse rover6 waypoint21 waypoint48)
	(can_traverse rover6 waypoint0 waypoint9)
	(can_traverse rover6 waypoint9 waypoint0)
	(can_traverse rover6 waypoint0 waypoint26)
	(can_traverse rover6 waypoint26 waypoint0)
	(can_traverse rover6 waypoint0 waypoint29)
	(can_traverse rover6 waypoint29 waypoint0)
	(can_traverse rover6 waypoint12 waypoint2)
	(can_traverse rover6 waypoint2 waypoint12)
	(can_traverse rover6 waypoint15 waypoint11)
	(can_traverse rover6 waypoint11 waypoint15)
	(can_traverse rover6 waypoint15 waypoint38)
	(can_traverse rover6 waypoint38 waypoint15)
	(can_traverse rover6 waypoint19 waypoint1)
	(can_traverse rover6 waypoint1 waypoint19)
	(can_traverse rover6 waypoint19 waypoint4)
	(can_traverse rover6 waypoint4 waypoint19)
	(can_traverse rover6 waypoint19 waypoint23)
	(can_traverse rover6 waypoint23 waypoint19)
	(can_traverse rover6 waypoint13 waypoint39)
	(can_traverse rover6 waypoint39 waypoint13)
	(can_traverse rover6 waypoint13 waypoint42)
	(can_traverse rover6 waypoint42 waypoint13)
	(can_traverse rover6 waypoint20 waypoint36)
	(can_traverse rover6 waypoint36 waypoint20)
	(can_traverse rover6 waypoint20 waypoint41)
	(can_traverse rover6 waypoint41 waypoint20)
	(can_traverse rover6 waypoint20 waypoint45)
	(can_traverse rover6 waypoint45 waypoint20)
	(can_traverse rover6 waypoint20 waypoint49)
	(can_traverse rover6 waypoint49 waypoint20)
	(can_traverse rover6 waypoint32 waypoint24)
	(can_traverse rover6 waypoint24 waypoint32)
	(can_traverse rover6 waypoint32 waypoint34)
	(can_traverse rover6 waypoint34 waypoint32)
	(can_traverse rover6 waypoint35 waypoint28)
	(can_traverse rover6 waypoint28 waypoint35)
	(can_traverse rover6 waypoint35 waypoint31)
	(can_traverse rover6 waypoint31 waypoint35)
	(can_traverse rover6 waypoint33 waypoint27)
	(can_traverse rover6 waypoint27 waypoint33)
	(at rover7 waypoint34)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint34 waypoint1)
	(can_traverse rover7 waypoint1 waypoint34)
	(can_traverse rover7 waypoint34 waypoint9)
	(can_traverse rover7 waypoint9 waypoint34)
	(can_traverse rover7 waypoint34 waypoint16)
	(can_traverse rover7 waypoint16 waypoint34)
	(can_traverse rover7 waypoint34 waypoint21)
	(can_traverse rover7 waypoint21 waypoint34)
	(can_traverse rover7 waypoint34 waypoint23)
	(can_traverse rover7 waypoint23 waypoint34)
	(can_traverse rover7 waypoint34 waypoint27)
	(can_traverse rover7 waypoint27 waypoint34)
	(can_traverse rover7 waypoint34 waypoint29)
	(can_traverse rover7 waypoint29 waypoint34)
	(can_traverse rover7 waypoint34 waypoint37)
	(can_traverse rover7 waypoint37 waypoint34)
	(can_traverse rover7 waypoint34 waypoint41)
	(can_traverse rover7 waypoint41 waypoint34)
	(can_traverse rover7 waypoint1 waypoint19)
	(can_traverse rover7 waypoint19 waypoint1)
	(can_traverse rover7 waypoint1 waypoint24)
	(can_traverse rover7 waypoint24 waypoint1)
	(can_traverse rover7 waypoint1 waypoint43)
	(can_traverse rover7 waypoint43 waypoint1)
	(can_traverse rover7 waypoint9 waypoint2)
	(can_traverse rover7 waypoint2 waypoint9)
	(can_traverse rover7 waypoint9 waypoint6)
	(can_traverse rover7 waypoint6 waypoint9)
	(can_traverse rover7 waypoint9 waypoint11)
	(can_traverse rover7 waypoint11 waypoint9)
	(can_traverse rover7 waypoint9 waypoint47)
	(can_traverse rover7 waypoint47 waypoint9)
	(can_traverse rover7 waypoint16 waypoint3)
	(can_traverse rover7 waypoint3 waypoint16)
	(can_traverse rover7 waypoint16 waypoint4)
	(can_traverse rover7 waypoint4 waypoint16)
	(can_traverse rover7 waypoint16 waypoint25)
	(can_traverse rover7 waypoint25 waypoint16)
	(can_traverse rover7 waypoint16 waypoint42)
	(can_traverse rover7 waypoint42 waypoint16)
	(can_traverse rover7 waypoint16 waypoint46)
	(can_traverse rover7 waypoint46 waypoint16)
	(can_traverse rover7 waypoint21 waypoint7)
	(can_traverse rover7 waypoint7 waypoint21)
	(can_traverse rover7 waypoint21 waypoint30)
	(can_traverse rover7 waypoint30 waypoint21)
	(can_traverse rover7 waypoint21 waypoint48)
	(can_traverse rover7 waypoint48 waypoint21)
	(can_traverse rover7 waypoint23 waypoint13)
	(can_traverse rover7 waypoint13 waypoint23)
	(can_traverse rover7 waypoint23 waypoint49)
	(can_traverse rover7 waypoint49 waypoint23)
	(can_traverse rover7 waypoint27 waypoint32)
	(can_traverse rover7 waypoint32 waypoint27)
	(can_traverse rover7 waypoint27 waypoint33)
	(can_traverse rover7 waypoint33 waypoint27)
	(can_traverse rover7 waypoint27 waypoint45)
	(can_traverse rover7 waypoint45 waypoint27)
	(can_traverse rover7 waypoint29 waypoint0)
	(can_traverse rover7 waypoint0 waypoint29)
	(can_traverse rover7 waypoint29 waypoint15)
	(can_traverse rover7 waypoint15 waypoint29)
	(can_traverse rover7 waypoint29 waypoint39)
	(can_traverse rover7 waypoint39 waypoint29)
	(can_traverse rover7 waypoint37 waypoint8)
	(can_traverse rover7 waypoint8 waypoint37)
	(can_traverse rover7 waypoint37 waypoint35)
	(can_traverse rover7 waypoint35 waypoint37)
	(can_traverse rover7 waypoint37 waypoint36)
	(can_traverse rover7 waypoint36 waypoint37)
	(can_traverse rover7 waypoint37 waypoint40)
	(can_traverse rover7 waypoint40 waypoint37)
	(can_traverse rover7 waypoint41 waypoint22)
	(can_traverse rover7 waypoint22 waypoint41)
	(can_traverse rover7 waypoint19 waypoint5)
	(can_traverse rover7 waypoint5 waypoint19)
	(can_traverse rover7 waypoint19 waypoint38)
	(can_traverse rover7 waypoint38 waypoint19)
	(can_traverse rover7 waypoint19 waypoint44)
	(can_traverse rover7 waypoint44 waypoint19)
	(can_traverse rover7 waypoint24 waypoint18)
	(can_traverse rover7 waypoint18 waypoint24)
	(can_traverse rover7 waypoint24 waypoint28)
	(can_traverse rover7 waypoint28 waypoint24)
	(can_traverse rover7 waypoint43 waypoint14)
	(can_traverse rover7 waypoint14 waypoint43)
	(can_traverse rover7 waypoint2 waypoint12)
	(can_traverse rover7 waypoint12 waypoint2)
	(can_traverse rover7 waypoint42 waypoint31)
	(can_traverse rover7 waypoint31 waypoint42)
	(can_traverse rover7 waypoint30 waypoint17)
	(can_traverse rover7 waypoint17 waypoint30)
	(can_traverse rover7 waypoint13 waypoint10)
	(can_traverse rover7 waypoint10 waypoint13)
	(can_traverse rover7 waypoint49 waypoint20)
	(can_traverse rover7 waypoint20 waypoint49)
	(can_traverse rover7 waypoint0 waypoint26)
	(can_traverse rover7 waypoint26 waypoint0)
	(at rover8 waypoint13)
	(available rover8)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_imaging rover8)
	(can_traverse rover8 waypoint13 waypoint1)
	(can_traverse rover8 waypoint1 waypoint13)
	(can_traverse rover8 waypoint13 waypoint8)
	(can_traverse rover8 waypoint8 waypoint13)
	(can_traverse rover8 waypoint13 waypoint10)
	(can_traverse rover8 waypoint10 waypoint13)
	(can_traverse rover8 waypoint13 waypoint14)
	(can_traverse rover8 waypoint14 waypoint13)
	(can_traverse rover8 waypoint13 waypoint19)
	(can_traverse rover8 waypoint19 waypoint13)
	(can_traverse rover8 waypoint13 waypoint31)
	(can_traverse rover8 waypoint31 waypoint13)
	(can_traverse rover8 waypoint13 waypoint32)
	(can_traverse rover8 waypoint32 waypoint13)
	(can_traverse rover8 waypoint13 waypoint37)
	(can_traverse rover8 waypoint37 waypoint13)
	(can_traverse rover8 waypoint13 waypoint39)
	(can_traverse rover8 waypoint39 waypoint13)
	(can_traverse rover8 waypoint13 waypoint43)
	(can_traverse rover8 waypoint43 waypoint13)
	(can_traverse rover8 waypoint1 waypoint24)
	(can_traverse rover8 waypoint24 waypoint1)
	(can_traverse rover8 waypoint1 waypoint29)
	(can_traverse rover8 waypoint29 waypoint1)
	(can_traverse rover8 waypoint1 waypoint34)
	(can_traverse rover8 waypoint34 waypoint1)
	(can_traverse rover8 waypoint1 waypoint35)
	(can_traverse rover8 waypoint35 waypoint1)
	(can_traverse rover8 waypoint1 waypoint41)
	(can_traverse rover8 waypoint41 waypoint1)
	(can_traverse rover8 waypoint8 waypoint30)
	(can_traverse rover8 waypoint30 waypoint8)
	(can_traverse rover8 waypoint8 waypoint44)
	(can_traverse rover8 waypoint44 waypoint8)
	(can_traverse rover8 waypoint10 waypoint20)
	(can_traverse rover8 waypoint20 waypoint10)
	(can_traverse rover8 waypoint10 waypoint22)
	(can_traverse rover8 waypoint22 waypoint10)
	(can_traverse rover8 waypoint10 waypoint48)
	(can_traverse rover8 waypoint48 waypoint10)
	(can_traverse rover8 waypoint14 waypoint40)
	(can_traverse rover8 waypoint40 waypoint14)
	(can_traverse rover8 waypoint14 waypoint46)
	(can_traverse rover8 waypoint46 waypoint14)
	(can_traverse rover8 waypoint19 waypoint3)
	(can_traverse rover8 waypoint3 waypoint19)
	(can_traverse rover8 waypoint19 waypoint4)
	(can_traverse rover8 waypoint4 waypoint19)
	(can_traverse rover8 waypoint19 waypoint5)
	(can_traverse rover8 waypoint5 waypoint19)
	(can_traverse rover8 waypoint19 waypoint21)
	(can_traverse rover8 waypoint21 waypoint19)
	(can_traverse rover8 waypoint19 waypoint23)
	(can_traverse rover8 waypoint23 waypoint19)
	(can_traverse rover8 waypoint19 waypoint25)
	(can_traverse rover8 waypoint25 waypoint19)
	(can_traverse rover8 waypoint19 waypoint38)
	(can_traverse rover8 waypoint38 waypoint19)
	(can_traverse rover8 waypoint31 waypoint12)
	(can_traverse rover8 waypoint12 waypoint31)
	(can_traverse rover8 waypoint31 waypoint42)
	(can_traverse rover8 waypoint42 waypoint31)
	(can_traverse rover8 waypoint32 waypoint16)
	(can_traverse rover8 waypoint16 waypoint32)
	(can_traverse rover8 waypoint32 waypoint18)
	(can_traverse rover8 waypoint18 waypoint32)
	(can_traverse rover8 waypoint32 waypoint27)
	(can_traverse rover8 waypoint27 waypoint32)
	(can_traverse rover8 waypoint32 waypoint36)
	(can_traverse rover8 waypoint36 waypoint32)
	(can_traverse rover8 waypoint39 waypoint45)
	(can_traverse rover8 waypoint45 waypoint39)
	(can_traverse rover8 waypoint43 waypoint7)
	(can_traverse rover8 waypoint7 waypoint43)
	(can_traverse rover8 waypoint43 waypoint17)
	(can_traverse rover8 waypoint17 waypoint43)
	(can_traverse rover8 waypoint24 waypoint2)
	(can_traverse rover8 waypoint2 waypoint24)
	(can_traverse rover8 waypoint29 waypoint0)
	(can_traverse rover8 waypoint0 waypoint29)
	(can_traverse rover8 waypoint29 waypoint15)
	(can_traverse rover8 waypoint15 waypoint29)
	(can_traverse rover8 waypoint34 waypoint9)
	(can_traverse rover8 waypoint9 waypoint34)
	(can_traverse rover8 waypoint35 waypoint28)
	(can_traverse rover8 waypoint28 waypoint35)
	(can_traverse rover8 waypoint30 waypoint33)
	(can_traverse rover8 waypoint33 waypoint30)
	(can_traverse rover8 waypoint44 waypoint26)
	(can_traverse rover8 waypoint26 waypoint44)
	(can_traverse rover8 waypoint44 waypoint49)
	(can_traverse rover8 waypoint49 waypoint44)
	(can_traverse rover8 waypoint3 waypoint11)
	(can_traverse rover8 waypoint11 waypoint3)
	(can_traverse rover8 waypoint3 waypoint47)
	(can_traverse rover8 waypoint47 waypoint3)
	(can_traverse rover8 waypoint25 waypoint6)
	(can_traverse rover8 waypoint6 waypoint25)
	(at rover9 waypoint17)
	(available rover9)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(can_traverse rover9 waypoint17 waypoint5)
	(can_traverse rover9 waypoint5 waypoint17)
	(can_traverse rover9 waypoint17 waypoint18)
	(can_traverse rover9 waypoint18 waypoint17)
	(can_traverse rover9 waypoint17 waypoint30)
	(can_traverse rover9 waypoint30 waypoint17)
	(can_traverse rover9 waypoint17 waypoint35)
	(can_traverse rover9 waypoint35 waypoint17)
	(can_traverse rover9 waypoint17 waypoint45)
	(can_traverse rover9 waypoint45 waypoint17)
	(can_traverse rover9 waypoint17 waypoint48)
	(can_traverse rover9 waypoint48 waypoint17)
	(can_traverse rover9 waypoint5 waypoint0)
	(can_traverse rover9 waypoint0 waypoint5)
	(can_traverse rover9 waypoint5 waypoint12)
	(can_traverse rover9 waypoint12 waypoint5)
	(can_traverse rover9 waypoint5 waypoint14)
	(can_traverse rover9 waypoint14 waypoint5)
	(can_traverse rover9 waypoint5 waypoint15)
	(can_traverse rover9 waypoint15 waypoint5)
	(can_traverse rover9 waypoint5 waypoint19)
	(can_traverse rover9 waypoint19 waypoint5)
	(can_traverse rover9 waypoint18 waypoint6)
	(can_traverse rover9 waypoint6 waypoint18)
	(can_traverse rover9 waypoint18 waypoint24)
	(can_traverse rover9 waypoint24 waypoint18)
	(can_traverse rover9 waypoint18 waypoint32)
	(can_traverse rover9 waypoint32 waypoint18)
	(can_traverse rover9 waypoint18 waypoint36)
	(can_traverse rover9 waypoint36 waypoint18)
	(can_traverse rover9 waypoint18 waypoint43)
	(can_traverse rover9 waypoint43 waypoint18)
	(can_traverse rover9 waypoint18 waypoint49)
	(can_traverse rover9 waypoint49 waypoint18)
	(can_traverse rover9 waypoint30 waypoint3)
	(can_traverse rover9 waypoint3 waypoint30)
	(can_traverse rover9 waypoint30 waypoint8)
	(can_traverse rover9 waypoint8 waypoint30)
	(can_traverse rover9 waypoint30 waypoint21)
	(can_traverse rover9 waypoint21 waypoint30)
	(can_traverse rover9 waypoint30 waypoint23)
	(can_traverse rover9 waypoint23 waypoint30)
	(can_traverse rover9 waypoint30 waypoint33)
	(can_traverse rover9 waypoint33 waypoint30)
	(can_traverse rover9 waypoint30 waypoint37)
	(can_traverse rover9 waypoint37 waypoint30)
	(can_traverse rover9 waypoint30 waypoint44)
	(can_traverse rover9 waypoint44 waypoint30)
	(can_traverse rover9 waypoint35 waypoint1)
	(can_traverse rover9 waypoint1 waypoint35)
	(can_traverse rover9 waypoint35 waypoint4)
	(can_traverse rover9 waypoint4 waypoint35)
	(can_traverse rover9 waypoint35 waypoint9)
	(can_traverse rover9 waypoint9 waypoint35)
	(can_traverse rover9 waypoint35 waypoint25)
	(can_traverse rover9 waypoint25 waypoint35)
	(can_traverse rover9 waypoint35 waypoint28)
	(can_traverse rover9 waypoint28 waypoint35)
	(can_traverse rover9 waypoint35 waypoint41)
	(can_traverse rover9 waypoint41 waypoint35)
	(can_traverse rover9 waypoint45 waypoint27)
	(can_traverse rover9 waypoint27 waypoint45)
	(can_traverse rover9 waypoint45 waypoint47)
	(can_traverse rover9 waypoint47 waypoint45)
	(can_traverse rover9 waypoint48 waypoint10)
	(can_traverse rover9 waypoint10 waypoint48)
	(can_traverse rover9 waypoint0 waypoint11)
	(can_traverse rover9 waypoint11 waypoint0)
	(can_traverse rover9 waypoint12 waypoint2)
	(can_traverse rover9 waypoint2 waypoint12)
	(can_traverse rover9 waypoint12 waypoint31)
	(can_traverse rover9 waypoint31 waypoint12)
	(can_traverse rover9 waypoint14 waypoint13)
	(can_traverse rover9 waypoint13 waypoint14)
	(can_traverse rover9 waypoint14 waypoint40)
	(can_traverse rover9 waypoint40 waypoint14)
	(can_traverse rover9 waypoint15 waypoint29)
	(can_traverse rover9 waypoint29 waypoint15)
	(can_traverse rover9 waypoint15 waypoint38)
	(can_traverse rover9 waypoint38 waypoint15)
	(can_traverse rover9 waypoint32 waypoint16)
	(can_traverse rover9 waypoint16 waypoint32)
	(can_traverse rover9 waypoint32 waypoint20)
	(can_traverse rover9 waypoint20 waypoint32)
	(can_traverse rover9 waypoint32 waypoint34)
	(can_traverse rover9 waypoint34 waypoint32)
	(can_traverse rover9 waypoint36 waypoint39)
	(can_traverse rover9 waypoint39 waypoint36)
	(can_traverse rover9 waypoint43 waypoint42)
	(can_traverse rover9 waypoint42 waypoint43)
	(can_traverse rover9 waypoint43 waypoint46)
	(can_traverse rover9 waypoint46 waypoint43)
	(can_traverse rover9 waypoint49 waypoint7)
	(can_traverse rover9 waypoint7 waypoint49)
	(can_traverse rover9 waypoint33 waypoint22)
	(can_traverse rover9 waypoint22 waypoint33)
	(can_traverse rover9 waypoint44 waypoint26)
	(can_traverse rover9 waypoint26 waypoint44)
	(on_board camera0 rover0)
	(calibration_target camera0 objective3)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective7)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover5)
	(calibration_target camera2 objective3)
	(supports camera2 high_res)
	(on_board camera3 rover6)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover5)
	(calibration_target camera4 objective1)
	(supports camera4 high_res)
	(on_board camera5 rover6)
	(calibration_target camera5 objective4)
	(supports camera5 low_res)
	(on_board camera6 rover1)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover1)
	(calibration_target camera7 objective0)
	(supports camera7 low_res)
	(on_board camera8 rover4)
	(calibration_target camera8 objective1)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover5)
	(calibration_target camera9 objective5)
	(supports camera9 colour)
	(supports camera9 high_res)
	(supports camera9 low_res)
	(on_board camera10 rover9)
	(calibration_target camera10 objective1)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(on_board camera11 rover8)
	(calibration_target camera11 objective7)
	(supports camera11 low_res)
	(on_board camera12 rover2)
	(calibration_target camera12 objective5)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover7)
	(calibration_target camera13 objective0)
	(supports camera13 colour)
	(supports camera13 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint24)
	(visible_from objective1 waypoint25)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint32)
	(visible_from objective1 waypoint33)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint35)
	(visible_from objective1 waypoint36)
	(visible_from objective1 waypoint37)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint39)
	(visible_from objective1 waypoint40)
	(visible_from objective1 waypoint41)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint17)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint26)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint11)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint18)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint6)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint8)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint10)
	(visible_from objective7 waypoint11)
	(visible_from objective7 waypoint12)
	(visible_from objective7 waypoint13)
	(visible_from objective7 waypoint14)
	(visible_from objective7 waypoint15)
	(visible_from objective7 waypoint16)
	(visible_from objective7 waypoint17)
	(visible_from objective7 waypoint18)
	(visible_from objective7 waypoint19)
	(visible_from objective7 waypoint20)
	(visible_from objective7 waypoint21)
	(visible_from objective7 waypoint22)
	(visible_from objective7 waypoint23)
	(visible_from objective7 waypoint24)
	(visible_from objective7 waypoint25)
	(visible_from objective7 waypoint26)
	(visible_from objective7 waypoint27)
	(visible_from objective7 waypoint28)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint30)
	(visible_from objective7 waypoint31)
	(visible_from objective7 waypoint32)
	(visible_from objective7 waypoint33)
	(visible_from objective7 waypoint34)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint36)
	(visible_from objective7 waypoint37)
	(visible_from objective7 waypoint38)
	(visible_from objective7 waypoint39)
	(visible_from objective7 waypoint40)
	(visible_from objective7 waypoint41)
	(visible_from objective7 waypoint42)
	(visible_from objective7 waypoint43)
)

(:goal (and
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint25)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint43)
(communicated_image_data objective1 high_res)
(communicated_image_data objective6 high_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective5 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective1 low_res)
	)
)

(:metric minimize (total-time))
)
