(in-package :shop-openstacks)

#.(make-problem 'OS-SEQUENCEDSTRIPS-P40_2 'OPENSTACKS-SEQUENCEDSTRIPS-ADL-INCLUDED '((NEXT-COUNT
                                                                                      N0
                                                                                      N1)
                                                                                     (NEXT-COUNT
                                                                                      N1
                                                                                      N2)
                                                                                     (NEXT-COUNT
                                                                                      N2
                                                                                      N3)
                                                                                     (NEXT-COUNT
                                                                                      N3
                                                                                      N4)
                                                                                     (NEXT-COUNT
                                                                                      N4
                                                                                      N5)
                                                                                     (NEXT-COUNT
                                                                                      N5
                                                                                      N6)
                                                                                     (NEXT-COUNT
                                                                                      N6
                                                                                      N7)
                                                                                     (NEXT-COUNT
                                                                                      N7
                                                                                      N8)
                                                                                     (NEXT-COUNT
                                                                                      N8
                                                                                      N9)
                                                                                     (NEXT-COUNT
                                                                                      N9
                                                                                      N10)
                                                                                     (NEXT-COUNT
                                                                                      N10
                                                                                      N11)
                                                                                     (NEXT-COUNT
                                                                                      N11
                                                                                      N12)
                                                                                     (NEXT-COUNT
                                                                                      N12
                                                                                      N13)
                                                                                     (NEXT-COUNT
                                                                                      N13
                                                                                      N14)
                                                                                     (NEXT-COUNT
                                                                                      N14
                                                                                      N15)
                                                                                     (NEXT-COUNT
                                                                                      N15
                                                                                      N16)
                                                                                     (NEXT-COUNT
                                                                                      N16
                                                                                      N17)
                                                                                     (NEXT-COUNT
                                                                                      N17
                                                                                      N18)
                                                                                     (NEXT-COUNT
                                                                                      N18
                                                                                      N19)
                                                                                     (NEXT-COUNT
                                                                                      N19
                                                                                      N20)
                                                                                     (NEXT-COUNT
                                                                                      N20
                                                                                      N21)
                                                                                     (NEXT-COUNT
                                                                                      N21
                                                                                      N22)
                                                                                     (NEXT-COUNT
                                                                                      N22
                                                                                      N23)
                                                                                     (NEXT-COUNT
                                                                                      N23
                                                                                      N24)
                                                                                     (NEXT-COUNT
                                                                                      N24
                                                                                      N25)
                                                                                     (NEXT-COUNT
                                                                                      N25
                                                                                      N26)
                                                                                     (NEXT-COUNT
                                                                                      N26
                                                                                      N27)
                                                                                     (NEXT-COUNT
                                                                                      N27
                                                                                      N28)
                                                                                     (NEXT-COUNT
                                                                                      N28
                                                                                      N29)
                                                                                     (NEXT-COUNT
                                                                                      N29
                                                                                      N30)
                                                                                     (NEXT-COUNT
                                                                                      N30
                                                                                      N31)
                                                                                     (NEXT-COUNT
                                                                                      N31
                                                                                      N32)
                                                                                     (NEXT-COUNT
                                                                                      N32
                                                                                      N33)
                                                                                     (NEXT-COUNT
                                                                                      N33
                                                                                      N34)
                                                                                     (NEXT-COUNT
                                                                                      N34
                                                                                      N35)
                                                                                     (NEXT-COUNT
                                                                                      N35
                                                                                      N36)
                                                                                     (NEXT-COUNT
                                                                                      N36
                                                                                      N37)
                                                                                     (NEXT-COUNT
                                                                                      N37
                                                                                      N38)
                                                                                     (NEXT-COUNT
                                                                                      N38
                                                                                      N39)
                                                                                     (NEXT-COUNT
                                                                                      N39
                                                                                      N40)
                                                                                     (STACKS-AVAIL
                                                                                      N0)
                                                                                     (WAITING
                                                                                      O1)
                                                                                     (INCLUDES
                                                                                      O1
                                                                                      P36)
                                                                                     (WAITING
                                                                                      O2)
                                                                                     (INCLUDES
                                                                                      O2
                                                                                      P31)
                                                                                     (WAITING
                                                                                      O3)
                                                                                     (INCLUDES
                                                                                      O3
                                                                                      P26)
                                                                                     (WAITING
                                                                                      O4)
                                                                                     (INCLUDES
                                                                                      O4
                                                                                      P36)
                                                                                     (INCLUDES
                                                                                      O4
                                                                                      P38)
                                                                                     (WAITING
                                                                                      O5)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O5
                                                                                      P27)
                                                                                     (WAITING
                                                                                      O6)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P20)
                                                                                     (INCLUDES
                                                                                      O6
                                                                                      P40)
                                                                                     (WAITING
                                                                                      O7)
                                                                                     (INCLUDES
                                                                                      O7
                                                                                      P36)
                                                                                     (WAITING
                                                                                      O8)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P14)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P19)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P20)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P21)
                                                                                     (INCLUDES
                                                                                      O8
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O9)
                                                                                     (INCLUDES
                                                                                      O9
                                                                                      P37)
                                                                                     (WAITING
                                                                                      O10)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P29)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P37)
                                                                                     (INCLUDES
                                                                                      O10
                                                                                      P38)
                                                                                     (WAITING
                                                                                      O11)
                                                                                     (INCLUDES
                                                                                      O11
                                                                                      P13)
                                                                                     (WAITING
                                                                                      O12)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P1)
                                                                                     (INCLUDES
                                                                                      O12
                                                                                      P19)
                                                                                     (WAITING
                                                                                      O13)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P6)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P11)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P17)
                                                                                     (INCLUDES
                                                                                      O13
                                                                                      P24)
                                                                                     (WAITING
                                                                                      O14)
                                                                                     (INCLUDES
                                                                                      O14
                                                                                      P35)
                                                                                     (WAITING
                                                                                      O15)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P3)
                                                                                     (INCLUDES
                                                                                      O15
                                                                                      P9)
                                                                                     (WAITING
                                                                                      O16)
                                                                                     (INCLUDES
                                                                                      O16
                                                                                      P7)
                                                                                     (WAITING
                                                                                      O17)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P4)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O17
                                                                                      P17)
                                                                                     (WAITING
                                                                                      O18)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O18
                                                                                      P23)
                                                                                     (WAITING
                                                                                      O19)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P22)
                                                                                     (INCLUDES
                                                                                      O19
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O20)
                                                                                     (INCLUDES
                                                                                      O20
                                                                                      P20)
                                                                                     (WAITING
                                                                                      O21)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P25)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P26)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P30)
                                                                                     (INCLUDES
                                                                                      O21
                                                                                      P37)
                                                                                     (WAITING
                                                                                      O22)
                                                                                     (INCLUDES
                                                                                      O22
                                                                                      P12)
                                                                                     (WAITING
                                                                                      O23)
                                                                                     (INCLUDES
                                                                                      O23
                                                                                      P33)
                                                                                     (WAITING
                                                                                      O24)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P14)
                                                                                     (INCLUDES
                                                                                      O24
                                                                                      P39)
                                                                                     (WAITING
                                                                                      O25)
                                                                                     (INCLUDES
                                                                                      O25
                                                                                      P13)
                                                                                     (WAITING
                                                                                      O26)
                                                                                     (INCLUDES
                                                                                      O26
                                                                                      P10)
                                                                                     (WAITING
                                                                                      O27)
                                                                                     (INCLUDES
                                                                                      O27
                                                                                      P13)
                                                                                     (WAITING
                                                                                      O28)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P13)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P15)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P16)
                                                                                     (INCLUDES
                                                                                      O28
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O29)
                                                                                     (INCLUDES
                                                                                      O29
                                                                                      P32)
                                                                                     (WAITING
                                                                                      O30)
                                                                                     (INCLUDES
                                                                                      O30
                                                                                      P5)
                                                                                     (INCLUDES
                                                                                      O30
                                                                                      P8)
                                                                                     (WAITING
                                                                                      O31)
                                                                                     (INCLUDES
                                                                                      O31
                                                                                      P31)
                                                                                     (WAITING
                                                                                      O32)
                                                                                     (INCLUDES
                                                                                      O32
                                                                                      P7)
                                                                                     (INCLUDES
                                                                                      O32
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O32
                                                                                      P11)
                                                                                     (WAITING
                                                                                      O33)
                                                                                     (INCLUDES
                                                                                      O33
                                                                                      P5)
                                                                                     (WAITING
                                                                                      O34)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P18)
                                                                                     (INCLUDES
                                                                                      O34
                                                                                      P28)
                                                                                     (WAITING
                                                                                      O35)
                                                                                     (INCLUDES
                                                                                      O35
                                                                                      P9)
                                                                                     (INCLUDES
                                                                                      O35
                                                                                      P15)
                                                                                     (WAITING
                                                                                      O36)
                                                                                     (INCLUDES
                                                                                      O36
                                                                                      P2)
                                                                                     (INCLUDES
                                                                                      O36
                                                                                      P10)
                                                                                     (INCLUDES
                                                                                      O36
                                                                                      P13)
                                                                                     (WAITING
                                                                                      O37)
                                                                                     (INCLUDES
                                                                                      O37
                                                                                      P11)
                                                                                     (INCLUDES
                                                                                      O37
                                                                                      P19)
                                                                                     (WAITING
                                                                                      O38)
                                                                                     (INCLUDES
                                                                                      O38
                                                                                      P34)
                                                                                     (INCLUDES
                                                                                      O38
                                                                                      P37)
                                                                                     (WAITING
                                                                                      O39)
                                                                                     (INCLUDES
                                                                                      O39
                                                                                      P5)
                                                                                     (WAITING
                                                                                      O40)
                                                                                     (INCLUDES
                                                                                      O40
                                                                                      P17)
                                                                                     (=
                                                                                      (TOTAL-COST)
                                                                                      0)
                                                                                     (COUNT
                                                                                      N0)
                                                                                     (COUNT
                                                                                      N1)
                                                                                     (COUNT
                                                                                      N2)
                                                                                     (COUNT
                                                                                      N3)
                                                                                     (COUNT
                                                                                      N4)
                                                                                     (COUNT
                                                                                      N5)
                                                                                     (COUNT
                                                                                      N6)
                                                                                     (COUNT
                                                                                      N7)
                                                                                     (COUNT
                                                                                      N8)
                                                                                     (COUNT
                                                                                      N9)
                                                                                     (COUNT
                                                                                      N10)
                                                                                     (COUNT
                                                                                      N11)
                                                                                     (COUNT
                                                                                      N12)
                                                                                     (COUNT
                                                                                      N13)
                                                                                     (COUNT
                                                                                      N14)
                                                                                     (COUNT
                                                                                      N15)
                                                                                     (COUNT
                                                                                      N16)
                                                                                     (COUNT
                                                                                      N17)
                                                                                     (COUNT
                                                                                      N18)
                                                                                     (COUNT
                                                                                      N19)
                                                                                     (COUNT
                                                                                      N20)
                                                                                     (COUNT
                                                                                      N21)
                                                                                     (COUNT
                                                                                      N22)
                                                                                     (COUNT
                                                                                      N23)
                                                                                     (COUNT
                                                                                      N24)
                                                                                     (COUNT
                                                                                      N25)
                                                                                     (COUNT
                                                                                      N26)
                                                                                     (COUNT
                                                                                      N27)
                                                                                     (COUNT
                                                                                      N28)
                                                                                     (COUNT
                                                                                      N29)
                                                                                     (COUNT
                                                                                      N30)
                                                                                     (COUNT
                                                                                      N31)
                                                                                     (COUNT
                                                                                      N32)
                                                                                     (COUNT
                                                                                      N33)
                                                                                     (COUNT
                                                                                      N34)
                                                                                     (COUNT
                                                                                      N35)
                                                                                     (COUNT
                                                                                      N36)
                                                                                     (COUNT
                                                                                      N37)
                                                                                     (COUNT
                                                                                      N38)
                                                                                     (COUNT
                                                                                      N39)
                                                                                     (COUNT
                                                                                      N40)
                                                                                     (ORDER
                                                                                      O1)
                                                                                     (ORDER
                                                                                      O2)
                                                                                     (ORDER
                                                                                      O3)
                                                                                     (ORDER
                                                                                      O4)
                                                                                     (ORDER
                                                                                      O5)
                                                                                     (ORDER
                                                                                      O6)
                                                                                     (ORDER
                                                                                      O7)
                                                                                     (ORDER
                                                                                      O8)
                                                                                     (ORDER
                                                                                      O9)
                                                                                     (ORDER
                                                                                      O10)
                                                                                     (ORDER
                                                                                      O11)
                                                                                     (ORDER
                                                                                      O12)
                                                                                     (ORDER
                                                                                      O13)
                                                                                     (ORDER
                                                                                      O14)
                                                                                     (ORDER
                                                                                      O15)
                                                                                     (ORDER
                                                                                      O16)
                                                                                     (ORDER
                                                                                      O17)
                                                                                     (ORDER
                                                                                      O18)
                                                                                     (ORDER
                                                                                      O19)
                                                                                     (ORDER
                                                                                      O20)
                                                                                     (ORDER
                                                                                      O21)
                                                                                     (ORDER
                                                                                      O22)
                                                                                     (ORDER
                                                                                      O23)
                                                                                     (ORDER
                                                                                      O24)
                                                                                     (ORDER
                                                                                      O25)
                                                                                     (ORDER
                                                                                      O26)
                                                                                     (ORDER
                                                                                      O27)
                                                                                     (ORDER
                                                                                      O28)
                                                                                     (ORDER
                                                                                      O29)
                                                                                     (ORDER
                                                                                      O30)
                                                                                     (ORDER
                                                                                      O31)
                                                                                     (ORDER
                                                                                      O32)
                                                                                     (ORDER
                                                                                      O33)
                                                                                     (ORDER
                                                                                      O34)
                                                                                     (ORDER
                                                                                      O35)
                                                                                     (ORDER
                                                                                      O36)
                                                                                     (ORDER
                                                                                      O37)
                                                                                     (ORDER
                                                                                      O38)
                                                                                     (ORDER
                                                                                      O39)
                                                                                     (ORDER
                                                                                      O40)
                                                                                     (PRODUCT
                                                                                      P1)
                                                                                     (PRODUCT
                                                                                      P2)
                                                                                     (PRODUCT
                                                                                      P3)
                                                                                     (PRODUCT
                                                                                      P4)
                                                                                     (PRODUCT
                                                                                      P5)
                                                                                     (PRODUCT
                                                                                      P6)
                                                                                     (PRODUCT
                                                                                      P7)
                                                                                     (PRODUCT
                                                                                      P8)
                                                                                     (PRODUCT
                                                                                      P9)
                                                                                     (PRODUCT
                                                                                      P10)
                                                                                     (PRODUCT
                                                                                      P11)
                                                                                     (PRODUCT
                                                                                      P12)
                                                                                     (PRODUCT
                                                                                      P13)
                                                                                     (PRODUCT
                                                                                      P14)
                                                                                     (PRODUCT
                                                                                      P15)
                                                                                     (PRODUCT
                                                                                      P16)
                                                                                     (PRODUCT
                                                                                      P17)
                                                                                     (PRODUCT
                                                                                      P18)
                                                                                     (PRODUCT
                                                                                      P19)
                                                                                     (PRODUCT
                                                                                      P20)
                                                                                     (PRODUCT
                                                                                      P21)
                                                                                     (PRODUCT
                                                                                      P22)
                                                                                     (PRODUCT
                                                                                      P23)
                                                                                     (PRODUCT
                                                                                      P24)
                                                                                     (PRODUCT
                                                                                      P25)
                                                                                     (PRODUCT
                                                                                      P26)
                                                                                     (PRODUCT
                                                                                      P27)
                                                                                     (PRODUCT
                                                                                      P28)
                                                                                     (PRODUCT
                                                                                      P29)
                                                                                     (PRODUCT
                                                                                      P30)
                                                                                     (PRODUCT
                                                                                      P31)
                                                                                     (PRODUCT
                                                                                      P32)
                                                                                     (PRODUCT
                                                                                      P33)
                                                                                     (PRODUCT
                                                                                      P34)
                                                                                     (PRODUCT
                                                                                      P35)
                                                                                     (PRODUCT
                                                                                      P36)
                                                                                     (PRODUCT
                                                                                      P37)
                                                                                     (PRODUCT
                                                                                      P38)
                                                                                     (PRODUCT
                                                                                      P39)
                                                                                     (PRODUCT
                                                                                      P40)
                                                                                     (:GOAL
                                                                                      (AND
                                                                                       (SHIPPED
                                                                                        O1)
                                                                                       (SHIPPED
                                                                                        O2)
                                                                                       (SHIPPED
                                                                                        O3)
                                                                                       (SHIPPED
                                                                                        O4)
                                                                                       (SHIPPED
                                                                                        O5)
                                                                                       (SHIPPED
                                                                                        O6)
                                                                                       (SHIPPED
                                                                                        O7)
                                                                                       (SHIPPED
                                                                                        O8)
                                                                                       (SHIPPED
                                                                                        O9)
                                                                                       (SHIPPED
                                                                                        O10)
                                                                                       (SHIPPED
                                                                                        O11)
                                                                                       (SHIPPED
                                                                                        O12)
                                                                                       (SHIPPED
                                                                                        O13)
                                                                                       (SHIPPED
                                                                                        O14)
                                                                                       (SHIPPED
                                                                                        O15)
                                                                                       (SHIPPED
                                                                                        O16)
                                                                                       (SHIPPED
                                                                                        O17)
                                                                                       (SHIPPED
                                                                                        O18)
                                                                                       (SHIPPED
                                                                                        O19)
                                                                                       (SHIPPED
                                                                                        O20)
                                                                                       (SHIPPED
                                                                                        O21)
                                                                                       (SHIPPED
                                                                                        O22)
                                                                                       (SHIPPED
                                                                                        O23)
                                                                                       (SHIPPED
                                                                                        O24)
                                                                                       (SHIPPED
                                                                                        O25)
                                                                                       (SHIPPED
                                                                                        O26)
                                                                                       (SHIPPED
                                                                                        O27)
                                                                                       (SHIPPED
                                                                                        O28)
                                                                                       (SHIPPED
                                                                                        O29)
                                                                                       (SHIPPED
                                                                                        O30)
                                                                                       (SHIPPED
                                                                                        O31)
                                                                                       (SHIPPED
                                                                                        O32)
                                                                                       (SHIPPED
                                                                                        O33)
                                                                                       (SHIPPED
                                                                                        O34)
                                                                                       (SHIPPED
                                                                                        O35)
                                                                                       (SHIPPED
                                                                                        O36)
                                                                                       (SHIPPED
                                                                                        O37)
                                                                                       (SHIPPED
                                                                                        O38)
                                                                                       (SHIPPED
                                                                                        O39)
                                                                                       (SHIPPED
                                                                                        O40)))) '(:TASK
                                                                                                  PLAN)) 