#!/bin/bash
# Assumptions:
# 1.  Executed from shop/jenkins/ directory.
# 2.  There is a directory, on jenkins, the workspace, that contains a
# checked out copy of shop (checked out as "shop-trunk/" and has a
# copy of asdf in it.
# 3.  The environment variable LISP specifies the name of the lisp
# implementation to test.  See start-lisp.sh to see how to specify an
# executable path for the lisp implementations, if you don't have them
# in your path.
# 4.  If you want this to work /outside/ Jenkins, bind the WORKSPACE
# environment variable to a directory configured per (2), above.

# set up temporary directory for writing fasls
if [ -e tmp ]; then
    rm -r tmp
fi
mkdir -p /tmp/fasls

export CL_SOURCE_REGISTRY="${WORKSPACE}/shop-trunk//:"
export ASDF_OUTPUT_TRANSLATIONS="(:output-translations (T (\"${WORKSPACE}/tmp/fasls\" :implementation)) :ignore-inherited-configuration)"

source ./start-lisp.sh
( DO $lisp_command $lisp_eval '(load "build-shop2.lisp")' )

if (( $? ))
  then
    exit 1
  fi

( DO $lisp_command $lisp_eval '(load "test-shop2.lisp")' )

if (( $? ))
  then
    exit 1
  fi

exit 0



# Local Variables:
# mode: sh
# End:
