(define (problem depotprob6587) (:domain Depot)
(:objects
	depot0 depot1 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 truck2 truck3 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - Hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate4)
	(at pallet2 distributor0)
	(clear crate9)
	(at pallet3 distributor1)
	(clear crate7)
	(at pallet4 distributor0)
	(clear crate2)
	(at pallet5 distributor1)
	(clear crate1)
	(at pallet6 depot0)
	(clear crate3)
	(at pallet7 distributor1)
	(clear crate8)
	(at truck0 depot1)
	(= (speed truck0) 2)
	(at truck1 distributor1)
	(= (speed truck1) 2)
	(at truck2 depot1)
	(= (speed truck2) 8)
	(at truck3 depot0)
	(= (speed truck3) 5)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 5)
	(at hoist1 depot1)
	(available hoist1)
	(= (power hoist1) 4)
	(at hoist2 distributor0)
	(available hoist2)
	(= (power hoist2) 2)
	(at hoist3 distributor1)
	(available hoist3)
	(= (power hoist3) 4)
	(at hoist4 depot0)
	(available hoist4)
	(= (power hoist4) 4)
	(at hoist5 depot0)
	(available hoist5)
	(= (power hoist5) 5)
	(at hoist6 depot0)
	(available hoist6)
	(= (power hoist6) 10)
	(at hoist7 distributor1)
	(available hoist7)
	(= (power hoist7) 1)
	(at crate0 distributor1)
	(on crate0 pallet3)
	(= (weight crate0) 92)
	(at crate1 distributor1)
	(on crate1 pallet5)
	(= (weight crate1) 8)
	(at crate2 distributor0)
	(on crate2 pallet4)
	(= (weight crate2) 65)
	(at crate3 depot0)
	(on crate3 pallet6)
	(= (weight crate3) 14)
	(at crate4 depot1)
	(on crate4 pallet1)
	(= (weight crate4) 3)
	(at crate5 distributor1)
	(on crate5 crate0)
	(= (weight crate5) 13)
	(at crate6 distributor1)
	(on crate6 pallet7)
	(= (weight crate6) 33)
	(at crate7 distributor1)
	(on crate7 crate5)
	(= (weight crate7) 76)
	(at crate8 distributor1)
	(on crate8 crate6)
	(= (weight crate8) 31)
	(at crate9 distributor0)
	(on crate9 pallet2)
	(= (weight crate9) 91)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 depot1) 10)
	(= (distance depot0 distributor0) 1)
	(= (distance depot0 distributor1) 6)
	(= (distance depot1 depot0) 10)
	(= (distance depot1 depot1) 0)
	(= (distance depot1 distributor0) 6)
	(= (distance depot1 distributor1) 8)
	(= (distance distributor0 depot0) 3)
	(= (distance distributor0 depot1) 8)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 5)
	(= (distance distributor1 depot0) 10)
	(= (distance distributor1 depot1) 1)
	(= (distance distributor1 distributor0) 8)
	(= (distance distributor1 distributor1) 0)
)

(:goal (and
		(on crate1 pallet7)
		(on crate2 pallet4)
		(on crate3 crate8)
		(on crate4 pallet0)
		(on crate6 pallet1)
		(on crate7 crate3)
		(on crate8 pallet6)
	)
)

(:metric minimize (total-time)))
