(define (problem depotprob6512) (:domain Depot)
(:objects
	depot0 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - Crate
	hoist0 hoist1 hoist2 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate7)
	(at pallet1 distributor0)
	(clear crate2)
	(at pallet2 distributor1)
	(clear crate6)
	(at truck0 distributor1)
	(= (speed truck0) 4)
	(at truck1 distributor1)
	(= (speed truck1) 5)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 3)
	(at hoist1 distributor0)
	(available hoist1)
	(= (power hoist1) 7)
	(at hoist2 distributor1)
	(available hoist2)
	(= (power hoist2) 9)
	(at crate0 depot0)
	(on crate0 pallet0)
	(= (weight crate0) 6)
	(at crate1 depot0)
	(on crate1 crate0)
	(= (weight crate1) 22)
	(at crate2 distributor0)
	(on crate2 pallet1)
	(= (weight crate2) 23)
	(at crate3 distributor1)
	(on crate3 pallet2)
	(= (weight crate3) 87)
	(at crate4 depot0)
	(on crate4 crate1)
	(= (weight crate4) 89)
	(at crate5 distributor1)
	(on crate5 crate3)
	(= (weight crate5) 50)
	(at crate6 distributor1)
	(on crate6 crate5)
	(= (weight crate6) 18)
	(at crate7 depot0)
	(on crate7 crate4)
	(= (weight crate7) 93)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 distributor0) 5)
	(= (distance depot0 distributor1) 4)
	(= (distance distributor0 depot0) 6)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 10)
	(= (distance distributor1 depot0) 5)
	(= (distance distributor1 distributor0) 2)
	(= (distance distributor1 distributor1) 0)
)

(:goal (and
		(on crate0 crate4)
		(on crate2 crate6)
		(on crate4 crate7)
		(on crate5 pallet2)
		(on crate6 pallet1)
		(on crate7 pallet0)
	)
)

(:metric minimize (total-time)))
