(define (problem depotprob1817) (:domain Depot)
(:objects
	depot0 depot1 depot2 depot3 depot4 depot5 - Depot
	distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - Distributor
	truck0 truck1 truck2 truck3 truck4 truck5 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 pallet12 pallet13 pallet14 pallet15 pallet16 pallet17 pallet18 pallet19 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 crate15 crate16 crate17 crate18 crate19 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 hoist12 hoist13 hoist14 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 depot1)
	(clear crate17)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 depot4)
	(clear pallet4)
	(at pallet5 depot5)
	(clear crate8)
	(at pallet6 distributor0)
	(clear pallet6)
	(at pallet7 distributor1)
	(clear crate19)
	(at pallet8 distributor2)
	(clear crate13)
	(at pallet9 distributor3)
	(clear crate16)
	(at pallet10 distributor4)
	(clear crate14)
	(at pallet11 distributor5)
	(clear crate0)
	(at pallet12 distributor4)
	(clear crate18)
	(at pallet13 distributor2)
	(clear crate15)
	(at pallet14 depot3)
	(clear pallet14)
	(at pallet15 depot3)
	(clear pallet15)
	(at pallet16 distributor1)
	(clear pallet16)
	(at pallet17 distributor2)
	(clear crate6)
	(at pallet18 distributor3)
	(clear pallet18)
	(at pallet19 distributor1)
	(clear pallet19)
	(at truck0 depot2)
	(= (speed truck0) 7)
	(at truck1 distributor4)
	(= (speed truck1) 1)
	(at truck2 distributor2)
	(= (speed truck2) 10)
	(at truck3 depot0)
	(= (speed truck3) 3)
	(at truck4 distributor3)
	(= (speed truck4) 8)
	(at truck5 distributor0)
	(= (speed truck5) 4)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 3)
	(at hoist1 depot1)
	(available hoist1)
	(= (power hoist1) 2)
	(at hoist2 depot2)
	(available hoist2)
	(= (power hoist2) 2)
	(at hoist3 depot3)
	(available hoist3)
	(= (power hoist3) 10)
	(at hoist4 depot4)
	(available hoist4)
	(= (power hoist4) 1)
	(at hoist5 depot5)
	(available hoist5)
	(= (power hoist5) 7)
	(at hoist6 distributor0)
	(available hoist6)
	(= (power hoist6) 6)
	(at hoist7 distributor1)
	(available hoist7)
	(= (power hoist7) 10)
	(at hoist8 distributor2)
	(available hoist8)
	(= (power hoist8) 5)
	(at hoist9 distributor3)
	(available hoist9)
	(= (power hoist9) 2)
	(at hoist10 distributor4)
	(available hoist10)
	(= (power hoist10) 9)
	(at hoist11 distributor5)
	(available hoist11)
	(= (power hoist11) 4)
	(at hoist12 depot0)
	(available hoist12)
	(= (power hoist12) 10)
	(at hoist13 depot5)
	(available hoist13)
	(= (power hoist13) 9)
	(at hoist14 depot5)
	(available hoist14)
	(= (power hoist14) 6)
	(at crate0 distributor5)
	(on crate0 pallet11)
	(= (weight crate0) 86)
	(at crate1 depot0)
	(on crate1 pallet0)
	(= (weight crate1) 47)
	(at crate2 distributor4)
	(on crate2 pallet10)
	(= (weight crate2) 93)
	(at crate3 distributor2)
	(on crate3 pallet8)
	(= (weight crate3) 92)
	(at crate4 distributor1)
	(on crate4 pallet7)
	(= (weight crate4) 36)
	(at crate5 distributor4)
	(on crate5 crate2)
	(= (weight crate5) 1)
	(at crate6 distributor2)
	(on crate6 pallet17)
	(= (weight crate6) 27)
	(at crate7 depot5)
	(on crate7 pallet5)
	(= (weight crate7) 37)
	(at crate8 depot5)
	(on crate8 crate7)
	(= (weight crate8) 50)
	(at crate9 depot0)
	(on crate9 crate1)
	(= (weight crate9) 60)
	(at crate10 depot0)
	(on crate10 crate9)
	(= (weight crate10) 57)
	(at crate11 distributor3)
	(on crate11 pallet9)
	(= (weight crate11) 80)
	(at crate12 depot1)
	(on crate12 pallet1)
	(= (weight crate12) 75)
	(at crate13 distributor2)
	(on crate13 crate3)
	(= (weight crate13) 76)
	(at crate14 distributor4)
	(on crate14 crate5)
	(= (weight crate14) 84)
	(at crate15 distributor2)
	(on crate15 pallet13)
	(= (weight crate15) 2)
	(at crate16 distributor3)
	(on crate16 crate11)
	(= (weight crate16) 13)
	(at crate17 depot1)
	(on crate17 crate12)
	(= (weight crate17) 70)
	(at crate18 distributor4)
	(on crate18 pallet12)
	(= (weight crate18) 2)
	(at crate19 distributor1)
	(on crate19 crate4)
	(= (weight crate19) 48)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 depot1) 1)
	(= (distance depot0 depot2) 4)
	(= (distance depot0 depot3) 7)
	(= (distance depot0 depot4) 7)
	(= (distance depot0 depot5) 8)
	(= (distance depot0 distributor0) 10)
	(= (distance depot0 distributor1) 6)
	(= (distance depot0 distributor2) 1)
	(= (distance depot0 distributor3) 9)
	(= (distance depot0 distributor4) 2)
	(= (distance depot0 distributor5) 7)
	(= (distance depot1 depot0) 2)
	(= (distance depot1 depot1) 0)
	(= (distance depot1 depot2) 8)
	(= (distance depot1 depot3) 2)
	(= (distance depot1 depot4) 10)
	(= (distance depot1 depot5) 2)
	(= (distance depot1 distributor0) 7)
	(= (distance depot1 distributor1) 1)
	(= (distance depot1 distributor2) 5)
	(= (distance depot1 distributor3) 5)
	(= (distance depot1 distributor4) 6)
	(= (distance depot1 distributor5) 9)
	(= (distance depot2 depot0) 4)
	(= (distance depot2 depot1) 5)
	(= (distance depot2 depot2) 0)
	(= (distance depot2 depot3) 5)
	(= (distance depot2 depot4) 3)
	(= (distance depot2 depot5) 3)
	(= (distance depot2 distributor0) 1)
	(= (distance depot2 distributor1) 4)
	(= (distance depot2 distributor2) 3)
	(= (distance depot2 distributor3) 5)
	(= (distance depot2 distributor4) 1)
	(= (distance depot2 distributor5) 9)
	(= (distance depot3 depot0) 3)
	(= (distance depot3 depot1) 10)
	(= (distance depot3 depot2) 5)
	(= (distance depot3 depot3) 0)
	(= (distance depot3 depot4) 8)
	(= (distance depot3 depot5) 6)
	(= (distance depot3 distributor0) 10)
	(= (distance depot3 distributor1) 10)
	(= (distance depot3 distributor2) 2)
	(= (distance depot3 distributor3) 7)
	(= (distance depot3 distributor4) 1)
	(= (distance depot3 distributor5) 1)
	(= (distance depot4 depot0) 9)
	(= (distance depot4 depot1) 8)
	(= (distance depot4 depot2) 2)
	(= (distance depot4 depot3) 3)
	(= (distance depot4 depot4) 0)
	(= (distance depot4 depot5) 8)
	(= (distance depot4 distributor0) 2)
	(= (distance depot4 distributor1) 5)
	(= (distance depot4 distributor2) 3)
	(= (distance depot4 distributor3) 3)
	(= (distance depot4 distributor4) 10)
	(= (distance depot4 distributor5) 5)
	(= (distance depot5 depot0) 6)
	(= (distance depot5 depot1) 1)
	(= (distance depot5 depot2) 9)
	(= (distance depot5 depot3) 8)
	(= (distance depot5 depot4) 6)
	(= (distance depot5 depot5) 0)
	(= (distance depot5 distributor0) 7)
	(= (distance depot5 distributor1) 8)
	(= (distance depot5 distributor2) 9)
	(= (distance depot5 distributor3) 1)
	(= (distance depot5 distributor4) 1)
	(= (distance depot5 distributor5) 6)
	(= (distance distributor0 depot0) 7)
	(= (distance distributor0 depot1) 10)
	(= (distance distributor0 depot2) 6)
	(= (distance distributor0 depot3) 8)
	(= (distance distributor0 depot4) 6)
	(= (distance distributor0 depot5) 6)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 4)
	(= (distance distributor0 distributor2) 3)
	(= (distance distributor0 distributor3) 1)
	(= (distance distributor0 distributor4) 7)
	(= (distance distributor0 distributor5) 5)
	(= (distance distributor1 depot0) 9)
	(= (distance distributor1 depot1) 9)
	(= (distance distributor1 depot2) 9)
	(= (distance distributor1 depot3) 1)
	(= (distance distributor1 depot4) 1)
	(= (distance distributor1 depot5) 9)
	(= (distance distributor1 distributor0) 6)
	(= (distance distributor1 distributor1) 0)
	(= (distance distributor1 distributor2) 10)
	(= (distance distributor1 distributor3) 4)
	(= (distance distributor1 distributor4) 4)
	(= (distance distributor1 distributor5) 5)
	(= (distance distributor2 depot0) 3)
	(= (distance distributor2 depot1) 1)
	(= (distance distributor2 depot2) 3)
	(= (distance distributor2 depot3) 1)
	(= (distance distributor2 depot4) 2)
	(= (distance distributor2 depot5) 3)
	(= (distance distributor2 distributor0) 7)
	(= (distance distributor2 distributor1) 8)
	(= (distance distributor2 distributor2) 0)
	(= (distance distributor2 distributor3) 2)
	(= (distance distributor2 distributor4) 6)
	(= (distance distributor2 distributor5) 8)
	(= (distance distributor3 depot0) 8)
	(= (distance distributor3 depot1) 5)
	(= (distance distributor3 depot2) 2)
	(= (distance distributor3 depot3) 1)
	(= (distance distributor3 depot4) 6)
	(= (distance distributor3 depot5) 9)
	(= (distance distributor3 distributor0) 5)
	(= (distance distributor3 distributor1) 4)
	(= (distance distributor3 distributor2) 7)
	(= (distance distributor3 distributor3) 0)
	(= (distance distributor3 distributor4) 4)
	(= (distance distributor3 distributor5) 8)
	(= (distance distributor4 depot0) 3)
	(= (distance distributor4 depot1) 10)
	(= (distance distributor4 depot2) 4)
	(= (distance distributor4 depot3) 2)
	(= (distance distributor4 depot4) 3)
	(= (distance distributor4 depot5) 8)
	(= (distance distributor4 distributor0) 7)
	(= (distance distributor4 distributor1) 6)
	(= (distance distributor4 distributor2) 8)
	(= (distance distributor4 distributor3) 10)
	(= (distance distributor4 distributor4) 0)
	(= (distance distributor4 distributor5) 9)
	(= (distance distributor5 depot0) 3)
	(= (distance distributor5 depot1) 3)
	(= (distance distributor5 depot2) 7)
	(= (distance distributor5 depot3) 5)
	(= (distance distributor5 depot4) 5)
	(= (distance distributor5 depot5) 3)
	(= (distance distributor5 distributor0) 2)
	(= (distance distributor5 distributor1) 3)
	(= (distance distributor5 distributor2) 8)
	(= (distance distributor5 distributor3) 4)
	(= (distance distributor5 distributor4) 3)
	(= (distance distributor5 distributor5) 0)
)

(:goal (and
		(on crate0 pallet14)
		(on crate1 pallet15)
		(on crate2 pallet13)
		(on crate3 pallet18)
		(on crate5 pallet12)
		(on crate6 pallet6)
		(on crate7 pallet5)
		(on crate8 crate10)
		(on crate9 pallet17)
		(on crate10 crate17)
		(on crate11 pallet1)
		(on crate12 pallet16)
		(on crate13 crate16)
		(on crate15 pallet7)
		(on crate16 crate15)
		(on crate17 pallet2)
		(on crate18 pallet4)
		(on crate19 pallet9)
	)
)

(:metric minimize (total-time)))
