(define (problem depotprob4398) (:domain Depot)
(:objects
	depot0 depot1 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 truck2 truck3 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate5)
	(at pallet1 depot1)
	(clear crate3)
	(at pallet2 distributor0)
	(clear crate4)
	(at pallet3 distributor1)
	(clear pallet3)
	(at pallet4 depot1)
	(clear crate0)
	(at pallet5 distributor1)
	(clear pallet5)
	(at pallet6 depot1)
	(clear pallet6)
	(at pallet7 distributor0)
	(clear pallet7)
	(at truck0 depot1)
	(= (speed truck0) 1)
	(at truck1 depot1)
	(= (speed truck1) 5)
	(at truck2 depot0)
	(= (speed truck2) 9)
	(at truck3 distributor1)
	(= (speed truck3) 1)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 9)
	(at hoist1 depot1)
	(available hoist1)
	(= (power hoist1) 1)
	(at hoist2 distributor0)
	(available hoist2)
	(= (power hoist2) 2)
	(at hoist3 distributor1)
	(available hoist3)
	(= (power hoist3) 10)
	(at hoist4 distributor1)
	(available hoist4)
	(= (power hoist4) 6)
	(at hoist5 depot1)
	(available hoist5)
	(= (power hoist5) 9)
	(at hoist6 depot1)
	(available hoist6)
	(= (power hoist6) 1)
	(at hoist7 distributor1)
	(available hoist7)
	(= (power hoist7) 9)
	(at crate0 depot1)
	(on crate0 pallet4)
	(= (weight crate0) 32)
	(at crate1 depot1)
	(on crate1 pallet1)
	(= (weight crate1) 46)
	(at crate2 depot0)
	(on crate2 pallet0)
	(= (weight crate2) 39)
	(at crate3 depot1)
	(on crate3 crate1)
	(= (weight crate3) 24)
	(at crate4 distributor0)
	(on crate4 pallet2)
	(= (weight crate4) 2)
	(at crate5 depot0)
	(on crate5 crate2)
	(= (weight crate5) 25)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 depot1) 2)
	(= (distance depot0 distributor0) 1)
	(= (distance depot0 distributor1) 9)
	(= (distance depot1 depot0) 9)
	(= (distance depot1 depot1) 0)
	(= (distance depot1 distributor0) 8)
	(= (distance depot1 distributor1) 5)
	(= (distance distributor0 depot0) 1)
	(= (distance distributor0 depot1) 9)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 1)
	(= (distance distributor1 depot0) 5)
	(= (distance distributor1 depot1) 7)
	(= (distance distributor1 distributor0) 2)
	(= (distance distributor1 distributor1) 0)
)

(:goal (and
		(on crate0 pallet3)
		(on crate2 pallet1)
		(on crate3 pallet0)
		(on crate4 crate3)
		(on crate5 pallet2)
	)
)

(:metric minimize (total-time)))
