(define (problem depotprob1234) (:domain Depot)
(:objects
	depot0 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - Crate
	hoist0 hoist1 hoist2 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate5)
	(at pallet1 distributor0)
	(clear pallet1)
	(at pallet2 distributor1)
	(clear crate3)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor0)
	(clear crate4)
	(at pallet5 distributor1)
	(clear crate1)
	(at truck0 distributor1)
	(= (speed truck0) 3)
	(at truck1 depot0)
	(= (speed truck1) 7)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 1)
	(at hoist1 distributor0)
	(available hoist1)
	(= (power hoist1) 10)
	(at hoist2 distributor1)
	(available hoist2)
	(= (power hoist2) 8)
	(at crate0 distributor0)
	(on crate0 pallet4)
	(= (weight crate0) 90)
	(at crate1 distributor1)
	(on crate1 pallet5)
	(= (weight crate1) 25)
	(at crate2 distributor1)
	(on crate2 pallet2)
	(= (weight crate2) 96)
	(at crate3 distributor1)
	(on crate3 crate2)
	(= (weight crate3) 29)
	(at crate4 distributor0)
	(on crate4 crate0)
	(= (weight crate4) 4)
	(at crate5 depot0)
	(on crate5 pallet0)
	(= (weight crate5) 93)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 distributor0) 3)
	(= (distance depot0 distributor1) 5)
	(= (distance distributor0 depot0) 5)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 5)
	(= (distance distributor1 depot0) 5)
	(= (distance distributor1 distributor0) 1)
	(= (distance distributor1 distributor1) 0)
)

(:goal (and
		(on crate0 pallet3)
		(on crate1 crate4)
		(on crate3 pallet1)
		(on crate4 pallet5)
		(on crate5 crate1)
	)
)

(:metric minimize (total-time)))
